alpha_frac – Ateles
alpha_frac Function
14 statements
Source File
private elemental function alpha_frac(denominator, numerator)
Quotient of two alpha values.
This function computes alpha(numerator)/alpha(denominator).
Note
This is intended to keep as many integer operations together as possible.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: denominator
Legendre mode of the to use in the denominator.
integer, intent(in) :: numerator
Legendre mode of the to use in the numeratorr.
Return Value real(kind=rk)
Called by
Call graph
ply_split_legendre_matrix calls alpha_frac
ply_split_legendre_test calls alpha_frac, ply_split_legendre_matrix
ply_split_element_init calls ply_split_legendre_matrix
ply_split_legendre_test_prog calls ply_split_legendre_matrix, ply_split_legendre_test
ply_sample_adaptive calls ply_split_element_init
ply_split_element_1d_test calls ply_split_element_init
ply_split_element_2d_test calls ply_split_element_init
ply_split_element_3d_test calls ply_split_element_init
ply_split_element_test calls ply_split_element_init, ply_split_element_1d_test, ply_split_element_2d_test, ply_split_element_3d_test
ply_sample_data calls ply_sample_adaptive
ply_split_element_test_prog calls ply_split_element_test