alpha_beta – Ateles
alpha_beta Function
14 statements
Source File
private elemental function alpha_beta(denominator, numerator)
Prodcut of alpha(numerator) * beta(denominator) / alpha(denominator) as needed by the Clenshaw algorithm in ply_split_legendre_matrix.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: denominator
Legendre mode for the in the denominator and the .
integer, intent(in) :: numerator
Legendre mode for the in the numerator.
Return Value real(kind=rk)
Called by
Call graph
ply_split_legendre_matrix calls alpha_beta
ply_split_legendre_test calls alpha_beta, ply_split_legendre_matrix
ply_split_element_init calls ply_split_legendre_matrix
ply_split_legendre_test_prog calls ply_split_legendre_matrix, ply_split_legendre_test
ply_sample_adaptive calls ply_split_element_init
ply_split_element_1d_test calls ply_split_element_init
ply_split_element_2d_test calls ply_split_element_init
ply_split_element_3d_test calls ply_split_element_init
ply_split_element_test calls ply_split_element_init, ply_split_element_1d_test, ply_split_element_2d_test, ply_split_element_3d_test
ply_sample_data calls ply_sample_adaptive
ply_split_element_test_prog calls ply_split_element_test