alt_get_penaltyIP – Ateles
alt_get_penaltyIP Function
7 statements
Source File
private function alt_get_penaltyIP(maxPolyDegree, elemLength, ip_param) result(penaltyIP)
Return the penalty parameter for the IP discretizations of higher order equations.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: maxPolyDegree
The maximal polynomial degree of the discretization (starting from 0 for FVM)
real(kind=rk), intent(in) :: elemLength
The length of an element.
real(kind=rk), intent(in) :: ip_param
The Interior Penalty paramter (should be large enough to ensure stability)
Return Value real(kind=rk)
The resulting penalty parameter
Called by
Call graph
atl_modg_viscnavierstokes_onedim_numflux calls alt_get_penaltyip
atl_modg_filnvrstk_numflux calls atl_modg_viscnavierstokes_onedim_numflux
atl_modg_navierstokes_numflux calls atl_modg_viscnavierstokes_onedim_numflux
compute_rhs_cubes_modg calls atl_modg_filnvrstk_numflux, atl_modg_navierstokes_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg