append_da_vecprojection – Ateles
append_da_vecprojection Subroutine
96 statements
Source File
private subroutine append_da_vecprojection(me, val, length, pos, wasadded)
appending a sorted list of values to the dynamic array
with this subroutine, a given list of sorted values can be added to the dynamic array. the actual positions of these values in the dynamic array will be returned, so it can be found again easily later. with the wasadded flag, it is indicated,\n wasadded = true, if this entry had to be added,\n wasadded = false, if this was already found in the array.
Arguments
Type Intent Optional Attributes Name
type(dyn_projectionarray_type) :: me
type(ply_prj_init_type), intent(in) :: val(:)
integer, intent(in), optional :: length
optional length to expand the array
integer, intent(out), optional :: pos(:)
position in the array, the values are found at.
logical, intent(out), optional :: wasadded(:)
flag to indicate, if val was newly added
Calls
Called by
Call graph
append_da_vecprojection calls expand
expand calls expand_da_projection
append calls append_da_vecprojection
atl_load_projection calls append, atl_load_general_projection, atl_load_subprojection
ply_fill_dynprojectarray calls append
sorttruncate_da_projection calls append
sorttruncate calls sorttruncate_da_projection
atl_initialize calls atl_load_projection
atl_load_general_projection calls ply_fill_dynprojectarray
atl_load_subprojection calls ply_fill_dynprojectarray
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize