atl_init_spacebasis – Ateles
atl_init_spacebasis Subroutine
26 statements
Source File
public subroutine atl_init_spacebasis(scheme_list, minlevel, maxlevel)
Initialize the space basis, this subroutine has to be called before using the module variable space_basis#basis.
It reads the spatial part of the scheme table in the configuration script and fills the basis accordingly.
Arguments
Type Intent Optional Attributes Name
type(atl_scheme_type), intent(inout) :: scheme_list(minlevel:maxlevel)
The list of schemes on the different level
integer, intent(in) :: minlevel
The minumum refinement level of the mesh
integer, intent(in) :: maxlevel
The maximum refinement level of the mesh
Calls
Called by
Call graph
atl_init_spacebasis calls ply_init_modg_covolumecoeffs, ply_init_modg_multilevelcoeffs, tem_abort
ply_init_modg_covolumecoeffs calls ply_gausslegpoints, ply_legendre_1d, ply_scalprodleg
ply_init_modg_multilevelcoeffs calls ply_gausslegpoints, ply_legendre_1d
atl_initialize calls atl_init_spacebasis
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program