atl_get_new_varSys_data_ptr – Ateles
atl_get_new_varSys_data_ptr Function
8 statements
Source File
public function atl_get_new_varSys_data_ptr(solverData) result(resPtr)
Routine to get a pointer to a new instance of atl_varSys_data_type to be used as method data for a variable in the variable system.
A new instance is allocated and a c_ptr to this type is returned. We currently don't need a reference to this instance besides the one that will be stored in the variable syste, thus we don't keep one here.
! the point_data_type need to be levelwise init(res%pointData%pointX) init(res%pointData%pointY) init(res%pointData%pointZ) init(res%pointData%elemPos)
Arguments
Type Intent Optional Attributes Name
type(atl_varSys_solverData_type), intent(in), target :: solverData
The prototype is used to initialize the new instance.
Return Value type(c_ptr)
Pointer to the newly created instance.
Called by
Call graph
append_advection_1d_consvars calls atl_get_new_varsys_data_ptr
append_heat_1d_consvars calls atl_get_new_varsys_data_ptr
append_heat_2d_consvars calls atl_get_new_varsys_data_ptr
append_heat_consvars calls atl_get_new_varsys_data_ptr
atl_append_acoustic_2d_vars calls atl_get_new_varsys_data_ptr
atl_append_acoustic_vars calls atl_get_new_varsys_data_ptr
atl_append_euler_1d_consvars calls atl_get_new_varsys_data_ptr
atl_append_euler_1d_derivedvars calls atl_get_new_varsys_data_ptr
atl_append_euler_1d_primvars calls atl_get_new_varsys_data_ptr
atl_append_euler_2d_consvars calls atl_get_new_varsys_data_ptr
atl_append_euler_2d_derivedvars calls atl_get_new_varsys_data_ptr
atl_append_euler_2d_primvars calls atl_get_new_varsys_data_ptr
atl_append_euler_consvars calls atl_get_new_varsys_data_ptr
atl_append_euler_derivedvars calls atl_get_new_varsys_data_ptr
atl_append_euler_primvars calls atl_get_new_varsys_data_ptr
atl_append_lineareuler_2d_derivedvars calls atl_get_new_varsys_data_ptr
atl_append_lineareuler_2d_vars calls atl_get_new_varsys_data_ptr
atl_append_lineareuler_derivedvars calls atl_get_new_varsys_data_ptr
atl_append_lineareuler_vars calls atl_get_new_varsys_data_ptr
atl_append_maxwell_2d_vars calls atl_get_new_varsys_data_ptr
atl_append_maxwell_vars calls atl_get_new_varsys_data_ptr
atl_append_maxwelldivcorr_vars calls atl_get_new_varsys_data_ptr
atl_append_nerplanck_vars calls atl_get_new_varsys_data_ptr
atl_append_newmaterialvars calls atl_get_new_varsys_data_ptr
atl_append_newsourcevars calls atl_get_new_varsys_data_ptr
atl_append_nvrstk_derivedvars calls atl_get_new_varsys_data_ptr
atl_append_rans_consvars calls atl_get_new_varsys_data_ptr
atl_append_rans_primvars calls atl_get_new_varsys_data_ptr
atl_set_opvar_getelement calls atl_get_new_varsys_data_ptr
atl_set_stfun_getelement calls atl_get_new_varsys_data_ptr