atl_assign_face_matPrp – Ateles
atl_assign_face_matPrp Subroutine
60 statements
Source File
private subroutine atl_assign_face_matPrp(minLevel, maxLevel, mesh_list, currentLevel, spatial_dim, material_list, materialFun)
Define material properties for the faces of all fluid elements and inherit the face material property to all ghost elements on the finer level.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: minLevel
integer, intent(in) :: maxLevel
type(atl_cube_elem_type), intent(in) :: mesh_list(minlevel:maxlevel)
List of mesh for different kernels
integer, intent(in) :: currentLevel
currentLevel
integer, intent(in) :: spatial_dim
The spatial dimension
type(atl_material_type), intent(inout) :: material_list(minlevel:maxlevel)
The description of the material properties on the element basis. The indices of variables in the global varSys that are used as material's, penalization's or whatever's data sources.
This data is needed to calculate the number of total material components.
type(atl_materialFun_type), intent(in) :: materialFun
Calls
Called by
Call graph
atl_assign_face_matprp calls childfacepos, elemposop, facepos, faces, fromfinerface, leftpos, nelems, rightpos, tem_abort
atl_init_materialparams calls atl_assign_face_matprp
atl_initialize calls atl_init_materialparams
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program