atl_eqn_linearEuler_init – Ateles
atl_eqn_linearEuler_init Subroutine
38 statements
Source File
public subroutine atl_eqn_linearEuler_init(conf, thandle, equation, nDimensions, varSys_data, initSource)
Initialization of the linearized Euler equations.
This routine sets up the necessary infrastructure for the linearized Euler equations. It reads the configuration from the given script in conf under the table provided in thandle and sets function pointers and variables accordingly.
ToDo: no source terms implemented yet
Arguments
Type Intent Optional Attributes Name
type(flu_State), intent(in) :: conf
Handle to the Lua configuration
integer, intent(in) :: thandle
Handle to the equation table in the Lua script given in conf.
type(atl_Equations_type), intent(inout) :: equation
Equation system to set with this routine.
integer, intent(in) :: nDimensions
Number of spatial dimensions, the Euler equations should live on.
Has to be 1, 2 or 3.
type(atl_varSys_solverData_type), intent(inout) :: varSys_data
the pointer to the data required for the varsys
type(atl_init_source_type), intent(inout) :: initSource
Type to be filled with the possible source variables for the equation system. These source variables are later on used to extract the corresponding information from the configuration file.
Calls
Called by
Call graph
atl_eqn_lineareuler_init calls atl_eqn_update_background, atl_getlineareulerfluxes, atl_init_lineareuler_2d_vars, atl_init_lineareuler_vars, atl_init_lineuler_sourceterms, atl_load_lineareuler
atl_eqn_update_background calls tem_temporal_for
atl_getlineareulerfluxes calls aot_get_val, tem_abort, upper_to_lower
atl_init_lineareuler_2d_vars calls atl_append_lineareuler_2d_derivedvars, atl_append_lineareuler_2d_vars, tem_varSys_init
atl_init_lineareuler_vars calls atl_append_lineareuler_derivedvars, atl_append_lineareuler_vars, tem_varSys_init
atl_init_lineuler_sourceterms calls append, init
atl_load_lineareuler calls aot_get_val, aot_table_close, aot_table_open, tem_abort, tem_horizontalSpacer, tem_load_temporal
atl_append_lineareuler_2d_derivedvars calls tem_abort, atl_get_new_varsys_data_ptr, tem_varSys_append_derVar
atl_append_lineareuler_2d_vars calls atl_get_new_varsys_data_ptr, tem_varSys_append_stateVar
atl_append_lineareuler_derivedvars calls tem_abort, atl_get_new_varsys_data_ptr, tem_varSys_append_derVar
atl_append_lineareuler_vars calls atl_get_new_varsys_data_ptr, tem_varSys_append_stateVar
atl_init_equation calls atl_eqn_lineareuler_init
atl_initialize calls atl_init_equation
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program