atl_create_materialBoundaryList – Ateles
atl_create_materialBoundaryList Subroutine
54 statements
Source File
private subroutine atl_create_materialBoundaryList(material, materialFun, boundary, mesh, time_weights)
Create separate compute list for constant-constant, constant-variable (or vice versa) and variable-variable material parameter compute faces on this rank.
Arguments
Type Intent Optional Attributes Name
type(atl_material_type), intent(inout) :: material
The description of the material properties. The compute lists in the material description is filled up by calling this subroutine. The indizes of variables in the global varSys that are used as material's, penalization's or whatever's data sources.
This data is needed to calculate the number of total material components.
type(atl_materialFun_type), intent(in) :: materialFun
type(atl_level_boundary_type), intent(in) :: boundary
Boundary description for the all the levels.
type(atl_cube_elem_type), intent(in) :: mesh
Description of the mesh
logical, intent(in), optional :: time_weights
Calls
Called by
Call graph
atl_create_materialboundarylist calls append, init, pnttid, tem_abort, tem_startTimer, tem_stopTimer, val
atl_init_materialparams calls atl_create_materialboundarylist
atl_update_materialparams calls atl_create_materialboundarylist
atl_initialize calls atl_init_materialparams
atl_preprocess_modg_1d_kernel calls atl_update_materialparams
atl_preprocess_modg_2d_kernel calls atl_update_materialparams
atl_preprocess_modg_kernel calls atl_update_materialparams
atl_initialize_program calls atl_initialize
preprocess_local_rhs_cubes calls atl_preprocess_modg_kernel
preprocess_rhs_cubes calls atl_preprocess_modg_1d_kernel, atl_preprocess_modg_2d_kernel, atl_preprocess_modg_kernel
atl_harvesting calls atl_initialize
atl_preprocess_local_rhs calls preprocess_local_rhs_cubes
atl_preprocess_rhs calls preprocess_rhs_cubes
ateles calls atl_initialize_program