atl_modg_1d_modalVolToModalFace – Ateles
atl_modg_1d_modalVolToModalFace Subroutine
27 statements
Source File
public subroutine atl_modg_1d_modalVolToModalFace(mesh, statedata, facedata, nScalars, modg_1d, equation)
Projects modal representation of each cell to its faces, i.e. this subroutine creates a modal representation on the faces.
Arguments
Type Intent Optional Attributes Name
type(atl_cube_elem_type), intent(in) :: mesh
The elements we apply the projection for.
type(atl_statedata_type), intent(in) :: statedata
Volumetric, modal states for each element.
type(atl_facedata_type), intent(inout) :: facedata
Modal representation on the face (will be updated by this routine for all fluid elements in mesh).
integer, intent(in) :: nScalars
The number of scalars varaibales in your equation system.
type(atl_modg_1d_scheme_type), intent(in) :: modg_1d
The parameters of your modg scheme.
type(atl_Equations_type) :: equation
The equation you solve.
Calls
Call graph
atl_modg_1d_modalvoltomodalface calls nelems, modg_1d_voltoface_grad_q, modg_1d_voltoface_q, tem_abort
modg_1d_voltoface_grad_q calls tem_abort, ply_calcdiff_leg_1d, ply_facevalleftbndans
modg_1d_voltoface_q calls tem_abort, ply_facevalleftbndans