atl_get_penaltyIP_2d – Ateles
atl_get_penaltyIP_2d Function
7 statements
Source File
public function atl_get_penaltyIP_2d(maxPolyDegree, elemLength, ip_param) result(penaltyIP)
Return the penalty parameter for the IP discretizations of higher order equations.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: maxPolyDegree
The maximal polynomial degree of the discretization (starting from 0 for FVM)
real(kind=rk), intent(in) :: elemLength
The length of an element.
real(kind=rk), intent(in) :: ip_param
The Interior Penalty paramter (should be large enough to ensure stability)
Return Value real(kind=rk)
The resulting penalty parameter
Called by
Call graph
modg_2d_viscnavierstokes_onedim_numflux calls atl_get_penaltyip_2d
modg_2d_viscrans_onedim_numflux calls atl_get_penaltyip_2d
atl_modg_2d_filnvrstk_numflux calls modg_2d_viscrans_onedim_numflux
atl_modg_2d_navierstokes_numflux calls modg_2d_viscnavierstokes_onedim_numflux
compute_rhs_cubes_modg_2d calls atl_modg_2d_filnvrstk_numflux, atl_modg_2d_navierstokes_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg_2d