atl_modg_modalVolToModalFace – Ateles
atl_modg_modalVolToModalFace Subroutine
54 statements
Source File
public subroutine atl_modg_modalVolToModalFace(nElems_fluid, length, volState, faceRep, nScalars, nDerivatives, modg)
Projects modal representation of each cell to its faces, i.e. this subroutine creates a modal representation on the faces.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nElems_fluid
number of fluid elements
real(kind=rk), intent(in) :: length
length of cubic element
real(kind=rk), intent(in) :: volState(:,:,:)
Volumetric, modal states for each element.
type(atl_faceRep_type), intent(inout) :: faceRep(:)
Modal representation on the face (will be updated by this routine for all fluid elements in mesh).
integer, intent(in) :: nScalars
number of variables
integer, intent(in) :: nDerivatives
number of derivatives
type(atl_modg_scheme_type), intent(in) :: modg
The parameters of your modg scheme.
Calls
Called by
Call graph
atl_modg_modalvoltomodalface calls atl_modg_voltoface_grad_q, atl_modg_voltoface_p, modg_voltoface_q_x, modg_voltoface_q_y, modg_voltoface_q_z, ply_change_poly_space, tem_abort
atl_modg_voltoface_grad_q calls tem_abort, ply_calcdiff_leg, ply_facevalleftbndans
atl_modg_voltoface_p calls tem_abort, ply_facevalleftbndans
ply_calcdiff_leg calls ply_calcdiff_leg_x_vec, ply_calcdiff_leg_y_vec, ply_calcdiff_leg_z_vec
preprocess_rhs_cubes calls atl_modg_modalvoltomodalface
atl_preprocess_rhs calls preprocess_rhs_cubes
global_corrector_substep calls atl_preprocess_rhs
imexrk_substep calls atl_preprocess_rhs, imexrk_substep
mesh_timestep_euler calls atl_preprocess_rhs, mesh_timestep_euler
rk2_substep calls atl_preprocess_rhs, rk2_substep
rk4_substep calls atl_preprocess_rhs, rk4_substep
rktaylor_substep calls atl_preprocess_rhs, rktaylor_substep
mesh_timestep_imexrk calls imexrk_substep
mesh_timestep_predcor_cerk4 calls global_corrector_substep
mesh_timestep_rk4 calls rk4_substep
mesh_timestep_rktaylor calls rktaylor_substep
mesh_timestep_ssprk2 calls rk2_substep