atl_viscRans_2d – Ateles
atl_viscRans_2d Subroutine
18 statements
Source File
public subroutine atl_viscRans_2d(left, left_grad, right, right_grad, isen_coeff, mu, lambda, thermCond, heatCap, penaltyIP, rans_params, flux)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: left(6)
The state on the face from its left limit (in conservative variables).
real(kind=rk), intent(in) :: left_grad(6,2)
The gradient state on the face from its left limit (in conservative variables).
real(kind=rk), intent(in) :: right(6)
The state on the face from its right limit (in conservative variables).
real(kind=rk), intent(in) :: right_grad(6,2)
The gradient state on the face from its right limit (in conservative variables).
real(kind=rk), intent(in) :: isen_coeff
The adaiabtic expansion coefficient
real(kind=rk), intent(in) :: mu
Resulting flux for the left element (in conservative variables). Dynamic Viscosity
real(kind=rk), intent(in) :: lambda
Viscosity
real(kind=rk), intent(in) :: thermCond
The thermal cond
real(kind=rk), intent(in) :: heatCap
The specific heat capacity (per mass unit mass, at constant volume)
real(kind=rk), intent(in) :: penaltyIP
The penalty parameter
type(atl_navier_stokes_rans_type), intent(in) :: rans_params
The constants for the Rans eqn
real(kind=rk), intent(out) :: flux(6)
Calls
Called by
Call graph
atl_viscrans_2d calls atl_viscphysfluxrans_2d
atl_viscphysfluxrans_2d calls atl_get_lower_bound_turb_disscipation, atl_get_pointwise_velocity_gradient_2d, atl_get_pointwise_visc_stress_tensor_2d
modg_2d_viscrans_onedim_numflux calls atl_viscrans_2d
atl_modg_2d_filnvrstk_numflux calls modg_2d_viscrans_onedim_numflux
compute_rhs_cubes_modg_2d calls atl_modg_2d_filnvrstk_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg_2d