atl_modg_2d_project_NumFlux – Ateles
atl_modg_2d_project_NumFlux Subroutine
74 statements
Source File
public subroutine atl_modg_2d_project_NumFlux(mesh, equation, kerneldata, facedata, penalizationdata, usePenalization, scheme, poly_proj, dl_prod, dl_prodDiff)
Subroutine to project modal representations of numerical flux and source terms onto test functions.
Arguments
Type Intent Optional Attributes Name
type(atl_cube_elem_type), intent(in) :: mesh
Descritption of the cubical elements in the mesh
type(atl_Equations_type), intent(in) :: equation
The equation description.
type(atl_kerneldata_type), intent(inout) :: kerneldata
The data of the kernel. Holds the physical fluxes.
type(atl_facedata_type), intent(inout) :: facedata
The representation on the face + representation of the flux.
type(atl_penalizationData_type), intent(in) :: penalizationdata
Volumetric data for the penalization
logical, intent(in) :: usePenalization
Flag to indicate whether the penalization data has to be considered, or if it is taken care of somewhere else (imex)
type(atl_modg_2d_scheme_type), intent(in) :: scheme
The parameters of the MODG scheme
type(ply_poly_project_type), intent(inout) :: poly_proj
Projection for the current level
real(kind=rk), intent(in) :: dl_prod(2,scheme%maxPolyDegree+1)
Precomputed scalar products of the test and ansatz function
real(kind=rk), intent(in) :: dl_prodDiff(2,scheme%maxPolyDegree+1)
Calls
Called by
Call graph
atl_modg_2d_project_numflux calls nelems, modg_2d_project_numfluxx_difftestx_q, modg_2d_project_numfluxx_q, modg_2d_project_numfluxy_difftesty_q, modg_2d_project_numfluxy_q, modg_2d_project_penalization_q, modg_2d_project_stabviscnumfluxx_q, modg_2d_project_stabviscnumfluxy_q, ply_change_poly_space, tem_abort
modg_2d_project_numfluxx_difftestx_q calls ply_facevalleftbndgradtest, ply_facevalrightbndgradtest
modg_2d_project_numfluxx_q calls ply_facevalleftbndtest, ply_facevalrightbndtest
modg_2d_project_numfluxy_difftesty_q calls ply_facevalleftbndgradtest, ply_facevalrightbndgradtest
modg_2d_project_numfluxy_q calls ply_facevalleftbndtest, ply_facevalrightbndtest
modg_2d_project_penalization_q calls nelems, ply_scalproddualleg
modg_2d_project_stabviscnumfluxx_q calls ply_poly_project_m2n, ply_poly_project_n2m, atl_mult_nu11_navierstokes_2d, atl_mult_nu11_rans_2d, atl_mult_nu21_navierstokes_2d, atl_mult_nu21_rans_2d, ply_facevalleftbndtest, ply_facevalleftbndtestgrad, ply_facevalrightbndtest, ply_facevalrightbndtestgrad, ply_scalproddualleg, ply_scalprodduallegdiff
modg_2d_project_stabviscnumfluxy_q calls ply_poly_project_m2n, ply_poly_project_n2m, atl_mult_nu12_navierstokes_2d, atl_mult_nu12_rans_2d, atl_mult_nu22_navierstokes_2d, atl_mult_nu22_rans_2d, ply_facevalleftbndtest, ply_facevalleftbndtestgrad, ply_facevalrightbndtest, ply_facevalrightbndtestgrad, ply_scalproddualleg, ply_scalprodduallegdiff
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
compute_rhs_cubes_modg_2d calls atl_modg_2d_project_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg_2d
atl_compute_rhs calls compute_rhs_cubes
global_corrector_substep calls atl_compute_rhs
imexrk_substep calls atl_compute_rhs
mesh_timestep_euler calls atl_compute_rhs
rk2_substep calls atl_compute_rhs
rk4_substep calls atl_compute_rhs
rktaylor_substep calls atl_compute_rhs