atl_initialize_state_der – Ateles
atl_initialize_state_der Subroutine
13 statements
Source File
public subroutine atl_initialize_state_der(state_der)
This routine is used to initialize an array in an OpenMP PARALLEL region. Usually this is done using a WORKSHARE directive, but due to a bug in Intel 15 we cannot make use of WORKSHARE.
This routine is specifically made to initialize the state_der array of the atl_kerneldata_type, which is a three-dimensional array.
With these dimension we then can calculate the number of elements in the array. This number is then used in a collapsed loop to initialize the array elements.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(inout) :: state_der(:,:,:)
The state derivates of the kerneldata.
Called by
Call graph
modg_1d_compute_project_physflux calls atl_initialize_state_der
modg_2d_compute_project_physflux calls atl_initialize_state_der
modg_compute_project_physflux calls atl_initialize_state_der
compute_rhs_cubes_modg calls modg_compute_project_physflux
compute_rhs_cubes_modg_1d calls modg_1d_compute_project_physflux
compute_rhs_cubes_modg_2d calls modg_2d_compute_project_physflux
compute_rhs_cubes calls compute_rhs_cubes_modg, compute_rhs_cubes_modg_1d, compute_rhs_cubes_modg_2d
atl_compute_rhs calls compute_rhs_cubes