atl_init_facerep – Ateles
atl_init_facerep Subroutine
11 statements
Source File
private subroutine atl_init_facerep(nScalars, nFaceDofs, faceRep, dimLevelDesc, dir, boundary)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nScalars
The number of scalar variables to store on the faces.
integer, intent(in) :: nFaceDofs
The number of degrees of freedoms on the face.
type(atl_faceRep_type), intent(out) :: faceRep
The face representation to be initialized.
type(tem_levelDesc_type), intent(in) :: dimLevelDesc
Dimension-by-dimension level description of the mesh.
integer, intent(in) :: dir
The spatial direciton:\n 1 -> x direction \n 2 -> y direction \n 3 -> z direction
type(atl_level_boundary_type), intent(in) :: boundary
The boundary description for the faces on the current level.
Called by
Call graph
atl_init_facedata_asym calls atl_init_facerep
atl_init_facedata_sym calls atl_init_facerep
atl_init_facedata calls atl_init_facedata_asym, atl_init_facedata_sym
atl_init_elem_container calls atl_init_facedata
atl_initialize calls atl_init_elem_container