atl_modg_acoustic_numFlux – Ateles
atl_modg_acoustic_numFlux Subroutine
16 statements
Source File
public subroutine atl_modg_acoustic_numFlux(mesh, equation, facedata, scheme)
Calculate the numerical flux for acoustic equation and MODG scheme
Arguments
Type Intent Optional Attributes Name
type(atl_cube_elem_type), intent(in) :: mesh
The mesh you are working with.
type(atl_Equations_type), intent(in) :: equation
The equation you solve.
type(atl_facedata_type), intent(inout) :: facedata
The face representation of the state.
type(atl_modg_scheme_type), intent(in) :: scheme
Parameters of the modal dg scheme
Calls
Called by
Call graph
atl_modg_acoustic_numflux calls faces, atl_acoustic_numflux, vartransformindices
atl_acoustic_numflux calls atl_acoustic_numflux_cube_vec
atl_acoustic_numflux_cube_vec calls atl_acoustic_numflux_onedir
compute_rhs_cubes_modg calls atl_modg_acoustic_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg
atl_compute_rhs calls compute_rhs_cubes
global_corrector_substep calls atl_compute_rhs
imexrk_substep calls atl_compute_rhs
mesh_timestep_euler calls atl_compute_rhs
rk2_substep calls atl_compute_rhs
rk4_substep calls atl_compute_rhs
rktaylor_substep calls atl_compute_rhs