atl_modg_2d_project_physFlux_testFunc – Ateles
atl_modg_2d_project_physFlux_testFunc Subroutine
25 statements
Source File
public subroutine atl_modg_2d_project_physFlux_testFunc(mesh, equation, kerneldata, iElem, dl_prod, iDir, scheme, state_data, nDofs)
Subroutine to project modal representations of physical flux, numerical flux and source terms onto test functions.
Arguments
Type Intent Optional Attributes Name
type(atl_cube_elem_type), intent(in) :: mesh
Descritption of the cubical elements in the mesh
type(atl_Equations_type), intent(in) :: equation
The equation description.
type(atl_kerneldata_type), intent(inout) :: kerneldata
The data of the kernel. Holds the physical fluxes.
integer, intent(in) :: iElem
The element index
real(kind=rk), intent(in) :: dl_prod(2,scheme%maxPolyDegree+1)
integer, intent(in) :: iDir
The direction
type(atl_modg_2d_scheme_type), intent(in) :: scheme
The parameters of the MODG scheme
real(kind=rk), intent(in) :: state_data(nDofs,equation%varSys%nScalars)
The physical fluxes that needs to be projected
integer, intent(in) :: nDofs
The total degrees of freedom
Calls
Called by
Call graph
atl_modg_2d_project_physflux_testfunc calls modg_2d_project_physfluxx_p, modg_2d_project_physfluxx_q, modg_2d_project_physfluxy_p, modg_2d_project_physfluxy_q
modg_2d_project_physfluxx_p calls ply_scalprodduallegdiff
modg_2d_project_physfluxx_q calls ply_scalprodduallegdiff
modg_2d_project_physfluxy_p calls ply_scalprodduallegdiff
modg_2d_project_physfluxy_q calls ply_scalprodduallegdiff
modg_2d_compute_project_physflux calls atl_modg_2d_project_physflux_testfunc
compute_rhs_cubes_modg_2d calls modg_2d_compute_project_physflux
compute_rhs_cubes calls compute_rhs_cubes_modg_2d
atl_compute_rhs calls compute_rhs_cubes