atl_load_filtNS – Ateles
atl_load_filtNS Subroutine
11 statements
Source File
public subroutine atl_load_filtNS(filtNavierStokes, navierStokes, euler, conf, eq_table)
subroutine to initialize an equation of type filtered-navier-stokes equation (turbulence modelling) as defined in the configuration file
Arguments
Type Intent Optional Attributes Name
type(atl_FiltNavierStokes_type), intent(out) :: filtNavierStokes
Output of this subroutine, the data inside this argument will be set to the values of the configuration file
type(atl_navierStokes_type), intent(out) :: navierStokes
type(atl_euler_type), intent(out) :: euler
type(flu_State), intent(in) :: conf
Variable of type flu_State which is a flu binding to the configuration file
integer, intent(in) :: eq_table
A handle to the equation table inside the configuration file
Calls
Called by
Call graph
atl_load_filtns calls aot_get_val, atl_load_navierstokes
atl_load_navierstokes calls aot_get_val, atl_load_euler, tem_abort
atl_load_euler calls aot_get_val, tem_abort
atl_eqn_filtered_nvrstk_init calls atl_load_filtns
atl_init_equation calls atl_eqn_filtered_nvrstk_init
atl_initialize calls atl_init_equation
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize