atl_modg_1d_euler_penalization_NonConst – Ateles
atl_modg_1d_euler_penalization_NonConst Subroutine
23 statements
Source File
public subroutine atl_modg_1d_euler_penalization_NonConst(equation, poly_proj, nodal_data, scheme_min, penalizationData, iElem, material)
Arguments
Type Intent Optional Attributes Name
type(atl_Equations_type), intent(in) :: equation
The equation you solve.
type(ply_poly_project_type), intent(inout) :: poly_proj
Poly project
real(kind=rk), intent(in), optional :: nodal_data(:,:)
The state in nodal form
type(atl_scheme_type), intent(inout) :: scheme_min
The scheme information
type(atl_penalizationData_type), intent(inout) :: penalizationData
The penalization data
integer, intent(in) :: iElem
The current Element
type(atl_material_type), intent(in) :: material
Material description for the faces on the current level
Calls
Called by
Call graph
atl_modg_1d_euler_penalization_nonconst calls ply_poly_project_n2m, ply_convertfromoversample
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d, ply_pnttoleg_3d, ply_fxt_n2m_1d, ply_fxt_n2m_2d, ply_fxt_n2m_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_pnttoleg_2d calls ply_pnttoleg_2d_multvar, ply_pnttoleg_2d_singvar
ply_pnttoleg_3d calls ply_pnttoleg_3d_multvar, ply_pnttoleg_3d_singvar
ply_fxt_n2m_1d calls fxtf_flptld_n2m
ply_fxt_n2m_2d calls fxtf_flptld_n2m
ply_fxt_n2m_3d calls fxtf_flptld_n2m
ply_l2p_trafo_1d calls ply_l2_projection
ply_l2p_trafo_2d calls ply_l2_projection
ply_l2p_trafo_3d calls ply_l2_projection
modg_1d_compute_project_physflux calls atl_modg_1d_euler_penalization_nonconst
compute_rhs_cubes_modg_1d calls modg_1d_compute_project_physflux
compute_rhs_cubes calls compute_rhs_cubes_modg_1d
atl_compute_rhs calls compute_rhs_cubes