atl_append_acoustic_2d_vars – Ateles
atl_append_acoustic_2d_vars Subroutine
17 statements
Source File
public subroutine atl_append_acoustic_2d_vars(equation, methodData)
\brief append the variables for acoustic simulations the acoustic equation only has 'primitive' variables or different speaking, the equation describe the pertubation in primitive variables
Arguments
Type Intent Optional Attributes Name
type(atl_Equations_type), intent(inout) :: equation
The equation type .
type(atl_varSys_solverData_type), target :: methodData
the pointer to the data required for the varsys
Calls
Called by
Call graph
atl_append_acoustic_2d_vars calls atl_get_new_varsys_data_ptr, tem_varSys_append_stateVar
atl_init_acoustic_2d_vars calls atl_append_acoustic_2d_vars
atl_eqn_acoustic_init calls atl_init_acoustic_2d_vars
atl_init_equation calls atl_eqn_acoustic_init
atl_initialize calls atl_init_equation