atl_init_explicitLocalPredictorGlobalCorrector – Ateles
atl_init_explicitLocalPredictorGlobalCorrector Subroutine
28 statements
Source File
public subroutine atl_init_explicitLocalPredictorGlobalCorrector(me, minLevel, maxLevel, steps, statedata_list)
Routine to initialize explicit runge kutta scheme for timestepping.
Arguments
Type Intent Optional Attributes Name
type(atl_global_timestep_type), intent(inout) :: me
The datatype to initialize.
integer, intent(in) :: minLevel
The minimum of level of the mesh.
integer, intent(in) :: maxLevel
The maximum of level of the mesh.
integer, intent(in) :: steps
The number of steps in the runge kutta procedure
type(atl_statedata_type), intent(in) :: statedata_list(minLevel:maxLevel)
The state list used in your solver, for each level one entry.
Calls
Called by
Call graph
atl_init_explicitlocalpredictorglobalcorrector calls tem_abort
atl_init_global_time_integration calls atl_init_explicitlocalpredictorglobalcorrector
atl_init_elem_container calls atl_init_global_time_integration
atl_initialize calls atl_init_elem_container
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize