atl_nearest_projection – Ateles
atl_nearest_projection Subroutine
47 statements
Source File
private subroutine atl_nearest_projection(nPointsPerDir, nPnts, nPointsPerFace, scheme_dim, iLevel, preciceCpl)
For a 2D testcase just the edges are of importance, in 3D also triangles have to be provided loop over all faces and edges. Set an offset, to get from one face to the other For a 3D testcase in addition to the edges triangles have to be created
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nPointsPerDir
integer, intent(in) :: nPnts
integer, intent(in) :: nPointsPerFace
integer, intent(in) :: scheme_dim
integer, intent(in) :: iLevel
type(tem_precice_coupling_type), pointer :: preciceCpl
Calls
Called by
Call graph
atl_nearest_projection calls edges, interpol_data, posidlvl, posids, tem_create_edges_triangles, tem_precice_set_edge, tem_precice_set_triangle, triangles
atl_write_equipoints calls atl_nearest_projection
atl_write_nonequipoints calls atl_nearest_projection
atl_write_precice_getpoint calls atl_write_equipoints, atl_write_nonequipoints
atl_init_precice calls atl_write_precice_getpoint
atl_initialize calls atl_init_precice