atl_init_elem_bnd – Ateles
atl_init_elem_bnd Subroutine
50 statements
Source File
public subroutine atl_init_elem_bnd(minLevel, maxLevel, bc_header, face_list, boundary_list, scheme_list)
Creates boundary informations for the faces.
Used for covolumes.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: minLevel
integer, intent(in) :: maxLevel
type(tem_bc_header_type), intent(in) :: bc_header
The boundary condition header data as given in the mesh.
type(tem_face_type), intent(inout) :: face_list(minLevel:maxLevel)
Description of the faces
type(atl_level_boundary_type), intent(inout) :: boundary_list(minLevel:maxLevel)
The created boundary information.
type(atl_scheme_type), intent(in) :: scheme_list(minLevel:maxLevel)
Scheme information
Calls
Called by
Call graph
atl_init_elem_bnd calls append, init, nelems, nghelems, tem_abort
atl_init_cube_container calls atl_init_elem_bnd
atl_init_elem_container calls atl_init_cube_container
atl_initialize calls atl_init_elem_container
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize