atl_writeRestart – Ateles
atl_writeRestart Subroutine
44 statements
Source File
public subroutine atl_writeRestart(mesh, restart, tree, equation, timing, varSys, timerHandle)
Writes a restart file for the current point in time.
Todo
HK: Not so sure about this output, is probably also already done by the treelm routines.
Arguments
Type Intent Optional Attributes Name
type(atl_cube_container_type), intent(inout) :: mesh
Informations and states of the cubic mesh.
type(tem_restart_type) :: restart
the restart infotmation
type(treelmesh_type) :: tree
mesh, provided in treelm format
type(atl_Equations_type), intent(in) :: equation
The equation system you use.
type(tem_time_type), intent(in) :: timing
current simulation time information
type(tem_varSys_type), intent(in) :: varSys
integer, intent(in) :: timerHandle
Timer handle to measure write restart time
Calls
Called by
Call graph
atl_writerestart calls serializedata, tem_restart_closeWrite, tem_restart_openWrite, tem_restart_writeData, tem_startTimer, tem_stopTimer
serializedata calls ply_transfer_dofs, tem_LevelOf, tem_abort
ply_transfer_dofs calls ply_transfer_dofs_1d, ply_transfer_dofs_2d, ply_transfer_dofs_3d
atl_writerestartifnecessary calls atl_writerestart
atl_harvesting calls atl_writerestart
atl_finalize_program calls atl_writerestartifnecessary
atl_initialize_program calls atl_writerestartifnecessary
atl_solve_program calls atl_writerestartifnecessary
ateles calls atl_finalize_program, atl_initialize_program, atl_solve_program