atl_varSys_load_user – Ateles
atl_varSys_load_user Subroutine
23 statements
Source File
public subroutine atl_varSys_load_user(L, parent, specifics, appender, iError)
Method to load user defined variables from the configuration.
This adds the possibility to load ateles specific variable types.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Lua script to load the variable data from.
integer, intent(in) :: parent
Parent table in the Lua script to read the variable from.
type(c_ptr), intent(out) :: specifics
Data to read for the solver specific variable
procedure(tem_append_solverVar_method), pointer :: appender
Function pointer to use for appending the solver variable.
integer, intent(out) :: iError
Indication whether the attempted reading was successful.
Calls
Call graph
atl_varsys_load_user calls aot_get_val, atl_legpolyvar_load
atl_legpolyvar_load calls aot_get_val, tem_abort