atl_modg_1d_euler_physFlux_nonConst – Ateles
atl_modg_1d_euler_physFlux_nonConst Subroutine
18 statements
Source File
public subroutine atl_modg_1d_euler_physFlux_nonConst(equation, poly_proj, res, pointVal, penalty_char, U_o)
Calculate the physical flux for the MODG scheme and Euler equation with variable characteristic (mask function) in the element.
Arguments
Type Intent Optional Attributes Name
type(atl_Equations_type) :: equation
The equation you solve.
type(ply_poly_project_type), intent(inout) :: poly_proj
Parameters for projection
real(kind=rk), intent(inout) :: res(:,:)
The physical flux result to be stored in
real(kind=rk), intent(in) :: pointVal(:,:)
Nodal representation of the polynomial with in each cell.
real(kind=rk), intent(in) :: penalty_char(:)
Characteristic (mask) function of the material penalization.
This should be 0 everywhere where there is no material, and 1 where there is material. obstacle velocity
real(kind=rk), intent(in) :: U_o(:)
Calls
Called by
Call graph
atl_modg_1d_euler_physflux_nonconst calls atl_physfluxeuler_1d
modg_1d_compute_project_physflux calls atl_modg_1d_euler_physflux_nonconst
compute_rhs_cubes_modg_1d calls modg_1d_compute_project_physflux
compute_rhs_cubes calls compute_rhs_cubes_modg_1d
atl_compute_rhs calls compute_rhs_cubes