atl_modg_2d_modalVolToModalFace – Ateles
atl_modg_2d_modalVolToModalFace Subroutine
62 statements
Source File
public subroutine atl_modg_2d_modalVolToModalFace(mesh, statedata, facedata, equation, modg_2d)
Projects modal representation of each cell to its faces, i.e. this subroutine creates a modal representation on the faces.
Arguments
Type Intent Optional Attributes Name
type(atl_cube_elem_type), intent(in) :: mesh
The elements we apply the projection for.
type(atl_statedata_type), intent(in) :: statedata
Volumetric, modal states for each element.
type(atl_facedata_type), intent(inout) :: facedata
Modal representation on the face (will be updated by this routine for all fluid elements in mesh).
type(atl_Equations_type), intent(in) :: equation
The equation system under consideration
type(atl_modg_2d_scheme_type), intent(in) :: modg_2d
The parameters of your modg scheme.
Calls
Called by
Call graph
atl_modg_2d_modalvoltomodalface calls nelems, atl_modg_2d_voltoface_grad_q, atl_modg_2d_voltoface_p, atl_modg_2d_voltoface_q, ply_change_poly_space, tem_abort
atl_modg_2d_voltoface_grad_q calls tem_abort, ply_calcdiff_leg_2d, ply_facevalleftbndans
atl_modg_2d_voltoface_p calls tem_abort, ply_facevalleftbndans
atl_modg_2d_voltoface_q calls tem_abort, ply_facevalleftbndans
ply_calcdiff_leg_2d calls ply_calcdiff_leg_2d_normal
preprocess_rhs_cubes calls atl_modg_2d_modalvoltomodalface
atl_preprocess_rhs calls preprocess_rhs_cubes
global_corrector_substep calls atl_preprocess_rhs
imexrk_substep calls atl_preprocess_rhs, imexrk_substep
mesh_timestep_euler calls atl_preprocess_rhs, mesh_timestep_euler
rk2_substep calls atl_preprocess_rhs, rk2_substep
rk4_substep calls atl_preprocess_rhs, rk4_substep
rktaylor_substep calls atl_preprocess_rhs, rktaylor_substep
mesh_timestep_imexrk calls imexrk_substep
mesh_timestep_predcor_cerk4 calls global_corrector_substep
mesh_timestep_rk4 calls rk4_substep
mesh_timestep_rktaylor calls rktaylor_substep
mesh_timestep_ssprk2 calls rk2_substep