atl_init_facedata_sym – Ateles
atl_init_facedata_sym Subroutine
18 statements
Source File
private subroutine atl_init_facedata_sym(faces, facedata, minLevel, maxLevel, nDim, nScalars, nFaceDofs, boundary)
Creates the datastructures for modal representations on the faces. This routine creates symmetric representations, i.e. state and fluxes have the same number of variables on the face.
Arguments
Type Intent Optional Attributes Name
type(tem_face_type), intent(in) :: faces(minLevel:maxLevel)
Description of the faces (levelwise).
type(atl_facedata_type), intent(out), allocatable :: facedata(:)
The face data to be initialized (levelwise, running from minLevel to maxLevel).
integer, intent(in) :: minLevel
The minimum refinement level of the mesh.
integer, intent(in) :: maxLevel
The maximum refinement level of the mesh.
integer, intent(in) :: nDim
The number of dimensions of the used scheme.
integer, intent(in) :: nScalars
The number of scalar variables to store on the faces.
integer, intent(in) :: nFaceDofs(minLevel:maxLevel)
The number of degrees of freedoms on the face (one value for each level).
type(atl_level_boundary_type), intent(in) :: boundary(minLevel:maxLevel)
The boundary description for the faces on all levels of the mesh.
Calls
Called by
Call graph
atl_init_facedata_sym calls atl_init_facerep
atl_init_facedata calls atl_init_facedata_sym
atl_init_elem_container calls atl_init_facedata
atl_initialize calls atl_init_elem_container
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize