atl_eqn_nvrstk_load_bc – Ateles
atl_eqn_nvrstk_load_bc Subroutine
656 statements
Source File
public subroutine atl_eqn_nvrstk_load_bc(equation, bc_state, bc_state_gradient, bc_varDict, bc_varDict_gradient, bc_normal_vec, bc_normal_vec_gradient, bc_trafo, bc_trafo_gradient, bc_label, bc_kind, thandle, conf)
VK! density for viscous terms VKbc_state_gradient(1,1) = bc_state(1) VKkvp%key = trim(bc_state_gradient(1,1)%state_name) VKcall append(me = bc_varDict_gradient, val = kvp)
VK ! v_normal for viscous terms VK bc_state_gradient(2,1)%state_name = 'v_norm' VK bc_state_gradient(2,1)%style = 'dirichlet_mirror' VK bc_state_gradient(2,1)%isDefined = .true. VK kvp%key = trim(bc_state_gradient(2,1)%state_name) VK call append(me = bc_varDict_gradient, val = kvp)
VK ! v_tan for viscous terms VK call atl_load_bc_state(bc = bc_state_gradient(3,1), & VK & state_name = 'v_tan', & VK & style = 'dirichlet_mirror', & VK & conf = conf, & VK & bc_handle = thandle, & VK & varDict = bc_varDict_gradient, & VK & varSys = equation%varSys)
VK ! v_tan for viscous terms VK call atl_load_bc_state(bc = bc_state_gradient(4,1), & VK & state_name = 'v_tan2', & VK & style = 'dirichlet_mirror', & VK & conf = conf, & VK & bc_handle = thandle, & VK & varDict = bc_varDict_gradient, & VK & varSys = equation%varSys)
VK ! Temperature for viscous terms VK call atl_load_bc_state(bc = bc_state_gradient(pIndex,1), & VK & state_name = 'temperature', & VK & style = 'dirichlet_mirror', & VK & conf = conf, & VK & bc_handle = thandle, & VK & varDict = bc_varDict_gradient, & VK & varSys = equation%varSys)
VK ! ... the face values VK bc_trafo_gradient(1)%identity = .false. VK bc_normal_vec_gradient(1) = .true.
VK ! density for viscous terms VK bc_state_gradient(1,1) = bc_state(1) VK kvp%key = trim(bc_state_gradient(1,1)%state_name) VK call append(me = bc_varDict_gradient, val = kvp)
VK ! v_normal for viscous terms VK bc_state_gradient(2,1)%state_name = 'v_norm' VK bc_state_gradient(2,1)%style = 'dirichlet_mirror' VK bc_state_gradient(2,1)%isDefined = .true. VK kvp%key = trim(bc_state_gradient(2,1)%state_name) VK call append(me = bc_varDict_gradient, val = kvp)
VK ! v_tan for viscous terms VK bc_state_gradient(3,1)%state_name = 'v_tan' VK bc_state_gradient(3,1)%style = 'dirichlet_mirror' VK bc_state_gradient(3,1)%isDefined = .true. VK kvp%key = trim(bc_state_gradient(3,1)%state_name) VK call append(me = bc_varDict_gradient, val = kvp)
VK ! v_tan for viscous terms VK bc_state_gradient(4,1)%state_name = 'v_tan2' VK bc_state_gradient(4,1)%style = 'dirichlet_mirror' VK bc_state_gradient(4,1)%isDefined = .true. VK kvp%key = trim(bc_state_gradient(4,1)%state_name) VK call append(me = bc_varDict_gradient, val = kvp)
VK ! Energy for viscous terms VK bc_state_gradient(pIndex,1) = bc_state(pIndex) VK kvp%key = trim(bc_state_gradient(pIndex,1)%state_name) VK call append(me = bc_varDict_gradient, val = kvp)
VK ! For the viscous terms ... VK ! ... the face values VK bc_trafo_gradient(1)%identity = .false. VK bc_normal_vec_gradient(1) = .true.
VK ! density for viscous terms VK bc_state_gradient(1,1) = bc_state(1) VK kvp%key = trim(bc_state_gradient(1,1)%state_name) VK call append(me = bc_varDict_gradient, val = kvp)
VK ! v_normal for viscous terms VK bc_state_gradient(2,1)%state_name = 'v_norm' VK bc_state_gradient(2,1)%style = 'dirichlet_mirror' VK bc_state_gradient(2,1)%isDefined = .true. VK kvp%key = trim(bc_state_gradient(2,1)%state_name) VK call append(me = bc_varDict_gradient, val = kvp)
VK ! v_tan for viscous terms VK bc_state_gradient(3,1)%state_name = 'v_tan' VK bc_state_gradient(3,1)%style = 'neumann' VK bc_state_gradient(3,1)%isDefined = .true. VK kvp%key = trim(bc_state_gradient(3,1)%state_name) VK call append(me = bc_varDict_gradient, val = kvp)
VK ! v_tan for viscous terms VK bc_state_gradient(4,1)%state_name = 'v_tan2' VK bc_state_gradient(4,1)%style = 'neumann' VK bc_state_gradient(4,1)%isDefined = .true. VK kvp%key = trim(bc_state_gradient(4,1)%state_name) VK call append(me = bc_varDict_gradient, val = kvp)
VK ! Energy for viscous terms VK bc_state_gradient(pIndex,1) = bc_state(pIndex) VK kvp%key = trim(bc_state_gradient(pIndex,1)%state_name) VK call append(me = bc_varDict_gradient, val = kvp)
VK ! add the conservative ones to varDict VK do iVar=1,pIndex VK kvp%key = trim(bc_state_gradient(iVar)%state_name) VK call append(me = bc_varDict_gradient, val = kvp) VK end do
VK VK ! For the viscous parts of the equation VK ! ... the face values VK bc_trafo_gradient(1)%identity = .false. VK bc_normal_vec_gradient(1) = .true.
VK bc_state_gradient(iVar, 1) = bc_state_gradient(iVar,2) VK kvp%key = trim(bc_state_gradient(iVar,1)%state_name) VK call append(me = bc_varDict_gradient, val = kvp) VK bc_trafo_gradient(1)%identity = .false. VK bc_normal_vec_gradient(1) = .true.
VK bc_state_gradient(iVar, 1) = bc_state_gradient(iVar,2) VK kvp%key = trim(bc_state_gradient(iVar,1)%state_name) VK call append(me = bc_varDict_gradient, val = kvp) VK bc_trafo_gradient(1)%identity = .false. VK bc_normal_vec_gradient(1) = .true.
VK bc_state_gradient(iVar,1) = bc_state_gradient(iVar,2) VK kvp%key = trim(bc_state_gradient(iVar,1)%state_name) VK call append(me = bc_varDict_gradient, val = kvp) VK bc_trafo_gradient(1)%identity = .false. VK bc_normal_vec_gradient(1) = .true.
VK bc_state_gradient(iVar,1) = bc_state_gradient(iVar,2) VK kvp%key = trim(bc_state_gradient(iVar,1)%state_name) VK call append(me = bc_varDict_gradient, val = kvp)
Arguments
Type Intent Optional Attributes Name
class(atl_Equations_type), intent(inout) :: equation
type(tem_bc_state_type), intent(out), allocatable :: bc_state(:)
type(tem_bc_state_type), intent(out), allocatable :: bc_state_gradient(:)
type(grw_stringkeyvaluepairarray_type), intent(out) :: bc_varDict
Dictionary of boundary variables in bc_state
type(grw_stringkeyvaluepairarray_type), intent(out) :: bc_varDict_gradient
Dictionary of boundary variables in bc_state_gradient
logical, intent(out) :: bc_normal_vec
logical, intent(out) :: bc_normal_vec_gradient
type(atl_eqn_var_trafo_type), intent(out) :: bc_trafo
type(atl_eqn_var_trafo_type), intent(out) :: bc_trafo_gradient
character(len=*), intent(in) :: bc_label
character(len=*), intent(in) :: bc_kind
integer, intent(in) :: thandle
type(flu_State) :: conf
Calls
Call graph
atl_eqn_nvrstk_load_bc calls append, init, atl_load_bc_state, tem_abort, truncate
atl_load_bc_state calls tem_load_bc_state