atl_append_euler_2d_derivedVars – Ateles
atl_append_euler_2d_derivedVars Subroutine
105 statements
Source File
public subroutine atl_append_euler_2d_derivedVars(varSys, solverData)
Arguments
Type Intent Optional Attributes Name
type(tem_varSys_type), intent(inout) :: varSys
type(atl_varSys_solverData_type), target :: solverData
the pointer to the data required for the varsys to fulfill all operations and derivations on the variables
Calls
Called by
Call graph
atl_append_euler_2d_derivedvars calls atl_get_new_varsys_data_ptr, outputappendresult, tem_get_new_varSys_data_ptr, tem_varSys_append_derVar
outputappendresult calls tem_abort
atl_init_euler_2d_vars calls atl_append_euler_2d_derivedvars
atl_eqn_euler_init calls atl_init_euler_2d_vars
atl_eqn_nvrstk_init calls atl_init_euler_2d_vars
atl_init_equation calls atl_eqn_euler_init, atl_eqn_nvrstk_init
atl_initialize calls atl_init_equation