atl_modg_2d_filNvrStk_physFlux_NonConst – Ateles
atl_modg_2d_filNvrStk_physFlux_NonConst Subroutine
31 statements
Source File
public subroutine atl_modg_2d_filNvrStk_physFlux_NonConst(equation, res, state, iElem, iDir, penalizationData, poly_proj, material, nodal_data, nodal_GradData, nodal_res, ElemLength, scheme_min, scheme_current)
Calculate the physical flux for the MODG scheme and Navier-Stokes equation (with non-constant penalizations).
Arguments
Type Intent Optional Attributes Name
type(atl_Equations_type), intent(in) :: equation
The equation you solve.
real(kind=rk), intent(inout) :: res(:,:)
To store the resulting phy flux in modal form
real(kind=rk), intent(in), optional :: state(:,:)
The state of the equation
integer, intent(in) :: iElem
The current Element
integer, intent(in) :: iDir
The current Direction
type(atl_penalizationData_type), intent(inout) :: penalizationData
The penalization data
type(ply_poly_project_type), intent(inout) :: poly_proj
Poly project
type(atl_material_type), intent(inout) :: material
Material description for the faces on the current level
real(kind=rk), intent(in), optional :: nodal_data(:,:)
The state in nodal form
real(kind=rk), intent(in), optional :: nodal_GradData(:,:,:)
real(kind=rk), intent(inout) :: nodal_res(:,:)
real(kind=rk), intent(in) :: ElemLength
Length of the element
type(atl_scheme_type), intent(inout) :: scheme_min
The scheme information
type(atl_scheme_type), intent(inout) :: scheme_current
Calls
Call graph
atl_modg_2d_filnvrstk_physflux_nonconst calls dertransformindices, atl_physfluxrans_2d, atl_viscphysfluxrans_2d, vartransformindices
atl_viscphysfluxrans_2d calls atl_get_lower_bound_turb_disscipation, atl_get_pointwise_velocity_gradient_2d, atl_get_pointwise_visc_stress_tensor_2d