atl_solve_program – Ateles
atl_solve_program Subroutine
91 statements
Source File
public subroutine atl_solve_program(params, equation, tree, nCellsNoBnd, element_container, poly_proj_list, precice_dt)
NE ! Dump and reset the timer after each Iteration NE call atl_dumpTimers(general = params%general, & NE & nElems = tree%global%nElems, & NE & nDofs = element_container%cubes & NE & %scheme_list(tree%global%minLevel) & NE & %nDofs, & NE & nVars = equation%varSys%nScalars) NE call atl_resetTimers()
Arguments
Type Intent Optional Attributes Name
type(atl_solver_param_type), intent(inout) :: params
type(atl_Equations_type), intent(inout) :: equation
type(treelmesh_type), intent(in) :: tree
integer, intent(inout) :: nCellsNoBnd(:)
type(atl_element_container_type), intent(inout) :: element_container
type(ply_poly_project_type), intent(inout) :: poly_proj_list(:)
real(kind=rk), intent(inout), optional :: precice_dt
Calls
Called by
Call graph
atl_solve_program calls bits, atl_check_val, atl_get_timestep, atl_inittimestepinfo, atl_kerneldata_update_estimates, atl_writerestartifnecessary, ply_sampled_track_output, tem_convergence_check, tem_horizontalSpacer, tem_opVar_reduction_transient_update, tem_precice_advance, tem_precice_ongoing, tem_simControl_clearStat, tem_simControl_dump_now, tem_simControl_syncUpdate, tem_startTimer, tem_status_run_end, tem_status_run_terminate, tem_stopTimer, tem_trackmem, val
ateles calls atl_solve_program