atl_modg_2d_set_bnd – Ateles
atl_modg_2d_set_bnd Subroutine
84 statements
Source File
public subroutine atl_modg_2d_set_bnd(bc, boundary, facedata, statedata, modg, equation, time, mesh, poly_proj, nodalBnd, material, currentLevel)
Subroutine to set face values to impose boundary conditions at a certain point of the domain. The subroutine is operating levelwise.
!!OMP PARALLEL & !!OMP PRIVATE(iBC, iDir, iAlign, iFace) & !!OMP DEFAULT(shared)
signfact = int(signfact * sidefact)
!!OMP END PARALLEL
Arguments
Type Intent Optional Attributes Name
type(atl_boundary_type), intent(in) :: bc(:)
The global description of the boundaries.
type(atl_level_boundary_type), intent(in) :: boundary
The levelwise collection of boundary elements and boundary faces.
type(atl_facedata_type), intent(inout) :: facedata
The face data on the current level
type(atl_statedata_type), intent(inout) :: statedata
The state data on the current level
type(atl_modg_2d_scheme_type), intent(inout) :: modg
The parameters of th the modg scheme.
type(atl_Equations_type), intent(in) :: equation
The underlying equation system
type(tem_time_type), intent(in) :: time
The absolute time point.
type(atl_cube_elem_type), intent(in) :: mesh
The description of the mesh on the current level.
type(ply_poly_project_type), intent(inout) :: poly_proj
Data for the projection methods
logical, intent(in) :: nodalBnd
Set boundaries in nodal fashion by default? If set to false, the boundaries may still be set in nodal way whenever necessary (e.g. boundaries which have space-time dependence, etc.)
type(atl_faceMaterialData_type), intent(in), optional :: material(2)
Material description of the faces contained in boundary. One entry for each spatial direction, i.e. x,y.
integer, intent(in) :: currentLevel
the level to compute on
Calls
Called by
Call graph
atl_modg_2d_set_bnd calls atl_modg_2d_bnd, val
atl_modg_2d_bnd calls modg_2d_modal_bnd, modg_2d_nodal_bnd, tem_abort
modg_2d_modal_bnd calls val, tem_abort, ply_poly_project_n2m, modg_2d_bnd_extrapolate, modg_2d_bnd_mirrorpoint
modg_2d_nodal_bnd calls val, tem_abort, ply_poly_project_m2n, ply_poly_project_n2m, modg_2d_bnd_extrapolate, modg_2d_bnd_mirrorpoint, ply_convert2oversample, ply_convertfromoversample
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
modg_2d_bnd_mirrorpoint calls val, get_valofindex, tem_startTimer, tem_stopTimer
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
preprocess_rhs_cubes calls atl_modg_2d_set_bnd
atl_preprocess_rhs calls preprocess_rhs_cubes
global_corrector_substep calls atl_preprocess_rhs
imexrk_substep calls atl_preprocess_rhs, imexrk_substep
mesh_timestep_euler calls atl_preprocess_rhs, mesh_timestep_euler
rk2_substep calls atl_preprocess_rhs, rk2_substep
rk4_substep calls atl_preprocess_rhs, rk4_substep
rktaylor_substep calls atl_preprocess_rhs, rktaylor_substep
mesh_timestep_imexrk calls imexrk_substep
mesh_timestep_predcor_cerk4 calls global_corrector_substep
mesh_timestep_rk4 calls rk4_substep
mesh_timestep_rktaylor calls rktaylor_substep
mesh_timestep_ssprk2 calls rk2_substep