atl_load_euler – Ateles
atl_load_euler Subroutine
46 statements
Source File
public subroutine atl_load_euler(euler, conf, eq_table)
Subroutine to initialize an equation of type euler equation as defined in the configuration file
Arguments
Type Intent Optional Attributes Name
type(atl_euler_type), intent(out) :: euler
Resulting description of the Euler equation parameters.
type(flu_State) :: conf
Handle to the configuration script, to load the parameters from.
integer, intent(in) :: eq_table
Handle to the table containing the description for the equation system.
Calls
Called by
Call graph
atl_load_euler calls aot_get_val, tem_abort
atl_eqn_euler_init calls atl_load_euler
atl_load_navierstokes calls atl_load_euler
atl_eqn_nvrstk_init calls atl_load_navierstokes
atl_init_equation calls atl_eqn_euler_init, atl_eqn_nvrstk_init, atl_eqn_filtered_nvrstk_init
atl_load_filtns calls atl_load_navierstokes
atl_eqn_filtered_nvrstk_init calls atl_load_filtns
atl_initialize calls atl_init_equation
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize