atl_init_elem_container – Ateles
atl_init_elem_container Subroutine
67 statements
Source File
public subroutine atl_init_elem_container(me, equation, conf, tree, time, readRestart, proc, commPattern, boundary)
Initialize the container module.
This routine builds up the necessary information as requested by the configuration in the Lua script conf.
Arguments
Type Intent Optional Attributes Name
type(atl_element_container_type), intent(inout) :: me
complete domain
type(atl_Equations_type), intent(inout) :: equation
Description of the equation system
type(flu_State) :: conf
Handle for the Lua config file
type(treelmesh_type), intent(inout) :: tree
The mesh in treelm format.
type(tem_time_type) :: time
Representation of the current time
logical, intent(in) :: readRestart
Should a restart be read?
type(tem_comm_env_type) :: proc
mpi communication environment with mpi communicator
type(tem_commPattern_type) :: commPattern
mpi communication pattern type
type(tem_BC_prop_type), intent(inout) :: boundary
Calls
Called by
Call graph
atl_init_elem_container calls init_tem_bc_prop, atl_init_facedata, load_tem, atl_global_time_integration_load, atl_init_cube_container, atl_init_global_time_integration, atl_init_physcheck, atl_init_scheme, init_kernel, tem_global_mesh_read
atl_initialize calls atl_init_elem_container
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program