atl_writeRestartIfNecessary – Ateles
atl_writeRestartIfNecessary Subroutine
24 statements
Source File
public subroutine atl_writeRestartIfNecessary(restart, simControl, equation, tree, mesh, force)
Writes a restart file, if necessary.
This routine checks whether writing restart files is activated at all. If so, it further checks whether a restart file has to be written at current point in time. If this also applies, a third check ensures that there wasn't already a restart file written for the current point in time.
Arguments
Type Intent Optional Attributes Name
type(tem_restart_type) :: restart
the restart infotmation
type(tem_simControl_type), intent(inout) :: simControl
type(atl_Equations_type), intent(in) :: equation
The equation system you use.
type(treelmesh_type) :: tree
mesh, provided in treelm format
type(atl_cube_container_type), intent(inout) :: mesh
Informations and states of the cubic mesh.
logical, optional :: force
Set this to true to override the restart interval check.
Calls
Called by
Call graph
atl_writerestartifnecessary calls bits, atl_writerestart, tem_getOptValOrDef, tem_simControl_dump_now, tem_timeControl_check
atl_writerestart calls serializedata, tem_restart_closeWrite, tem_restart_openWrite, tem_restart_writeData, tem_startTimer, tem_stopTimer
serializedata calls ply_transfer_dofs, tem_LevelOf, tem_abort
ply_transfer_dofs calls ply_transfer_dofs_1d, ply_transfer_dofs_2d, ply_transfer_dofs_3d
atl_finalize_program calls atl_writerestartifnecessary
atl_initialize_program calls atl_writerestartifnecessary
atl_solve_program calls atl_writerestartifnecessary
ateles calls atl_finalize_program, atl_initialize_program, atl_solve_program