atl_eqn_euler_implicit_pen – Ateles
atl_eqn_euler_implicit_pen Subroutine
138 statements
Source File
public subroutine atl_eqn_euler_implicit_pen(material, eqn, weighted_dt, ndims, poly_proj, state, timestep_rhs)
Solve the equation system with just the penalization terms to find an implicit update for the IMEX timestepping procedure.
Arguments
Type Intent Optional Attributes Name
type(atl_material_type), intent(in) :: material
Definition of the material, which directly describes the penalization.
We expect the mask function Chi to be defined in materialdat(:,:,1), the obstacle velocity U_o in materialdat(:,:,2:nDims+1) and the obstacle Temperature T_o in materialdat(:,:,nDims+2).
type(atl_euler_type), intent(in) :: eqn
Definition of parameters in the Euler equations.
This has to provide cv, the viscous permeability and the thermal permeability.
real(kind=rk), intent(in) :: weighted_dt
Timestep which is already weighted by the time integration scheme.
integer, intent(in) :: ndims
Number of dimensions, the equation system is computed in (2 or 3).
type(ply_poly_project_type), intent(inout) :: poly_proj
Description of the projection for the material.
real(kind=rk), intent(inout) :: state(:,:,:)
The state variables of the equation system, they will be updated to the solution of the implicit computation for penalization.
real(kind=rk), intent(out) :: timestep_rhs(:,:,:)
Right hand side contribution by the implicit calculation.
Calls
Called by
Call graph
atl_eqn_euler_implicit_pen calls ply_poly_project_m2n, ply_poly_project_n2m, ply_convert2oversample, ply_convertfromoversample
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
ply_poly_project_m2n_multivar calls ply_legtopnt_2d, ply_legtopnt_3d, ply_fxt_m2n_1d, ply_fxt_m2n_2d, ply_fxt_m2n_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d, ply_pnttoleg_3d, ply_fxt_n2m_1d, ply_fxt_n2m_2d, ply_fxt_n2m_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
implicit_update calls atl_eqn_euler_implicit_pen
mesh_timestep_imexrk calls implicit_update