atl_get_numBndElems – Ateles
atl_get_numBndElems Function
17 statements
Source File
public function atl_get_numBndElems(minLevel, maxLevel, boundary_list) result(nBndElems)
Get the number of (virtual) boundary elements for each level and each direction.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: minLevel
integer, intent(in) :: maxLevel
type(atl_level_boundary_type), intent(in) :: boundary_list(minLevel:maxLevel)
Boundary description for all levels.
Return Value integer, (minLevel:maxLevel,1:3)
The number of (virtual) boundary elements for each level and each spatial direction
Called by
Call graph
atl_init_modg_1d_kernel calls atl_get_numbndelems
atl_init_modg_2d_kernel calls atl_get_numbndelems
atl_init_modg_kernel calls atl_get_numbndelems
atl_stabilize calls atl_get_numbndelems
init_kernel calls atl_init_modg_1d_kernel, atl_init_modg_2d_kernel, atl_init_modg_kernel
mesh_timestep_euler calls atl_stabilize, mesh_timestep_euler
mesh_timestep_imexrk calls atl_stabilize
mesh_timestep_rk4 calls atl_stabilize
mesh_timestep_rktaylor calls atl_stabilize
mesh_timestep_ssprk2 calls atl_stabilize
atl_harvesting calls atl_stabilize
atl_init_elem_container calls init_kernel
atl_initialize calls atl_init_elem_container