atl_acoustic_numflux_cube_vec – Ateles
atl_acoustic_numflux_cube_vec Subroutine
18 statements
Source File
private subroutine atl_acoustic_numflux_cube_vec(nTotalFaces, nSides, nFaceDofs, faceRep, faceFlux, leftPos, rightPos, var, acoustic, idir)
VK leftstate = faceRep(left,iDof,var,2) VK rightstate = faceRep(right,iDof,var,1) VK VK ! call lax friedrich flux VK call atl_laxFriedAcoustic(left = leftstate, & VK & right = rightstate, & VK & acoustic = acoustic, & VK & flux = flux, & VK & iDir = idir) VK VK faceFlux(left,iDof,var,2) = flux
VK !upwind case (at the moment not needed, since U0=0) VK faceFlux(left, iDof,var,2)= faceRep(left,iDof,var,2) VK faceFlux(right,iDof,var,1) = faceFlux(left,iDof,var,2) VK
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nTotalFaces
integer, intent(in) :: nSides
integer, intent(in) :: nFaceDofs
real(kind=rk), intent(in) :: faceRep(nTotalFaces,nFaceDofs,4,2)
real(kind=rk), intent(inout) :: faceFlux(nTotalFaces,nFaceDofs,4,2)
integer, intent(in) :: leftPos(nSides)
integer, intent(in) :: rightPos(nsides)
integer, intent(in) :: var(4)
type(atl_acoustic_type), intent(in) :: acoustic
Datatype for acoustic equation include all background data
integer, intent(in) :: idir
Direction of the flow, used for background velocity
Calls
Called by
Call graph
atl_acoustic_numflux_cube_vec calls atl_acoustic_numflux_onedir
atl_acoustic_numflux calls atl_acoustic_numflux_cube_vec
atl_modg_acoustic_numflux calls atl_acoustic_numflux
compute_rhs_cubes_modg calls atl_modg_acoustic_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg