atl_op_divideVecByScal_forElement – Ateles
atl_op_divideVecByScal_forElement Subroutine
17 statements
Source File
public subroutine atl_op_divideVecByScal_forElement(fun, varSys, elempos, time, tree, nElems, nDofs, res)
Arguments
Type Intent Optional Attributes Name
class(tem_varSys_op_type), intent(in) :: fun
Description of the method to obtain the variables, here some preset values might be stored, like the space time function to use or the required variables.
type(tem_varSys_type), intent(in) :: varSys
The variable system to obtain the variable from.
integer, intent(in) :: elempos(:)
TreeID of the element to get the variable for.
type(tem_time_type), intent(in) :: time
Point in time at which to evaluate the variable.
type(treelmesh_type), intent(in) :: tree
global treelm mesh info
integer, intent(in) :: nElems
Number of values to obtain for this variable (vectorized access).
integer, intent(in) :: nDofs
Number of degrees of freedom within an element.
real(kind=rk), intent(out) :: res(:)
Resulting values for the requested variable.
Linearized array dimension: (n requested entries) x (nComponents of this variable) x (nDegrees of freedom) Access: (iElem-1)fun%nComponentsnDofs + (iDof-1)*fun%nComponents + iComp
Calls
Call graph
atl_op_dividevecbyscal_forelement calls atl_generic_frommodal_getelement
atl_generic_frommodal_getelement calls get_element, ply_poly_project_m2n, ply_poly_project_n2m, ply_convert2oversample, ply_convertfromoversample, ply_dof_2degree, tem_LevelOf, val
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
ply_dof_2degree calls ply_degree_2dof
ply_poly_project_m2n_multivar calls ply_legtopnt_2d, ply_legtopnt_3d, ply_fxt_m2n_1d, ply_fxt_m2n_2d, ply_fxt_m2n_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d, ply_pnttoleg_3d, ply_fxt_n2m_1d, ply_fxt_n2m_2d, ply_fxt_n2m_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d