atl_init_cellStateBuffer – Ateles
atl_init_cellStateBuffer Subroutine
119 statements
Source File
public subroutine atl_init_cellStateBuffer(scheme, nVars, levelDesc, nBndElems, commPattern)
Initialize the parallel module to make it usable in ATELES.
... cell states ... cell states ... cell states
Arguments
Type Intent Optional Attributes Name
type(atl_scheme_type), intent(in) :: scheme
the the data of the kernel on the current level.
integer, intent(in) :: nVars
the number of variables in our equation.
type(tem_levelDesc_type), intent(inout) :: levelDesc
the buffer for the cell state transfer you want to be initialized.
integer, intent(in) :: nBndElems
The number of boundary elements.
type(tem_commPattern_type), intent(in) :: commPattern
mpi communication pattern type
Calls
Called by
Call graph
atl_init_cellstatebuffer calls buf_real, elempos, val
atl_init_parallel_module calls atl_init_cellstatebuffer
atl_init_modg_1d_kernel calls atl_init_parallel_module
atl_init_modg_2d_kernel calls atl_init_parallel_module
atl_init_modg_kernel calls atl_init_parallel_module
init_kernel calls atl_init_modg_1d_kernel, atl_init_modg_2d_kernel, atl_init_modg_kernel
atl_init_elem_container calls init_kernel