atl_dumpWeights – Ateles
atl_dumpWeights Subroutine
27 statements
Source File
public subroutine atl_dumpWeights(tree)
Dump weights to a file.
Arguments
Type Intent Optional Attributes Name
type(treelmesh_type), intent(in) :: tree
Calls
Called by
Call graph
atl_dumpweights calls atl_getweights, tem_create_EndianSuffix, tem_dump_weights
atl_getweights calls tem_getTimerVal
atl_finalize_program calls atl_dumpweights
ateles calls atl_finalize_program