atl_init_cube_container – Ateles
atl_init_cube_container Subroutine
52 statements
Source File
public subroutine atl_init_cube_container(tree, boundary, cube_container, conf, equation, proc, commPattern, need_element_deviations)
Method to initialize a cube mesh by tree and boundary definitions obtained by treelm.
now we build the face information of our mesh. VK stencil is not required for modg, but for tracking
Arguments
Type Intent Optional Attributes Name
type(treelmesh_type), intent(inout) :: tree
The tree representation of your mesh.
type(tem_BC_prop_type), intent(in) :: boundary
The boundaries of your simulation domain
type(atl_cube_container_type), intent(inout) :: cube_container
The container with all cubic elements, generated with this routine.
type(flu_State), intent(in) :: conf
Handle for the Lua config file
type(atl_Equations_type), intent(inout) :: equation
The equation you are simulating.
type(tem_comm_env_type) :: proc
mpi communication environment with mpi communicator
type(tem_commPattern_type) :: commPattern
mpi communication pattern type
logical, intent(in) :: need_element_deviations
Calls
Called by
Call graph
atl_init_cube_container calls atl_define_schemestencil, atl_init_bndlist, atl_init_cube_elem, atl_init_elem_bnd, tem_build_face_info, tem_build_horizontalDependencies, tem_build_verticalDependencies, tem_cleanupDependencyArrays, tem_find_allElements, tem_horizontalSpacer, tem_init_elemLevels, tem_stencil_dump
atl_define_schemestencil calls init, tem_stencil_map_toTreelmDef
atl_init_bndlist calls atl_init_face_bnd, atl_load_bc
atl_init_cube_elem calls calc_barycoord
atl_init_elem_bnd calls append, init, nelems, nghelems, tem_abort
atl_init_face_bnd calls append, init, tem_abort, leftpos, rightpos
atl_load_bc calls tem_abort, aot_get_val, aot_table_close, aot_table_open, tem_load_bc_header
calc_barycoord calls tem_BaryOfId
atl_init_elem_container calls atl_init_cube_container
atl_initialize calls atl_init_elem_container
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program