atl_init_parallel_module – Ateles
atl_init_parallel_module Subroutine
33 statements
Source File
public subroutine atl_init_parallel_module(scheme, nValsElem, nValsStateFace, nValsFluxFace, cube, boundary, createCellBuffer, createFaceBuffer, createStabFaceBuffer, createStabElemBuffer, nBndStabElems, minLevel, maxLevel, commPattern)
initialize the parallel module to make it usable in ATELES
Arguments
Type Intent Optional Attributes Name
type(atl_scheme_type), intent(in) :: scheme(minLevel:maxLevel)
levelwise list of schemes.
integer, intent(in) :: nValsElem
the number of scalar values for each element.
integer, intent(in) :: nValsStateFace
the number of scalar values on the face for the state
integer, intent(in) :: nValsFluxFace
the number of scalar values on the face for the flux
type(atl_cube_elem_type), intent(inout) :: cube(minLevel:maxLevel)
list of cubic meshes you want to build the buffers for.
type(atl_level_boundary_type), intent(in) :: boundary(minLevel:maxLevel)
The boundary description for the faces on the current level.
logical, intent(in) :: createCellBuffer
Boolean to indicate if cell state buffers a required or not.
logical, intent(in) :: createFaceBuffer
Boolean to indicate if face buffers a required or not.
logical, intent(in) :: createStabFaceBuffer
Boolean to indicate if face buffers for stabilization are required or not.
logical, intent(in) :: createStabElemBuffer
Boolean to indicate if elem buffers for stabilization are required or not.
integer, intent(in) :: nBndStabElems(minLevel:maxLevel,1:3)
The number of boundary elements for the stabilization element buffer
integer, intent(in) :: minLevel
The minimal refinement level of your mesh.
integer, intent(in) :: maxLevel
The maximum refinement level of your mesh.
type(tem_commPattern_type), intent(in) :: commPattern
mpi communication pattern type
Calls
Called by
Call graph
atl_init_parallel_module calls dimbydimdesc, atl_init_cellstatebuffer, atl_init_facestatebuffer
atl_init_cellstatebuffer calls buf_real, elempos, val
atl_init_facestatebuffer calls buf_int, buf_real, elempos, recvbuffer_flux, recvbuffer_state, sendbuffer_flux, sendbuffer_state, val
atl_init_modg_1d_kernel calls atl_init_parallel_module
atl_init_modg_2d_kernel calls atl_init_parallel_module
atl_init_modg_kernel calls atl_init_parallel_module
init_kernel calls atl_init_modg_1d_kernel, atl_init_modg_2d_kernel, atl_init_modg_kernel
atl_init_elem_container calls init_kernel
atl_initialize calls atl_init_elem_container