atl_readRestart – Ateles
atl_readRestart Subroutine
63 statements
Source File
public subroutine atl_readRestart(mesh, restart, tree, equation, proc)
Read the serialized restart file into the state vectors
Arguments
Type Intent Optional Attributes Name
type(atl_cube_container_type), intent(inout) :: mesh
Informations and states of the cubic mesh.
type(tem_restart_type) :: restart
type(treelmesh_type) :: tree
mesh, provided in treelm format
type(atl_Equations_type), intent(in) :: equation
type(tem_comm_env_type), intent(in) :: proc
The schemes on the levels
Calls
Called by
Call graph
atl_readrestart calls aot_get_val, aot_table_close, aot_table_open, serializedata, tem_open_distconf, tem_restart_closeRead, tem_restart_openRead, tem_restart_readData, upper_to_lower
serializedata calls ply_transfer_dofs, tem_LevelOf, tem_abort
ply_transfer_dofs calls ply_transfer_dofs_1d, ply_transfer_dofs_2d, ply_transfer_dofs_3d
atl_initialize calls atl_readrestart
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program