atl_init_kerneldata – Ateles
atl_init_kerneldata Subroutine
30 statements
Source File
public subroutine atl_init_kerneldata(kerneldata, statedata, nTotal, nVars, nDofs, nDervQuant, time, maxPolyDegree, nDims, poly_space, need_deviation, need_maxgrad)
Subroutine to init the atl_kerneldata_type. This routine should be used in the init routine of the kernel, since the dimensions of the fields in the atl_kerneldata_type depend on the combination of scheme and equation.
Arguments
Type Intent Optional Attributes Name
type(atl_kerneldata_type), intent(inout) :: kerneldata
The data type to initialize.
type(atl_statedata_type), intent(inout) :: statedata
The data type to initialize.
integer, intent(in) :: nTotal
The total number of cells (including only fluid, ghost, halo and boundary cells).
integer, intent(in) :: nVars
The number of scalar variables of the current equation.
integer, intent(in) :: nDofs
The number of degrees of freedom per scalar variable of your equation.
integer, intent(in) :: nDervQuant
The number of derived quantities the kernel will use in the future.
type(tem_time_type), intent(in) :: time
current time
integer, intent(in) :: maxPolyDegree
The maximal polynomial degree in each spatial direction.
integer, intent(in) :: nDims
Number of dimensions for the polynomials in the kerneldata.
integer, intent(in) :: poly_space
Kind of tensor product used to represent multidimensional polynomials in this kerneldata.
logical, intent(in) :: need_deviation
Should the maximal deviation be computed for the state?
logical, intent(in) :: need_maxgrad
Should the maximal gradient be computed for the state?
Calls
Called by
Call graph
atl_init_kerneldata calls atl_init_statedata
atl_init_modg_1d_kernel calls atl_init_kerneldata
atl_init_modg_2d_kernel calls atl_init_kerneldata
atl_init_modg_kernel calls atl_init_kerneldata
init_kernel calls atl_init_modg_1d_kernel, atl_init_modg_2d_kernel, atl_init_modg_kernel
atl_init_elem_container calls init_kernel
atl_initialize calls atl_init_elem_container