atl_append_euler_1d_derivedVars – Ateles
atl_append_euler_1d_derivedVars Subroutine
92 statements
Source File
public subroutine atl_append_euler_1d_derivedVars(varSys, solverData)
Arguments
Type Intent Optional Attributes Name
type(tem_varSys_type), intent(inout) :: varSys
The Euler variable system to modify. It has to contain the conservative and primitive variables already.
type(atl_varSys_solverData_type), target :: solverData
the pointer to the data required for the varsys to fulfill all operations and derivations on the variables
Calls
Called by
Call graph
atl_append_euler_1d_derivedvars calls atl_get_new_varsys_data_ptr, tem_abort, tem_get_new_varSys_data_ptr, tem_varSys_append_derVar
atl_init_euler_1d_vars calls atl_append_euler_1d_derivedvars
atl_eqn_euler_init calls atl_init_euler_1d_vars
atl_init_equation calls atl_eqn_euler_init
atl_initialize calls atl_init_equation