atl_init_materialParams – Ateles
atl_init_materialParams Subroutine
132 statements
Source File
public subroutine atl_init_materialParams(equation, tree, varSys_data, material_list, mesh_list, scheme_list, boundary_list, time, conf, proc, commPattern, poly_proj_list, levelPointer, initMaterial)
Read the configuration for the material paramters for Maxwell equations from configuration files and init the material parameter datatype.
Arguments
Type Intent Optional Attributes Name
type(atl_Equations_type), intent(inout) :: equation
Description on the equation system to solve.
type(treelmesh_type), intent(in) :: tree
Mesh data in treelmesh format.
type(atl_varSys_solverData_type), intent(inout) :: varSys_data
Data in variable system
type(atl_material_type), intent(inout) :: material_list(tree%global%minLevel:tree%global%maxLevel)
The description of the material properties. The compute lists in the material description is filled up by calling this subroutine.
type(atl_cube_elem_type), intent(inout) :: mesh_list(tree%global%minLevel:tree%global%maxLevel)
Description of the mesh
type(atl_scheme_type), intent(in) :: scheme_list(tree%global%minLevel:tree%global%maxLevel)
Information about the scheme
type(atl_level_boundary_type), intent(in) :: boundary_list(tree%global%minLevel:tree%global%maxLevel)
Global description of the boundary conditions.
type(tem_time_type), intent(in) :: time
The current simulation time
type(flu_State), intent(inout) :: conf
Flu binding to configuration file.
type(tem_comm_env_type), intent(inout) :: proc
mpi communication environment with mpi communicator
type(tem_commPattern_type), intent(inout) :: commPattern
mpi communication pattern type
type(ply_poly_project_type), intent(inout) :: poly_proj_list(:)
unique list for projection methods
integer, intent(in) :: levelPointer(:)
Pointer from treeIDlist entry to level-wise fluid part of total list. The length of this vector is the total number of cubic elements.
type(atl_init_material_type) :: initMaterial
Information about expected material parameters and the user defined variables to the expected material parameters.
Calls
Called by
Call graph
atl_init_materialparams calls aot_get_val, aot_table_close, aot_table_open, buf_int, elempos, faces, init, nelemsproc, atl_append_newmaterialvars, atl_assign_elem_varprop, atl_assign_face_matprp, atl_create_materialboundarylist, atl_create_materialcomputelist, atl_create_materialelemlist, atl_evalelemmaterial, atl_evalfacematerial, atl_getmaxpropspeed, atl_getmaxpropspeeddivcor, atl_init_facestatebuffer, atl_reassignstfunptr, recvbuffer_state, sendbuffer_state, tem_abort, tem_horizontalSpacer, tem_variable_loadMapping, val
atl_initialize calls atl_init_materialparams
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program