atl_initRestart – Ateles
atl_initRestart Subroutine
25 statements
Source File
public subroutine atl_initRestart(restart, equation, solver, mesh, tree, nDofsIO, scheme_dim)
Initializes writing restart files, if activated.
Prepares the solver specific information for the restart header and calls initialization of underlying restart functionality in treelm.
Arguments
Type Intent Optional Attributes Name
type(tem_restart_type), intent(inout) :: restart
Description of the restart structure to initialize.
type(atl_Equations_type), intent(in) :: equation
The variable system of the current equation system.
type(tem_solveHead_type), intent(in) :: solver
General description of the deployed solver.
type(atl_cube_container_type), intent(in) :: mesh
Levelwise representation of the mesh.
type(treelmesh_type), intent(in) :: tree
The octree of the mesh.
integer, intent(in) :: nDofsIO
The number of degrees of freedoms to write to/read from a restart file
integer, intent(in) :: scheme_dim
Dimensionality to be used for the state fields.
Calls
Called by
Call graph
atl_initrestart calls newunit, atl_writesolverspecinfo, tem_create_varMap, tem_init_restart, val
atl_writesolverspecinfo calls aot_out_close, aot_out_close_table, aot_out_open, aot_out_open_table, aot_out_val, tem_abort
atl_initialize calls atl_initrestart
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program