atl_modg_viscNavierStokes_oneDim_numFlux – Ateles
atl_modg_viscNavierStokes_oneDim_numFlux Subroutine
66 statements
Source File
public subroutine atl_modg_viscNavierStokes_oneDim_numFlux(equation, facedata, scheme, faces, faceDir, poly_proj, elemLength)
Numerical flux calculation for viscous part of the Navier-Stokes equation across the faces in a single spatial direction.
Arguments
Type Intent Optional Attributes Name
type(atl_Equations_type), intent(in) :: equation
The equation you solve.
type(atl_facedata_type), intent(inout) :: facedata
The face state if the equation
type(atl_modg_scheme_type), intent(in) :: scheme
Parameters of the modal dg scheme
type(tem_faceIterator_type), intent(in) :: faces
The faces to calculate the fluxes for.
integer, intent(in) :: faceDir
The spatial direction of the faces you calc the fluxes for, use the following: 1 --> x direction. \n 2 --> y direction. \n 3 --> z direction.
type(ply_poly_project_type), intent(inout) :: poly_proj
Parameter for used projection
real(kind=rk), intent(in) :: elemLength
The length of an element
Calls
Called by
Call graph
atl_modg_viscnavierstokes_onedim_numflux calls dertransformindices, ply_poly_project_m2n, ply_poly_project_n2m, alt_get_penaltyip, atl_viscnavierstokes, ply_convert2oversample, vartransformindices
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
atl_viscnavierstokes calls atl_viscphysfluxnavierstokes
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_poly_project_m2n_multivar calls ply_legtopnt_2d, ply_legtopnt_3d, ply_fxt_m2n_1d, ply_fxt_m2n_2d, ply_fxt_m2n_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d, ply_pnttoleg_3d, ply_fxt_n2m_1d, ply_fxt_n2m_2d, ply_fxt_n2m_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
atl_modg_filnvrstk_numflux calls atl_modg_viscnavierstokes_onedim_numflux
atl_modg_navierstokes_numflux calls atl_modg_viscnavierstokes_onedim_numflux
compute_rhs_cubes_modg calls atl_modg_filnvrstk_numflux, atl_modg_navierstokes_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg
atl_compute_rhs calls compute_rhs_cubes