atl_append_rans_consVars – Ateles
atl_append_rans_consVars Subroutine
20 statements
Source File
public subroutine atl_append_rans_consVars(equation, solverData)
Arguments
Type Intent Optional Attributes Name
type(atl_Equations_type), intent(inout) :: equation
The equation type.
type(atl_varSys_solverData_type), target :: solverData
the pointer to the data required for the varsys
Calls
Called by
Call graph
atl_append_rans_consvars calls atl_get_new_varsys_data_ptr, tem_varSys_append_stateVar
atl_init_rans_2d_vars calls atl_append_rans_consvars
atl_init_rans_vars calls atl_append_rans_consvars
atl_eqn_filtered_nvrstk_init calls atl_init_rans_2d_vars, atl_init_rans_vars
atl_init_equation calls atl_eqn_filtered_nvrstk_init
atl_initialize calls atl_init_equation