atl_load_projection – Ateles
atl_load_projection Subroutine
96 statements
Source File
public subroutine atl_load_projection(minLevel, maxLevel, equation, poly_proj_pos, dynprojectArray, conf, scheme_list, source_projPos, boundary_list, boundary_list_stab, ic_pos_list, material_list)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: minLevel
integer, intent(in) :: maxLevel
type(atl_Equations_type), intent(in) :: equation
integer, intent(inout) :: poly_proj_pos(minlevel:maxLevel)
type(dyn_projectionarray_type), intent(inout) :: dynprojectArray
type(flu_State), intent(in) :: conf
type(atl_scheme_type), intent(in) :: scheme_list(minlevel:maxLevel)
integer, intent(inout) :: source_projPos(minlevel:maxLevel)
The levelwise positions of the projections that has to be used for the sources
type(atl_level_boundary_type), intent(inout) :: boundary_list(minlevel:maxLevel)
type(atl_level_boundary_type), intent(inout) :: boundary_list_stab(minlevel:maxLevel)
integer, intent(inout), allocatable :: ic_pos_list(:)
type(atl_material_type), intent(inout) :: material_list(minlevel:maxLevel)
Calls
Called by
Call graph
atl_load_projection calls aot_table_close, aot_table_open, append, atl_load_general_projection, atl_load_subprojection
append calls append_da_projection, append_da_vecprojection
atl_load_general_projection calls ply_fill_dynprojectarray, tem_abort
atl_load_subprojection calls aot_table_close, aot_table_open, ply_fill_dynprojectarray
append_da_projection calls expand, sortedposofval
append_da_vecprojection calls expand
ply_fill_dynprojectarray calls append, ply_prj_header_load, ply_prj_init_define
expand calls expand_da_projection
sortedposofval calls sortposofval_projection
ply_prj_header_load calls tem_abort, aot_get_val, ply_fpt_header_display, ply_fpt_header_load, ply_fxt_header_display, ply_fxt_header_load, ply_l2p_header_display, ply_l2p_header_load, upper_to_lower
atl_initialize calls atl_load_projection
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program