atl_modg_project_PhysFlux_testFunc – Ateles
atl_modg_project_PhysFlux_testFunc Subroutine
38 statements
Source File
public subroutine atl_modg_project_PhysFlux_testFunc(mesh, equation, kerneldata, scheme, iDir, dl_prod, dirVec, iElem, state_der)
Subroutine to project modal representations of physical flux, numerical flux and source terms onto test functions.
Arguments
Type Intent Optional Attributes Name
type(atl_cube_elem_type), intent(in) :: mesh
Descritption of the cubical elements in the mesh
type(atl_Equations_type), intent(in) :: equation
The equation description.
type(atl_kerneldata_type), intent(inout) :: kerneldata
The data of the kernel. Holds the physical fluxes.
type(atl_modg_scheme_type), intent(in) :: scheme
The parameters of the MODG scheme
integer, intent(in) :: iDir
The direction
real(kind=rk), intent(in) :: dl_prod(2,scheme%maxPolyDegree+1)
stored scalar products of the testfunction and ansatz function
integer, intent(in) :: dirVec(3,3)
vector for direction indicators
integer, intent(in) :: iElem
real(kind=rk), intent(in) :: state_der(kerneldata%nDofs,equation%varSys%nScalars)
Calls
Called by
Call graph
atl_modg_project_physflux_testfunc calls modg_prj_pflux1_q_5, modg_prj_pflux1_q_6, modg_prj_pflux2_q_5, modg_prj_pflux2_q_6, modg_prj_pflux3_q_5, modg_prj_pflux3_q_6, modg_project_physflux_p, modg_project_physflux_q
modg_project_physflux_p calls ply_scalprodduallegdiff
modg_project_physflux_q calls ply_scalprodduallegdiff
modg_compute_project_physflux calls atl_modg_project_physflux_testfunc
compute_rhs_cubes_modg calls modg_compute_project_physflux
compute_rhs_cubes calls compute_rhs_cubes_modg
atl_compute_rhs calls compute_rhs_cubes