atl_load_general_projection – Ateles
atl_load_general_projection Subroutine
26 statements
Source File
private subroutine atl_load_general_projection(poly_proj_pos, dynprojectArray, minLevel, maxLevel, scheme_list, conf, parent)
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: poly_proj_pos(minlevel:maxLevel)
type(dyn_projectionarray_type), intent(inout) :: dynprojectArray
integer, intent(in) :: minLevel
integer, intent(in) :: maxLevel
type(atl_scheme_type), intent(in) :: scheme_list(minlevel:maxLevel)
type(flu_State), intent(in) :: conf
integer, intent(in) :: parent
Calls
Called by
Call graph
atl_load_general_projection calls ply_fill_dynprojectarray, tem_abort
ply_fill_dynprojectarray calls append, ply_prj_header_load, ply_prj_init_define
append calls append_da_projection, append_da_vecprojection
ply_prj_header_load calls tem_abort, aot_get_val, ply_fpt_header_display, ply_fpt_header_load, ply_fxt_header_display, ply_fxt_header_load, ply_l2p_header_display, ply_l2p_header_load, upper_to_lower
append_da_projection calls expand, sortedposofval
append_da_vecprojection calls expand
ply_fpt_header_load calls tem_abort, aot_get_val, upper_to_lower
ply_fxt_header_load calls tem_abort, aot_get_val
ply_l2p_header_load calls tem_abort, aot_get_val, upper_to_lower
atl_load_projection calls atl_load_general_projection
atl_initialize calls atl_load_projection
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program