atl_read_precice – Ateles
atl_read_precice Subroutine
44 statements
Source File
public subroutine atl_read_precice(stFunList, tree)
loop over linked list of spacetimefunction set the current to head loop over all shapes of that spacetimefunction check if there is a precice kind get the number of unquie points (xyz should be same number)
Arguments
Type Intent Optional Attributes Name
type(tem_st_fun_linkedList_type), intent(inout), target :: stFunList
This list contains all space-time-function
type(treelmesh_type), intent(in) :: tree
treelm mesh
Calls
Called by
Call graph
atl_read_precice calls pntlvl, posids, tem_precice_set_vertices_pos
atl_init_precice calls atl_read_precice
atl_initialize calls atl_init_precice
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program