atl_get_lower_bound_turb_disscipation – Ateles
atl_get_lower_bound_turb_disscipation Subroutine
29 statements
Source File
public subroutine atl_get_lower_bound_turb_disscipation(S, c_mu, omega, omega_r)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: S(2,2)
real(kind=rk), intent(in) :: c_mu
real(kind=rk), intent(in) :: omega
real(kind=rk), intent(out) :: omega_r
Called by
Call graph
atl_viscphysfluxrans_2d calls atl_get_lower_bound_turb_disscipation
eval_source_rans2d calls atl_get_lower_bound_turb_disscipation
atl_modg_2d_filnvrstk_physflux_const calls atl_viscphysfluxrans_2d
atl_modg_2d_filnvrstk_physflux_nonconst calls atl_viscphysfluxrans_2d
atl_viscrans_2d calls atl_viscphysfluxrans_2d
modg_2d_viscrans_onedim_numflux calls atl_viscrans_2d
atl_modg_2d_filnvrstk_numflux calls modg_2d_viscrans_onedim_numflux