atl_write_precice – Ateles
atl_write_precice Subroutine
39 statements
Source File
public subroutine atl_write_precice(stFunList, varSys, time, tree)
loop over linked list of spacetimefunction set the current to head loop over all shapes of that spacetimefunction check if there is a precice kind
check if this one has write flag get the number of unquie points (xyz should be same number) loop over the variables to write to precice Get_point routine for unquie array of points of that variable. Since the unique list of points is stored before, through the setup indices, we know depending on which kind of points we use, how many points we have. Thus we always access the right number of points, therefore we just have to call getvalofIndex just once independent from what kind of points we take for write to precice. write the scalar value to precice
Arguments
Type Intent Optional Attributes Name
type(tem_st_fun_linkedList_type), intent(inout), target :: stFunList
This list contains all space-time-function
type(tem_varSys_type), intent(in) :: varSys
Global variable system
type(tem_time_type), intent(in) :: time
The current absolute time.
type(treelmesh_type), intent(in) :: tree
treelm mesh
Calls
Called by
Call graph
atl_write_precice calls get_valofindex, ids, indexlvl, posids, tem_precice_write, varpos
atl_init_precice calls atl_write_precice
mesh_timestep_imexrk calls atl_write_precice
mesh_timestep_rk4 calls atl_write_precice
mesh_timestep_rktaylor calls atl_write_precice
mesh_timestep_ssprk2 calls atl_write_precice
atl_initialize calls atl_init_precice
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program