atl_eqn_euler_init – Ateles
atl_eqn_euler_init Subroutine
38 statements
Source File
public subroutine atl_eqn_euler_init(conf, thandle, equation, nDimensions, initSource, initMaterial, varSys_data)
Initialization of the Euler equation.
This routine sets up the necessary infrastructure for the Euler equations. It reads the configuration from the given script in conf under the table provided in thandle and sets function pointers and variables accordingly.
Arguments
Type Intent Optional Attributes Name
type(flu_State), intent(in) :: conf
Handle to the Lua configuration
integer, intent(in) :: thandle
Handle to the equation table in the Lua script given in conf.
type(atl_Equations_type), intent(inout) :: equation
Equation system to set with this routine.
integer, intent(in) :: nDimensions
Number of spatial dimensions, the Euler equations should live on.
Has to be 1, 2 or 3.
type(atl_init_source_type), intent(inout) :: initSource
Type to be filled with the possible source variables for the equation system. These source variables are later on used to extract the corresponding information from the configuration file.
type(atl_init_material_type), intent(inout) :: initMaterial
Type to be filled with the possible material variables for the equation system. These material variables are later on used to extract the corresponding information from the configuration file.
type(atl_varSys_solverData_type), intent(inout) :: varSys_data
the pointer to the data required for the varsys
Calls
Called by
Call graph
atl_eqn_euler_init calls atl_geteulerfluxes, atl_geteulerlinind, atl_init_euler_1d_sourceterms, atl_init_euler_1d_vars, atl_init_euler_2d_sourceterms, atl_init_euler_2d_vars, atl_init_euler_material, atl_init_euler_sourceterms, atl_init_euler_vars, atl_load_euler
atl_geteulerfluxes calls aot_get_val, tem_abort, upper_to_lower
atl_geteulerlinind calls aot_get_val, tem_abort, upper_to_lower
atl_init_euler_1d_sourceterms calls append, init
atl_init_euler_1d_vars calls atl_append_euler_1d_consvars, atl_append_euler_1d_derivedvars, atl_append_euler_1d_primvars, tem_varSys_init
atl_init_euler_2d_sourceterms calls append, init, truncate
atl_init_euler_2d_vars calls atl_append_euler_2d_consvars, atl_append_euler_2d_derivedvars, atl_append_euler_2d_primvars, tem_varSys_init
atl_init_euler_material calls append, init
atl_init_euler_sourceterms calls append, init
atl_init_euler_vars calls atl_append_euler_consvars, atl_append_euler_derivedvars, atl_append_euler_primvars, tem_varSys_init
atl_load_euler calls aot_get_val, tem_abort
atl_init_equation calls atl_eqn_euler_init
atl_initialize calls atl_init_equation
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program