atl_dump_materialFun – Ateles
atl_dump_materialFun Subroutine
14 statements
Source File
public subroutine atl_dump_materialFun(conf, material, key, varSys)
Dump material description to lua file
Arguments
Type Intent Optional Attributes Name
type(aot_out_type) :: conf
type(atl_materialFun_type), intent(in) :: material
character(len=*), intent(in) :: key
type(tem_varSys_type), intent(in) :: varSys
The variable system that contains the material variables
Calls
Called by
Call graph
atl_dump_materialfun calls aot_out_close_table, aot_out_open_table, aot_out_val, input_varpos, stripmatprefix, val
atl_eqn_write calls atl_dump_materialfun