atl_init_equation – Ateles
atl_init_equation Subroutine
104 statements
Source File
public subroutine atl_init_equation(equation, conf, varSys_data, initSource, initMaterial)
This subroutine reads the equation system to solve from the configuration.
It creates the necessary data structures and sets the required values according to the configuration.
Todo
All equation specific initialization routines should have a default
Arguments
Type Intent Optional Attributes Name
type(atl_Equations_type), intent(out) :: equation
Equation system to set with this routine.
type(flu_State), intent(in) :: conf
Handle to the Lua configuration
type(atl_varSys_solverData_type), intent(inout) :: varSys_data
the pointer to the data required for the varsys
type(atl_init_source_type), intent(inout) :: initSource
Type to be filled with the possible source variables for the equation system. These source variables are later on used to extract the corresponding information from the configuration file.
type(atl_init_material_type), intent(inout) :: initMaterial
Type to be filled with the possible material variables for the equation system. These material variables are later on used to extract the corresponding information from the configuration file.
Calls
Called by
Call graph
atl_init_equation calls aot_get_val, aot_table_close, aot_table_open, atl_eqn_acoustic_init, atl_eqn_advection_1d_init, atl_eqn_euler_init, atl_eqn_filtered_nvrstk_init, atl_eqn_heat_init, atl_eqn_lineareuler_init, atl_eqn_maxwell_init, atl_eqn_nvrstk_init, atl_init_nerplanck_vars, atl_initcoordinaterotations, atl_load_bbmem, atl_load_nernstplanck, tem_abort, upper_to_lower
atl_initialize calls atl_init_equation
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program