atl_modg_maxwellDivCor_numFlux – Ateles
atl_modg_maxwellDivCor_numFlux Subroutine
45 statements
Source File
public subroutine atl_modg_maxwellDivCor_numFlux(equation, facedata, scheme, poly_proj, material)
Calculate the numerical flux for Maxwell equation with hyperbolic divergence cleaning and MODG scheme
Arguments
Type Intent Optional Attributes Name
type(atl_Equations_type), intent(in) :: equation
The equation you solve.
type(atl_facedata_type), intent(inout) :: facedata
The face representation of the state.
type(atl_modg_scheme_type), intent(inout) :: scheme
Parameters of the modal dg scheme
type(ply_poly_project_type), intent(inout) :: poly_proj
Data for projection method
type(atl_material_type), intent(inout) :: material
Material description for the faces on the current level
Calls
Called by
Call graph
atl_modg_maxwelldivcor_numflux calls atl_maxwell_hc_flux, tem_abort, vartransformindices
atl_maxwell_hc_flux calls maxwell_hc_flux_cube, maxwell_hc_flux_cube_vec, maxwell_hc_flux_nonconst_cube_vec
maxwell_hc_flux_cube calls atl_physfluxmaxwelldivcor
maxwell_hc_flux_cube_vec calls atl_physfluxmaxwelldivcor
maxwell_hc_flux_nonconst_cube_vec calls maxwell_hc_flux_cube, ply_poly_project_m2n, ply_poly_project_n2m, ply_convert2oversample, ply_convertfromoversample
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
compute_rhs_cubes_modg calls atl_modg_maxwelldivcor_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg
atl_compute_rhs calls compute_rhs_cubes
global_corrector_substep calls atl_compute_rhs
imexrk_substep calls atl_compute_rhs
mesh_timestep_euler calls atl_compute_rhs
rk2_substep calls atl_compute_rhs
rk4_substep calls atl_compute_rhs
rktaylor_substep calls atl_compute_rhs