atl_init_nerplanck_vars – Ateles
atl_init_nerplanck_vars Subroutine
8 statements
Source File
public subroutine atl_init_nerplanck_vars(varSys, hasPrimitiveVariables, methodData)
Arguments
Type Intent Optional Attributes Name
type(tem_varSys_type), intent(out) :: varSys
logical, intent(out) :: hasPrimitiveVariables
type(atl_varSys_solverData_type) :: methodData
Calls
Called by
Call graph
atl_init_nerplanck_vars calls atl_append_nerplanck_vars, tem_varSys_init
atl_append_nerplanck_vars calls atl_get_new_varsys_data_ptr, tem_varSys_append_stateVar
atl_init_equation calls atl_init_nerplanck_vars
atl_initialize calls atl_init_equation
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program