atl_viscPhysFluxRans – Ateles
atl_viscPhysFluxRans Function
35 statements
Source File
public function atl_viscPhysFluxRans(state, state_gradient, isenCoeff, mu, lambda, thermCond, heatCap) result(physFlux)
Physical flux calculation along x direction for Euler equation.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: state(:)
The state in nodal space. Dimension is the number of vars, i.e. 5 for Navier-Stokes.
real(kind=rk), intent(in) :: state_gradient(:,:)
The state in nodal space. First dimension is the number of vars, i.e. 5 for Navier-Stokes. Second dimension is the dimension, e.g. 3 in two dimensions.
real(kind=rk), intent(in) :: isenCoeff
Adiabatice index, also known as isentropic expansion factor.
real(kind=rk), intent(in) :: mu
Dynamic Viscosity
real(kind=rk), intent(in) :: lambda
Viscosity
real(kind=rk), intent(in) :: thermCond
The thermal cond
real(kind=rk), intent(in) :: heatCap
The specific heat capacity (per mass unit mass, at constant volume)
Return Value real(kind=rk), (7)
The physical flux along the x axis for all variables
Calls
Called by
Call graph
atl_viscphysfluxrans calls tem_abort
atl_modg_filnvrstk_physflux_const calls atl_viscphysfluxrans
atl_modg_filnvrstk_physflux_nonconst calls atl_viscphysfluxrans