atl_load_solver_parameters – Ateles
atl_load_solver_parameters Subroutine
12 statements
Source File
public subroutine atl_load_solver_parameters(me, tree)
Routine to initialize the global parameters, sets the solver module variable.
Subroutine to initialize the global parameters like simulation name, etc. as specified in the given lua configuration file. The configuration file is passed as a handle to this subroutine.
Todo
HK: this is strange, the array of conf, should probably be moved somewhere else.
Arguments
Type Intent Optional Attributes Name
type(atl_solver_param_type), intent(inout) :: me
type(treelmesh_type), intent(inout) :: tree
Calls
Called by
Call graph
atl_load_solver_parameters calls conf, ply_sampled_tracking_load, tem_debug_load_main, tem_load_general, tem_load_restart, tem_logging_load_primary, tem_timeControl_start_at_sim
ply_sampled_tracking_load calls ply_sampling_load, tem_load_tracking
ply_sampling_load calls aot_get_val, aot_table_close, aot_table_open, ply_sampling_adaptive_load, tem_abort, upper_to_lower
ply_sampling_adaptive_load calls aot_get_val, tem_abort, upper_to_lower, ply_filter_element_load
atl_load_config calls atl_load_solver_parameters
ateles calls atl_load_config
atl_harvesting calls atl_load_config