atl_update_materialParams – Ateles
atl_update_materialParams Subroutine
16 statements
Source File
public subroutine atl_update_materialParams(equation, mesh, scheme, boundary, material, time, poly_proj, proc, commPattern)
Read the configuration for the material paramters for Maxwell equations from configuration files and init the material parameter datatype.
Arguments
Type Intent Optional Attributes Name
type(atl_Equations_type), intent(inout) :: equation
Description on the equation system to solve.
type(atl_cube_elem_type), intent(inout) :: mesh
Description of the mesh
type(atl_scheme_type), intent(in) :: scheme
Information about the scheme
type(atl_level_boundary_type), intent(in) :: boundary
Global description of the boundary conditions.
type(atl_material_type), intent(inout) :: material
The description of the material properties. The compute lists in the material description is filled up by calling this subroutine.
type(tem_time_type), intent(in) :: time
The current simulation time
type(ply_poly_project_type), intent(inout) :: poly_proj
unique list for projection methods
type(tem_comm_env_type), intent(inout) :: proc
mpi communication environment with mpi communicator
type(tem_commPattern_type), intent(inout) :: commPattern
mpi communication pattern type
Calls
Called by
Call graph
atl_update_materialparams calls atl_create_materialboundarylist, atl_evalelemmaterial, atl_evalfacematerial
atl_create_materialboundarylist calls append, init, pnttid, tem_abort, tem_startTimer, tem_stopTimer, val
atl_evalelemmaterial calls neigh, nelems, nghelems, pnttid, atl_reftophyscoord, tem_abort, tem_spacetime_for, tem_startTimer, tem_stopTimer
atl_evalfacematerial calls facepos, leftpos, nelems, pnttid, atl_reftophyscoord, ply_get_quadpoints_faces, ply_get_quadpoints_faces_1d, ply_get_quadpoints_faces_2d, rightpos, tem_abort, tem_spacetime_for, tem_startTimer, tem_stopTimer
atl_preprocess_modg_1d_kernel calls atl_update_materialparams
atl_preprocess_modg_2d_kernel calls atl_update_materialparams
atl_preprocess_modg_kernel calls atl_update_materialparams
preprocess_local_rhs_cubes calls atl_preprocess_modg_kernel
preprocess_rhs_cubes calls atl_preprocess_modg_1d_kernel, atl_preprocess_modg_2d_kernel, atl_preprocess_modg_kernel
atl_preprocess_local_rhs calls preprocess_local_rhs_cubes
atl_preprocess_rhs calls preprocess_rhs_cubes
global_corrector_substep calls atl_preprocess_rhs
imexrk_substep calls atl_preprocess_rhs
local_predictor_substep calls atl_preprocess_local_rhs
mesh_timestep_euler calls atl_preprocess_rhs
rk2_substep calls atl_preprocess_rhs
rk4_substep calls atl_preprocess_rhs
rktaylor_substep calls atl_preprocess_rhs