atl_fill_BCIndex – Ateles
atl_fill_BCIndex Subroutine
60 statements
Source File
public subroutine atl_fill_BCIndex(tree, bc, boundary_list, nDim, varSys, poly_proj_list, mesh_list)
Arguments
Type Intent Optional Attributes Name
type(treelmesh_type), intent(in) :: tree
global treelm mesh info
type(atl_boundary_type), intent(inout) :: bc(:)
Global description of all boundaries
type(atl_level_boundary_type), intent(in) :: boundary_list(tree%global%minLevel:tree%global%maxLevel)
The created boundary information.
integer, intent(in) :: nDim
type(tem_varSys_type), intent(in) :: varSys
The variable system to obtain the variable from.
type(ply_poly_project_type), intent(inout), target :: poly_proj_list(:)
unique list for projection methods
type(atl_cube_elem_type), intent(in) :: mesh_list(tree%global%minLevel:tree%global%maxLevel)
The mesh you are using.
Calls
Called by
Call graph
atl_fill_bcindex calls append, indexlvl, atl_get_points_from_bc, set_params, setup_indices
atl_get_points_from_bc calls atl_reftophyscoord, val
atl_initialize calls atl_fill_bcindex
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program