atl_banner – Ateles
atl_banner Subroutine
20 statements
Source File
public subroutine atl_banner(version_string)
Prominently let the user now, what he actually is running right now.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: version_string
Calls
Called by
Call graph
atl_banner calls tem_print_execInfo, utc_date_string
ateles calls atl_banner
atl_harvesting calls atl_banner