atl_append_euler_2d_consVars – Ateles
atl_append_euler_2d_consVars Subroutine
28 statements
Source File
public subroutine atl_append_euler_2d_consVars(equation, solverData)
Append conservative variables for Euler equations.
These are density, momentum and energy here.
Arguments
Type Intent Optional Attributes Name
type(atl_Equations_type), intent(inout) :: equation
The equation type .
type(atl_varSys_solverData_type), target :: solverData
the pointer to the data required for the varsys
Calls
Called by
Call graph
atl_append_euler_2d_consvars calls atl_get_new_varsys_data_ptr, outputappendresult, tem_varSys_append_stateVar
outputappendresult calls tem_abort
atl_init_euler_2d_vars calls atl_append_euler_2d_consvars
atl_eqn_euler_init calls atl_init_euler_2d_vars
atl_eqn_nvrstk_init calls atl_init_euler_2d_vars
atl_init_equation calls atl_eqn_euler_init, atl_eqn_nvrstk_init
atl_initialize calls atl_init_equation