atl_generic_fromModal_getElement – Ateles
atl_generic_fromModal_getElement Subroutine
97 statements
Source File
public recursive subroutine atl_generic_fromModal_getElement(fun, varSys, elempos, time, tree, nElems, nDofs, fnCalcPtr, solverData, res)
This routine prepares the data for variable derivation or operators. It gathers all input variables from the variable system, oversamples and projects them into nodal space, calls the function with the actual calculation and projects the results back into modal space. As these projections are common to all elementwise variable accesses, this generic routine does all necessary operations in a generic way.
Call the procedure that does the calculation
Arguments
Type Intent Optional Attributes Name
class(tem_varSys_op_type), intent(in) :: fun
Description of the method to obtain the variables, here some preset values might be stored, like the space time function to use or the required variables.
type(tem_varSys_type), intent(in) :: varSys
The variable system to obtain the variable from.
integer, intent(in) :: elempos(:)
TreeID of the element to get the variable for.
type(tem_time_type), intent(in) :: time
Point in time at which to evaluate the variable.
type(treelmesh_type), intent(in) :: tree
global treelm mesh info
integer, intent(in) :: nElems
Number of values to obtain for this variable (vectorized access).
integer, intent(in) :: nDofs
Number of degrees of freedom within an element. Careful: This argument determines how many dofs is returned in the output of this routine
procedure(atl_derive_fromModalData), pointer :: fnCalcPtr
Function pointer to perform specific operation. Sets in routine which calls this routine
type(atl_varSys_solverData_type), intent(inout) :: solverData
Solver data container
real(kind=rk), intent(out) :: res(:)
Resulting values for the requested variable.
Linearized array dimension: (n requested entries) x (nComponents of this variable) x (nDegrees of freedom) Access: (iElem-1)fun%nComponentsnDofs + (iDof-1)*fun%nComponents + iComp
Calls
Called by
Call graph
atl_generic_frommodal_getelement calls get_element, ply_poly_project_m2n, ply_poly_project_n2m, ply_convert2oversample, ply_convertfromoversample, ply_dof_2degree, tem_LevelOf, val
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
ply_dof_2degree calls ply_degree_2dof
ply_poly_project_m2n_multivar calls ply_legtopnt_2d, ply_legtopnt_3d, ply_fxt_m2n_1d, ply_fxt_m2n_2d, ply_fxt_m2n_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d, ply_pnttoleg_3d, ply_fxt_n2m_1d, ply_fxt_n2m_2d, ply_fxt_n2m_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
atl_kineticenergy_getelement calls atl_generic_frommodal_getelement
atl_lambda2_getelement calls atl_generic_frommodal_getelement
atl_machnumber_getelement calls atl_generic_frommodal_getelement
atl_op_dividevecbyscal_forelement calls atl_generic_frommodal_getelement
atl_op_division_forelement calls atl_generic_frommodal_getelement
atl_pressure_1d_getelement calls atl_generic_frommodal_getelement
atl_pressure_2d_getelement calls atl_generic_frommodal_getelement
atl_pressure_getelement calls atl_generic_frommodal_getelement
atl_qcriterion_getelement calls atl_generic_frommodal_getelement
atl_rans_pressure_getelement calls atl_generic_frommodal_getelement
atl_speedofsound_getelement calls atl_generic_frommodal_getelement
atl_temperature_getelement calls atl_generic_frommodal_getelement