atl_load_navierStokes – Ateles
atl_load_navierStokes Subroutine
33 statements
Source File
public subroutine atl_load_navierStokes(navierStokes, euler, conf, eq_table)
Subroutine to initialize an equation of type navier stokes equation as defined in the configuration file
Arguments
Type Intent Optional Attributes Name
type(atl_navierStokes_type), intent(out) :: navierStokes
Output of this subroutine, the data inside this argument will be set to the values of the configuration file
type(atl_euler_type), intent(out) :: euler
type(flu_State), intent(in) :: conf
Variable of type flu_State which is a flu binding to the configuration file (input)
integer, intent(in) :: eq_table
A handle to the equation table inside the configuration file
Calls
Called by
Call graph
atl_load_navierstokes calls aot_get_val, atl_load_euler, tem_abort
atl_load_euler calls aot_get_val, tem_abort
atl_eqn_nvrstk_init calls atl_load_navierstokes
atl_load_filtns calls atl_load_navierstokes
atl_eqn_filtered_nvrstk_init calls atl_load_filtns
atl_init_equation calls atl_eqn_nvrstk_init, atl_eqn_filtered_nvrstk_init
atl_initialize calls atl_init_equation
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize