atl_get_timestep – Ateles
atl_get_timestep Subroutine
56 statements
Source File
public subroutine atl_get_timestep(tree, mesh_list, scheme_list, material_list, equation, time, statedata_list, nCellsNoBnd, general, adaptive_timestep, initial, precice_dt)
Subrountine which gather all calls to get the timestep for the current iteration
There is an fixed_dt requested, use that instead of adaptive timestepping.
Arguments
Type Intent Optional Attributes Name
type(treelmesh_type), intent(in) :: tree
The treelmesh data structure
type(atl_cube_elem_type), intent(in) :: mesh_list(tree%global%minLevel:tree%global%maxLevel)
List of meshes for different kernels
type(atl_scheme_type), intent(inout) :: scheme_list(tree%global%minLevel:tree%global%maxLevel)
scheme desription
type(atl_material_type), intent(in) :: material_list(tree%global%minLevel:tree%global%maxLevel)
List of material parameter information for the mesh. One entry for level, running from minlevel to maxlevel.
type(atl_Equations_type), intent(inout) :: equation
type(atl_global_timestep_type), intent(in) :: time
Global timediscretization type
type(atl_statedata_type), intent(in) :: statedata_list(tree%global%minLevel:tree%global%maxLevel)
Local time
integer, intent(in) :: nCellsNoBnd(:)
type(tem_general_type), intent(in) :: general
general data coming from treelem
logical, intent(in) :: adaptive_timestep
Flag for adaptive timestep calculation
logical, intent(in) :: initial
Flag for timestep calculation because it is the init step
real(kind=rk), intent(out), optional :: precice_dt
Timestep specified from precice. If this value is present, precice is considered active.
Calls
Called by
Call graph
atl_get_timestep calls calculate_cfl_timestep, create_global_timestep, tem_abort, tem_isNaN
calculate_cfl_timestep calls tem_abort, atl_eqn_update_background, calc_timestep_acoustic_2d_cube, calc_timestep_acoustic_cube, calc_timestep_adv_cube, calc_timestep_ed_cube, calc_timestep_flow_cube, calc_timestep_flow_cube_1d, calc_timestep_flow_cube_2d, calc_timestep_flow_cube_mod, calc_timestep_heat_cube_1d, calc_timestep_lineareuler_2d_cube, calc_timestep_lineareuler_cube, calc_timestep_nerplanck_cube, calc_timestep_viscflow_cube, calc_timestep_viscflow_cube_2d
create_global_timestep calls calc_common_global_timestep
atl_eqn_update_background calls tem_temporal_for
calc_common_global_timestep calls mpi_allreduce
atl_initialize_program calls atl_get_timestep
atl_solve_program calls atl_get_timestep
ateles calls atl_initialize_program, atl_solve_program