atl_modg_stabViscNavierStokes_oneDim_numFlux – Ateles
atl_modg_stabViscNavierStokes_oneDim_numFlux Subroutine
31 statements
Source File
public subroutine atl_modg_stabViscNavierStokes_oneDim_numFlux(equation, facedata, scheme, faces, faceDir, poly_proj)
Numerical flux calculation for stab-viscous part of the Navier-Stokes equation across the faces in a single spatial direction.
Arguments
Type Intent Optional Attributes Name
type(atl_Equations_type), intent(in) :: equation
The equation you solve.
type(atl_facedata_type), intent(inout) :: facedata
The face state if the equation
type(atl_modg_scheme_type), intent(in) :: scheme
Parameters of the modal dg scheme
type(tem_faceIterator_type), intent(in) :: faces
The faces to calculate the fluxes for.
integer, intent(in) :: faceDir
The spatial direction of the faces you calc the fluxes for, use the following: 1 --> x direction. \n 2 --> y direction. \n 3 --> z direction.
type(ply_poly_project_type), intent(inout) :: poly_proj
Parameter for used projection
Called by
Call graph
atl_modg_filnvrstk_numflux calls atl_modg_stabviscnavierstokes_onedim_numflux
atl_modg_navierstokes_numflux calls atl_modg_stabviscnavierstokes_onedim_numflux
compute_rhs_cubes_modg calls atl_modg_filnvrstk_numflux, atl_modg_navierstokes_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg
atl_compute_rhs calls compute_rhs_cubes