atl_init_physCheck – Ateles
atl_init_physCheck Subroutine
28 statements
Source File
public subroutine atl_init_physCheck(check, conf, equation)
Arguments
Type Intent Optional Attributes Name
type(atl_physCheck_type), intent(out) :: check
The physical check to init.
type(flu_State), intent(in) :: conf
Handle for the Lua config file
type(atl_Equations_type), intent(in) :: equation
The equation you are simulating.
Calls
Called by
Call graph
atl_init_physcheck calls aot_get_val, aot_table_close, aot_table_open, tem_abort, tem_horizontalSpacer
atl_init_elem_container calls atl_init_physcheck
atl_initialize calls atl_init_elem_container
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program