atl_modg_1d_scheme_load_polyDegree – Ateles
atl_modg_1d_scheme_load_polyDegree Subroutine
90 statements
Source File
private subroutine atl_modg_1d_scheme_load_polyDegree(degree, conf, thandle, currentLevel, maxLevel)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: degree
type(flu_State) :: conf
integer, intent(in) :: thandle
integer, intent(in) :: currentLevel
integer, intent(in) :: maxLevel
Calls
Called by
Call graph
atl_modg_1d_scheme_load_polydegree calls aot_get_val, aot_table_close, aot_table_length, aot_table_open, tem_abort, upper_to_lower
atl_modg_1d_scheme_init calls atl_modg_1d_scheme_load_polydegree
atl_init_scheme calls atl_modg_1d_scheme_init
atl_init_elem_container calls atl_init_scheme
atl_initialize calls atl_init_elem_container