atl_append_nvrstk_derivedVars – Ateles
atl_append_nvrstk_derivedVars Subroutine
39 statements
Source File
public subroutine atl_append_nvrstk_derivedVars(varSys, solverData)
Append / set methods and data to compute derived quantities to the variable system.
Available quantities are:
inviscindicator: Indication whether the viscous terms are neglected in the element. It will be one where the viscous fluxes are computed and 0, where they'll be neglected.
shearestimate: Basis for the inviscindicator, provides the estimate for the maximal shear in the element. This is based on the derivative estimation, which is only computed if adaptivity for viscous terms is activated!
all quantities from the euler system, see atl_append_euler_derivedVars
Arguments
Type Intent Optional Attributes Name
type(tem_varSys_type), intent(inout) :: varSys
The variable system to modify. It has to contain the conservative and primitive variables already.
type(atl_varSys_solverData_type), target :: solverData
the pointer to the data required for the varsys to fulfill all operations and derivations on the variables
Calls
Called by
Call graph
atl_append_nvrstk_derivedvars calls atl_get_new_varsys_data_ptr, tem_abort, tem_varSys_append_derVar
atl_eqn_nvrstk_init calls atl_append_nvrstk_derivedvars
atl_init_equation calls atl_eqn_nvrstk_init
atl_initialize calls atl_init_equation
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize