atl_volToFace_1d – Ateles
atl_volToFace_1d Function
23 statements
Source File
private function atl_volToFace_1d(state, iAlign, maxPolyDeg, nDofsFace, nScalars) result(face)
Project elemental state to a particular face.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: state(:,:)
integer, intent(in) :: iAlign
The face alignment. 1 -> left face (ref. element at -1) 2 -> right face (ref. element at +1)
integer, intent(in) :: maxPolyDeg
integer, intent(in) :: nDofsFace
integer, intent(in) :: nScalars
Return Value real(kind=rk), (nDofsFace,nScalars)
Calls
Called by
Call graph
atl_voltoface_1d calls ply_facevalleftbndans
atl_set_covolume_bnd calls atl_voltoface_1d
atl_interpolate_elemstate calls atl_set_covolume_bnd, atl_interpolate_elemstate
atl_covolume_tocovolume calls atl_interpolate_elemstate
atl_covolume_tocovolume_1d calls atl_interpolate_elemstate
atl_covolume_tocovolume_2d calls atl_interpolate_elemstate
atl_covolume calls atl_covolume_tocovolume
atl_covolume_1d calls atl_covolume_tocovolume_1d
atl_covolume_2d calls atl_covolume_tocovolume_2d