atl_viscPhysFluxNavierStokes – Ateles
atl_viscPhysFluxNavierStokes Function
16 statements
Source File
public function atl_viscPhysFluxNavierStokes(state, state_gradient, mu, lambda, thermCond, heatCap) result(physFlux)
Physical flux calculation along x direction for Euler equation.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: state(:)
The state in nodal space. Dimension is the number of state variables i.e. 5 for Navier-Stokes.
real(kind=rk), intent(in) :: state_gradient(:,:)
The state in nodal space. First dimension is the number of variables i.e. 5 for Navier-Stokes. Second dimension is the dimension, e.g. 3 in two dimensions.
real(kind=rk), intent(in) :: mu
Dynamic Viscosity
real(kind=rk), intent(in) :: lambda
Viscosity
real(kind=rk), intent(in) :: thermCond
The thermal cond
real(kind=rk), intent(in) :: heatCap
The specific heat capacity (per mass unit mass, at constant volume)
Return Value real(kind=rk), (5)
The physical flux along the x axis for all variables
Called by
Call graph
atl_modg_navierstokes_physflux_const calls atl_viscphysfluxnavierstokes
atl_modg_navierstokes_physflux_nonconst calls atl_viscphysfluxnavierstokes
atl_viscnavierstokes calls atl_viscphysfluxnavierstokes
atl_modg_viscnavierstokes_onedim_numflux calls atl_viscnavierstokes
atl_modg_filnvrstk_numflux calls atl_modg_viscnavierstokes_onedim_numflux
atl_modg_navierstokes_numflux calls atl_modg_viscnavierstokes_onedim_numflux
compute_rhs_cubes_modg calls atl_modg_filnvrstk_numflux, atl_modg_navierstokes_numflux