atl_eqn_heat_init – Ateles
atl_eqn_heat_init Subroutine
21 statements
Source File
public subroutine atl_eqn_heat_init(conf, thandle, equation, nDimensions, varSys_data)
Initialization of the Heat equation.
This routine sets up the necessary infrastructure for the Heat equation. It reads the configuration from the given script in conf under the table provided in thandle and sets function pointers and variables accordingly.
The possible material properties.
Arguments
Type Intent Optional Attributes Name
type(flu_State), intent(in) :: conf
Handle to the Lua configuration
integer, intent(in) :: thandle
Handle to the equation table in the Lua script given in conf.
type(atl_Equations_type), intent(inout) :: equation
Equation system to set with this routine.
integer, intent(in) :: nDimensions
Number of spatial dimensions, the Euler equations should live on.
Has to be 1, 2 or 3.
type(atl_varSys_solverData_type), intent(inout) :: varSys_data
the pointer to the data required for the varsys
Calls
Called by
Call graph
atl_eqn_heat_init calls atl_init_heat_1d_vars, atl_init_heat_2d_vars, atl_init_heat_vars, atl_load_heat
atl_init_heat_1d_vars calls append_heat_1d_consvars, tem_varSys_init
atl_init_heat_2d_vars calls append_heat_2d_consvars, tem_varSys_init
atl_init_heat_vars calls append_heat_consvars, tem_varSys_init
atl_load_heat calls aot_get_val
append_heat_1d_consvars calls atl_get_new_varsys_data_ptr, tem_varSys_append_stateVar
append_heat_2d_consvars calls atl_get_new_varsys_data_ptr, tem_varSys_append_stateVar
append_heat_consvars calls atl_get_new_varsys_data_ptr, tem_varSys_append_stateVar
atl_init_equation calls atl_eqn_heat_init
atl_initialize calls atl_init_equation
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program