atl_eqn_write – Ateles
atl_eqn_write Subroutine
34 statements
Source File
public subroutine atl_eqn_write(equation, pconf)
Uses
atl_eqn_nvrstk_module
atl_eqn_euler_module
atl_eqn_advection_1d_module
atl_eqn_heat_module
atl_eqn_maxwell_module
atl_eqn_LinearEuler_module
atl_eqn_acoustic_module
Arguments
Type Intent Optional Attributes Name
type(atl_Equations_type), intent(in) :: equation
Equation information to write.
type(aot_out_type) :: pconf
Lua output handle to write the equation information to.
Needs to have been opened with aot_out_open.
Calls
Call graph
atl_eqn_write calls aot_out_close_table, aot_out_open_table, atl_dump_materialfun, atl_save_acoustic, atl_save_advection_1d, atl_save_euler, atl_save_heat, atl_save_lineareuler, atl_save_maxwell, atl_save_navierstokes
atl_dump_materialfun calls aot_out_close_table, aot_out_open_table, aot_out_val, input_varpos, stripmatprefix, val
atl_save_acoustic calls aot_out_val
atl_save_advection_1d calls aot_out_val
atl_save_euler calls aot_out_val
atl_save_heat calls aot_out_val
atl_save_lineareuler calls aot_out_val
atl_save_maxwell calls aot_out_val
atl_save_navierstokes calls atl_save_euler, aot_out_val