atl_viscPhysFluxRans_2d – Ateles
atl_viscPhysFluxRans_2d Function
40 statements
Source File
public function atl_viscPhysFluxRans_2d(state, state_gradient, isenCoeff, mu, lambda, thermCond, rans_params, heatCap) result(physFlux)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: state(:)
The state in nodal space. Dimension is the number of vars, i.e. 4 for Navier-Stokes.
real(kind=rk), intent(in) :: state_gradient(:,:)
The state in nodal space. First dimension is the number of vars, i.e. 4 for Navier-Stokes. Second dimension is the dimension, e.g. 2 in two dimensions.
real(kind=rk), intent(in) :: isenCoeff
Adiabatice index, also known as isentropic expansion factor.
real(kind=rk), intent(in) :: mu
Dynamic Viscosity
real(kind=rk), intent(in) :: lambda
Viscosity
real(kind=rk), intent(in) :: thermCond
The thermal cond
type(atl_navier_stokes_rans_type), intent(in) :: rans_params
The constants for the Rans eqn
real(kind=rk), intent(in) :: heatCap
The specific heat capacity (per mass unit mass, at constant volume)
Return Value real(kind=rk), (6)
The physical flux along the x axis for all variables
Calls
Called by
Call graph
atl_viscphysfluxrans_2d calls atl_get_lower_bound_turb_disscipation, atl_get_pointwise_velocity_gradient_2d, atl_get_pointwise_visc_stress_tensor_2d
atl_modg_2d_filnvrstk_physflux_const calls atl_viscphysfluxrans_2d
atl_modg_2d_filnvrstk_physflux_nonconst calls atl_viscphysfluxrans_2d
atl_viscrans_2d calls atl_viscphysfluxrans_2d
modg_2d_viscrans_onedim_numflux calls atl_viscrans_2d
atl_modg_2d_filnvrstk_numflux calls modg_2d_viscrans_onedim_numflux
compute_rhs_cubes_modg_2d calls atl_modg_2d_filnvrstk_numflux