atl_cons_positivity_preserv_2d – Ateles
atl_cons_positivity_preserv_2d Subroutine
63 statements
Source File
public subroutine atl_cons_positivity_preserv_2d(state, mesh, filter, euler, poly_proj)
Apply conservative limitation of denisty and energy to ensure positivity for density and pressure.
Arguments
Type Intent Optional Attributes Name
type(atl_statedata_type), intent(inout) :: state
type(atl_cube_elem_type), intent(in) :: mesh
type(atl_cons_positivity_preserv_type), intent(in) :: filter
type(atl_euler_type), intent(in) :: euler
type(ply_poly_project_type), intent(inout) :: poly_proj
Calls
Called by
Call graph
atl_cons_positivity_preserv_2d calls ply_poly_project_m2n, ply_poly_project_n2m, nelems, ply_convert2oversample, ply_convertfromoversample, solve_admissible_state_2d
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
solve_admissible_state_2d calls tem_abort
ply_poly_project_m2n_multivar calls ply_legtopnt_2d, ply_legtopnt_3d, ply_fxt_m2n_1d, ply_fxt_m2n_2d, ply_fxt_m2n_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d, ply_pnttoleg_3d, ply_fxt_n2m_1d, ply_fxt_n2m_2d, ply_fxt_n2m_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
atl_stabilize calls atl_cons_positivity_preserv_2d
mesh_timestep_euler calls atl_stabilize, mesh_timestep_euler
mesh_timestep_imexrk calls atl_stabilize
mesh_timestep_rk4 calls atl_stabilize
mesh_timestep_rktaylor calls atl_stabilize
mesh_timestep_ssprk2 calls atl_stabilize
atl_harvesting calls atl_stabilize