atl_init_LinearEuler_vars – Ateles
atl_init_LinearEuler_vars Subroutine
7 statements
Source File
public subroutine atl_init_LinearEuler_vars(equation, methodData)
Arguments
Type Intent Optional Attributes Name
type(atl_Equations_type), intent(inout) :: equation
The equation system
type(atl_varSys_solverData_type), intent(in) :: methodData
the pointer to the data required for the varsys
Calls
Called by
Call graph
atl_init_lineareuler_vars calls atl_append_lineareuler_derivedvars, atl_append_lineareuler_vars, tem_varSys_init
atl_append_lineareuler_derivedvars calls atl_get_new_varsys_data_ptr, tem_abort, tem_varSys_append_derVar
atl_append_lineareuler_vars calls atl_get_new_varsys_data_ptr, tem_varSys_append_stateVar
atl_eqn_lineareuler_init calls atl_init_lineareuler_vars
atl_init_equation calls atl_eqn_lineareuler_init
atl_initialize calls atl_init_equation
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize