atl_extend_covol_face – Ateles
atl_extend_covol_face Function
38 statements
Source File
private function atl_extend_covol_face(faceState, iDir, maxPolyDeg, nScalars) result(volState)
Lift face data to volume data.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: faceState(:,:)
integer, intent(in) :: iDir
The spatial direction: 1 -> x direction. 2 -> y direction. 3 -> z direction.
integer, intent(in) :: maxPolyDeg
integer, intent(in) :: nScalars
Return Value real(kind=rk), ((maxPolyDeg+1)**3,nScalars)
Called by
Call graph
atl_set_covolume_bnd calls atl_extend_covol_face
atl_interpolate_elemstate calls atl_set_covolume_bnd, atl_interpolate_elemstate
atl_covolume_tocovolume calls atl_interpolate_elemstate
atl_covolume_tocovolume_1d calls atl_interpolate_elemstate
atl_covolume_tocovolume_2d calls atl_interpolate_elemstate
atl_covolume calls atl_covolume_tocovolume
atl_covolume_1d calls atl_covolume_tocovolume_1d
atl_covolume_2d calls atl_covolume_tocovolume_2d