atl_load_bc_state – Ateles
atl_load_bc_state Subroutine
12 statements
Source File
public subroutine atl_load_bc_state(bc, state_name, nComp, style, conf, bc_handle, varDict, varSys, ErrCode)
Load the boundary condition for state variables.
This is only a thin wrapper around tem_load_bc_state, to always provide the solverData_evalElem routine.
Arguments
Type Intent Optional Attributes Name
type(tem_bc_state_type), intent(inout) :: bc
The boundary to fill
character(len=*), intent(in) :: state_name
The state variable to set with this boundary condition
integer, intent(in), optional :: nComp
Number of Components in this boundary variable.
character(len=*), intent(in), optional :: style
Style of this boundary condition dirichlet = set value itself neumann = set derivative of value
type(flu_State), intent(in) :: conf
integer, intent(in) :: bc_handle
Handle to the table describing the boundary
type(grw_stringkeyvaluepairarray_type), intent(inout) :: varDict
The dictionary that contains the mapping between expected variables and the actual variables defined by the user.
type(tem_varSys_type), intent(inout) :: varSys
integer, intent(out), optional :: ErrCode
Error code
Calls
Called by
Call graph
atl_load_bc_state calls tem_load_bc_state
atl_eqn_acoustic_load_bc calls atl_load_bc_state
atl_eqn_advection_1d_load_bc calls atl_load_bc_state
atl_eqn_euler_load_bc calls atl_load_bc_state
atl_eqn_lineareuler_load_bc calls atl_load_bc_state
atl_eqn_maxwell_load_bc calls atl_load_bc_state
atl_eqn_maxwelldivcor_load_bc calls atl_load_bc_state
atl_eqn_nvrstk_load_bc calls atl_load_bc_state
atl_eqn_rans_load_bc calls atl_load_bc_state
eqn_maxwell_2d_load_bc calls atl_load_bc_state