atl_init_face_bnd – Ateles
atl_init_face_bnd Subroutine
57 statements
Source File
private subroutine atl_init_face_bnd(minLevel, maxLevel, bc_header, face_list, boundary_list, scheme_list)
Creates boundary informations for the faces.
For each boundary face we create a virtual boundary element outside the fluid domain. Those virtual elements are indexed with an offset of the number of elements in the level. And these indices are than used for the faces to refer to this virtual element as a neighbor on the corresponding side.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: minLevel
integer, intent(in) :: maxLevel
type(tem_bc_header_type), intent(in) :: bc_header
The boundary condition header data as given in the mesh.
type(tem_face_type), intent(inout) :: face_list(minLevel:maxLevel)
Description of the faces
type(atl_level_boundary_type), intent(inout) :: boundary_list(minLevel:maxLevel)
The created boundary information.
type(atl_scheme_type), intent(in) :: scheme_list(minLevel:maxLevel)
Scheme information
Calls
Called by
Call graph
atl_init_face_bnd calls append, init, leftpos, rightpos, tem_abort
atl_init_bndlist calls atl_init_face_bnd
atl_init_cube_container calls atl_init_bndlist
atl_init_elem_container calls atl_init_cube_container
atl_initialize calls atl_init_elem_container