atl_modg_kernel_utests – Ateles
atl_modg_kernel_utests Subroutine
38 statements
Source File
public subroutine atl_modg_kernel_utests(passed)
Uses
atl_eqn_euler_var_module
atl_eqn_euler_derive_module
atl_equation_module
atl_varSys_module
Subroutine to test the various routines of this module.
Arguments
Type Intent Optional Attributes Name
logical, intent(out) :: passed
Calls
Call graph
atl_modg_kernel_utests calls atl_init_euler_vars, test_project_stabviscnumflux
atl_init_euler_vars calls atl_append_euler_consvars, atl_append_euler_derivedvars, atl_append_euler_primvars, tem_varSys_init
test_project_stabviscnumflux calls modg_project_stabviscnumfluxx_q, modg_project_stabviscnumfluxy_q, modg_project_stabviscnumfluxz_q, ply_poly_project_fillbody