atl_modg_coarseToFineElem_2d – Ateles
atl_modg_coarseToFineElem_2d Subroutine
52 statements
Source File
public subroutine atl_modg_coarseToFineElem_2d(minLevel, maxLevel, currentLevel, iDir, mesh, state_stab, scheme, nScalars)
Project coarse parent element to its 8 finer child elements by a simple L2 projection.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: minLevel
The minumum level of the mesh.
integer, intent(in) :: maxLevel
The maximum level of the mesh.
integer, intent(in) :: currentLevel
The current level (i.e. the coarse level).
integer, intent(in) :: iDir
The direction to project
type(atl_cube_elem_type), intent(in) :: mesh(minLevel:maxLevel)
The mesh representation.
type(atl_statedata_type), intent(inout) :: state_stab(minLevel:maxLevel,1:3)
The face representations (finer faces are interpolated from coarser ones).
type(atl_scheme_type), intent(in) :: scheme(minLevel:maxLevel)
The schemes on the different levels.
integer, intent(in) :: nScalars
The number of scalar variables in your equation system.
Calls
Called by
Call graph
atl_modg_coarsetofineelem_2d calls nelems, pnttid, modg_semirefineelem_2d, tem_childNumber, tem_startTimer, tem_stopTimer, total, val
atl_interpolate_elemstate calls atl_modg_coarsetofineelem_2d, atl_interpolate_elemstate
atl_covolume_tocovolume calls atl_interpolate_elemstate
atl_covolume_tocovolume_1d calls atl_interpolate_elemstate
atl_covolume_tocovolume_2d calls atl_interpolate_elemstate
atl_covolume calls atl_covolume_tocovolume
atl_covolume_1d calls atl_covolume_tocovolume_1d
atl_covolume_2d calls atl_covolume_tocovolume_2d
atl_stabilize calls atl_covolume, atl_covolume_1d, atl_covolume_2d