atl_refToPhysCoord – Ateles
atl_refToPhysCoord Subroutine
11 statements
Source File
public subroutine atl_refToPhysCoord(refPoints, nPoints, baryCoord, elemLength, physPoints)
Subroutine to move points defined on the reference element [-1,+1] to the physical element coordinates.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: refPoints(:,:)
The points of the reference elements you want to move to their physical location. Size is: nPoints for first dimension and 3 for the second dimension (x,y,z coordinates).
integer, intent(in) :: nPoints
The number of points to move.
real(kind=rk), intent(in) :: baryCoord(3)
The barycentric coordinate of the element you want to map to (x,y,z coord)
real(kind=rk), intent(in) :: elemLength
The length of the cubic element to map to.
real(kind=rk), intent(inout) :: physPoints(nPoints,3)
The physical points. Dimensions are the same as refPoints.
Called by
Call graph
atl_evalelemmaterial calls atl_reftophyscoord
atl_evalfacematerial calls atl_reftophyscoord
atl_fill_sourceindex calls atl_reftophyscoord
atl_get_points_from_bc calls atl_reftophyscoord
atl_load_initial_condition calls atl_reftophyscoord
atl_write_equipoints calls atl_reftophyscoord
implicit_update calls atl_reftophyscoord
modg_1d_bnd_mirrorpoint calls atl_reftophyscoord
atl_fill_bcindex calls atl_get_points_from_bc
atl_init_materialparams calls atl_evalelemmaterial, atl_evalfacematerial
atl_initialize calls atl_load_initial_condition, atl_fill_bcindex, atl_init_materialparams, atl_initialize_sources, atl_init_precice
atl_initialize_sources calls atl_fill_sourceindex
atl_update_materialparams calls atl_evalelemmaterial, atl_evalfacematerial
atl_write_precice_getpoint calls atl_write_equipoints
mesh_timestep_imexrk calls implicit_update
modg_1d_modal_bnd calls modg_1d_bnd_mirrorpoint
modg_1d_nodal_bnd calls modg_1d_bnd_mirrorpoint
atl_init_precice calls atl_write_precice_getpoint
atl_initialize_program calls atl_initialize
atl_modg_1d_bnd calls modg_1d_modal_bnd, modg_1d_nodal_bnd
atl_preprocess_modg_1d_kernel calls atl_update_materialparams
atl_preprocess_modg_2d_kernel calls atl_update_materialparams
atl_preprocess_modg_kernel calls atl_update_materialparams
atl_harvesting calls atl_initialize
atl_modg_1d_set_bnd calls atl_modg_1d_bnd
atl_set_covolume_bnd calls atl_modg_1d_bnd
preprocess_local_rhs_cubes calls atl_preprocess_modg_kernel
preprocess_rhs_cubes calls atl_preprocess_modg_1d_kernel, atl_preprocess_modg_2d_kernel, atl_preprocess_modg_kernel
ateles calls atl_initialize_program