atl_dumptimers – Ateles
atl_dumptimers Subroutine
62 statements
Source File
public subroutine atl_dumptimers(general, nElems, nDofs, nVars)
Performance results are written to a file for statistical review The file-format is simple can be evaluated with gnuplot
Todo
HK: Make mem-stuff configurable. Maybe reduce values from all processes to find global maximum.
Todo
HK: ensure, that timing is actually now, and it is valid to use the iter component of it as the overall number of iterations (might be different after restart?)
Arguments
Type Intent Optional Attributes Name
type(tem_general_type), intent(in) :: general
Parameters of the current simulation
integer(kind=long_k), intent(in) :: nElems
integer, intent(in) :: nDofs
The number of degrees of freedom per element per scalar variable
integer, intent(in) :: nVars
The number of scalar variables
Calls
Called by
Call graph
atl_dumptimers calls my_status_int, newunit, tem_getMaxTimerVal, tem_getTimerName, tem_getTimerVal
atl_finalize_program calls atl_dumptimers
ateles calls atl_finalize_program