atl_lambda2_getPoint – Ateles
atl_lambda2_getPoint Subroutine
20 statements
Source File
public subroutine atl_lambda2_getPoint(fun, varSys, point, time, tree, nPnts, res)
Arguments
Type Intent Optional Attributes Name
class(tem_varSys_op_type), intent(in) :: fun
Description of the method to obtain the variables, here some preset values might be stored, like the space time function to use or the required variables.
type(tem_varSys_type), intent(in) :: varSys
The variable system to obtain the variable from.
real(kind=rk), intent(in) :: point(:,:)
Three-dimensional coordinates at which the variable should be evaluated. Only useful for variables provided as space-time functions.
type(tem_time_type), intent(in) :: time
Point in time at which to evaluate the variable.
type(treelmesh_type), intent(in) :: tree
global treelm mesh info
integer, intent(in) :: nPnts
Number of values to obtain for this variable (vectorized access).
real(kind=rk), intent(out) :: res(:)
Resulting values for the requested variable.
Dimension: n requested entries x nComponents of this variable Access: (iElem-1)*fun%nComponents + iComp
Calls
Call graph
atl_lambda2_getpoint calls get_point, calc_eigenvalues_3by3_matrix, calc_matrix_qcriterion
calc_eigenvalues_3by3_matrix calls atl_bubblesortarray