atl_write_equiPoints – Ateles
atl_write_equiPoints Subroutine
113 statements
Source File
private subroutine atl_write_equiPoints(stFun, tree, mesh_list, varSys, preciceCpl)
ceate equidistant points for write to precice and use the number of these points for the setup_indices routine. If its set by the user, the Nearest-Pojection can be used for these points
get the number of unquie points, since in all dircetions the number of points is equal, just choose one direction (x, y or z) when there are no points, you dont write them to precice can happen in parallel VK write(,) 'number of Points to writ to precice is 0, & VK cycle this spacetimefunction' transform offset bit back shift the points according to the offset bit * small fraction of the boundingCubeLength hence it is mesh independent We assume here, that all points for a specific face are grouped together in order to make use of the posIDs Give the correct exchange points to precice (store it there) return indices which will be used for all further calls setup_indices for boundary variables are read_var in precice space-time function we are not able to use 'idx' created here as input for get_valOfIndex for write_vars.Therefore we have to do setup_indices for write_vars once during initialization and then store the idx in precice_coupling type. get the setup_indices for the shifted points
Since we are sending 5 times the same idx, for the unique Points and all of them have the same idx, we just need to store it once Create edges and triangles for the interpolation with equidistant points, if the user wants to make use of it, by setting that in the ateles config file
Arguments
Type Intent Optional Attributes Name
type(tem_st_fun_listElem_type), intent(inout), target :: stFun
This list contains space-time-function
type(treelmesh_type), intent(in) :: tree
Mesh data in treelmesh format.
type(atl_cube_elem_type), intent(in) :: mesh_list(tree%global%minLevel:tree%global%maxLevel)
type(tem_varSys_type), intent(in) :: varSys
type(tem_precice_coupling_type), pointer :: preciceCpl
This type contains all information, which are needed for the coupling with precice
Calls
Called by
Call graph
atl_write_equipoints calls append, indexlvl, interpol_data, pntlvl, posids, atl_nearest_projection, atl_reftophyscoord, setup_indices, tem_BaryOfId, tem_CoordOfReal, tem_IdOfCoord, tem_create_surface_equidistant_points, tem_precice_set_vertices_pos, val, varpos
atl_nearest_projection calls interpol_data, posids, edges, posidlvl, tem_create_edges_triangles, tem_precice_set_edge, tem_precice_set_triangle, triangles
atl_write_precice_getpoint calls atl_write_equipoints
atl_init_precice calls atl_write_precice_getpoint
atl_initialize calls atl_init_precice
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize