atl_init_bndList – Ateles
atl_init_bndList Subroutine
13 statements
Source File
public subroutine atl_init_bndList(conf, tree, equation, bc_prop, face_list, boundary_list, bc, bc_header, scheme_list)
Subroutine to create the levelwise list of boundaries.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: conf
Lua script to obtain the configuration data from.
type(treelmesh_type), intent(in) :: tree
global treelm mesh info
type(atl_Equations_type), intent(inout) :: equation
The equation to initialize the boundary info for.
type(tem_BC_prop_type), intent(in) :: bc_prop
The boundary properties.
type(tem_face_type), intent(inout) :: face_list(tree%global%minLevel:tree%global%maxLevel)
The description of the faces as provided by the tem_face_module
type(atl_level_boundary_type), intent(inout) :: boundary_list(tree%global%minLevel:tree%global%maxLevel)
The created boundary type.
type(atl_boundary_type), intent(out), allocatable :: bc(:)
Global description of all boundaries
type(tem_bc_header_type), intent(out) :: bc_header
The boundary condition header data as given in the mesh.
type(atl_scheme_type), intent(in) :: scheme_list(tree%global%minLevel:tree%global%maxLevel)
The scheme you are using.
Calls
Called by
Call graph
atl_init_bndlist calls atl_init_face_bnd, atl_load_bc
atl_init_face_bnd calls append, init, leftpos, rightpos, tem_abort
atl_load_bc calls aot_get_val, aot_table_close, aot_table_open, tem_abort, tem_load_bc_header
atl_init_cube_container calls atl_init_bndlist
atl_init_elem_container calls atl_init_cube_container
atl_initialize calls atl_init_elem_container
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize