atl_load_acoustic – Ateles
atl_load_acoustic Subroutine
18 statements
Source File
public subroutine atl_load_acoustic(acoustic, conf, eq_table)
Load the configuration for acoustic equations from the Lua script.
Arguments
Type Intent Optional Attributes Name
type(atl_acoustic_type), intent(inout) :: acoustic
type(flu_State) :: conf
integer, intent(in) :: eq_table
Calls
Called by
Call graph
atl_load_acoustic calls aot_get_val, aot_table_close, aot_table_open, tem_horizontalSpacer
atl_eqn_acoustic_init calls atl_load_acoustic
atl_init_equation calls atl_eqn_acoustic_init
atl_initialize calls atl_init_equation
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize