atl_varSys_getStateValOfIndex – Ateles
atl_varSys_getStateValOfIndex Subroutine
113 statements
Source File
public subroutine atl_varSys_getStateValOfIndex(fun, varSys, time, iLevel, idx, idxLen, nVals, res)
Routine for gettint the actual value for a given array of indices. The indices belong to the grwarray of points storing levelwise in Pointdata%pntLvl(iLevel). Hence this routines takes the indeices as input, can refer to the pointData and evaluate the variable and returns the values
Todo
Implement blocks of contiguous indices.
Arguments
Type Intent Optional Attributes Name
class(tem_varSys_op_type), intent(in) :: fun
Description of the method to obtain the variables,
type(tem_varSys_type), intent(in) :: varSys
The variable system to obtain the variable from.
type(tem_time_type), intent(in) :: time
Point in time at which to evaluate the variable.
integer, intent(in) :: iLevel
Level on which values are requested
integer, intent(in) :: idx(:)
Index of points in the growing array and variable val array to return. Size: n
integer, intent(in), optional :: idxLen(:)
With idx as start index in contiguous memory, idxLength defines length of each contiguous memory Size: nVals
integer, intent(in) :: nVals
Number of values to obtain for this variable (vectorized access).
real(kind=rk), intent(out) :: res(:)
Resulting values for the requested variable.
Dimension: n requested entries x nComponents of this variable Access: (iElem-1)*fun%nComponents + iComp
Calls
Call graph
atl_varsys_getstatevalofindex calls append, destroy, init, atl_evallegendretenspoly1d, atl_evallegendretenspoly2d, ply_evallegendretenspoly, tem_abort, tem_startTimer, tem_stopTimer, truncate, val