atl_modg_2d_heat_numFlux – Ateles
atl_modg_2d_heat_numFlux Subroutine
11 statements
Source File
public subroutine atl_modg_2d_heat_numFlux(mesh, equation, facedata, scheme, poly_proj)
Calculate the numerical flux for Heat equation and MODG scheme
Arguments
Type Intent Optional Attributes Name
type(atl_cube_elem_type), intent(in) :: mesh
The mesh you are working with.
type(atl_Equations_type), intent(in) :: equation
The equation you solve.
type(atl_facedata_type), intent(inout) :: facedata
The face representation of the state.
type(atl_modg_2d_scheme_type), intent(in) :: scheme
Parameters of the modal dg scheme
type(ply_poly_project_type), intent(inout) :: poly_proj
Parameter for used projection
Calls
Called by
Call graph
atl_modg_2d_heat_numflux calls faces, atl_modg_heat_numflux_sipg
compute_rhs_cubes_modg_2d calls atl_modg_2d_heat_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg_2d
atl_compute_rhs calls compute_rhs_cubes
global_corrector_substep calls atl_compute_rhs
imexrk_substep calls atl_compute_rhs
mesh_timestep_euler calls atl_compute_rhs
rk2_substep calls atl_compute_rhs
rk4_substep calls atl_compute_rhs
rktaylor_substep calls atl_compute_rhs