atl_append_nerplanck_vars – Ateles
atl_append_nerplanck_vars Subroutine
16 statements
Source File
public subroutine atl_append_nerplanck_vars(varSys, methodData)
Arguments
Type Intent Optional Attributes Name
type(tem_varSys_type), intent(inout) :: varSys
type(atl_varSys_solverData_type), target :: methodData
Calls
Called by
Call graph
atl_append_nerplanck_vars calls atl_get_new_varsys_data_ptr, tem_varSys_append_stateVar
atl_init_nerplanck_vars calls atl_append_nerplanck_vars
atl_init_equation calls atl_init_nerplanck_vars
atl_initialize calls atl_init_equation
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize