atl_init_precice – Ateles
atl_init_precice Subroutine
26 statements
Source File
public subroutine atl_init_precice(params, equation, tree, mesh_list, timestepLimit)
Read from preCICE the requested points
If coupling with precice is used, precice need to be initilized to calcualte e.g. the mapping, and communication and the precice_timestep loaded from the config file as input need to be called after precice_create and set?read/write/mesh positions to precice and before initial condition is writen to precice
get the internal precice name for the action writining initial data with this name we check is this action is required
check if action is required and if so, write initial condition to precice call to precice to exchange the initialize Data
Arguments
Type Intent Optional Attributes Name
type(atl_solver_param_type), intent(inout) :: params
type(atl_Equations_type), intent(inout), target :: equation
Description on the equation system to solve.
type(treelmesh_type), intent(in) :: tree
Mesh data in treelmesh format.
type(atl_cube_elem_type), intent(in) :: mesh_list(tree%global%minLevel:tree%global%maxLevel)
real(kind=rk), intent(inout) :: timestepLimit
timesteplimitation due to the precice timestep
Calls
Called by
Call graph
atl_init_precice calls atl_read_precice, atl_write_precice, atl_write_precice_getpoint, tem_horizontalSpacer, tem_precice_action_required, tem_precice_action_write_initdata, tem_precice_fulfilled_action, tem_precice_init, tem_precice_initialize_data, tem_startTimer, tem_stopTimer
atl_read_precice calls pntlvl, posids, tem_precice_set_vertices_pos
atl_write_precice calls get_valofindex, ids, indexlvl, posids, tem_precice_write, varpos
atl_write_precice_getpoint calls atl_write_equipoints, atl_write_nonequipoints
atl_write_equipoints calls indexlvl, pntlvl, posids, tem_precice_set_vertices_pos, varpos, append, interpol_data, atl_nearest_projection, atl_reftophyscoord, setup_indices, tem_BaryOfId, tem_CoordOfReal, tem_IdOfCoord, tem_create_surface_equidistant_points, val
atl_write_nonequipoints calls indexlvl, pntlvl, posids, tem_precice_set_vertices_pos, varpos, append, atl_nearest_projection, setup_indices, val
atl_initialize calls atl_init_precice
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program