atl_modg_2d_fineToCoarseFace – Ateles
atl_modg_2d_fineToCoarseFace Subroutine
73 statements
Source File
public subroutine atl_modg_2d_fineToCoarseFace(minLevel, maxLevel, currentLevel, mesh, facedata, scheme, nScalars)
difference between coarser and finer faces has to be 1).
Interpolates functions defined on finer faces to faces of the current level.\n \n faces on fine face on current level level ------------------------ ------------------------ | | | | | | 3 | 4 | | | | | | | | ------------------------ ---------->> | 5 | | | | | | | 1 | 2 | | | | | | | | ------------------------ ------------------------ \n This is accomplished with lower complexity (with respect to the polynomial degree) by a dimension by dimension approach: \n \n faces on fine face on current \n level level \n ------------------------ ------------------------ \n | | | | | \n | 3 | 4 | | | \n | | | | | \n ------------------------ ---------->> | 5 | \n | | | | | \n | 1 | 2 | | | \n | | | | | \n ------------------------ ------------------------ \n \ / \n \ / \n \ / \n \ / \n ------------------------ \n | | \n | b | \n | | \n ------------------------ \n | | \n | a | \n | | \n ------------------------ \n
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: minLevel
The minumum level of the mesh.
integer, intent(in) :: maxLevel
The maximum level of the mesh.
integer, intent(in) :: currentLevel
The current level (i.e. the coarse level).
type(atl_cube_elem_type), intent(in) :: mesh(minLevel:maxLevel)
The mesh representation.
type(atl_facedata_type), intent(inout) :: facedata(minLevel:maxLevel)
The face representations (finer faces are interpolated from coarser ones).
type(atl_scheme_type), intent(in) :: scheme(minLevel:maxLevel)
The schemes on the different levels.
integer, intent(in) :: nScalars
The number of scalar variables in your equation system.
Calls
Called by
Call graph
atl_modg_2d_finetocoarseface calls childposop, elemposop, fromfinerface, nelems, pnttid, modg_2d_semicoarseface, tem_startTimer, tem_stopTimer
compute_rhs_cubes_modg_2d calls atl_modg_2d_finetocoarseface
compute_rhs_cubes calls compute_rhs_cubes_modg_2d
atl_compute_rhs calls compute_rhs_cubes
global_corrector_substep calls atl_compute_rhs
imexrk_substep calls atl_compute_rhs
mesh_timestep_euler calls atl_compute_rhs
rk2_substep calls atl_compute_rhs
rk4_substep calls atl_compute_rhs
rktaylor_substep calls atl_compute_rhs