atl_evalLegendreTensPoly2d – Ateles
atl_evalLegendreTensPoly2d Subroutine
52 statements
Source File
public subroutine atl_evalLegendreTensPoly2d(coords, nCoords, maxPolyDegree, basisType, polyVal)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: coords(:,:)
Array of coordinates (on the reference element) to evaluate the tensor product polynomials at. First dimension is nCoord, second is 2 for x,y component.
integer, intent(in) :: nCoords
The number of coordinates to evaluate the polynomials at.
integer, intent(in) :: maxPolyDegree
The maximum polynomail degree of the MODG scheme.
integer, intent(in) :: basisType
real(kind=rk), intent(out), allocatable :: polyVal(:,:)
The polynomial values. First dimension is the number of tensor product polynomials and the second dimension is the number of points, i.e. nCoords.
Called by
Call graph
atl_op_gradient_forpoint calls atl_evallegendretenspoly2d
atl_op_gradient_fromindex calls atl_evallegendretenspoly2d
atl_varsys_getstateforpoint calls atl_evallegendretenspoly2d
atl_varsys_getstatevalofindex calls atl_evallegendretenspoly2d