atl_initialize_program – Ateles
atl_initialize_program Subroutine
72 statements
Source File
public subroutine atl_initialize_program(params, equation, tree, varSys_data, nCellsNoBnd, element_container, poly_proj_list, precice_dt)
Arguments
Type Intent Optional Attributes Name
type(atl_solver_param_type), intent(inout) :: params
type(atl_Equations_type), intent(out) :: equation
type(treelmesh_type), intent(inout) :: tree
type(atl_varSys_solverData_type), intent(out) :: varSys_data
Data Infomation of the variable System
integer, intent(out), allocatable :: nCellsNoBnd(:)
type(atl_element_container_type), intent(out) :: element_container
type(ply_poly_project_type), intent(out), allocatable :: poly_proj_list(:)
real(kind=rk), intent(out), optional :: precice_dt
Calls
Called by
Call graph
atl_initialize_program calls conf, nelems, atl_get_timestep, atl_initialize, atl_inittimestepinfo, atl_kerneldata_update_estimates, atl_writerestartifnecessary, ply_sampled_track_output, tem_abort, tem_horizontalSpacer, tem_startTimer, tem_stopTimer, tem_timeControl_dump, tem_trackmem, tem_trackmem_load
ateles calls atl_initialize_program