atl_init_euler_2d_vars – Ateles
atl_init_euler_2d_vars Subroutine
20 statements
Source File
public subroutine atl_init_euler_2d_vars(equation, solverData)
Init the variable system for Euler (inviscid) flow simulations.
The variable system describes, which variables are to be used and how they are organized in the memory. The first few variables up to the sys_mark are those, describing the state, and thus describe the output for regular restart files. Here these are the conservative variables density, momentum and energy. After the mark, there are additional values described that can be deduced from the state variables.
Todo
PV 20160129 make variable system name as argument to this routine since this routine is also used to initialize variables for Navier-Stokes with systemName euler_conservative.
Arguments
Type Intent Optional Attributes Name
type(atl_Equations_type), intent(inout) :: equation
The equation system
type(atl_varSys_solverData_type) :: solverData
the pointer to the data required for the varsys
Calls
Called by
Call graph
atl_init_euler_2d_vars calls atl_append_euler_2d_consvars, atl_append_euler_2d_derivedvars, atl_append_euler_2d_primvars, tem_varSys_init
atl_append_euler_2d_consvars calls atl_get_new_varsys_data_ptr, outputappendresult, tem_varSys_append_stateVar
atl_append_euler_2d_derivedvars calls atl_get_new_varsys_data_ptr, outputappendresult, tem_get_new_varSys_data_ptr, tem_varSys_append_derVar
atl_append_euler_2d_primvars calls positionofval, atl_get_new_varsys_data_ptr, outputappendresult, tem_get_new_varSys_data_ptr, tem_varSys_append_derVar
outputappendresult calls tem_abort
atl_eqn_euler_init calls atl_init_euler_2d_vars
atl_eqn_nvrstk_init calls atl_init_euler_2d_vars
atl_init_equation calls atl_eqn_euler_init, atl_eqn_nvrstk_init
atl_initialize calls atl_init_equation
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize