atl_primal_to_covolume_projection_2d – Ateles
atl_primal_to_covolume_projection_2d Subroutine
72 statements
Source File
public subroutine atl_primal_to_covolume_projection_2d(left, right, dir, filter, scheme, maxPolyDeg, covolume, order)
This routine projects to elements (left and right) onto its co-volume element. The geometrical setup is as follows:
     left                 right
|---------------------||---------------------| \ / \ / | |/ |---------------------| co-volume
The transformation to the co-volume is carried out by a simple (but efficient) L2-projection.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: left(:,:)
real(kind=rk), intent(in) :: right(:,:)
integer, intent(in) :: dir
type(atl_covolume_type), intent(in) :: filter
type(atl_scheme_type), intent(in) :: scheme
The numerical schemes for the current level to get the modg basis
integer, intent(in) :: maxPolyDeg
real(kind=rk), intent(out) :: covolume(:,:)
real(kind=rk), intent(in) :: order
Calls
Called by
Call graph
atl_primal_to_covolume_projection_2d calls tem_abort
atl_covolume_tocovolume_2d calls atl_primal_to_covolume_projection_2d
atl_covolume_2d calls atl_covolume_tocovolume_2d
atl_stabilize calls atl_covolume_2d
mesh_timestep_euler calls atl_stabilize
mesh_timestep_imexrk calls atl_stabilize
mesh_timestep_rk4 calls atl_stabilize
mesh_timestep_rktaylor calls atl_stabilize
mesh_timestep_ssprk2 calls atl_stabilize
atl_harvesting calls atl_stabilize