atl_stabilize – Ateles
atl_stabilize Subroutine
304 statements
Source File
public subroutine atl_stabilize(minlevel, maxlevel, statedata_list, statedata_stab_list, mesh_list, scheme_list, poly_proj_pos, poly_proj_list, equation, tree, bc, boundary, general, commStateTimer, material_list)
Subroutine to apply the stabilization procedure to the state vector.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: minlevel
integer, intent(in) :: maxlevel
type(atl_statedata_type), intent(inout) :: statedata_list(minlevel:maxlevel)
type(atl_statedata_type), intent(inout) :: statedata_stab_list(minlevel:maxlevel)
type(atl_cube_elem_type), intent(inout) :: mesh_list(minlevel:maxlevel)
type(atl_scheme_type), intent(inout) :: scheme_list(minlevel:maxlevel)
integer, intent(inout) :: poly_proj_pos(minlevel:maxlevel)
type(ply_poly_project_type), intent(inout) :: poly_proj_list(:)
type(atl_Equations_type), intent(in) :: equation
type(treelmesh_type), intent(in) :: tree
treelm mesh
type(atl_boundary_type), intent(in) :: bc(:)
The global description of the boundaries.
type(atl_level_boundary_type), intent(in) :: boundary(minlevel:maxlevel)
The levelwise collection of boundary elements and boundary faces.
type(tem_general_type), intent(inout) :: general
General treelm settings.
integer, intent(inout) :: commStateTimer
Timer for measuring the communication time inside this routine.
type(atl_material_type), intent(in) :: material_list(minlevel:maxlevel)
Calls
Called by
Call graph
atl_stabilize calls dimbydimdesc, ply_poly_project_m2n, nelems, atl_cheb_spectral_visc_1d, atl_cons_positivity_preserv, atl_cons_positivity_preserv_2d, atl_covolume, atl_covolume_1d, atl_covolume_2d, atl_get_numbndelems, atl_positivity_preserv, atl_positivity_preserv_2d, atl_spectral_visc_1d, atl_spectral_visc_2d, atl_spectral_visc_3d, ply_change_poly_space, ply_convert2oversample, tem_abort, tem_startTimer, tem_stopTimer
mesh_timestep_euler calls atl_stabilize, mesh_timestep_euler
mesh_timestep_imexrk calls atl_stabilize
mesh_timestep_rk4 calls atl_stabilize
mesh_timestep_rktaylor calls atl_stabilize
mesh_timestep_ssprk2 calls atl_stabilize
atl_harvesting calls atl_stabilize