atl_viscPhysFluxNavierStokes_2d – Ateles
atl_viscPhysFluxNavierStokes_2d Function
15 statements
Source File
public function atl_viscPhysFluxNavierStokes_2d(state, state_gradient, mu, lambda, thermCond, heatCap) result(physFlux)
Physical flux calculation along x direction for Euler equation.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: state(:)
The state in nodal space. Dimension is the number of vars, i.e. 4 for Navier-Stokes.
real(kind=rk), intent(in) :: state_gradient(:,:)
The state in nodal space. First dimension is the number of vars, i.e. 4 for Navier-Stokes. Second dimension is the dimension, e.g. 2 in two dimensions.
real(kind=rk), intent(in) :: mu
Dynamic Viscosity
real(kind=rk), intent(in) :: lambda
Viscosity
real(kind=rk), intent(in) :: thermCond
The thermal cond
real(kind=rk), intent(in) :: heatCap
The specific heat capacity (per mass unit mass, at constant volume)
Return Value real(kind=rk), (4)
The physical flux along the x axis for all variables
Called by
Call graph
atl_modg_2d_navierstokes_physflux_const calls atl_viscphysfluxnavierstokes_2d
atl_modg_2d_navierstokes_physflux_nonconst calls atl_viscphysfluxnavierstokes_2d
atl_viscnavierstokes_2d calls atl_viscphysfluxnavierstokes_2d
modg_2d_viscnavierstokes_onedim_numflux calls atl_viscnavierstokes_2d
atl_modg_2d_navierstokes_numflux calls modg_2d_viscnavierstokes_onedim_numflux
compute_rhs_cubes_modg_2d calls atl_modg_2d_navierstokes_numflux