atl_op_Gradient_forElement – Ateles
atl_op_Gradient_forElement Subroutine
72 statements
Source File
public subroutine atl_op_Gradient_forElement(fun, varSys, elempos, time, tree, nElems, nDofs, res)
This routine takes in a variable and differentiates it in a modal way
Arguments
Type Intent Optional Attributes Name
class(tem_varSys_op_type), intent(in) :: fun
Description of the method to obtain the variables, here some preset values might be stored, like the space time function to use or the required variables.
type(tem_varSys_type), intent(in) :: varSys
The variable system to obtain the variable from.
integer, intent(in) :: elempos(:)
TreeID of the element to get the variable for.
type(tem_time_type), intent(in) :: time
Point in time at which to evaluate the variable.
type(treelmesh_type), intent(in) :: tree
global treelm mesh info
integer, intent(in) :: nElems
Number of values to obtain for this variable (vectorized access).
integer, intent(in) :: nDofs
Number of degrees of freedom within an element.
real(kind=rk), intent(out) :: res(:)
Resulting values for the requested variable.
Linearized array dimension: (n requested entries) x (nComponents of this variable) x (nDegrees of freedom) Access: (iElem-1)fun%nComponentsnDofs + (iDof-1)*fun%nComponents + iComp
Calls
Call graph
atl_op_gradient_forelement calls get_element, ply_calcdiff_leg, ply_calcdiff_leg_1d, ply_calcdiff_leg_2d, tem_CoordOfId, tem_LevelOf, tem_startTimer, tem_stopTimer, val
ply_calcdiff_leg calls ply_calcdiff_leg_x_vec, ply_calcdiff_leg_y_vec, ply_calcdiff_leg_z_vec
ply_calcdiff_leg_2d calls ply_calcdiff_leg_2d_normal