atl_initialize – Ateles
atl_initialize Subroutine
95 statements
Source File
public subroutine atl_initialize(params, container, equation, tree, varSys_data, timestepLimit, poly_proj_list)
Routine to initialize the complete Ateles solver.
It reads the configuration from the given Lua script, and creates the necessary data structures for the computation.
For a detailed description see Initialization
COUPLING USING EQUIDISTANT AND NON-EQUIDISTANT POINTS Reminder: For the equidistant and non-equidistant points the call for the setup_indices is included in the atl_write_equiPoints/atl_writenonequiPoints routine.
Arguments
Type Intent Optional Attributes Name
type(atl_solver_param_type), intent(inout) :: params
type(atl_element_container_type), intent(inout), target :: container
Container of mesh data. This includes information about the mesh parts, the scheme, but also the initial kernel states (i.e. initial conditions).
type(atl_Equations_type), intent(inout), target :: equation
Description on the equation system to solve.
type(treelmesh_type), intent(inout) :: tree
Mesh data in treelmesh format.
type(atl_varSys_solverData_type), intent(inout), target :: varSys_data
Data infomation of the variable System
real(kind=rk), intent(inout), optional :: timestepLimit
timesteplimitation due to the precice timestep
type(ply_poly_project_type), intent(inout), allocatable, target :: poly_proj_list(:)
unique list for projection methods
Calls
atl_initialize w atl_alloc_temp
w
w atl_allocate_sourceData
w
w atl_bc_state_set_fromPoint
w
w atl_create_fortranVar
w
w atl_fill_BCIndex
w
w atl_flux_initGodunov
w
w atl_init_elem_container
w
w atl_init_equation
w
w atl_init_materialParams
w
w atl_init_penalization
w
w atl_init_precice
w
w atl_init_spacebasis
w
w atl_init_varSys_solverData
w
w atl_initialize_sources
w
w atl_initRestart
w
w atl_initWeights
w
w atl_load_initial_condition
w
w atl_load_projection
w
w atl_readRestart
w
w atl_store_bcVarPos
w
w close_config
w
w conf
w
w init
w
w ply_fill_project_list
w
w ply_sampled_track_init
w
w tem_create_subTree_of_st_funList
w
w tem_init_convergence
w
w tem_open_distconf
w
w tem_opVar_reduction_transient_init
w
w tem_precice_create
w
w tem_stencil_map_toTreelmDef
w
w tem_variable_load
w
w tem_varSys_append_luaVar
w
w tem_varSys_append_meshInfoVar
w
Called by
Call graph
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program