atl_load_config – Ateles
atl_load_config Subroutine
29 statements
Source File
public subroutine atl_load_config(params, tree, configFile)
Arguments
Type Intent Optional Attributes Name
type(atl_solver_param_type), intent(inout) :: params
type(treelmesh_type), intent(out) :: tree
Mesh data in treelmesh format.
character(len=*), intent(in), optional :: configFile
Filename to use as default, when no argument provided.
defaults to 'ateles.lua' if not provided.
Calls
Called by
Call graph
atl_load_config calls conf, atl_load_solver_parameters, tem_open_distconf_array
atl_load_solver_parameters calls conf, ply_sampled_tracking_load, tem_debug_load_main, tem_load_general, tem_load_restart, tem_logging_load_primary, tem_timeControl_start_at_sim
ply_sampled_tracking_load calls ply_sampling_load, tem_load_tracking
ply_sampling_load calls aot_get_val, aot_table_close, aot_table_open, ply_sampling_adaptive_load, tem_abort, upper_to_lower
ateles calls atl_load_config
atl_harvesting calls atl_load_config