atl_writeSolverSpecInfo – Ateles
atl_writeSolverSpecInfo Subroutine
36 statements
Source File
public subroutine atl_writeSolverSpecInfo(mesh, scheme_dim, minlevel, outUnit)
Write solver specific info to scratch file
Arguments
Type Intent Optional Attributes Name
type(atl_cube_container_type), intent(in) :: mesh
The mesh type
integer, intent(in) :: scheme_dim
The scheme dimension
integer, intent(in) :: minlevel
Minimal level in the domain to pick the polynomial basis type.
integer, intent(inout) :: outUnit
unit to output solver info in lua format
Calls
Called by
Call graph
atl_writesolverspecinfo calls aot_out_close, aot_out_close_table, aot_out_open, aot_out_open_table, aot_out_val, tem_abort
atl_initrestart calls atl_writesolverspecinfo
atl_initialize calls atl_initrestart
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program