atl_modg_1d_scheme_init – Ateles
atl_modg_1d_scheme_init Subroutine
32 statements
Source File
public subroutine atl_modg_1d_scheme_init(me, nDofs, nFaceDofs, conf, thandle, currentLevel, maxLevel)
Arguments
Type Intent Optional Attributes Name
type(atl_modg_1d_scheme_type), intent(out) :: me
integer, intent(out) :: nDofs
integer, intent(out) :: nFaceDofs
type(flu_State) :: conf
integer, intent(in) :: thandle
integer, intent(in) :: currentLevel
The current level of the mesh
integer, intent(in) :: maxLevel
The maximal level of the mesh
Calls
Called by
Call graph
atl_modg_1d_scheme_init calls aot_get_val, atl_modg_1d_scheme_load_polydegree, tem_abort, upper_to_lower
atl_modg_1d_scheme_load_polydegree calls aot_get_val, tem_abort, upper_to_lower, aot_table_close, aot_table_length, aot_table_open
atl_init_scheme calls atl_modg_1d_scheme_init
atl_init_elem_container calls atl_init_scheme
atl_initialize calls atl_init_elem_container
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize