atl_evalFaceMaterial – Ateles
atl_evalFaceMaterial Subroutine
117 statements
Source File
private subroutine atl_evalFaceMaterial(mesh, scheme, material, materialFun, time, spatial_dim, poly_proj, time_weights)
Subroutine to evaluate the material properties on the nodes of the compute faces (left and right element's trace).
Arguments
Type Intent Optional Attributes Name
type(atl_cube_elem_type), intent(in) :: mesh
Description of the mesh
type(atl_scheme_type), intent(in) :: scheme
Information about the scheme
type(atl_material_type), intent(inout) :: material
The description of the material properties. The compute lists in the material description is filled up by calling this subroutine. The indizes of variables in the global varSys that are used as material's, penalization's or whatever's data sources.
This data is needed to calculate the number of total material components.
type(atl_materialFun_type), intent(in) :: materialFun
type(tem_time_type), intent(in) :: time
The current simulation time
integer, intent(in) :: spatial_dim
The spatial dimension
type(ply_poly_project_type), intent(inout) :: poly_proj
Projection method for current level
logical, intent(in), optional :: time_weights
Calls
Called by
Call graph
atl_evalfacematerial calls facepos, leftpos, nelems, pnttid, atl_reftophyscoord, ply_get_quadpoints_faces, ply_get_quadpoints_faces_1d, ply_get_quadpoints_faces_2d, rightpos, tem_abort, tem_spacetime_for, tem_startTimer, tem_stopTimer
atl_init_materialparams calls atl_evalfacematerial
atl_update_materialparams calls atl_evalfacematerial
atl_initialize calls atl_init_materialparams
atl_preprocess_modg_1d_kernel calls atl_update_materialparams
atl_preprocess_modg_2d_kernel calls atl_update_materialparams
atl_preprocess_modg_kernel calls atl_update_materialparams
atl_initialize_program calls atl_initialize
preprocess_local_rhs_cubes calls atl_preprocess_modg_kernel
preprocess_rhs_cubes calls atl_preprocess_modg_1d_kernel, atl_preprocess_modg_2d_kernel, atl_preprocess_modg_kernel
atl_harvesting calls atl_initialize
atl_preprocess_local_rhs calls preprocess_local_rhs_cubes
atl_preprocess_rhs calls preprocess_rhs_cubes
ateles calls atl_initialize_program