atl_eqn_update_background – Ateles
atl_eqn_update_background Subroutine
24 statements
Source File
public subroutine atl_eqn_update_background(me, time, nDimensions)
Routine which updates the background since it is a temporal function and
Arguments
Type Intent Optional Attributes Name
type(atl_LinearEuler_type), intent(inout) :: me
linearEuler type including background
type(tem_time_type), intent(in) :: time
timer object incl. the current time information
integer, intent(in) :: nDimensions
spatial dimension
Calls
Called by
Call graph
atl_eqn_update_background calls tem_temporal_for
atl_eqn_lineareuler_init calls atl_eqn_update_background
calculate_cfl_timestep calls atl_eqn_update_background
preprocess_rhs_cubes calls atl_eqn_update_background
atl_preprocess_rhs calls preprocess_rhs_cubes
atl_get_timestep calls calculate_cfl_timestep
atl_init_equation calls atl_eqn_lineareuler_init
atl_initialize calls atl_init_equation
atl_initialize_program calls atl_get_timestep, atl_initialize
atl_solve_program calls atl_get_timestep
global_corrector_substep calls atl_preprocess_rhs
imexrk_substep calls atl_preprocess_rhs, imexrk_substep
mesh_timestep_euler calls atl_preprocess_rhs, mesh_timestep_euler
rk2_substep calls atl_preprocess_rhs, rk2_substep
rk4_substep calls atl_preprocess_rhs, rk4_substep
rktaylor_substep calls atl_preprocess_rhs, rktaylor_substep
mesh_timestep_imexrk calls imexrk_substep
mesh_timestep_predcor_cerk4 calls global_corrector_substep
mesh_timestep_rk4 calls rk4_substep
mesh_timestep_rktaylor calls rktaylor_substep
mesh_timestep_ssprk2 calls rk2_substep
ateles calls atl_initialize_program, atl_solve_program
atl_harvesting calls atl_initialize