atl_eqn_nvrstk_init – Ateles
atl_eqn_nvrstk_init Subroutine
44 statements
Source File
public subroutine atl_eqn_nvrstk_init(conf, thandle, equation, nDimensions, initSource, initMaterial, varSys_data)
Initialization of the Navier-Stokes equations.
This routine sets up the necessary infrastructure for the Navier-Stokes equations. It reads the configuration from the given script in conf under the table provided in thandle and sets function pointers and variables accordingly.
Arguments
Type Intent Optional Attributes Name
type(flu_State), intent(in) :: conf
Handle to the Lua configuration
integer, intent(in) :: thandle
Handle to the equation table in the Lua script given in conf.
type(atl_Equations_type), intent(inout) :: equation
Equation system to set with this routine.
integer, intent(in) :: nDimensions
Number of spatial dimensions, the Euler equations should live on.
Has to be 1, 2 or 3.
type(atl_init_source_type), intent(inout) :: initSource
Type to be filled with the possible source variables for the equation system. These source variables are later on used to extract the corresponding information from the configuration file.
type(atl_init_material_type), intent(inout) :: initMaterial
Type to be filled with the possible material variables for the equation system. These material variables are later on used to extract the corresponding information from the configuration file.
type(atl_varSys_solverData_type), intent(inout) :: varSys_data
the pointer to the data required for the varsys
Calls
Called by
Call graph
atl_eqn_nvrstk_init calls atl_append_nvrstk_derivedvars, atl_geteulerfluxes, atl_geteulerlinind, atl_init_euler_2d_sourceterms, atl_init_euler_2d_vars, atl_init_euler_material, atl_init_euler_sourceterms, atl_init_euler_vars, atl_load_navierstokes
atl_append_nvrstk_derivedvars calls atl_get_new_varsys_data_ptr, tem_abort, tem_varSys_append_derVar
atl_geteulerfluxes calls aot_get_val, tem_abort, upper_to_lower
atl_geteulerlinind calls aot_get_val, tem_abort, upper_to_lower
atl_init_euler_2d_sourceterms calls append, init, truncate
atl_init_euler_2d_vars calls atl_append_euler_2d_consvars, atl_append_euler_2d_derivedvars, atl_append_euler_2d_primvars, tem_varSys_init
atl_init_euler_material calls append, init
atl_init_euler_sourceterms calls append, init
atl_init_euler_vars calls atl_append_euler_consvars, atl_append_euler_derivedvars, atl_append_euler_primvars, tem_varSys_init
atl_load_navierstokes calls aot_get_val, atl_load_euler, tem_abort
atl_append_euler_2d_consvars calls atl_get_new_varsys_data_ptr, outputappendresult, tem_varSys_append_stateVar
atl_append_euler_2d_derivedvars calls atl_get_new_varsys_data_ptr, tem_varSys_append_derVar, outputappendresult, tem_get_new_varSys_data_ptr
atl_append_euler_2d_primvars calls atl_get_new_varsys_data_ptr, tem_varSys_append_derVar, positionofval, outputappendresult, tem_get_new_varSys_data_ptr
atl_append_euler_consvars calls atl_get_new_varsys_data_ptr, tem_varSys_append_stateVar
atl_append_euler_derivedvars calls atl_get_new_varsys_data_ptr, tem_abort, tem_varSys_append_derVar, tem_get_new_varSys_data_ptr
atl_append_euler_primvars calls atl_get_new_varsys_data_ptr, tem_abort, tem_varSys_append_derVar, positionofval, tem_get_new_varSys_data_ptr
atl_load_euler calls aot_get_val, tem_abort
outputappendresult calls tem_abort
atl_init_equation calls atl_eqn_nvrstk_init
atl_initialize calls atl_init_equation
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program