atl_init_statedata – Ateles
atl_init_statedata Subroutine
10 statements
Source File
public subroutine atl_init_statedata(statedata, nTotal, nDofs, nVars, time)
Initialize the statedata.
Arguments
Type Intent Optional Attributes Name
type(atl_statedata_type), intent(inout) :: statedata
integer, intent(in) :: nTotal
The total number of cells (including only fluid, ghost, halo and boundary cells).
integer, intent(in) :: nDofs
The number of degrees of freedom per scalar variable of your equation.
integer, intent(in) :: nVars
The number of scalar variables of the current equation.
type(tem_time_type), intent(in) :: time
current time
Called by
Call graph
atl_init_kerneldata calls atl_init_statedata
atl_init_modg_1d_kernel calls atl_init_statedata, atl_init_kerneldata
atl_init_modg_2d_kernel calls atl_init_statedata, atl_init_kerneldata
atl_init_modg_kernel calls atl_init_statedata, atl_init_kerneldata
init_kernel calls atl_init_modg_1d_kernel, atl_init_modg_2d_kernel, atl_init_modg_kernel
atl_init_elem_container calls init_kernel
atl_initialize calls atl_init_elem_container