atl_physFluxEuler_1d – Ateles
atl_physFluxEuler_1d Function
13 statements
Source File
public function atl_physFluxEuler_1d(state, isenCoeff, penalty_scaling, U_o) result(physFlux)
Physical flux calculation along x direction for Euler equation.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: state(:)
The state in nodal space. Dimension is the number of vars, i.e. 3 for Euler 1d
real(kind=rk), intent(in) :: isenCoeff
Adiabatic index, also known as isentropic expansion factor.
real(kind=rk), intent(in) :: penalty_scaling
The scaling of the mass flux due to the penality in the porous material.
It is given by $1 + (\frac{1}{\phi} - 1) \Chi$ Thus, if there is no porous media, this factor has to be 1.
real(kind=rk), intent(in) :: U_o
Obstacle velocity
Return Value real(kind=rk), (3)
The physical flux along the x axis for all variables
Called by
Call graph
atl_averagefluxeuler_1d calls atl_physfluxeuler_1d
atl_godunoveuler1d calls atl_physfluxeuler_1d
atl_laxfriedeuler_1d calls atl_physfluxeuler_1d
atl_modg_1d_euler_physflux_const calls atl_physfluxeuler_1d
atl_modg_1d_euler_physflux_nonconst calls atl_physfluxeuler_1d
modg_1d_compute_project_physflux calls atl_physfluxeuler_1d, atl_modg_1d_euler_physflux_const, atl_modg_1d_euler_physflux_nonconst
compute_rhs_cubes_modg_1d calls modg_1d_compute_project_physflux
compute_rhs_cubes calls compute_rhs_cubes_modg_1d
atl_compute_rhs calls compute_rhs_cubes