atl_modg_euler_oneDim_numFlux_nonconst – Ateles
atl_modg_euler_oneDim_numFlux_nonconst Subroutine
42 statements
Source File
public subroutine atl_modg_euler_oneDim_numFlux_nonconst(equation, nSides, faceRep, faceFlux, leftPos, rightPos, poly_proj, varRotation, material_left, material_right)
Numerical flux calculation for Euler equation across the faces in a single spatial direction.
Arguments
Type Intent Optional Attributes Name
type(atl_Equations_type), intent(in) :: equation
The equation you solve.
integer, intent(in) :: nSides
The number of faces to compute the flux for
real(kind=rk), intent(in) :: faceRep(:,:,:,:)
The state on the face.
real(kind=rk), intent(inout) :: faceFlux(:,:,:,:)
The fluxes on the face.
integer, intent(in) :: leftPos(:)
The positions of the faces to calculate the fluxes for (for elements left and right of the face).
integer, intent(in) :: rightPos(:)
The positions of the faces to calculate the fluxes for (for elements left and right of the face).
type(ply_poly_project_type), intent(inout) :: poly_proj
Parameter for used projection
integer, intent(in) :: varRotation(equation%varSys%nScalars)
real(kind=rk), intent(in) :: material_left(:,:,:)
The penalization material left and right of the face
real(kind=rk), intent(in) :: material_right(:,:,:)
The penalization material left and right of the face
Calls
Called by
Call graph
atl_modg_euler_onedim_numflux_nonconst calls ply_poly_project_m2n, ply_poly_project_n2m, ply_convert2oversample, ply_convertfromoversample
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
ply_poly_project_m2n_multivar calls ply_legtopnt_2d, ply_legtopnt_3d, ply_fxt_m2n_1d, ply_fxt_m2n_2d, ply_fxt_m2n_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d, ply_pnttoleg_3d, ply_fxt_n2m_1d, ply_fxt_n2m_2d, ply_fxt_n2m_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
atl_modg_euler_numflux calls atl_modg_euler_onedim_numflux_nonconst
atl_modg_filnvrstk_numflux calls atl_modg_euler_onedim_numflux_nonconst
atl_modg_navierstokes_numflux calls atl_modg_euler_onedim_numflux_nonconst
compute_rhs_cubes_modg calls atl_modg_euler_numflux, atl_modg_filnvrstk_numflux, atl_modg_navierstokes_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg
atl_compute_rhs calls compute_rhs_cubes