atl_equation_evaluate_source_nodal – Ateles
atl_equation_evaluate_source_nodal Subroutine
62 statements
Source File
public subroutine atl_equation_evaluate_source_nodal(fun, varSys, currentLevel, nDim, time, eval_rhs, state, poly_proj, polyProjBody, sourceData, consts)
Arguments
Type Intent Optional Attributes Name
class(atl_source_op_type), intent(in) :: fun
Description of method to update source
type(tem_varSys_type), intent(in) :: varSys
variable system
integer, intent(in) :: currentLevel
The current Level information
integer, intent(in) :: nDim
The dimension information
type(tem_time_type), intent(in) :: time
Point in time at which to evaluate the variable.
procedure(atl_compute_source_interface), pointer :: eval_rhs
The pointer to the equation specific RHS evaluation
real(kind=rk), intent(in) :: state(:,:,:)
type(ply_poly_project_type), intent(inout) :: poly_proj
Parameters for projection
type(ply_prj_body_type) :: polyProjBody
the data needed for the projection method
real(kind=rk), intent(inout) :: sourceData(:,:,:)
real(kind=rk), intent(in), optional :: consts(:)
Calls
Called by
Call graph
atl_equation_evaluate_source_nodal calls get_valofindex, ply_poly_project_m2n, ply_poly_project_n2m, ply_convert2oversample, ply_convertfromoversample, val
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
ply_poly_project_m2n_multivar calls ply_legtopnt_2d, ply_legtopnt_3d, ply_fxt_m2n_1d, ply_fxt_m2n_2d, ply_fxt_m2n_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d, ply_pnttoleg_3d, ply_fxt_n2m_1d, ply_fxt_n2m_2d, ply_fxt_n2m_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
atl_eval_source_spongelayer calls atl_equation_evaluate_source_nodal
atl_eval_source_spongelayer_2d calls atl_equation_evaluate_source_nodal
eval_source_gravitation calls atl_equation_evaluate_source_nodal
eval_source_gravitation_2d calls atl_equation_evaluate_source_nodal
eval_source_pml_2d calls atl_equation_evaluate_source_nodal