atl_eqn_maxwell_init – Ateles
atl_eqn_maxwell_init Subroutine
29 statements
Source File
public subroutine atl_eqn_maxwell_init(equation, nDimensions, divCorr, initSource, initMaterial, varSys_data)
Initialization of the Maxwell equations.
This routine sets up the necessary infrastructure for the Maxwell equations. It reads the configuration from the given script in conf under the table provided in thandle and sets function pointers and variables accordingly.
Arguments
Type Intent Optional Attributes Name
type(atl_Equations_type), intent(inout) :: equation
Equation system to set with this routine.
integer, intent(in) :: nDimensions
Number of spatial dimensions, the Maxwell equations should live on.
Has to be 2 or 3.
logical, intent(in) :: divCorr
Use divergence correction?
type(atl_init_source_type), intent(inout) :: initSource
Type to be filled with the possible source variables for the equation system. These source variables are later on used to extract the corresponding information from the configuration file.
type(atl_init_material_type), intent(inout) :: initMaterial
Type to be filled with the possible material variables for the equation system. These material variables are later on used to extract the corresponding information from the configuration file.
type(atl_varSys_solverData_type), intent(inout) :: varSys_data
the pointer to the data required for the varsys
Calls
Called by
Call graph
atl_eqn_maxwell_init calls atl_init_maxwell_2d_sourceterms, atl_init_maxwell_2d_vars, atl_init_maxwell_material, atl_init_maxwell_sourceterms, atl_init_maxwell_vars, atl_init_maxwelldivcorr_material, atl_init_maxwelldivcorr_sourceterms, atl_init_maxwelldivcorr_vars
atl_init_maxwell_2d_sourceterms calls append, init
atl_init_maxwell_2d_vars calls atl_append_maxwell_2d_vars, tem_varSys_init
atl_init_maxwell_material calls append, init
atl_init_maxwell_sourceterms calls append, init
atl_init_maxwell_vars calls atl_append_maxwell_vars, tem_varSys_init
atl_init_maxwelldivcorr_material calls append, init
atl_init_maxwelldivcorr_sourceterms calls append, init
atl_init_maxwelldivcorr_vars calls atl_append_maxwelldivcorr_vars, tem_varSys_init
atl_append_maxwell_2d_vars calls atl_get_new_varsys_data_ptr, tem_varSys_append_stateVar
atl_append_maxwell_vars calls atl_get_new_varsys_data_ptr, tem_varSys_append_stateVar
atl_append_maxwelldivcorr_vars calls atl_append_maxwell_vars, atl_get_new_varsys_data_ptr, tem_abort, tem_varSys_append_stateVar
atl_init_equation calls atl_eqn_maxwell_init
atl_initialize calls atl_init_equation
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program