atl_ini_positivity_preserv – Ateles
atl_ini_positivity_preserv Subroutine
15 statements
Source File
public subroutine atl_ini_positivity_preserv(conf, parent_table, filter)
Subroutine to load configuration file options for the spectral viscosity method.
Arguments
Type Intent Optional Attributes Name
type(flu_State), intent(in) :: conf
flu binding to lua configuration file.
integer, intent(in) :: parent_table
The parent table
type(atl_positivity_preserv_type), intent(out) :: filter
The filter to initialize
Calls
Called by
Call graph
atl_ini_positivity_preserv calls aot_get_val, tem_abort, tem_horizontalSpacer
atl_ini_stabilization calls atl_ini_positivity_preserv
atl_init_scheme calls atl_ini_stabilization
atl_init_elem_container calls atl_init_scheme
atl_initialize calls atl_init_elem_container