atl_modg_2d_navierstokes_numFlux – Ateles
atl_modg_2d_navierstokes_numFlux Subroutine
15 statements
Source File
public subroutine atl_modg_2d_navierstokes_numFlux(mesh, equation, facedata, scheme, poly_proj, material)
Calculate the numerical flux for Navier-Stokes equation and MODG scheme
Arguments
Type Intent Optional Attributes Name
type(atl_cube_elem_type), intent(in) :: mesh
The mesh you are working with.
type(atl_Equations_type), intent(in) :: equation
The equation you solve.
type(atl_facedata_type), intent(inout) :: facedata
The face representation of the state.
type(atl_modg_2d_scheme_type), intent(in) :: scheme
Parameters of the modal dg scheme
type(ply_poly_project_type), intent(inout) :: poly_proj
Parameter for used projection
type(atl_material_type), intent(inout) :: material
Material description for the faces on the current level
Calls
Called by
Call graph
atl_modg_2d_navierstokes_numflux calls faces, atl_modg_2d_euler_onedim_numflux_const, atl_modg_2d_euler_onedim_numflux_nonconst, modg_2d_stabviscnavierstokes_onedim_numflux, modg_2d_viscnavierstokes_onedim_numflux, vartransformindices
atl_modg_2d_euler_onedim_numflux_const calls ply_poly_project_m2n, ply_poly_project_n2m, ply_convert2oversample, ply_convertfromoversample
atl_modg_2d_euler_onedim_numflux_nonconst calls ply_poly_project_m2n, ply_poly_project_n2m, ply_convert2oversample, ply_convertfromoversample
modg_2d_viscnavierstokes_onedim_numflux calls vartransformindices, dertransformindices, ply_poly_project_m2n, ply_poly_project_n2m, atl_get_penaltyip_2d, atl_viscnavierstokes_2d
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
atl_viscnavierstokes_2d calls atl_viscphysfluxnavierstokes_2d
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
compute_rhs_cubes_modg_2d calls atl_modg_2d_navierstokes_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg_2d
atl_compute_rhs calls compute_rhs_cubes
global_corrector_substep calls atl_compute_rhs
imexrk_substep calls atl_compute_rhs
mesh_timestep_euler calls atl_compute_rhs
rk2_substep calls atl_compute_rhs
rk4_substep calls atl_compute_rhs
rktaylor_substep calls atl_compute_rhs