atl_acoustic_2d_numFlux_oneDir – Ateles
atl_acoustic_2d_numFlux_oneDir Function
9 statements
Source File
private function atl_acoustic_2d_numFlux_oneDir(left, right, acoustic, iDir) result(flux)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: left(3)
State to compute the fluxes (rho, u, v, w)
real(kind=rk), intent(in) :: right(3)
State to compute the fluxes (rho, u, v, w)
type(atl_acoustic_type), intent(in) :: acoustic
Datatype for acoustic equation include all background data
integer, intent(in) :: iDir
Direction of flux, used fot background velocity
Return Value real(kind=rk), (3)
The resulting flux in x direction
Called by
Call graph
atl_acoustic_2d_numflux_cube_vec calls atl_acoustic_2d_numflux_onedir
atl_acoustic_2d_numflux calls atl_acoustic_2d_numflux_cube_vec
atl_modg_2d_acoustic_numflux calls atl_acoustic_2d_numflux
compute_rhs_cubes_modg_2d calls atl_modg_2d_acoustic_numflux