atl_ini_stabilization – Ateles
atl_ini_stabilization Subroutine
69 statements
Source File
public subroutine atl_ini_stabilization(conf, parent_table, filter)
Arguments
Type Intent Optional Attributes Name
type(flu_State), intent(in) :: conf
flu binding to lua configuration file.
integer, intent(in) :: parent_table
The parent table in the config file
type(atl_stabilization_type), intent(out), allocatable :: filter(:)
The stabilization type to be initialized
Calls
Called by
Call graph
atl_ini_stabilization calls aot_get_val, aot_table_close, aot_table_length, aot_table_open, atl_ini_cons_positivity_preserv, atl_ini_covolume, atl_ini_positivity_preserv, atl_ini_spectral_visc, tem_abort
atl_ini_cons_positivity_preserv calls aot_get_val, tem_abort, tem_horizontalSpacer
atl_ini_covolume calls aot_get_val, tem_abort, tem_horizontalSpacer
atl_ini_positivity_preserv calls aot_get_val, tem_abort, tem_horizontalSpacer
atl_ini_spectral_visc calls aot_get_val, tem_abort, tem_horizontalSpacer
atl_init_scheme calls atl_ini_stabilization
atl_init_elem_container calls atl_init_scheme
atl_initialize calls atl_init_elem_container
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize