atl_load_subprojection – Ateles
atl_load_subprojection Subroutine
32 statements
Source File
private subroutine atl_load_subprojection(minLevel, maxLevel, subkey, proj_pos, dynprojectArray, general_pos_list, conf, scheme_list, parent)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: minLevel
integer, intent(in) :: maxLevel
character(len=*), intent(in) :: subkey
integer, intent(out) :: proj_pos(minlevel:maxlevel)
type(dyn_projectionarray_type), intent(inout) :: dynprojectArray
integer, intent(in) :: general_pos_list(minLevel:maxLevel)
type(flu_State), intent(in) :: conf
type(atl_scheme_type), intent(in) :: scheme_list(minlevel:maxLevel)
integer, intent(in) :: parent
Calls
Called by
Call graph
atl_load_subprojection calls aot_table_close, aot_table_open, ply_fill_dynprojectarray
ply_fill_dynprojectarray calls append, ply_prj_header_load, ply_prj_init_define
append calls append_da_projection, append_da_vecprojection
ply_prj_header_load calls aot_get_val, ply_fpt_header_display, ply_fpt_header_load, ply_fxt_header_display, ply_fxt_header_load, ply_l2p_header_display, ply_l2p_header_load, tem_abort, upper_to_lower
append_da_projection calls expand, sortedposofval
append_da_vecprojection calls expand
ply_fpt_header_load calls aot_get_val, tem_abort, upper_to_lower
ply_fxt_header_load calls aot_get_val, tem_abort
ply_l2p_header_load calls aot_get_val, tem_abort, upper_to_lower
atl_load_projection calls atl_load_subprojection
atl_initialize calls atl_load_projection
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program