atl_load_LinearEuler – Ateles
atl_load_LinearEuler Subroutine
26 statements
Source File
public subroutine atl_load_LinearEuler(LinearEuler, conf, eq_table, spatial_dim)
subroutine to initialize an equation of type linear euler equation as defined in the configuration file
Arguments
Type Intent Optional Attributes Name
type(atl_LinearEuler_type), intent(out) :: LinearEuler
Resulting description of the Euler equation parameters.
type(flu_State) :: conf
Handle to the configuration script, to load the parameters from.
integer, intent(in) :: eq_table
Handle to the table containing the description for the equation system.
integer :: spatial_dim
The spatial dimension of the Euler equation
Calls
Called by
Call graph
atl_load_lineareuler calls aot_get_val, aot_table_close, aot_table_open, tem_abort, tem_horizontalSpacer, tem_load_temporal
atl_eqn_lineareuler_init calls atl_load_lineareuler
atl_init_equation calls atl_eqn_lineareuler_init
atl_initialize calls atl_init_equation
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize