atl_initialize_sources – Ateles
atl_initialize_sources Subroutine
28 statements
Source File
public subroutine atl_initialize_sources(source, initSource, conf, equation, poly_proj_list, mesh_list, tree, varSys_data)
Arguments
Type Intent Optional Attributes Name
type(atl_source_type), intent(inout) :: source
Instance of atl_source_type to be initialized. This instance will contain the source definitions from lua as well as the corresponding variables in the global variable system.
type(atl_init_source_type), intent(in) :: initSource
Initialize source type contains possible source terms and function pointers to update those source terms
type(flu_State), intent(inout) :: conf
lua state
type(atl_Equations_type), intent(inout) :: equation
Description on the equation system to solve.
type(ply_poly_project_type), intent(in) :: poly_proj_list(:)
unique list for projection methods
type(atl_cube_elem_type), intent(in) :: mesh_list(tree%global%minLevel:)
Mesh list to access the level descriptors
type(treelmesh_type), intent(in) :: tree
Mesh data in treelmesh format.
type(atl_varSys_solverData_type), intent(in), target :: varSys_data
Calls
Called by
Call graph
atl_initialize_sources calls append, init, atl_append_newsourcevars, atl_fill_sourceindex, atl_source_prim2cons, tem_variable_loadMapping
atl_append_newsourcevars calls positionofval, atl_get_new_varsys_data_ptr, tem_abort, tem_varSys_append_derVar, val
atl_fill_sourceindex calls append, nelems, atl_reftophyscoord, set_params, setup_indices, val
atl_source_prim2cons calls get_params, tem_abort, val
atl_initialize calls atl_initialize_sources
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program