atl_getEulerLinInd – Ateles
atl_getEulerLinInd Subroutine
48 statements
Source File
public subroutine atl_getEulerLinInd(euler, conf, eqn_handle, eqn_dim)
Getting the linearization indicator for Euler equations from the config.
Set the function pointer to compute the linearization indicator according to the setting by the user. Available indicators are:
'density' to use the maximal relative deviation in density
'energy' to use the maximal relative deviation in energy
'error' to use an error estimate
If linear_limit is 0, the indicator is completely deactivated and euler%linear will always return .false.
Arguments
Type Intent Optional Attributes Name
type(atl_euler_type), intent(inout) :: euler
The equations type to set the numerical flux in.
type(flu_State) :: conf
Configuration file handle to get the numerical flux setting from.
integer, intent(in) :: eqn_handle
Handle to the equation table in the configuration script.
integer, intent(in) :: eqn_dim
Dimension of the equation to set the flux for.
Calls
Called by
Call graph
atl_geteulerlinind calls aot_get_val, tem_abort, upper_to_lower
atl_eqn_euler_init calls atl_geteulerlinind
atl_eqn_nvrstk_init calls atl_geteulerlinind
atl_init_equation calls atl_eqn_euler_init, atl_eqn_nvrstk_init
atl_initialize calls atl_init_equation
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize