atl_physFluxMaxwellDivCor – Ateles
atl_physFluxMaxwellDivCor Function
18 statements
Source File
public function atl_physFluxMaxwellDivCor(state, material) result(flux)
Function for physical flux of the Maxwell equations in terms of D and B.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: state(8)
State to compute the fluxes from (D,B).
real(kind=rk), intent(in) :: material(4)
Material parameters (mu, epsilon) the flux calculation
Return Value real(kind=rk), (8)
The resulting flux in x direction
Called by
Call graph
compute_physfluxdivcor_nonconst calls atl_physfluxmaxwelldivcor
maxwell_hc_flux_cube calls atl_physfluxmaxwelldivcor
maxwell_hc_flux_cube_vec calls atl_physfluxmaxwelldivcor
atl_maxwell_hc_flux calls maxwell_hc_flux_cube, maxwell_hc_flux_cube_vec, maxwell_hc_flux_nonconst_cube_vec
atl_modg_maxwelldivcor_physflux_nonconst calls compute_physfluxdivcor_nonconst
maxwell_hc_flux_nonconst_cube_vec calls maxwell_hc_flux_cube
atl_modg_maxwelldivcor_numflux calls atl_maxwell_hc_flux
compute_rhs_cubes_modg calls atl_modg_maxwelldivcor_numflux