atl_modg_project_NumFlux – Ateles
atl_modg_project_NumFlux Subroutine
111 statements
Source File
public subroutine atl_modg_project_NumFlux(mesh, equation, kerneldata, facedata, scheme, poly_proj, dl_prod, dl_prodDiff, dirVec, penalizationdata, usePenalization)
Subroutine to project modal representations of physical flux, numerical flux and source terms onto test functions.
TODO NA - maybe move this call out of this routine ?
Arguments
Type Intent Optional Attributes Name
type(atl_cube_elem_type), intent(in) :: mesh
Descritption of the cubical elements in the mesh
type(atl_Equations_type), intent(in) :: equation
The equation description.
type(atl_kerneldata_type), intent(inout) :: kerneldata
The data of the kernel. Holds the physical fluxes.
type(atl_facedata_type), intent(inout) :: facedata
The representation on the face + representation of the flux.
type(atl_modg_scheme_type), intent(in) :: scheme
The parameters of the MODG scheme
type(ply_poly_project_type), intent(inout) :: poly_proj
Projection for the current level
real(kind=rk), intent(in) :: dl_prod(2,scheme%maxPolyDegree+1)
stored scalar products of the testfunction and anstaz function
real(kind=rk), intent(in) :: dl_prodDiff(2,scheme%maxPolyDegree+1)
integer, intent(in) :: dirVec(3,3)
vector for direction indicators
type(atl_penalizationData_type), intent(in) :: penalizationdata
Volumetric data for the penalization
logical, intent(in) :: usePenalization
Flag to indicate, whether we need to take care of the penalization terms here or not.
Calls
Called by
Call graph
atl_modg_project_numflux calls nelems, modg_project_numflux_difftest_q, modg_project_numflux_p, modg_project_numflux_q, modg_project_penalization_q, modg_project_stabviscnumfluxx_q, modg_project_stabviscnumfluxy_q, modg_project_stabviscnumfluxz_q, ply_change_poly_space, tem_abort
modg_project_numflux_difftest_q calls ply_facevalleftbndgradtest, ply_facevalrightbndgradtest
modg_project_numflux_p calls ply_facevalleftbndtest, ply_facevalrightbndtest
modg_project_numflux_q calls ply_facevalleftbndtest, ply_facevalrightbndtest
modg_project_penalization_q calls ply_scalproddualleg
modg_project_stabviscnumfluxx_q calls ply_poly_project_m2n, ply_poly_project_n2m, atl_mult_nu11_navierstokes, atl_mult_nu21_navierstokes, atl_mult_nu31_navierstokes, ply_facevalleftbndtest, ply_facevalleftbndtestgrad, ply_facevalrightbndtest, ply_facevalrightbndtestgrad, ply_scalproddualleg, ply_scalprodduallegdiff
modg_project_stabviscnumfluxy_q calls ply_poly_project_m2n, ply_poly_project_n2m, atl_mult_nu12_navierstokes, atl_mult_nu22_navierstokes, atl_mult_nu32_navierstokes, ply_facevalleftbndtest, ply_facevalleftbndtestgrad, ply_facevalrightbndtest, ply_facevalrightbndtestgrad, ply_scalproddualleg, ply_scalprodduallegdiff
modg_project_stabviscnumfluxz_q calls ply_poly_project_m2n, ply_poly_project_n2m, atl_mult_nu13_navierstokes, atl_mult_nu23_navierstokes, atl_mult_nu33_navierstokes, ply_facevalleftbndtest, ply_facevalleftbndtestgrad, ply_facevalrightbndtest, ply_facevalrightbndtestgrad, ply_scalproddualleg, ply_scalprodduallegdiff
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
compute_rhs_cubes_modg calls atl_modg_project_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg
atl_compute_rhs calls compute_rhs_cubes
global_corrector_substep calls atl_compute_rhs
imexrk_substep calls atl_compute_rhs
mesh_timestep_euler calls atl_compute_rhs
rk2_substep calls atl_compute_rhs
rk4_substep calls atl_compute_rhs
rktaylor_substep calls atl_compute_rhs