atl_modg_1d_bnd – Ateles
atl_modg_1d_bnd Function
21 statements
Source File
public function atl_modg_1d_bnd(bc, faceOp, poly_proj, equation, tree, normalRot, isNodalScheme, time, faceDir, leftOrRight, bndBaryCoord, elemLength, faceMaterial) result(modalFace)
Subroutine to create the modal representation for a ceratin boundary face.
Arguments
Type Intent Optional Attributes Name
type(atl_boundary_type), intent(in) :: bc
The boundary condition to generate the modal representation for.
real(kind=rk), intent(inout) :: faceOp(:,:)
The modal representation on the face of the neighboring element.
type(ply_poly_project_type), intent(inout) :: poly_proj
The parameters for projection method.
type(atl_Equations_type), intent(in) :: equation
The equation system you use.
type(treelmesh_type), intent(in) :: tree
treelm mesh
type(coordRotation_type), intent(in) :: normalRot
Rotation indices to rotate global coordinate system into face normal coordinate system.
logical, intent(in) :: isNodalScheme
Does the solver require isNodalScheme information anyway?
type(tem_time_type), intent(in) :: time
The absolute time point.
integer, intent(in) :: faceDir
The spatial direction of the boundary face, i.e.: \n 1 -> x direction
integer, intent(in) :: leftOrRight
Is left or right of the fluid element a boundary face.
real(kind=rk), intent(in) :: bndBaryCoord(1:3)
The barycentric boundary element coordinates
real(kind=rk), intent(in) :: elemLength
The length of an element on the current level
real(kind=rk), intent(in), optional :: faceMaterial(:,:)
The material of the boundary face. First dimension is the number of points on the face. Second dimension is the number of material parameters.
Return Value real(kind=rk), (1,equation%varSys%nScalars)
The modal representation on the boundary face.
Calls
Called by
Call graph
atl_modg_1d_bnd calls modg_1d_modal_bnd, modg_1d_nodal_bnd
modg_1d_modal_bnd calls modg_1d_bnd_extrapolate, modg_1d_bnd_mirrormodalconst, modg_1d_bnd_mirrorpoint, tem_abort, val
modg_1d_nodal_bnd calls modg_1d_bnd_extrapolate, modg_1d_bnd_mirrorpoint, tem_abort, val
modg_1d_bnd_mirrorpoint calls get_point, atl_reftophyscoord, ply_get_quadpoints_faces_1d
atl_modg_1d_set_bnd calls atl_modg_1d_bnd
atl_set_covolume_bnd calls atl_modg_1d_bnd
atl_interpolate_elemstate calls atl_set_covolume_bnd, atl_interpolate_elemstate
preprocess_rhs_cubes calls atl_modg_1d_set_bnd
atl_preprocess_rhs calls preprocess_rhs_cubes
atl_covolume_tocovolume calls atl_interpolate_elemstate
atl_covolume_tocovolume_1d calls atl_interpolate_elemstate
atl_covolume_tocovolume_2d calls atl_interpolate_elemstate
atl_covolume calls atl_covolume_tocovolume
atl_covolume_1d calls atl_covolume_tocovolume_1d
atl_covolume_2d calls atl_covolume_tocovolume_2d
global_corrector_substep calls atl_preprocess_rhs
imexrk_substep calls atl_preprocess_rhs
mesh_timestep_euler calls atl_preprocess_rhs
rk2_substep calls atl_preprocess_rhs
rk4_substep calls atl_preprocess_rhs
rktaylor_substep calls atl_preprocess_rhs