atl_physFluxEuler_2d – Ateles
atl_physFluxEuler_2d Function
16 statements
Source File
public function atl_physFluxEuler_2d(state, isenCoeff, penalty_char, porosity, U_o) result(physFlux)
Physical flux calculation along x direction for Euler equation.
Todo
JZ: here, we devide by a polynomial, we should be careful! We are leaving the polynomial space here!
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: state(:)
The state in nodal space. Dimension is the number of vars, i.e. 5 for Euler
real(kind=rk), intent(in) :: isenCoeff
Adiabatice index, also known as isentropic expansion factor.
real(kind=rk), intent(in) :: penalty_char
The value of the characteristic function (stemming from penalization)
real(kind=rk), intent(in) :: porosity
The porosity at the current point
real(kind=rk), intent(in) :: U_o
Velocity of the obstacle
Return Value real(kind=rk), allocatable, (:)
The physical flux along the x axis for all variables
Called by
Call graph
atl_godunoveuler2d calls atl_physfluxeuler_2d
atl_laxfriedeuler_2d calls atl_physfluxeuler_2d
atl_modg_2d_euler_physflux_const calls atl_physfluxeuler_2d
atl_modg_2d_euler_physflux_nonconst calls atl_physfluxeuler_2d
atl_modg_2d_navierstokes_physflux_const calls atl_physfluxeuler_2d
atl_modg_2d_navierstokes_physflux_nonconst calls atl_physfluxeuler_2d
modg_2d_compute_project_physflux calls atl_physfluxeuler_2d
compute_rhs_cubes_modg_2d calls modg_2d_compute_project_physflux
compute_rhs_cubes calls compute_rhs_cubes_modg_2d
atl_compute_rhs calls compute_rhs_cubes