atl_modg_2d_volToFace_grad_Q – Ateles
atl_modg_2d_volToFace_grad_Q Subroutine
67 statements
Source File
public subroutine atl_modg_2d_volToFace_grad_Q(volState, maxPolyDegree, faceDir, nScalars, nElems, elemLength, faceState)
Project modal representation of gradients of an element to one of its faces for Q space.
Project modal representation of gradients of an element onto one of its faces. Therefore, this function returns the modal representation of the solution's gradient on the face. This function can project onto an arbitrary face direction.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: volState(:,:,:)
The modal representation in the volume. First dimension is the number of voluemtrix numbers of degrees of freedom and second dimension is the number of scalar variables in the equation system.
integer, intent(in) :: maxPolyDegree
The maximal polynomial degree per spatial direction.
integer, intent(in) :: faceDir
The face to project the modal representation to. Use one of the first six directions of \link tem_param_module \endlink, e.g. \link tem_param_module::q__e \endlink
integer, intent(in) :: nScalars
The number of scalar variables in your equation system.
integer, intent(in) :: nElems
The number of elements
real(kind=rk), intent(in) :: elemLength
The lenght of an element
real(kind=rk), intent(inout) :: faceState(:,:,:,:)
The modal representation on the face
Calls
Called by
Call graph
atl_modg_2d_voltoface_grad_q calls ply_calcdiff_leg_2d, ply_facevalleftbndans, tem_abort
ply_calcdiff_leg_2d calls ply_calcdiff_leg_2d_normal
atl_modg_2d_modalvoltomodalface calls atl_modg_2d_voltoface_grad_q
preprocess_rhs_cubes calls atl_modg_2d_modalvoltomodalface
atl_preprocess_rhs calls preprocess_rhs_cubes
global_corrector_substep calls atl_preprocess_rhs
imexrk_substep calls atl_preprocess_rhs
mesh_timestep_euler calls atl_preprocess_rhs
rk2_substep calls atl_preprocess_rhs
rk4_substep calls atl_preprocess_rhs
rktaylor_substep calls atl_preprocess_rhs