atl_modg_heat_numFlux_sipg – Ateles
atl_modg_heat_numFlux_sipg Subroutine
52 statements
Source File
public subroutine atl_modg_heat_numFlux_sipg(equation, facedata, faces, faceDir, dofs, elem_len, maxPolyDeg)
Numerical flux calculation for Heat equation across the faces in a single spatial direction.
Arguments
Type Intent Optional Attributes Name
type(atl_Equations_type), intent(in) :: equation
The equation you solve.
type(atl_facedata_type), intent(inout) :: facedata
The face state if the equation
type(tem_faceIterator_type), intent(in) :: faces
The faces to calculate the fluxes for.
integer, intent(in) :: faceDir
The spatial direction of the faces you calc the fluxes for, use the following: 1 --> x direction. \n 2 --> y direction. \n 3 --> z direction.
integer, intent(in) :: dofs
Parameter for used projection
real(kind=rk), intent(in) :: elem_len
Length of the element
integer, intent(in) :: maxPolyDeg
Max polynomial degree
Called by
Call graph
atl_modg_2d_heat_numflux calls atl_modg_heat_numflux_sipg
atl_modg_heat_numflux calls atl_modg_heat_numflux_sipg
compute_rhs_cubes_modg calls atl_modg_heat_numflux
compute_rhs_cubes_modg_2d calls atl_modg_2d_heat_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg, compute_rhs_cubes_modg_2d
atl_compute_rhs calls compute_rhs_cubes