atl_modg_euler_numFlux – Ateles
atl_modg_euler_numFlux Subroutine
11 statements
Source File
public subroutine atl_modg_euler_numFlux(equation, facedata, poly_proj, material)
Calculate the numerical flux for Euler equation and MODG scheme
Arguments
Type Intent Optional Attributes Name
type(atl_Equations_type), intent(in) :: equation
The equation you solve.
type(atl_facedata_type), intent(inout) :: facedata
The face representation of the state.
type(ply_poly_project_type), intent(inout) :: poly_proj
Parameter for projection.
type(atl_material_type), intent(inout) :: material
Material description for the faces on the current level
Calls
Called by
Call graph
atl_modg_euler_numflux calls atl_modg_euler_onedim_numflux_const, atl_modg_euler_onedim_numflux_nonconst, vartransformindices
atl_modg_euler_onedim_numflux_const calls ply_poly_project_m2n, ply_poly_project_n2m, ply_convert2oversample, ply_convertfromoversample
atl_modg_euler_onedim_numflux_nonconst calls ply_poly_project_m2n, ply_poly_project_n2m, ply_convert2oversample, ply_convertfromoversample
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
ply_poly_project_m2n_multivar calls ply_legtopnt_2d, ply_legtopnt_3d, ply_fxt_m2n_1d, ply_fxt_m2n_2d, ply_fxt_m2n_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d, ply_pnttoleg_3d, ply_fxt_n2m_1d, ply_fxt_n2m_2d, ply_fxt_n2m_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
compute_rhs_cubes_modg calls atl_modg_euler_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg
atl_compute_rhs calls compute_rhs_cubes
global_corrector_substep calls atl_compute_rhs
imexrk_substep calls atl_compute_rhs
mesh_timestep_euler calls atl_compute_rhs
rk2_substep calls atl_compute_rhs
rk4_substep calls atl_compute_rhs
rktaylor_substep calls atl_compute_rhs