atl_init_modg_kernel – Ateles
atl_init_modg_kernel Subroutine
47 statements
Source File
public subroutine atl_init_modg_kernel(kerneldata_list, statedata_list, statedata_stab_list, mesh_list, scheme_list, boundary_list, boundary_stab_list, equation, tree, time, commPattern, need_deviation)
Initiate the MODG kernel for cubic elements on all levels.
Arguments
Type Intent Optional Attributes Name
type(atl_kerneldata_type), allocatable :: kerneldata_list(:)
Array of kerneldata_types, one for each level. They will be initialized.
type(atl_statedata_type), allocatable :: statedata_list(:)
Array of statedata_types, one for each level.
type(atl_statedata_type), allocatable :: statedata_stab_list(:,:)
type(atl_cube_elem_type), allocatable :: mesh_list(:)
List of cubic meshes. One entry per level.
type(atl_scheme_type), allocatable :: scheme_list(:)
List of schemes on the levels.
type(atl_level_boundary_type), allocatable :: boundary_list(:)
The boundary description for the faces on the current level.
type(atl_level_boundary_type), allocatable :: boundary_stab_list(:)
The boundary description for the faces on the current level.
type(atl_Equations_type) :: equation
The equation type.
type(treelmesh_type), intent(in) :: tree
The tree of the simulation domain
type(tem_time_type), intent(in) :: time
current time
type(tem_commPattern_type), intent(in) :: commPattern
mpi communication pattern type
logical, intent(in) :: need_deviation
Flag to indicate whether maximal polynomial deviations should be computed for the state.
Calls
Called by
Call graph
atl_init_modg_kernel calls dimbydimdesc, nelems, atl_get_numbndelems, atl_init_kerneldata, atl_init_parallel_module, atl_init_statedata
atl_init_kerneldata calls atl_init_statedata
atl_init_parallel_module calls dimbydimdesc, atl_init_cellstatebuffer, atl_init_facestatebuffer
atl_init_cellstatebuffer calls buf_real, elempos, val
atl_init_facestatebuffer calls buf_int, buf_real, elempos, recvbuffer_flux, recvbuffer_state, sendbuffer_flux, sendbuffer_state, val
init_kernel calls atl_init_modg_kernel
atl_init_elem_container calls init_kernel
atl_initialize calls atl_init_elem_container
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize