atl_physCheck_euler2d – Ateles
atl_physCheck_euler2d Function
55 statements
Source File
private function atl_physCheck_euler2d(statedata, euler2d, scheme, poly_proj, nElems_fluid, tolerance, total) result(isPhysical)
Routine to check if the physical values of a state are physically meaningful or not for the Euler equation.
Arguments
Type Intent Optional Attributes Name
type(atl_statedata_type), intent(in) :: statedata
type(atl_euler_type), intent(in) :: euler2d
type(atl_scheme_type), intent(in) :: scheme
type(ply_poly_project_type), intent(inout) :: poly_proj
integer, intent(in) :: nElems_fluid
real(kind=rk), intent(in) :: tolerance
integer(kind=long_k), intent(in) :: total(:)
Return Value logical
Calls
Called by
Call graph
atl_physcheck_euler2d calls ply_poly_project_m2n, ply_convert2oversample, tem_abort, tem_isNaN
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_poly_project_m2n_multivar calls ply_legtopnt_2d, ply_legtopnt_3d, ply_fxt_m2n_1d, ply_fxt_m2n_2d, ply_fxt_m2n_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_legtopnt_2d calls ply_legtopnt_2d_multvar, ply_legtopnt_2d_singvar
ply_legtopnt_3d calls ply_legtopnt_3d_multvar, ply_legtopnt_3d_singvar
ply_fxt_m2n_1d calls fxtf_flptld_m2n
ply_fxt_m2n_2d calls fxtf_flptld_m2n
ply_fxt_m2n_3d calls fxtf_flptld_m2n
ply_l2p_trafo_1d calls ply_l2_projection
ply_l2p_trafo_2d calls ply_l2_projection
ply_l2p_trafo_3d calls ply_l2_projection
atl_check_val calls atl_physcheck_euler2d
atl_solve_program calls atl_check_val
ateles calls atl_solve_program