atl_modg_1d_invMassMatrix – Ateles
atl_modg_1d_invMassMatrix Subroutine
15 statements
Source File
public subroutine atl_modg_1d_invMassMatrix(mesh, kerneldata, statedata, elementalTimestep, timestep, scheme)
Applies the inverse of the mass matrix for a 3D scheme.
Arguments
Type Intent Optional Attributes Name
type(atl_cube_elem_type) :: mesh
The mesh you are working with.
type(atl_kerneldata_type) :: kerneldata
The data of the kernel.
type(atl_statedata_type) :: statedata
THe state if the equation
procedure(atl_elemental_timestep_vec), intent(in), pointer :: elementalTimestep
The elemental timestepping routine, because of performance, this is constant.
type(atl_timestep_type) :: timestep
The timestepping data.
type(atl_modg_1d_scheme_type), intent(in) :: scheme
Parameters of the modal dg scheme
Calls
Called by
Call graph
atl_modg_1d_invmassmatrix calls nelems, modg_1d_invmassmatrix_q
postprocess_rhs_cubes calls atl_modg_1d_invmassmatrix
atl_postprocess_rhs calls postprocess_rhs_cubes
global_corrector_substep calls atl_postprocess_rhs
imexrk_substep calls atl_postprocess_rhs, imexrk_substep
mesh_timestep_euler calls atl_postprocess_rhs, mesh_timestep_euler
rk2_substep calls atl_postprocess_rhs, rk2_substep
rk4_substep calls atl_postprocess_rhs, rk4_substep
rktaylor_substep calls atl_postprocess_rhs, rktaylor_substep
mesh_timestep_imexrk calls imexrk_substep
mesh_timestep_predcor_cerk4 calls global_corrector_substep
mesh_timestep_rk4 calls rk4_substep
mesh_timestep_rktaylor calls rktaylor_substep
mesh_timestep_ssprk2 calls rk2_substep