atl_create_fortranVar – Ateles
atl_create_fortranVar Subroutine
15 statements
Source File
public subroutine atl_create_fortranVar(me)
This routine creates hard coded variables which are required by ateles.
For example: Lot of boundary condition variables require constant zero as spacetime-function, thus we create a variable "zero_const" here to be able to refer to it in boundary condition definitions.
Arguments
Type Intent Optional Attributes Name
type(tem_variable_type), intent(out), allocatable :: me(:)
Contains list of hard coded variables
Calls
Called by
Call graph
atl_create_fortranvar calls const, geom
atl_initialize calls atl_create_fortranvar
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program