atl_append_rans_primVars – Ateles
atl_append_rans_primVars Subroutine
46 statements
Source File
public subroutine atl_append_rans_primVars(varSys, primVar, solverData, nDim)
Arguments
Type Intent Optional Attributes Name
type(tem_varSys_type), intent(inout) :: varSys
The variable system to append primitive variables to
integer, intent(out), allocatable :: primVar(:)
Indices of the primitive variables in the overall system.
type(atl_varSys_solverData_type), target :: solverData
the pointer to the data required for the varsys to fulfill all operations and derivations on the variables
integer, intent(in) :: nDim
Calls
Called by
Call graph
atl_append_rans_primvars calls positionofval, atl_get_new_varsys_data_ptr, tem_abort, tem_get_new_varSys_data_ptr, tem_varSys_append_derVar
atl_init_rans_2d_vars calls atl_append_rans_primvars
atl_init_rans_vars calls atl_append_rans_primvars
atl_eqn_filtered_nvrstk_init calls atl_init_rans_2d_vars, atl_init_rans_vars
atl_init_equation calls atl_eqn_filtered_nvrstk_init
atl_initialize calls atl_init_equation