atl_ere_eval_onEdge – Ateles
atl_ere_eval_onEdge Subroutine
111 statements
Source File
public elemental subroutine atl_ere_eval_onEdge(me, rho_left, vn_left, v1_left, v2_left, p_left, rho_right, vn_right, v1_right, v2_right, p_right, rho, vn, v1, v2, p)
Evaluate the state on the edge using the exact riemann solver
Todo
clarify what to do with v1 and v2
Todo
clarify what to do with v1 and v2
Todo
clarify what to do with v1 and v2
Todo
clarify what to do with v1 and v2
Todo
clarify what to do with v1 and v2
Todo
clarify what to do with v1 and v2
Arguments
Type Intent Optional Attributes Name
type(atl_ere_solState1D_type), intent(in) :: me
Description of the general constants for the Riemann solver.
real(kind=rk), intent(in) :: rho_left
real(kind=rk), intent(in) :: vn_left
real(kind=rk), intent(in) :: v1_left
real(kind=rk), intent(in) :: v2_left
real(kind=rk), intent(in) :: p_left
real(kind=rk), intent(in) :: rho_right
real(kind=rk), intent(in) :: vn_right
real(kind=rk), intent(in) :: v1_right
real(kind=rk), intent(in) :: v2_right
real(kind=rk), intent(in) :: p_right
real(kind=rk), intent(out) :: rho
real(kind=rk), intent(out) :: vn
real(kind=rk), intent(out) :: v1
real(kind=rk), intent(out) :: v2
real(kind=rk), intent(out) :: p
Calls
Called by
Call graph
atl_ere_eval_onedge calls nr_1side, nr_start
atl_godunoveuler calls atl_ere_eval_onedge
atl_godunoveuler1d calls atl_ere_eval_onedge
atl_godunoveuler2d calls atl_ere_eval_onedge