atl_write_nonequiPoints – Ateles
atl_write_nonequiPoints Subroutine
69 statements
Source File
private subroutine atl_write_nonequiPoints(varSys, tree, stFun, preciceCpl)
setup_indices for boundary variables are read_var in precice space-time function we are not able to use 'idx' created here as input for get_valOfIndex for write_vars.Therefore we have to do setup_indices for write_vars once during initialization and then store the idx in precice_coupling type. This is done for the non-equidistant points. We also set the vertices and the edges as well as the triangles for the Interpolation between the domains.
Obtain the point coordinates to get values for get the number of unquie points (xyz should be same number) VK write(,) 'number of Points to write to precice is 0, cycle & VK & this spacetimefunction' shift the points via the offset bit for the get_point routine get the unquie list of points get the unquie list of points serialize them since precice needs a 1d array transform offet bit back shift the points according to the offset bit * small fraction of the boundingCubeLength hence it is mesh independent loop over the variables to write to precice get_point routine for unquie array of points of that variable get the setup_indices for the shifted points
Since we are sending 5 times the same idx, for the unique Points and all of them have the same idx, we just need to store it once send the points to precice and get back the positionID allocate posID array
From here on the Nearest-Projection is introduced, which has to be activated by the user in the ateles-config file.
We assume here, that all points for a specific face are grouped together in order to make use of the posIDs Call to create the edges and triangles acoording to the dimension
Arguments
Type Intent Optional Attributes Name
type(tem_varSys_type), intent(in) :: varSys
Global variable system
type(treelmesh_type), intent(in) :: tree
information about the mesh
type(tem_st_fun_listElem_type), intent(inout) :: stFun
contains the elements in spacetime-function
type(tem_precice_coupling_type), pointer :: preciceCpl
Calls
Called by
Call graph
atl_write_nonequipoints calls append, indexlvl, pntlvl, posids, atl_nearest_projection, setup_indices, tem_precice_set_vertices_pos, val, varpos
atl_nearest_projection calls posids, edges, interpol_data, posidlvl, tem_create_edges_triangles, tem_precice_set_edge, tem_precice_set_triangle, triangles
atl_write_precice_getpoint calls atl_write_nonequipoints
atl_init_precice calls atl_write_precice_getpoint
atl_initialize calls atl_init_precice
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize