atl_append_euler_1d_consVars – Ateles
atl_append_euler_1d_consVars Subroutine
24 statements
Source File
public subroutine atl_append_euler_1d_consVars(equation, solverData)
Append conservative variables for Euler equations.
These are density, momentum and energy here.
Arguments
Type Intent Optional Attributes Name
type(atl_Equations_type), intent(inout) :: equation
The equation type .
type(atl_varSys_solverData_type), target :: solverData
The type to be used as method data. This type has to contain all information necessary to determine the values of the variables in the variable system.
Calls
Called by
Call graph
atl_append_euler_1d_consvars calls atl_get_new_varsys_data_ptr, tem_varSys_append_stateVar
atl_init_euler_1d_vars calls atl_append_euler_1d_consvars
atl_eqn_euler_init calls atl_init_euler_1d_vars
atl_init_equation calls atl_eqn_euler_init
atl_initialize calls atl_init_equation