atl_mult_nu12_Rans_2d – Ateles
atl_mult_nu12_Rans_2d Function
19 statements
Source File
public function atl_mult_nu12_Rans_2d(state, velocity, inVec, mu, lambda, rans_params) result(outVec)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: state(6)
The state array
real(kind=rk), intent(in) :: velocity(2)
The velocity
real(kind=rk), intent(in) :: inVec(6)
Vector to be multiplied with nu11
real(kind=rk), intent(in) :: mu
Dynamic Viscosity
real(kind=rk), intent(in) :: lambda
Viscosity
type(atl_navier_stokes_rans_type), intent(in) :: rans_params
The constants for the Rans eqn
Return Value real(kind=rk), (6)
The result of the matrix vector product
Called by
Call graph
modg_2d_project_stabviscnumfluxy_q calls atl_mult_nu12_rans_2d
atl_modg_2d_project_numflux calls modg_2d_project_stabviscnumfluxy_q
compute_rhs_cubes_modg_2d calls atl_modg_2d_project_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg_2d