atl_append_lineareuler_derivedVars – Ateles
atl_append_lineareuler_derivedVars Subroutine
46 statements
Source File
private subroutine atl_append_lineareuler_derivedVars(varSys, methodData)
Arguments
Type Intent Optional Attributes Name
type(tem_varSys_type), intent(inout) :: varSys
The Euler variable system to modify. It has to contain the conservative and primitive variables already.
type(atl_varSys_solverData_type), target :: methodData
the pointer to the data required for the varsys to fulfill all operations and derivations on the variables
Calls
Called by
Call graph
atl_append_lineareuler_derivedvars calls atl_get_new_varsys_data_ptr, tem_abort, tem_varSys_append_derVar
atl_init_lineareuler_vars calls atl_append_lineareuler_derivedvars
atl_eqn_lineareuler_init calls atl_init_lineareuler_vars
atl_init_equation calls atl_eqn_lineareuler_init
atl_initialize calls atl_init_equation