atl_initTimeStepInfo – Ateles
atl_initTimeStepInfo Subroutine
152 statements
Source File
public subroutine atl_initTimeStepInfo(equation, mesh, poly_proj, timestep, control, statedata, kerneldata)
Subroutine to initialize the timestep information for the first iteration
Arguments
Type Intent Optional Attributes Name
type(atl_Equations_type), intent(in) :: equation
The equaton you are using.
type(atl_cube_elem_type), intent(in) :: mesh
Mesh description
type(ply_poly_project_type), intent(inout) :: poly_proj
The projection methos of the simulation.
type(atl_timestep_type), intent(inout) :: timestep
Timestep information. This routine will update information about the the maximum velocity and the maximum speed of sound in the system.
type(atl_timestep_control_type), intent(in) :: control
Description of the timestep control.
type(atl_statedata_type), intent(in) :: statedata
The current state for all elements on the current level
type(atl_kerneldata_type), intent(in) :: kerneldata
Additional information on the state.
Calls
Called by
Call graph
atl_inittimestepinfo calls ply_poly_project_m2n, nelems, atl_eqn_euler_1d_cons2prim, atl_eqn_euler_2d_cons2prim, atl_eqn_euler_cons2prim, ply_convert2oversample, tem_abort
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_poly_project_m2n_multivar calls ply_legtopnt_2d, ply_legtopnt_3d, ply_fxt_m2n_1d, ply_fxt_m2n_2d, ply_fxt_m2n_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_legtopnt_2d calls ply_legtopnt_2d_multvar, ply_legtopnt_2d_singvar
ply_legtopnt_3d calls ply_legtopnt_3d_multvar, ply_legtopnt_3d_singvar
ply_fxt_m2n_1d calls fxtf_flptld_m2n
ply_fxt_m2n_2d calls fxtf_flptld_m2n
ply_fxt_m2n_3d calls fxtf_flptld_m2n
ply_l2p_trafo_1d calls ply_l2_projection
ply_l2p_trafo_2d calls ply_l2_projection
ply_l2p_trafo_3d calls ply_l2_projection
atl_initialize_program calls atl_inittimestepinfo
atl_solve_program calls atl_inittimestepinfo
ateles calls atl_initialize_program, atl_solve_program