atl_init_global_time_integration – Ateles
atl_init_global_time_integration Subroutine
54 statements
Source File
public subroutine atl_init_global_time_integration(me, minLevel, maxLevel, statedata_list, mesh_list, equation)
Routine to init the timestepping scheme.
This allocates datafields as needed. Be aware that the configuration has to be loaded beforehand!
Arguments
Type Intent Optional Attributes Name
type(atl_global_timestep_type), intent(inout) :: me
the scheme you want to initialize.
integer, intent(in) :: minLevel
The minimum level of the mesh
integer, intent(in) :: maxLevel
The maximum level of the mesh.
type(atl_statedata_type), intent(in) :: statedata_list(minLevel:maxLevel)
The state list used in your solver, for each level one entry.
type(atl_cube_elem_type), intent(in) :: mesh_list(minLevel:maxLevel)
Mesh description
type(atl_Equations_type), intent(in) :: equation
The equaton you are using.
Calls
Called by
Call graph
atl_init_global_time_integration calls nelems, atl_init_explicit_ssprk, atl_init_expliciteuler, atl_init_explicitlocalpredictorglobalcorrector, atl_init_explicitrungekutta, atl_init_explicitrungekuttataylor, atl_init_imexrungekutta, tem_abort
atl_init_explicit_ssprk calls tem_abort
atl_init_explicitlocalpredictorglobalcorrector calls tem_abort
atl_init_explicitrungekutta calls tem_abort
atl_init_explicitrungekuttataylor calls tem_abort
atl_init_imexrungekutta calls tem_abort
atl_init_elem_container calls atl_init_global_time_integration
atl_initialize calls atl_init_elem_container
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program