atl_modg_maxwellDivCor_physFlux_NonConst – Ateles
atl_modg_maxwellDivCor_physFlux_NonConst Subroutine
29 statements
Source File
public subroutine atl_modg_maxwellDivCor_physFlux_NonConst(equation, res, state, iElem, iDir, penalizationData, poly_proj, material, nodal_data, nodal_GradData, nodal_res, ElemLength, scheme_min, scheme_current)
Calculate the physical flux for the MODG scheme and Maxwell equation with hyperbolic divergenc cleaning.
Arguments
Type Intent Optional Attributes Name
type(atl_Equations_type), intent(in) :: equation
The equation you solve.
real(kind=rk), intent(inout) :: res(:,:)
To store the resulting phy flux in modal form
real(kind=rk), intent(in), optional :: state(:,:)
The state of the equation
integer, intent(in) :: iElem
The current Element
integer, intent(in) :: iDir
The current Direction
type(atl_penalizationData_type), intent(inout) :: penalizationData
The penalization data
type(ply_poly_project_type), intent(inout) :: poly_proj
Poly project
type(atl_material_type), intent(inout) :: material
Material description for the faces on the current level
real(kind=rk), intent(in), optional :: nodal_data(:,:)
The state in nodal form
real(kind=rk), intent(in), optional :: nodal_GradData(:,:,:)
real(kind=rk), intent(inout) :: nodal_res(:,:)
real(kind=rk), intent(in) :: ElemLength
Length of the element
type(atl_scheme_type), intent(inout) :: scheme_min
The scheme information
type(atl_scheme_type), intent(inout) :: scheme_current
Calls
Call graph
atl_modg_maxwelldivcor_physflux_nonconst calls compute_physfluxdivcor_nonconst, tem_abort, vartransformindices
compute_physfluxdivcor_nonconst calls ply_poly_project_m2n, ply_poly_project_n2m, atl_physfluxmaxwelldivcor, ply_convert2oversample, ply_convertfromoversample
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
ply_poly_project_m2n_multivar calls ply_legtopnt_2d, ply_legtopnt_3d, ply_fxt_m2n_1d, ply_fxt_m2n_2d, ply_fxt_m2n_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d, ply_pnttoleg_3d, ply_fxt_n2m_1d, ply_fxt_n2m_2d, ply_fxt_n2m_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d