atl_viscNavierStokes – Ateles
atl_viscNavierStokes Subroutine
16 statements
Source File
public subroutine atl_viscNavierStokes(left, left_grad, right, right_grad, mu, lambda, thermCond, heatCap, penaltyIP, flux)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: left(5)
The state on the face from its left limit (in conservative variables).
real(kind=rk), intent(in) :: left_grad(5,3)
The gradient state on the face from its left limit (in conservative variables).
real(kind=rk), intent(in) :: right(5)
The state on the face from its right limit (in conservative variables).
real(kind=rk), intent(in) :: right_grad(5,3)
The gradient state on the face from its right limit (in conservative variables).
real(kind=rk), intent(in) :: mu
Resulting flux for the left element (in conservative variables). Dynamic Viscosity
real(kind=rk), intent(in) :: lambda
Viscosity
real(kind=rk), intent(in) :: thermCond
The thermal cond
real(kind=rk), intent(in) :: heatCap
The specific heat capacity (per mass unit mass, at constant volume)
real(kind=rk), intent(in) :: penaltyIP
The penalty parameter
real(kind=rk), intent(out) :: flux(5)
Calls
Called by
Call graph
atl_viscnavierstokes calls atl_viscphysfluxnavierstokes
atl_modg_viscnavierstokes_onedim_numflux calls atl_viscnavierstokes
atl_modg_filnvrstk_numflux calls atl_modg_viscnavierstokes_onedim_numflux
atl_modg_navierstokes_numflux calls atl_modg_viscnavierstokes_onedim_numflux
compute_rhs_cubes_modg calls atl_modg_filnvrstk_numflux, atl_modg_navierstokes_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg