atl_deriveQcriterion – Ateles
atl_deriveQcriterion Subroutine
23 statements
Source File
private subroutine atl_deriveQcriterion(fun, varSys, tree, iElem, elempos, nodalInput, nodalRes)
This routine evaluates the q_criterion. The input is the nodal value of
Arguments
Type Intent Optional Attributes Name
class(tem_varSys_op_type), intent(in) :: fun
Description of the method to obtain the variables, here some preset values might be stored, like the space time function to use or the required variables.
type(tem_varSys_type), intent(in) :: varSys
The variable system to obtain the variable from.
type(treelmesh_type), intent(in) :: tree
global treelm mesh info
integer, intent(in) :: iElem
The current element index
integer, intent(in) :: elempos(:)
TreeID of the element to get the variable for.
type(atl_derive_inputVar_type) :: nodalInput(:)
The input data. nodalInput contains one entry for each input variable. This entry itself contains the nodal data for the dofs and components of the input variable. These nodal data has to be gained by oversampling and projecting the modal state into nodal space.
real(kind=rk), allocatable :: nodalRes(:,:)
The result in nodal space
Calls
Call graph
atl_deriveqcriterion calls calc_eigenvalues_3by3_matrix, calc_matrix_qcriterion, tem_LevelOf
calc_eigenvalues_3by3_matrix calls atl_bubblesortarray