atl_write_precice_getPoint – Ateles
atl_write_precice_getPoint Subroutine
27 statements
Source File
public subroutine atl_write_precice_getPoint(stFunList, varSys, tree, mesh_list)
loop over linked list of spacetimefunction set the current to head check if there is a precice kind loop over all shapes of that spacetimefunction
check if this one has write flag
Arguments
Type Intent Optional Attributes Name
type(tem_st_fun_linkedList_type), intent(inout), target :: stFunList
This list contains all space-time-function
type(tem_varSys_type), intent(in) :: varSys
Global variable system
type(treelmesh_type), intent(in) :: tree
treelm mesh
type(atl_cube_elem_type), intent(in) :: mesh_list(tree%global%minLevel:tree%global%maxLevel)
Calls
Called by
Call graph
atl_write_precice_getpoint calls atl_write_equipoints, atl_write_nonequipoints
atl_write_equipoints calls append, indexlvl, interpol_data, pntlvl, posids, atl_nearest_projection, atl_reftophyscoord, setup_indices, tem_BaryOfId, tem_CoordOfReal, tem_IdOfCoord, tem_create_surface_equidistant_points, tem_precice_set_vertices_pos, val, varpos
atl_write_nonequipoints calls append, indexlvl, pntlvl, posids, atl_nearest_projection, setup_indices, tem_precice_set_vertices_pos, val, varpos
atl_nearest_projection calls interpol_data, posids, edges, posidlvl, tem_create_edges_triangles, tem_precice_set_edge, tem_precice_set_triangle, triangles
atl_init_precice calls atl_write_precice_getpoint
atl_initialize calls atl_init_precice
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program