atl_varSys_getStateForPoint – Ateles
atl_varSys_getStateForPoint Subroutine
79 statements
Source File
public subroutine atl_varSys_getStateForPoint(fun, varSys, point, time, tree, nPnts, res)
Interface description for a variable access method (single point).
To obtain values of a given variable, it is necessary to state the space and time at which the variable should be evaluated. The interface is vectorized and provides n values at n different space locations at the same time. Of course the variable system itself also needs to be passed in, to allow the computation of other derived quantities as needed. The method description itself is passed in automatically, and has not to be provided explicitly.
Arguments
Type Intent Optional Attributes Name
class(tem_varSys_op_type), intent(in) :: fun
Description of the method to obtain the variables, here some preset values might be stored, like the space time function to use or the required variables.
type(tem_varSys_type), intent(in) :: varSys
The variable system to obtain the variable from.
real(kind=rk), intent(in) :: point(:,:)
Three-dimensional coordinates at which the variable should be evaluated. Only useful for variables provided as space-time functions.
type(tem_time_type), intent(in) :: time
Point in time at which to evaluate the variable.
type(treelmesh_type), intent(in) :: tree
global treelm mesh info
integer, intent(in) :: nPnts
Number of values to obtain for this variable (vectorized access).
real(kind=rk), intent(out) :: res(:)
Resulting values for the requested variable.
Dimension: n requested entries x nComponents of this variable Access: (iElem-1)*fun%nComponents + iComp
Calls
Call graph
atl_varsys_getstateforpoint calls atl_evallegendretenspoly1d, atl_evallegendretenspoly2d, ply_evallegendretenspoly, tem_BaryOfId, tem_CoordOfReal, tem_ElemSize, tem_IdOfCoord, tem_LevelOf, tem_PosOfId, tem_abort, tem_startTimer, tem_stopTimer