atl_covolume_to_primal_projection – Ateles
atl_covolume_to_primal_projection Function
55 statements
Source File
public function atl_covolume_to_primal_projection(left, right, dir, filter, scheme, maxPolyDeg, nScalars, state) result(primal)
This routine projects two co-volume elements (left and right) onto its primal element. The geometrical setup is as follows:
     left (co-vol.)       right (co-vol.)
|---------------------||---------------------| \ / \ / | |/ |---------------------| primal element
The transformation to the primal element is carried out by a simple (but efficient) L2-projection.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: left(:,:)
real(kind=rk), intent(in) :: right(:,:)
integer, intent(in) :: dir
type(atl_covolume_type), intent(in) :: filter
type(atl_scheme_type), intent(in) :: scheme
The numerical schemes for the current level to get the modg basis
integer, intent(in) :: maxPolyDeg
integer, intent(in) :: nScalars
real(kind=rk), intent(in) :: state(:,:)
Return Value real(kind=rk), ((maxPolyDeg+1)**3,nScalars)
Calls
Called by
Call graph
atl_covolume_to_primal_projection calls tem_abort
atl_covolume_tocovolume calls atl_covolume_to_primal_projection
atl_covolume calls atl_covolume_tocovolume
atl_stabilize calls atl_covolume
mesh_timestep_euler calls atl_stabilize
mesh_timestep_imexrk calls atl_stabilize
mesh_timestep_rk4 calls atl_stabilize
mesh_timestep_rktaylor calls atl_stabilize
mesh_timestep_ssprk2 calls atl_stabilize
atl_harvesting calls atl_stabilize