atl_finalize_program – Ateles
atl_finalize_program Subroutine
35 statements
Source File
public subroutine atl_finalize_program(params, equation, tree, nCellsNoBnd, element_container)
Arguments
Type Intent Optional Attributes Name
type(atl_solver_param_type), intent(inout) :: params
type(atl_Equations_type), intent(inout) :: equation
type(treelmesh_type), intent(inout) :: tree
integer, intent(inout), allocatable :: nCellsNoBnd(:)
type(atl_element_container_type), intent(inout) :: element_container
Calls
Called by
Call graph
atl_finalize_program calls close_config, conf, free_treelmesh, atl_deallocate_sourcedata, atl_dumptimers, atl_dumpweights, atl_writerestartifnecessary, tem_horizontalSpacer, tem_precice_finalize, tem_restart_finalize, tem_simControl_dump_now, tem_status_dump, tem_status_run_terminate, tem_tracking_finalize
atl_dumptimers calls my_status_int, newunit, tem_getMaxTimerVal, tem_getTimerName, tem_getTimerVal
atl_dumpweights calls atl_getweights, tem_create_EndianSuffix, tem_dump_weights
atl_writerestartifnecessary calls tem_simControl_dump_now, bits, atl_writerestart, tem_getOptValOrDef, tem_timeControl_check
ateles calls atl_finalize_program