atl_eqn_acoustic_init – Ateles
atl_eqn_acoustic_init Subroutine
23 statements
Source File
public subroutine atl_eqn_acoustic_init(conf, thandle, equation, nDimensions, initSource, varSys_data)
Initialization of the Acoustic equation.
This routine sets up the necessary infrastructure for the Acoustic equations. It reads the configuration from the given script in conf under the table provided in thandle and sets function pointers and variables accordingly.
Arguments
Type Intent Optional Attributes Name
type(flu_State), intent(in) :: conf
Handle to the Lua configuration
integer, intent(in) :: thandle
Handle to the equation table in the Lua script given in conf.
type(atl_Equations_type), intent(inout) :: equation
Equation system to set with this routine.
integer, intent(in) :: nDimensions
Number of spatial dimensions, the Euler equations should live on.
Has to be 1, 2 or 3.
type(atl_init_source_type), intent(inout) :: initSource
Type to be filled with the possible source variables for the equation system. These source variables are later on used to extract the corresponding information from the configuration file.
type(atl_varSys_solverData_type), intent(inout) :: varSys_data
the pointer to the data required for the varsys
Calls
Called by
Call graph
atl_eqn_acoustic_init calls atl_init_acoustic_2d_sourceterms, atl_init_acoustic_2d_vars, atl_init_acoustic_sourceterms, atl_init_acoustic_vars, atl_load_acoustic
atl_init_acoustic_2d_sourceterms calls append, init
atl_init_acoustic_2d_vars calls atl_append_acoustic_2d_vars, tem_varSys_init
atl_init_acoustic_sourceterms calls append, init
atl_init_acoustic_vars calls atl_append_acoustic_vars, tem_varSys_init
atl_load_acoustic calls aot_get_val, aot_table_close, aot_table_open, tem_horizontalSpacer
atl_append_acoustic_2d_vars calls atl_get_new_varsys_data_ptr, tem_varSys_append_stateVar
atl_append_acoustic_vars calls atl_get_new_varsys_data_ptr, tem_varSys_append_stateVar
atl_init_equation calls atl_eqn_acoustic_init
atl_initialize calls atl_init_equation
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program