atl_eqn_advection_1d_load_bc – Ateles
atl_eqn_advection_1d_load_bc Subroutine
63 statements
Source File
public subroutine atl_eqn_advection_1d_load_bc(equation, bc_state, bc_state_gradient, bc_varDict, bc_varDict_gradient, bc_normal_vec, bc_normal_vec_gradient, bc_trafo, bc_trafo_gradient, bc_label, bc_kind, thandle, conf)
Reading boundary conditions for the advection equations in 1D.
This routine has to conform to the interface definition atl_equation_module#eqn_load_bc.
VK allocate(bc_normal_vec_gradient(2)) VK allocate(bc_trafo_gradient(2))
Arguments
Type Intent Optional Attributes Name
class(atl_Equations_type), intent(inout) :: equation
type(tem_bc_state_type), intent(out), allocatable :: bc_state(:)
type(tem_bc_state_type), intent(out), allocatable :: bc_state_gradient(:)
type(grw_stringkeyvaluepairarray_type), intent(out) :: bc_varDict
Dictionary of boundary variables in bc_state
type(grw_stringkeyvaluepairarray_type), intent(out) :: bc_varDict_gradient
Dictionary of boundary variables in bc_state_gradient
logical, intent(out) :: bc_normal_vec
logical, intent(out) :: bc_normal_vec_gradient
type(atl_eqn_var_trafo_type), intent(out) :: bc_trafo
type(atl_eqn_var_trafo_type), intent(out) :: bc_trafo_gradient
character(len=*), intent(in) :: bc_label
character(len=*), intent(in) :: bc_kind
integer, intent(in) :: thandle
type(flu_State) :: conf
Calls
Call graph
atl_eqn_advection_1d_load_bc calls append, init, atl_load_bc_state, tem_abort, truncate
atl_load_bc_state calls tem_load_bc_state