atl_modg_2d_bnd – Ateles
atl_modg_2d_bnd Subroutine
24 statements
Source File
public subroutine atl_modg_2d_bnd(bc, faceOp, poly_proj, nDerivatives, equation, normalRot, isNodalScheme, time, currentFace, currentLevel, nquadpoints, ndofs, oversamp_dofs, modalFace, faceMaterial)
Subroutine to create the modal representation for a ceratin boundary face.
Arguments
Type Intent Optional Attributes Name
type(atl_boundary_type), intent(in) :: bc
The boundary condition to generate the modal representation for.
real(kind=rk), intent(inout) :: faceOp(:,:)
The modal representation on the face of the neighboring element.
type(ply_poly_project_type), intent(inout) :: poly_proj
The parameters for projection method.
integer, intent(in) :: nDerivatives
The number of derivative boundaries to be set
type(atl_Equations_type), intent(in) :: equation
The equation system you use.
type(coordRotation_type), intent(in) :: normalRot
Rotation indices to rotate global coordinate system into face normal coordinate system.
logical, intent(in) :: isNodalScheme
Does the solver require isNodalScheme information anyway?
type(tem_time_type), intent(in) :: time
The absolute time point.
integer, intent(in) :: currentFace
Current face to compute, needed to get correct position in index array
integer, intent(in) :: currentLevel
the level to compute on
integer, intent(in) :: nquadpoints
integers for allocation of temp arrays, depend on number of quadrature points and for modal values number of dofs
integer, intent(in) :: ndofs
integers for allocation of temp arrays, depend on number of quadrature points and for modal values number of dofs
integer, intent(in) :: oversamp_dofs
integers for allocation of temp arrays, depend on number of quadrature points and for modal values number of dofs
real(kind=rk), intent(inout) :: modalFace(:,:)
The modal representation on the boundary face.
real(kind=rk), intent(in), optional :: faceMaterial(:,:)
The material of the boundary face. First dimension is the number of points on the face. Second dimension is the number of material parameters.
Calls
Called by
Call graph
atl_modg_2d_bnd calls modg_2d_modal_bnd, modg_2d_nodal_bnd, tem_abort
modg_2d_modal_bnd calls tem_abort, ply_poly_project_n2m, modg_2d_bnd_extrapolate, modg_2d_bnd_mirrorpoint, val
modg_2d_nodal_bnd calls tem_abort, ply_poly_project_m2n, ply_poly_project_n2m, modg_2d_bnd_extrapolate, modg_2d_bnd_mirrorpoint, ply_convert2oversample, ply_convertfromoversample, val
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
modg_2d_bnd_mirrorpoint calls val, get_valofindex, tem_startTimer, tem_stopTimer
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
atl_modg_2d_set_bnd calls atl_modg_2d_bnd
atl_set_covolume_bnd calls atl_modg_2d_bnd
atl_interpolate_elemstate calls atl_set_covolume_bnd, atl_interpolate_elemstate
preprocess_rhs_cubes calls atl_modg_2d_set_bnd
atl_preprocess_rhs calls preprocess_rhs_cubes
atl_covolume_tocovolume calls atl_interpolate_elemstate
atl_covolume_tocovolume_1d calls atl_interpolate_elemstate
atl_covolume_tocovolume_2d calls atl_interpolate_elemstate
atl_covolume calls atl_covolume_tocovolume
atl_covolume_1d calls atl_covolume_tocovolume_1d
atl_covolume_2d calls atl_covolume_tocovolume_2d
global_corrector_substep calls atl_preprocess_rhs
imexrk_substep calls atl_preprocess_rhs
mesh_timestep_euler calls atl_preprocess_rhs
rk2_substep calls atl_preprocess_rhs
rk4_substep calls atl_preprocess_rhs
rktaylor_substep calls atl_preprocess_rhs