atl_preprocess_modg_2d_kernel – Ateles
atl_preprocess_modg_2d_kernel Subroutine
15 statements
Source File
public subroutine atl_preprocess_modg_2d_kernel(currentLevel, minLevel, maxLevel, equation, statedata, mesh_list, boundary_list, scheme_list, poly_proj_material, material_list, commPattern, proc)
Subroutine to execute the preprocessing for the MODG kernels. Currently this includes: Convert external source terms to modal representation.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: currentLevel
integer, intent(in) :: minLevel
integer, intent(in) :: maxLevel
type(atl_Equations_type), intent(inout) :: equation
type(atl_statedata_type), intent(inout) :: statedata
type(atl_cube_elem_type), intent(inout) :: mesh_list(minlevel:maxlevel)
type(atl_level_boundary_type), intent(in) :: boundary_list(minlevel:maxLevel)
type(atl_scheme_type), intent(inout) :: scheme_list(minlevel:maxlevel)
type(ply_poly_project_type), intent(inout) :: poly_proj_material
type(atl_material_type), intent(inout) :: material_list(minlevel:maxlevel)
type(tem_commPattern_type) :: commPattern
mpi communication pattern type
type(tem_comm_env_type) :: proc
mpi communication environment with mpi communicator
Calls
Called by
Call graph
atl_preprocess_modg_2d_kernel calls atl_update_materialparams
atl_update_materialparams calls atl_create_materialboundarylist, atl_evalelemmaterial, atl_evalfacematerial
atl_create_materialboundarylist calls append, init, pnttid, tem_abort, tem_startTimer, tem_stopTimer, val
atl_evalelemmaterial calls neigh, nelems, nghelems, pnttid, atl_reftophyscoord, tem_abort, tem_spacetime_for, tem_startTimer, tem_stopTimer
atl_evalfacematerial calls facepos, leftpos, nelems, pnttid, atl_reftophyscoord, ply_get_quadpoints_faces, ply_get_quadpoints_faces_1d, ply_get_quadpoints_faces_2d, rightpos, tem_abort, tem_spacetime_for, tem_startTimer, tem_stopTimer
preprocess_rhs_cubes calls atl_preprocess_modg_2d_kernel
atl_preprocess_rhs calls preprocess_rhs_cubes
global_corrector_substep calls atl_preprocess_rhs
imexrk_substep calls atl_preprocess_rhs, imexrk_substep
mesh_timestep_euler calls atl_preprocess_rhs, mesh_timestep_euler
rk2_substep calls atl_preprocess_rhs, rk2_substep
rk4_substep calls atl_preprocess_rhs, rk4_substep
rktaylor_substep calls atl_preprocess_rhs, rktaylor_substep
mesh_timestep_imexrk calls imexrk_substep
mesh_timestep_predcor_cerk4 calls global_corrector_substep
mesh_timestep_rk4 calls rk4_substep
mesh_timestep_rktaylor calls rktaylor_substep
mesh_timestep_ssprk2 calls rk2_substep