atl_check_val – Ateles
atl_check_val Subroutine
122 statements
Source File
public subroutine atl_check_val(minlevel, maxlevel, statedata_list, mesh_list, stat, equation, scheme_list, poly_proj_pos, poly_proj_list, check, iteration, time)
Routine to check if the physical values of a state are physically meaningful or not.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: minlevel
integer, intent(in) :: maxlevel
type(atl_statedata_type), intent(in) :: statedata_list(minlevel:maxlevel)
type(atl_cube_elem_type), intent(in) :: mesh_list(minlevel:maxlevel)
type(tem_status_type), intent(inout) :: stat
The current status bits from the treelm general configuration
type(atl_Equations_type), intent(in) :: equation
type(atl_scheme_type), intent(in) :: scheme_list(minlevel:maxlevel)
integer, intent(in) :: poly_proj_pos(minlevel:maxlevel)
type(ply_poly_project_type), intent(inout) :: poly_proj_list(:)
type(atl_physCheck_type), intent(in) :: check
integer, intent(in) :: iteration
type(atl_global_timestep_type), intent(inout) :: time
Calls
Called by
Call graph
atl_check_val calls nelems, atl_cflcheck_euler, atl_cflcheck_navier, atl_physcheck_acoustic, atl_physcheck_acoustic_2d, atl_physcheck_euler, atl_physcheck_euler1d, atl_physcheck_euler2d, atl_physcheck_lineareuler, atl_physcheck_lineareuler_2d, atl_physcheck_maxwell, atl_physcheck_rans, atl_physcheck_rans_2d, tem_abort
atl_physcheck_acoustic calls tem_abort, ply_poly_project_m2n, ply_convert2oversample, tem_isNaN
atl_physcheck_acoustic_2d calls tem_abort, ply_poly_project_m2n, ply_convert2oversample, tem_isNaN
atl_physcheck_euler calls tem_abort, ply_poly_project_m2n, ply_convert2oversample, tem_isNaN
atl_physcheck_euler1d calls tem_abort, ply_poly_project_m2n, ply_convert2oversample, tem_isNaN
atl_physcheck_euler2d calls tem_abort, ply_poly_project_m2n, ply_convert2oversample, tem_isNaN
atl_physcheck_lineareuler calls tem_abort, ply_poly_project_m2n, ply_convert2oversample, tem_isNaN
atl_physcheck_lineareuler_2d calls tem_abort, ply_poly_project_m2n, ply_convert2oversample, tem_isNaN
atl_physcheck_maxwell calls tem_isNaN
atl_physcheck_rans calls tem_abort, ply_poly_project_m2n, ply_convert2oversample, tem_isNaN
atl_physcheck_rans_2d calls tem_abort, ply_poly_project_m2n, ply_convert2oversample, tem_isNaN
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_poly_project_m2n_multivar calls ply_legtopnt_2d, ply_legtopnt_3d, ply_fxt_m2n_1d, ply_fxt_m2n_2d, ply_fxt_m2n_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
atl_solve_program calls atl_check_val
ateles calls atl_solve_program