atl_init_euler_2d_sourceTerms – Ateles
atl_init_euler_2d_sourceTerms Subroutine
15 statements
Source File
public subroutine atl_init_euler_2d_sourceTerms(possVars, eval_source)
This routine initializes possible source variables and returns the filled up list of the poss_srcVars
Arguments
Type Intent Optional Attributes Name
type(tem_possible_variable_type), intent(inout) :: possVars
type(atl_eqn_sourceMap_type), intent(out), allocatable :: eval_source(:)
Calls
Called by
Call graph
atl_init_euler_2d_sourceterms calls append, init, truncate
atl_eqn_euler_init calls atl_init_euler_2d_sourceterms
atl_eqn_nvrstk_init calls atl_init_euler_2d_sourceterms
atl_init_equation calls atl_eqn_euler_init, atl_eqn_nvrstk_init
atl_initialize calls atl_init_equation
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize