atl_set_covolume_bnd – Ateles
atl_set_covolume_bnd Subroutine
96 statements
Source File
public subroutine atl_set_covolume_bnd(bc, boundary, state, scheme, equation, tree, time, mesh, poly_proj, nodalBnd, iDir, iLevel)
Routine to set boundary values for the covolume filter.
!!OMP PARALLEL & !!OMP PRIVATE(iBC, iAlign, iFace) & !!OMP DEFAULT(shared)
MODG
MODG_2D
MODG_1D
!!OMP END PARALLEL
Arguments
Type Intent Optional Attributes Name
type(atl_boundary_type), intent(in) :: bc(:)
The global description of the boundaries.
type(atl_level_boundary_type), intent(in) :: boundary
The levelwise collection of boundary elements and boundary faces.
type(atl_statedata_type), intent(inout) :: state
The face data on the current level
type(atl_scheme_type), intent(inout) :: scheme
The parameters of th the modg scheme.
type(atl_Equations_type), intent(in) :: equation
The underlying equation system
type(treelmesh_type), intent(in) :: tree
treelm mesh
type(tem_time_type), intent(in) :: time
The absolute time point.
type(atl_cube_elem_type), intent(in) :: mesh
The description of the mesh on the current level.
type(ply_poly_project_type), intent(inout) :: poly_proj
Data for the projection methods
logical, intent(in) :: nodalBnd
Set boundaries in nodal fashion by default? If set to false, the boundaries may still be set in nodal way whenever necessary (e.g. boundaries which have space-time dependence, etc.)
integer, intent(in) :: iDir
The spatial direction to set
integer, intent(in) :: iLevel
current Level working on
Calls
Called by
Call graph
atl_set_covolume_bnd calls atl_extend_covol_face, atl_extend_covol_face_1d, atl_extend_covol_face_2d, atl_modg_1d_bnd, atl_modg_2d_bnd, atl_modg_bnd, atl_voltoface, atl_voltoface_1d, atl_voltoface_2d, tem_abort, val
atl_modg_1d_bnd calls modg_1d_modal_bnd, modg_1d_nodal_bnd
atl_modg_2d_bnd calls tem_abort, modg_2d_modal_bnd, modg_2d_nodal_bnd
atl_modg_bnd calls tem_abort, modg_modal_bnd, modg_nodal_bnd
atl_voltoface calls ply_facevalleftbndans
atl_voltoface_1d calls ply_facevalleftbndans
atl_voltoface_2d calls ply_facevalleftbndans
modg_1d_modal_bnd calls tem_abort, val, modg_1d_bnd_extrapolate, modg_1d_bnd_mirrormodalconst, modg_1d_bnd_mirrorpoint
modg_1d_nodal_bnd calls tem_abort, val, modg_1d_bnd_extrapolate, modg_1d_bnd_mirrorpoint
modg_2d_modal_bnd calls tem_abort, val, ply_poly_project_n2m, modg_2d_bnd_extrapolate, modg_2d_bnd_mirrorpoint
modg_2d_nodal_bnd calls tem_abort, val, ply_poly_project_m2n, ply_poly_project_n2m, modg_2d_bnd_extrapolate, modg_2d_bnd_mirrorpoint, ply_convert2oversample, ply_convertfromoversample
modg_modal_bnd calls tem_abort, val, ply_poly_project_n2m, modg_bnd_extrapolate, modg_bnd_mirrorpoint, ply_convertfromoversample
modg_nodal_bnd calls tem_abort, val, ply_poly_project_m2n, ply_poly_project_n2m, modg_bnd_extrapolate, modg_bnd_mirrorpoint, ply_convert2oversample, ply_convertfromoversample
atl_interpolate_elemstate calls atl_set_covolume_bnd, atl_interpolate_elemstate
atl_covolume_tocovolume calls atl_interpolate_elemstate
atl_covolume_tocovolume_1d calls atl_interpolate_elemstate
atl_covolume_tocovolume_2d calls atl_interpolate_elemstate
atl_covolume calls atl_covolume_tocovolume
atl_covolume_1d calls atl_covolume_tocovolume_1d
atl_covolume_2d calls atl_covolume_tocovolume_2d
atl_stabilize calls atl_covolume, atl_covolume_1d, atl_covolume_2d