atl_eqn_maxwellDivCor_load_bc – Ateles
atl_eqn_maxwellDivCor_load_bc Subroutine
102 statements
Source File
public subroutine atl_eqn_maxwellDivCor_load_bc(equation, bc_state, bc_state_gradient, bc_varDict, bc_varDict_gradient, bc_normal_vec, bc_normal_vec_gradient, bc_trafo, bc_trafo_gradient, bc_label, bc_kind, thandle, conf)
Subroutine to load boundary conditions for Maxwell equations with divergence correction from a Lua configuration file. For the correction in E-field dirichlet bc and for correction in B-field neumann bc are defined.
VK allocate(bc_normal_vec_gradient(2)) VK allocate(bc_trafo_gradient(2))
Arguments
Type Intent Optional Attributes Name
class(atl_Equations_type), intent(inout) :: equation
type(tem_bc_state_type), intent(out), allocatable :: bc_state(:)
type(tem_bc_state_type), intent(out), allocatable :: bc_state_gradient(:)
type(grw_stringkeyvaluepairarray_type), intent(out) :: bc_varDict
Dictionary of boundary variables in bc_state
type(grw_stringkeyvaluepairarray_type), intent(out) :: bc_varDict_gradient
Dictionary of boundary variables in bc_state_gradient
logical, intent(out) :: bc_normal_vec
logical, intent(out) :: bc_normal_vec_gradient
type(atl_eqn_var_trafo_type), intent(out) :: bc_trafo
type(atl_eqn_var_trafo_type), intent(out) :: bc_trafo_gradient
character(len=*), intent(in) :: bc_label
Unused variable, Needed for interface compatibility in module atl_equation_init_module.f90.
character(len=*), intent(in) :: bc_kind
integer, intent(in) :: thandle
Unused variable, Needed for interface compatibility in module atl_equation_init_module.f90.
type(flu_State) :: conf
Unused variable, Needed for interface compatibility in module atl_equation_init_module.f90.
Calls
Call graph
atl_eqn_maxwelldivcor_load_bc calls append, init, atl_load_bc_state, tem_abort, truncate
atl_load_bc_state calls tem_load_bc_state