atl_equation_evaluate_source_modal – Ateles
atl_equation_evaluate_source_modal Subroutine
51 statements
Source File
public subroutine atl_equation_evaluate_source_modal(fun, varSys, currentLevel, nDim, time, eval_rhs, state, poly_proj, polyProjBody, sourceData, consts)
Arguments
Type Intent Optional Attributes Name
class(atl_source_op_type), intent(in) :: fun
Description of method to update source
type(tem_varSys_type), intent(in) :: varSys
variable system
integer, intent(in) :: currentLevel
The current Level information
integer, intent(in) :: nDim
The dimension information
type(tem_time_type), intent(in) :: time
Point in time at which to evaluate the variable.
procedure(atl_compute_source_interface), pointer :: eval_rhs
The pointer to the equation specific RHS evaluation
real(kind=rk), intent(in) :: state(:,:,:)
type(ply_poly_project_type), intent(inout) :: poly_proj
Parameters for projection
type(ply_prj_body_type) :: polyProjBody
the data needed for the projection method
real(kind=rk), intent(inout) :: sourceData(:,:,:)
real(kind=rk), intent(in), optional :: consts(:)
Calls
Called by
Call graph
atl_equation_evaluate_source_modal calls get_valofindex, ply_poly_project_n2m, ply_convertfromoversample, val
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d, ply_pnttoleg_3d, ply_fxt_n2m_1d, ply_fxt_n2m_2d, ply_fxt_n2m_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_pnttoleg_2d calls ply_pnttoleg_2d_multvar, ply_pnttoleg_2d_singvar
ply_pnttoleg_3d calls ply_pnttoleg_3d_multvar, ply_pnttoleg_3d_singvar
ply_fxt_n2m_1d calls fxtf_flptld_n2m
ply_fxt_n2m_2d calls fxtf_flptld_n2m
ply_fxt_n2m_3d calls fxtf_flptld_n2m
ply_l2p_trafo_1d calls ply_l2_projection
ply_l2p_trafo_2d calls ply_l2_projection
ply_l2p_trafo_3d calls ply_l2_projection
atl_eval_source_currentdensity calls atl_equation_evaluate_source_modal
atl_eval_source_currentdensity_2d calls atl_equation_evaluate_source_modal
atl_eval_source_force calls atl_equation_evaluate_source_modal
atl_eval_source_force_2d calls atl_equation_evaluate_source_modal
atl_eval_source_massinjection calls atl_equation_evaluate_source_modal
atl_eval_source_massinjection_2d calls atl_equation_evaluate_source_modal
eval_source_arbitrary calls atl_equation_evaluate_source_modal
eval_source_arbitrary_2d calls atl_equation_evaluate_source_modal
eval_source_charge calls atl_equation_evaluate_source_modal