atl_modg_2d_coarseToFineFace – Ateles
atl_modg_2d_coarseToFineFace Subroutine
73 statements
Source File
public subroutine atl_modg_2d_coarseToFineFace(minLevel, maxLevel, currentLevel, mesh, facedata, scheme, nScalars)
difference between coarser and finer faces has to be 1).
Interpolates functions defined on faces of the current level to faces of the next finer level. \n \n faces on fine face on current \n level level \n ------------------------ ------------------------ \n | | | | | \n | 3 | 4 | | | \n | | | | | \n ------------------------ <<---------- | 5 | \n | | | | | \n | 1 | 2 | | | \n | | | | | \n ------------------------ ------------------------ \n \n This is accomplished with lower complexity (with respect to the polynomial degree) by a dimension by dimension approach: \n \n faces on fine face on current \n level level \n ------------------------ ------------------------ \n | | | | | \n | 3 | 4 | | | \n | | | | | \n ------------------------ <<---------- | 5 | \n | | | | | \n | 1 | 2 | | | \n | | | | | \n ------------------------ ------------------------ \n \ / \n \ / \n \ / \n \ / \n ------------------------ \n | | \n | b | \n | | \n ------------------------ \n | | \n | a | \n | | \n ------------------------ \n
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: minLevel
The minumum level of the mesh.
integer, intent(in) :: maxLevel
The maximum level of the mesh.
integer, intent(in) :: currentLevel
The current level (i.e. the coarse level).
type(atl_cube_elem_type), intent(in) :: mesh(minLevel:maxLevel)
The mesh representation.
type(atl_facedata_type), intent(inout) :: facedata(minLevel:maxLevel)
The face representations (finer faces are interpolated from coarser ones).
type(atl_scheme_type), intent(in) :: scheme(minLevel:maxLevel)
The schemes on the different levels.
integer, intent(in) :: nScalars
The number of scalar variables in your equation system.
Calls
Called by
Call graph
atl_modg_2d_coarsetofineface calls childposop, elemposop, fromfinerface, nelems, pnttid, modg_2d_semirefineface, tem_startTimer, tem_stopTimer
preprocess_rhs_cubes calls atl_modg_2d_coarsetofineface
atl_preprocess_rhs calls preprocess_rhs_cubes
global_corrector_substep calls atl_preprocess_rhs
imexrk_substep calls atl_preprocess_rhs, imexrk_substep
mesh_timestep_euler calls atl_preprocess_rhs, mesh_timestep_euler
rk2_substep calls atl_preprocess_rhs, rk2_substep
rk4_substep calls atl_preprocess_rhs, rk4_substep
rktaylor_substep calls atl_preprocess_rhs, rktaylor_substep
mesh_timestep_imexrk calls imexrk_substep
mesh_timestep_predcor_cerk4 calls global_corrector_substep
mesh_timestep_rk4 calls rk4_substep
mesh_timestep_rktaylor calls rktaylor_substep
mesh_timestep_ssprk2 calls rk2_substep