atl_init_maxwell_material – Ateles
atl_init_maxwell_material Subroutine
7 statements
Source File
public subroutine atl_init_maxwell_material(possVars)
Adds the properties of the expected source terms to the list of possible variables to extract these expected variables later on from the configuration file.
Arguments
Type Intent Optional Attributes Name
type(tem_possible_variable_type), intent(out) :: possVars
Calls
Called by
Call graph
atl_init_maxwell_material calls append, init
atl_eqn_maxwell_init calls atl_init_maxwell_material
atl_init_equation calls atl_eqn_maxwell_init
atl_initialize calls atl_init_equation
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize