atl_init_scheme – Ateles
atl_init_scheme Subroutine
59 statements
Source File
public subroutine atl_init_scheme(me, conf, minLevel, maxLevel)
subroutine to intialize a scheme as specified by a given lua script file.
Arguments
Type Intent Optional Attributes Name
type(atl_scheme_type), intent(out) :: me(minlevel:maxlevel)
the scheme you want to initialize.
type(flu_State), intent(in) :: conf
flu binding to lua configuration file.
integer, intent(in) :: minLevel
The global minimum level of the mesh
integer, intent(in) :: maxLevel
The global maximum level of the mesh
Calls
Called by
Call graph
atl_init_scheme calls aot_get_val, aot_table_close, aot_table_open, atl_ini_stabilization, atl_modg_1d_scheme_init, atl_modg_2d_scheme_init, atl_modg_scheme_init, compute_scalprod_dualleg, init_local_time_integration, tem_abort, upper_to_lower
atl_ini_stabilization calls aot_get_val, aot_table_close, aot_table_open, tem_abort, aot_table_length, atl_ini_cons_positivity_preserv, atl_ini_covolume, atl_ini_positivity_preserv, atl_ini_spectral_visc
atl_modg_1d_scheme_init calls aot_get_val, tem_abort, upper_to_lower, atl_modg_1d_scheme_load_polydegree
atl_modg_2d_scheme_init calls aot_get_val, tem_abort, upper_to_lower, atl_modg_2d_scheme_load_polydegree
atl_modg_scheme_init calls aot_get_val, tem_abort, upper_to_lower, atl_modg_scheme_load_polydegree
compute_scalprod_dualleg calls ply_scalproddualleg, ply_scalprodduallegdiff
atl_ini_cons_positivity_preserv calls aot_get_val, tem_abort, tem_horizontalSpacer
atl_ini_covolume calls aot_get_val, tem_abort, tem_horizontalSpacer
atl_ini_positivity_preserv calls aot_get_val, tem_abort, tem_horizontalSpacer
atl_ini_spectral_visc calls aot_get_val, tem_abort, tem_horizontalSpacer
atl_modg_1d_scheme_load_polydegree calls aot_get_val, aot_table_close, aot_table_open, tem_abort, upper_to_lower, aot_table_length
atl_modg_2d_scheme_load_polydegree calls aot_get_val, aot_table_close, aot_table_open, tem_abort, upper_to_lower, aot_table_length
atl_modg_scheme_load_polydegree calls aot_get_val, aot_table_close, aot_table_open, tem_abort, upper_to_lower, aot_table_length
atl_init_elem_container calls atl_init_scheme
atl_initialize calls atl_init_elem_container
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program