atl_load_initial_condition – Ateles
atl_load_initial_condition Subroutine
196 statements
Source File
public subroutine atl_load_initial_condition(cube_container, equation, prj_pos, poly_proj_list, conf, LuaFile, tree)
subroutine to load the initial conditions from a lua configuration file.
@note Todo Do not set input here, but handle generic case (use variable system)
\remark ATTENTION: we set the initial conditions only in fluid cells! so we have no initial condition for ghost and halo cells here!
Arguments
Type Intent Optional Attributes Name
type(atl_cube_container_type), intent(inout) :: cube_container
Container which holds all cubic elements for the mesh.
This parameter has to be initialzed already, since we need information about the physical coordinates of the cells.
type(atl_Equations_type), intent(inout) :: equation
Description of the equations to solve.
integer, intent(in) :: prj_pos(tree%global%minLevel:tree%global%maxLevel)
Levelwise position pointer for the projection method used for IC
type(ply_poly_project_type), intent(inout) :: poly_proj_list(:)
unique list for projection methods
type(flu_State), intent(inout) :: conf
Handle, providing access to the configuration script
character(len=*), intent(in) :: LuaFile
Name of Lua configuration file.
type(treelmesh_type), intent(in) :: tree
Tree representation of your mesh.
Calls
Called by
Call graph
atl_load_initial_condition calls aot_init_path, ply_poly_project_n2m, nelems, atl_reftophyscoord, ply_convertfromoversample, tem_abort, tem_load_ic, tem_spatial_for, val
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d, ply_pnttoleg_3d, ply_fxt_n2m_1d, ply_fxt_n2m_2d, ply_fxt_n2m_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_pnttoleg_2d calls ply_pnttoleg_2d_multvar, ply_pnttoleg_2d_singvar
ply_pnttoleg_3d calls ply_pnttoleg_3d_multvar, ply_pnttoleg_3d_singvar
ply_fxt_n2m_1d calls fxtf_flptld_n2m
ply_fxt_n2m_2d calls fxtf_flptld_n2m
ply_fxt_n2m_3d calls fxtf_flptld_n2m
ply_l2p_trafo_1d calls ply_l2_projection
ply_l2p_trafo_2d calls ply_l2_projection
ply_l2p_trafo_3d calls ply_l2_projection
atl_initialize calls atl_load_initial_condition
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program