atl_init_faceStateBuffer – Ateles
atl_init_faceStateBuffer Subroutine
146 statements
Source File
public subroutine atl_init_faceStateBuffer(nFaceDofs, faces, nValsState, nValsFlux, boundary, commPattern, initRealBuf)
... cell states
Todo
HK: can we not cancel out 0-sized messages? (is this part ever executed?)
Todo
HK: can we not cancel out 0-sized messages? (is this part ever executed?)
Todo
HK: can we not cancel out 0-sized messages? (is this part ever executed?)
Todo
HK: can we not cancel out 0-sized messages? (is this part ever executed?)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nFaceDofs
The number of degrees of freedoms per scalar variable per face.
type(tem_face_type), intent(inout) :: faces
list of cubic meshes you want to build the buffers for.
integer, intent(in) :: nValsState
the number of scalar values on the face for the state
integer, intent(in) :: nValsFlux
the number of scalar values on the face for the flux
type(atl_level_boundary_type), intent(in) :: boundary
The boundary description for the faces on the current level.
type(tem_commPattern_type), intent(in) :: commPattern
mpi communication pattern type
logical, optional :: initRealBuf
Init real buffer (default), if not the integer buffer is initialized.
Calls
Called by
Call graph
atl_init_facestatebuffer calls buf_int, buf_real, elempos, recvbuffer_flux, recvbuffer_state, sendbuffer_flux, sendbuffer_state, val
atl_init_materialparams calls atl_init_facestatebuffer
atl_init_parallel_module calls atl_init_facestatebuffer
atl_init_modg_1d_kernel calls atl_init_parallel_module
atl_init_modg_2d_kernel calls atl_init_parallel_module
atl_init_modg_kernel calls atl_init_parallel_module
atl_initialize calls atl_init_materialparams
atl_initialize_program calls atl_initialize
init_kernel calls atl_init_modg_1d_kernel, atl_init_modg_2d_kernel, atl_init_modg_kernel
atl_harvesting calls atl_initialize
atl_init_elem_container calls init_kernel
ateles calls atl_initialize_program