atl_load_bc – Ateles
atl_load_bc Subroutine
47 statements
Source File
public subroutine atl_load_bc(bc, bc_header, bc_prop, equation, conf, parent)
Get the boundary configuration.
Arguments
Type Intent Optional Attributes Name
type(atl_boundary_type), intent(out), allocatable :: bc(:)
Array of boundary conditions, will be allocated in this routine and has a length according to the number of boundary conditions in the mesh.
type(tem_bc_header_type), intent(out) :: bc_header
The boundary condition header data as given in the mesh.
type(tem_BC_prop_type), intent(in) :: bc_prop
The boundary property object, describing the given boundaries in the mesh, this has to be provided to allow the matching of boundary settings in the configuration to the boundary set in the mesh.
type(atl_Equations_type), intent(inout) :: equation
Description of the equation system, to read the boundary conditions in dependency on the equation system to solve.
type(flu_State) :: conf
Lua script to obtain the configuration data from.
integer, intent(in), optional :: parent
A parent Lua table, in which the boundary conditions are to be found.
Calls
Called by
Call graph
atl_load_bc calls aot_get_val, aot_table_close, aot_table_open, tem_abort, tem_load_bc_header
atl_init_bndlist calls atl_load_bc
atl_init_cube_container calls atl_init_bndlist
atl_init_elem_container calls atl_init_cube_container
atl_initialize calls atl_init_elem_container