calc_barycoord – Ateles
calc_barycoord Subroutine
10 statements
Source File
private subroutine calc_barycoord(treeids, nElems, bary_coord, tree)
Calculate barycentric coordinates of the tree ids given in treeids.
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(in) :: treeids(:)
Tree ids you want to build the barycentric coordinates for.
integer, intent(in) :: nElems
the number of tree ids in in treeids.
real(kind=rk), intent(out) :: bary_coord(:,:)
Array of barycenteric coordinates for the cells given in treeidsubset. This array has to be allocated before you can use it as an input argument. The dimensions are: First dimension is subsetsize and the second dimension is the space dimension, i.e. 3.
type(treelmesh_type), intent(in) :: tree
Tree representation of your mesh.
Calls
Called by
Call graph
calc_barycoord calls tem_BaryOfId
atl_init_cube_elem calls calc_barycoord
atl_init_cube_container calls atl_init_cube_elem
atl_init_elem_container calls atl_init_cube_container
atl_initialize calls atl_init_elem_container