calc_matrix_QCriterion – Ateles
calc_matrix_QCriterion Subroutine
30 statements
Source File
private subroutine calc_matrix_QCriterion(gradV, Q)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: gradV(:)
real(kind=rk), intent(inout) :: Q(:,:)
Called by
Call graph
atl_derivelambda2 calls calc_matrix_qcriterion
atl_deriveqcriterion calls calc_matrix_qcriterion
atl_lambda2_getpoint calls calc_matrix_qcriterion
atl_qcriterion_getpoint calls calc_matrix_qcriterion