calculate_cfl_timestep – Ateles
calculate_cfl_timestep Subroutine
64 statements
Source File
private subroutine calculate_cfl_timestep(length, cfl, cfl_visc, equation, dt, timestep, scheme, material, localtime)
Calculate the timestep for a whole part of a cubic mesh by a CFL condition.
This routine takes the primitive variables of the equation system and calculates the next timestep. The calculation is based on the cfl condition and the next restart timepoints.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: length
The length of the cubes you are calculating the cfl condition for.
real(kind=rk), intent(in) :: cfl
The CFL factor to apply (for the convective part of the equation).
real(kind=rk), intent(in) :: cfl_visc
The CFL factor to apply (for the viscous part of the equation).
type(atl_Equations_type), intent(inout) :: equation
The equation system to be used in the simulation.
real(kind=rk), intent(out) :: dt
Resulting timestep.
type(atl_timestep_type), intent(in) :: timestep
Timestep information
type(atl_scheme_type), intent(in) :: scheme
Info about the scheme.
type(atl_material_type), intent(in) :: material
Material information for all elements on the current level
type(tem_time_type), intent(in) :: localtime
Local time, required for update of temporal background in linear Euler
Calls
Called by
Call graph
calculate_cfl_timestep calls atl_eqn_update_background, calc_timestep_acoustic_2d_cube, calc_timestep_acoustic_cube, calc_timestep_adv_cube, calc_timestep_ed_cube, calc_timestep_flow_cube, calc_timestep_flow_cube_1d, calc_timestep_flow_cube_2d, calc_timestep_flow_cube_mod, calc_timestep_heat_cube_1d, calc_timestep_lineareuler_2d_cube, calc_timestep_lineareuler_cube, calc_timestep_nerplanck_cube, calc_timestep_viscflow_cube, calc_timestep_viscflow_cube_2d, tem_abort
atl_eqn_update_background calls tem_temporal_for
atl_get_timestep calls calculate_cfl_timestep
atl_initialize_program calls atl_get_timestep
atl_solve_program calls atl_get_timestep
ateles calls atl_initialize_program, atl_solve_program