calc_timestep_flow_cube_1d – Ateles
calc_timestep_flow_cube_1d Subroutine
10 statements
Source File
private subroutine calc_timestep_flow_cube_1d(cfl, length, dt, timestep, nPoly)
Calculate time step based on a given CFL condition for a cube in a flow simulation.
This subroutine calculates the timstep according to the CFL condition. Please notice, that this routine can be applied for flow simulations only.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: cfl
CFL number
real(kind=rk), intent(in) :: length
Reference length of all elements
real(kind=rk), intent(out) :: dt
Resulting time step width
type(atl_timestep_type), intent(in) :: timestep
Info about the timestep type
integer, intent(in) :: nPoly
The number of polynomials per spatial direction
Called by
Call graph
calculate_cfl_timestep calls calc_timestep_flow_cube_1d
atl_get_timestep calls calculate_cfl_timestep
atl_initialize_program calls atl_get_timestep
atl_solve_program calls atl_get_timestep
ateles calls atl_initialize_program, atl_solve_program