check_fxt_2d – Ateles
check_fxt_2d Subroutine
63 statements
Source File
subroutine check_fxt_2d(power, res)
todo NA: Check if nodes kind and factor are correctly used for
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: power
real(kind=rk), intent(out) :: res
Calls
Called by
Call graph
check_fxt_2d calls ply_poly_project_m2n, ply_poly_project_n2m, ply_poly_project_fillbody, ply_prj_init_define
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
ply_poly_project_fillbody calls ply_init_fxt, ply_init_l2p, ply_init_legfpt, ply_nodes_create, tem_abort
test_fxtd_n2m2n calls check_fxt_2d