check_fwd_bwd – Ateles
check_fwd_bwd Subroutine
25 statements
Source File
subroutine check_fwd_bwd(power, res)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: power
real(kind=rk), intent(out) :: res
Calls
Called by
Call graph
check_fwd_bwd calls ply_fpt_header_define, ply_init_legfpt
ply_fpt_header_define calls tem_abort
ply_init_legfpt calls fftw_plan_many_r2r, fftw_plan_r2r_1d, ply_fpt_init
ply_fpt_init calls ply_l, ply_l_int, ply_m, ply_m_int
ply_l calls ply_lambda
ply_l_int calls ply_l, ply_lambda
ply_m calls ply_lambda
ply_m_int calls ply_lambda
ply_fpt_ifpt_test calls check_fwd_bwd