check_fxt_1d – Ateles
check_fxt_1d Subroutine
27 statements
Source File
subroutine check_fxt_1d(res)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(out) :: res
Calls
Called by
Call graph
check_fxt_1d calls fxtf_flptld_init, fxtf_flptld_m2n, fxtf_flptld_n2m
fxtf_flptld_init calls fxt_flptld_init, fxt_flptld_wsize, fxt_vecld_new
fxtf_flptld_m2n calls fxtf_flptld_evl
fxtf_flptld_n2m calls fxtf_flptld_exp
test_fxtd_n2m2n calls check_fxt_1d