check_fxt_3D – Ateles
check_fxt_3D Subroutine
51 statements
Source File
subroutine check_fxt_3D(power, res)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: power
real(kind=rk), intent(out) :: res
Calls
Called by
Call graph
check_fxt_3d calls ply_poly_project_m2n, ply_poly_project_n2m, ply_convert2oversample, ply_convertfromoversample, ply_poly_project_fillbody, ply_prj_init_define
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
ply_poly_project_fillbody calls ply_init_fxt, ply_init_l2p, ply_init_legfpt, ply_nodes_create, tem_abort
test_fxtd_n2m2n calls check_fxt_3d