compute_physFlux_nonConst_2d – Ateles
compute_physFlux_nonConst_2d Subroutine
24 statements
Source File
private subroutine compute_physFlux_nonConst_2d(nDofs, nScalars, iElem, state_der, state, rot, nElems, elems, material, poly_proj, modalCoeffs, nodalPhysFlux)
Compute the physical flux in x direction.
For other directions a properly defined variable permutation can be used. This routine covers non-constant material parameters.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nDofs
dimensions
integer, intent(in) :: nScalars
dimensions
integer, intent(in) :: iElem
real(kind=rk), intent(inout) :: state_der(:,:)
Array to store the fluxes in.
real(kind=rk), intent(in) :: state(nDofs,nScalars)
State to compute the fluxes from.
integer, intent(in) :: rot(7)
Rotationing to index the variables.
integer, intent(in) :: nElems
Number of elements.
integer, intent(in) :: elems(nElems)
Element positions in the total state vector
real(kind=rk), intent(in) :: material(nElems,nDofs,3)
Material parameters (mu, epsilon) for all elements
type(ply_poly_project_type) :: poly_proj
Data for projection method
real(kind=rk), intent(inout) :: modalCoeffs(poly_proj%body_2D%oversamp_dofs,size(state,2),1)
Working array for modal coefficients of the current element in the loop.
real(kind=rk), intent(inout) :: nodalPhysFlux(poly_proj%body_2D%nquadpoints,size(state,2),2)
Working array for nodal representation of the physical flux along the 3 spatial directions.
Calls
Called by
Call graph
compute_physflux_nonconst_2d calls ply_poly_project_m2n, ply_poly_project_n2m, atl_physfluxmaxwell_2d, ply_convert2oversample, ply_convertfromoversample
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
ply_poly_project_m2n_multivar calls ply_legtopnt_2d, ply_legtopnt_3d, ply_fxt_m2n_1d, ply_fxt_m2n_2d, ply_fxt_m2n_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d, ply_pnttoleg_3d, ply_fxt_n2m_1d, ply_fxt_n2m_2d, ply_fxt_n2m_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
atl_modg_maxwell_2d_physflux_nonconst calls compute_physflux_nonconst_2d