compute_physFluxDivCor_nonConst – Ateles
compute_physFluxDivCor_nonConst Subroutine
21 statements
Source File
private subroutine compute_physFluxDivCor_nonConst(nDofs, nScalars, nquadpoints, state_der, state, rot, material, poly_proj, modalCoeffs, nodalPhysFlux, pointVal, iElem, nElems)
Compute the physical flux in x direction. For other directions a properly defined variable permutation can be used. This routine covers non-constant material parameters.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nDofs
dimensions
integer, intent(in) :: nScalars
dimensions
integer, intent(in) :: nquadpoints
dimensions
real(kind=rk), intent(inout) :: state_der(nDofs,nScalars)
Array to store the fluxes in.
real(kind=rk), intent(in) :: state(nDofs,nScalars)
State to compute the fluxes from.
integer, intent(in) :: rot(8)
Rotationing to index the variables.
real(kind=rk), intent(in) :: material(nElems,nDofs,4)
Material parameters (mu, epsilon) for all elements
type(ply_poly_project_type), intent(inout) :: poly_proj
Data for projection method
real(kind=rk), intent(inout) :: modalCoeffs(:,:)
Working array for modal coefficients of the current element in the loop.
real(kind=rk), intent(inout) :: nodalPhysFlux(:,:)
Working array for nodal representation of the physical flux along the 3 spatial directions.
real(kind=rk), intent(inout) :: pointVal(:,:)
Working array for nodal representation of the polynomial with in each cell.
integer, intent(in) :: iElem
integer, intent(in) :: nElems
Number of elements.
Calls
Called by
Call graph
compute_physfluxdivcor_nonconst calls ply_poly_project_m2n, ply_poly_project_n2m, atl_physfluxmaxwelldivcor, ply_convert2oversample, ply_convertfromoversample
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
ply_poly_project_m2n_multivar calls ply_legtopnt_2d, ply_legtopnt_3d, ply_fxt_m2n_1d, ply_fxt_m2n_2d, ply_fxt_m2n_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d, ply_pnttoleg_3d, ply_fxt_n2m_1d, ply_fxt_n2m_2d, ply_fxt_n2m_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
atl_modg_maxwelldivcor_physflux_nonconst calls compute_physfluxdivcor_nonconst