compute_rhs_cubes_modg – Ateles
compute_rhs_cubes_modg Subroutine
115 statements
Source File
private subroutine compute_rhs_cubes_modg(minLevel, maxLevel, currentLevel, mesh_list, kerneldata_list, statedata_list, facedata_list, source, penalizationdata_list, scheme_list, poly_proj_pos, poly_proj_list, equation, material_list, general, computePenalization)
Uses
atl_project_physflux_module
atl_modg_LoclinEuler_kernel_module
atl_modg_LinearEuler_kernel_module
atl_physFlux_module
atl_cube_elem_module
atl_elemental_time_integration_module
atl_equation_module
atl_source_types_module
atl_facedata_module
atl_modg_heat_kernel_module
treelmesh_module
atl_modg_kernel_module
ply_dynarray_project_module
atl_penalization_module
atl_modg_navierstokes_kernel_module
atl_kerneldata_module
atl_modg_maxwell_kernel_module
atl_modg_euler_kernel_module
ply_poly_project_module
atl_modg_acoustic_kernel_module
atl_modg_filNvrStk_kernel_module
atl_scheme_module
atl_modg_maxwellDivCor_kernel_module
atl_materialPrp_module
atl_modg_multilevel_module
Computes the right hand side for cubical elements and MODG scheme.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: minLevel
The minimum level of the mesh.
integer, intent(in) :: maxLevel
The maximum level of the mesh.
integer, intent(in) :: currentLevel
The level of the mesh you are computing the rhs for.
type(atl_cube_elem_type), intent(inout) :: mesh_list(minLevel:maxLevel)
List of mesh parts. For each level we have one.
type(atl_kerneldata_type), intent(inout) :: kerneldata_list(minLevel:maxLevel)
List of kerneldatas. For each level we have one
type(atl_statedata_type), intent(inout) :: statedata_list(minLevel:maxLevel)
List of states you want to calc the rhs for. For each level we have one.
type(atl_facedata_type), intent(inout) :: facedata_list(minLevel:maxLevel)
List of facedatas. For each level we have one
type(atl_source_type), intent(inout) :: source
Levelwise list of sources
type(atl_penalizationData_type), intent(inout) :: penalizationdata_list(minLevel:maxLevel)
Levelwise list of penalization data
type(atl_scheme_type), intent(inout) :: scheme_list(minLevel:maxLevel)
List of schemes, for each level.
integer, intent(in) :: poly_proj_pos(minLevel:maxLevel)
List of levelwise position of projection method in unique list
type(ply_poly_project_type), intent(inout) :: poly_proj_list(:)
unique list for projection methods
type(atl_Equations_type), intent(in) :: equation
The equation you are operating with.
type(atl_material_type), intent(inout) :: material_list(minlevel:maxlevel)
Information about the material parameters of the equation.
type(tem_general_type), intent(inout) :: general
General treelm settings
logical, intent(in), optional :: computePenalization
Flag to indicate whether penalization terms should be computed or not.
This is used to switch off the application of penalizing terms from the convective computation and instead compute it in an implicit update, see the atl_imexrk_module. Default is .true.!
Calls
Called by
Call graph
compute_rhs_cubes_modg calls exchange_real, atl_modg_acoustic_numflux, atl_modg_euler_numflux, atl_modg_filnvrstk_numflux, atl_modg_finetocoarseface, atl_modg_heat_numflux, atl_modg_lineareuler_numflux, atl_modg_maxwell_numflux, atl_modg_maxwelldivcor_numflux, atl_modg_navierstokes_numflux, atl_modg_project_numflux, atl_modg_project_source, atl_update_sourcedata, modg_compute_project_physflux, recvbuffer_flux, sendbuffer_flux, tem_abort, tem_startTimer, tem_stopTimer
compute_rhs_cubes calls compute_rhs_cubes_modg
atl_compute_rhs calls compute_rhs_cubes
global_corrector_substep calls atl_compute_rhs
imexrk_substep calls atl_compute_rhs, imexrk_substep
mesh_timestep_euler calls atl_compute_rhs, mesh_timestep_euler
rk2_substep calls atl_compute_rhs, rk2_substep
rk4_substep calls atl_compute_rhs, rk4_substep
rktaylor_substep calls atl_compute_rhs, rktaylor_substep
mesh_timestep_imexrk calls imexrk_substep
mesh_timestep_predcor_cerk4 calls global_corrector_substep
mesh_timestep_rk4 calls rk4_substep
mesh_timestep_rktaylor calls rktaylor_substep
mesh_timestep_ssprk2 calls rk2_substep