create_global_timestep – Ateles
create_global_timestep Subroutine
22 statements
Source File
private subroutine create_global_timestep(dt, nCells, minLevel, maxLevel, proc)
\brief subroutine to create a single global timestep.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(inout) :: dt(minLevel:maxLevel)
The delta t on the levels of your mesh. This will be update with the new global, local timestep.
integer, intent(in) :: nCells(minLevel:maxLevel)
The number of cells on the different levels.
integer, intent(in) :: minLevel
The minimum level of your mesh.
integer, intent(in) :: maxLevel
The maximum level of your mesh.
type(tem_comm_env_type), intent(in) :: proc
mpi communication enviroment with mpi communicator
Calls
Called by
Call graph
create_global_timestep calls calc_common_global_timestep
calc_common_global_timestep calls mpi_allreduce
atl_get_timestep calls create_global_timestep
atl_initialize_program calls atl_get_timestep
atl_solve_program calls atl_get_timestep
ateles calls atl_initialize_program, atl_solve_program