eval_source_gravitation – Ateles
eval_source_gravitation Subroutine
14 statements
Source File
private subroutine eval_source_gravitation(fun, varSys, time, mesh, poly_proj, currentLevel, state, material, sourcedata)
Todo
PV: Create a unit test for this routine and compare it to the version before the new varSys
Arguments
Type Intent Optional Attributes Name
class(atl_source_op_type), intent(in) :: fun
Description of method to update source
type(tem_varSys_type), intent(in) :: varSys
variable system
type(tem_time_type), intent(in) :: time
Point in time at which to evaluate the variable.
type(atl_cube_elem_type), intent(in) :: mesh
Current level mesh information
type(ply_poly_project_type), intent(inout) :: poly_proj
Parameters for projection
integer, intent(in) :: currentLevel
current level
real(kind=rk), intent(in) :: state(:,:,:)
The state in modal space. This is needed for several source terms that have to be applied to the current state
real(kind=rk), intent(in) :: material(:)
Material description for the complete domain. Used for evaluation of some source terms.
real(kind=rk), intent(inout) :: sourcedata(:,:,:)
The source data to update. When all source terms are added to this buffer, it is applied to the state.
Calls
Call graph
eval_source_gravitation calls atl_equation_evaluate_source_nodal
atl_equation_evaluate_source_nodal calls get_valofindex, ply_poly_project_m2n, ply_poly_project_n2m, ply_convert2oversample, ply_convertfromoversample, val
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
ply_poly_project_m2n_multivar calls ply_legtopnt_2d, ply_legtopnt_3d, ply_fxt_m2n_1d, ply_fxt_m2n_2d, ply_fxt_m2n_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d, ply_pnttoleg_3d, ply_fxt_n2m_1d, ply_fxt_n2m_2d, ply_fxt_n2m_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d