expand_da_projection – Ateles
expand_da_projection Subroutine
38 statements
Source File
private subroutine expand_da_projection(me, increment, length)
expanding the dynamic array
this is a helping subroutine, which doubles the container of the given dynamic array. as the container might be initially 0-sized, a module variable minlength has been introduced, which is used here, to at least create a container of this size.
Arguments
Type Intent Optional Attributes Name
type(dyn_projectionarray_type) :: me
integer, optional :: increment
integer, intent(in), optional :: length
optional length to expand the array
Called by
Call graph
expand calls expand_da_projection
append_da_projection calls expand
append_da_vecprojection calls expand
append calls append_da_projection, append_da_vecprojection
atl_load_projection calls append
ply_fill_dynprojectarray calls append
sorttruncate_da_projection calls append