fxtf_flptld_init – Ateles
fxtf_flptld_init Subroutine
24 statements
Source File
public subroutine fxtf_flptld_init(flpt, degree, nPoints, prec)
Initialize the flpt data structure for fast legendre polynomial transformation via the fxtpack.
Arguments
Type Intent Optional Attributes Name
type(fxtf_flptld_type), intent(out) :: flpt
Handle to the resulting fast polynomial table.
integer, intent(in) :: degree
Polynomial degree.
integer, intent(in), optional :: nPoints
Number of points.
Optional, defaults to degree+1.
real(kind=c_double), intent(in), optional :: prec
Required precision for the transformation.
Optional, defaults to 8 times the precision of c_double.
Calls
Called by
Call graph
fxtf_flptld_init calls fxt_flptld_init, fxt_flptld_wsize, fxt_vecld_new
check_fxt_1d calls fxtf_flptld_init
ply_init_fxt calls fxtf_flptld_init
fxtp_test calls fxtf_flptld_init
ply_poly_project_fillbody calls ply_init_fxt
test_fxtd_n2m2n calls check_fxt_1d, check_fxt_2d, check_fxt_3d
check_fpt calls ply_poly_project_fillbody
check_fpt_2d calls ply_poly_project_fillbody
check_fxt_2d calls ply_poly_project_fillbody
check_fxt_3d calls ply_poly_project_fillbody
ply_fill_project_list calls ply_poly_project_fillbody
test_project_stabviscnumflux calls ply_poly_project_fillbody
approximate_1d_jump calls ply_poly_project_fillbody
atl_initialize calls ply_fill_project_list
atl_modg_kernel_utests calls test_project_stabviscnumflux
ply_project_2d_fpt_lobattopoints_test calls check_fpt_2d
ply_project_2d_fpt_test calls check_fpt_2d
ply_project_fpt_lobattopoints_test calls check_fpt
ply_project_fpt_test calls check_fpt