fxtf_flptld_m2n – Ateles
fxtf_flptld_m2n Subroutine
9 statements
Source File
public subroutine fxtf_flptld_m2n(flpt, modal_data, nodal_data)
Convert modal data to nodal data using flpt.
This encapsualtes the pure C-Interface, with extraction of the array sizes and dealing with the flpt data.
Note: The modal and nodal data array sizes need to match the flpt definitions, provided in the fxtf_flptld_init call.
Arguments
Type Intent Optional Attributes Name
type(fxtf_flptld_type), intent(in) :: flpt
Description of the Fast Legendre Polynomial Transform
real(kind=rk), target :: modal_data(:)
Modal data
real(kind=rk), target :: nodal_data(:)
Nodal data
Calls
Called by
Call graph
fxtf_flptld_m2n calls fxtf_flptld_evl
check_fxt_1d calls fxtf_flptld_m2n
ply_fxt_m2n_1d calls fxtf_flptld_m2n
ply_fxt_m2n_2d calls fxtf_flptld_m2n
ply_fxt_m2n_3d calls fxtf_flptld_m2n
ply_poly_project_m2n_multivar calls ply_fxt_m2n_1d, ply_fxt_m2n_2d, ply_fxt_m2n_3d
test_fxtd_n2m2n calls check_fxt_1d
ply_poly_project_m2n calls ply_poly_project_m2n_multivar