imexrk_substep – Ateles
imexrk_substep Subroutine
30 statements
Source File
private recursive subroutine imexrk_substep(minLevel, maxLevel, currentLevel, mesh_list, tree, levelPointer, kerneldata_list, statedata_list, facedata_list, source, penalizationdata_list, boundary_list, bc, scheme_list, poly_proj_pos, poly_proj_list, timestep_list, equation, material_list, general, commStateTimer)
Uses
atl_compute_module
Subroutine calculates a substep of the IMEX Runge-Kutta timestepping scheme.
Calls itself recursively for the finer levels until the finest level is reached.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: minLevel
The minimum refinement level of the mesh.
integer, intent(in) :: maxLevel
The maximum refinement level of the mesh.
integer, intent(in) :: currentLevel
The level the timestep has to be performed for.
type(atl_cube_elem_type), intent(inout) :: mesh_list(minLevel:maxLevel)
List of mesh parts. For each level we have one.
type(treelmesh_type), intent(in) :: tree
treelm mesh
integer, intent(in) :: levelPointer(:)
Pointer for elements from global treeID list index to index in levelwise fluid lists
type(atl_kerneldata_type), intent(inout) :: kerneldata_list(minLevel:maxLevel)
List of kerneldatas. For each level we have one
type(atl_statedata_type), intent(inout) :: statedata_list(minLevel:maxLevel)
List of states you want to calc the rhs for. For each level we have one.
type(atl_facedata_type), intent(inout) :: facedata_list(minLevel:maxLevel)
List of faces states you want to calc the rhs for. For each level we have one.
type(atl_source_type), intent(inout) :: source
List of sources, for each level
type(atl_penalizationData_type), intent(inout) :: penalizationdata_list(minLevel:maxLevel)
List of penalization data, for each level.
type(atl_level_boundary_type), intent(inout) :: boundary_list(minLevel:maxLevel)
List of boundaries, for each level.
type(atl_boundary_type), intent(in) :: bc(:)
Global description of the boundaries
type(atl_scheme_type), intent(inout) :: scheme_list(minLevel:maxLevel)
List of schemes, for each level.
integer, intent(in) :: poly_proj_pos(minLevel:maxLevel)
List of position of projection method in unique projection list, for each level
type(ply_poly_project_type), intent(inout) :: poly_proj_list(:)
unique list for projection methods
type(atl_timestep_type), intent(inout) :: timestep_list(minLevel:maxLevel)
List of levelwise timestepping algorihtms
type(atl_Equations_type), intent(inout) :: equation
The equation you are operating with.
type(atl_material_type), intent(inout) :: material_list(minlevel:maxlevel)
Material parameter description.
type(tem_general_type), intent(inout) :: general
General treelm settings
integer, intent(inout) :: commStateTimer
Timer for measuring the communication time inside this routine.
Calls
Called by
Call graph
imexrk_substep calls imexrk_substep, atl_compute_rhs, atl_postprocess_rhs, atl_preprocess_rhs
atl_compute_rhs calls compute_rhs_cubes
atl_postprocess_rhs calls postprocess_rhs_cubes
atl_preprocess_rhs calls preprocess_rhs_cubes
mesh_timestep_imexrk calls imexrk_substep