implicit_update – Ateles
implicit_update Subroutine
86 statements
Source File
private subroutine implicit_update(equation, statedata, poly_proj, material, dt, timestep_list, weight, mesh)
Uses
ply_oversample_module
atl_eqn_maxwell_hlp_module
atl_eqn_euler_hlp_module
and the code from here should move into its hlp module.
Arguments
Type Intent Optional Attributes Name
type(atl_Equations_type), intent(in) :: equation
type(atl_statedata_type), intent(inout) :: statedata
type(ply_poly_project_type), intent(inout) :: poly_proj
type(atl_material_type), intent(in) :: material
real(kind=rk), intent(in) :: dt
type(atl_timestep_type), intent(inout) :: timestep_list
real(kind=rk), intent(in) :: weight
type(atl_cube_elem_type), intent(in) :: mesh
Calls
Called by
Call graph
implicit_update calls ply_poly_project_m2n, ply_poly_project_n2m, atl_eqn_euler_implicit_pen, atl_eqn_maxwell_implicit_pen, atl_reftophyscoord, ply_convert2oversample, ply_convertfromoversample, tem_abort
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
atl_eqn_euler_implicit_pen calls ply_poly_project_m2n, ply_poly_project_n2m, ply_convert2oversample, ply_convertfromoversample
atl_eqn_maxwell_implicit_pen calls ply_poly_project_m2n, ply_poly_project_n2m, ply_convert2oversample, ply_convertfromoversample
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
ply_poly_project_m2n_multivar calls ply_legtopnt_2d, ply_legtopnt_3d, ply_fxt_m2n_1d, ply_fxt_m2n_2d, ply_fxt_m2n_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d, ply_pnttoleg_3d, ply_fxt_n2m_1d, ply_fxt_n2m_2d, ply_fxt_n2m_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
mesh_timestep_imexrk calls implicit_update