init_kernel – Ateles
init_kernel Subroutine
25 statements
Source File
private subroutine init_kernel(time, cube_container, equation, tree, commPattern)
Initialize the kernel states for all parts of the mesh.
Intializes the kernel for the cubic elements of the mesh.
Arguments
Type Intent Optional Attributes Name
type(tem_time_type), intent(in) :: time
current time
type(atl_cube_container_type), intent(inout) :: cube_container
container of cubic elements.
type(atl_Equations_type), intent(in) :: equation
The equation we try to solve.
type(treelmesh_type) :: tree
The tree representation of the mesh.
type(tem_commPattern_type) :: commPattern
mpi communication pattern type
Calls
Called by
Call graph
init_kernel calls atl_init_modg_1d_kernel, atl_init_modg_2d_kernel, atl_init_modg_kernel, tem_abort
atl_init_modg_1d_kernel calls dimbydimdesc, nelems, atl_get_numbndelems, atl_init_kerneldata, atl_init_parallel_module, atl_init_statedata
atl_init_modg_2d_kernel calls dimbydimdesc, nelems, atl_get_numbndelems, atl_init_kerneldata, atl_init_parallel_module, atl_init_statedata
atl_init_modg_kernel calls dimbydimdesc, nelems, atl_get_numbndelems, atl_init_kerneldata, atl_init_parallel_module, atl_init_statedata
atl_init_kerneldata calls atl_init_statedata
atl_init_parallel_module calls dimbydimdesc, atl_init_cellstatebuffer, atl_init_facestatebuffer
atl_init_cellstatebuffer calls buf_real, elempos, val
atl_init_facestatebuffer calls buf_int, buf_real, elempos, recvbuffer_flux, recvbuffer_state, sendbuffer_flux, sendbuffer_state, val
atl_init_elem_container calls init_kernel
atl_initialize calls atl_init_elem_container
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program