init_local_time_integration – Ateles
init_local_time_integration Subroutine
4 statements
Source File
private subroutine init_local_time_integration(me)
Arguments
Type Intent Optional Attributes Name
type(atl_local_timestep_type), intent(inout) :: me
the scheme you want to initialize.
Called by
Call graph
atl_init_scheme calls init_local_time_integration
atl_init_elem_container calls atl_init_scheme
atl_initialize calls atl_init_elem_container
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize