local_predictor_substep – Ateles
local_predictor_substep Subroutine
16 statements
Source File
private subroutine local_predictor_substep(mesh, kerneldata, statedata, scheme, general, poly_proj_list, timestep, equation, material, boundary)
Subroutine calculates a substep of the local predictor
TODO here need to be the source position pointer????
Arguments
Type Intent Optional Attributes Name
type(atl_cube_elem_type), intent(inout) :: mesh
List of mesh parts. For each level we have one.
type(atl_kerneldata_type), intent(inout) :: kerneldata
List of kerneldatas. For each level we have one
type(atl_statedata_type), intent(inout) :: statedata
List of states you want to calc the rhs for. For each level we have one.
type(atl_scheme_type), intent(inout) :: scheme
List of schemes, for each level.
type(tem_general_type), intent(inout) :: general
General treelm settings
type(ply_poly_project_type), intent(inout) :: poly_proj_list(:)
List of project, for each level.
type(atl_timestep_type), intent(inout) :: timestep
List of levelwise timestepping algorihtms
type(atl_Equations_type), intent(inout) :: equation
The equation you are operating with.
type(atl_material_type), intent(inout) :: material
Material parameter description.
type(atl_level_boundary_type), intent(in) :: boundary
Calls
Called by
Call graph
local_predictor_substep calls atl_preprocess_local_rhs, nelems
atl_preprocess_local_rhs calls preprocess_local_rhs_cubes
preprocess_local_rhs_cubes calls atl_preprocess_modg_kernel, tem_abort, tem_startTimer, tem_stopTimer
atl_preprocess_modg_kernel calls atl_update_materialparams
mesh_timestep_predcor_cerk4 calls local_predictor_substep