maxwell_flux_cube_vec_2d – Ateles
maxwell_flux_cube_vec_2d Subroutine
35 statements
Source File
private subroutine maxwell_flux_cube_vec_2d(nTotalFaces, nSides, nFaceDofs, faceRep, faceFlux, leftPos, rightPos, var, material_left, material_right)
(formulation is based on TE mode formulation for 2D).
This subroutine assumes the Maxwell equations with D and B as input variables. Furthermore, it is able to handle jumping material parameters.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nTotalFaces
integer, intent(in) :: nSides
integer, intent(in) :: nFaceDofs
real(kind=rk), intent(in) :: faceRep(nTotalFaces,nFaceDofs,7,2)
real(kind=rk), intent(inout) :: faceFlux(nTotalFaces,nFaceDofs,7,2)
integer, intent(in) :: leftPos(nSides)
integer, intent(in) :: rightPos(nsides)
integer, intent(in) :: var(7)
real(kind=rk), intent(in) :: material_left(nSides,1,3)
real(kind=rk), intent(in) :: material_right(nSides,1,3)
Called by
Call graph
atl_maxwell_flux_2d calls maxwell_flux_cube_vec_2d
atl_modg_maxwell_2d_numflux calls atl_maxwell_flux_2d
compute_rhs_cubes_modg_2d calls atl_modg_maxwell_2d_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg_2d