maxwell_flux_nonconst_cube_vec – Ateles
maxwell_flux_nonconst_cube_vec Subroutine
40 statements
Source File
private subroutine maxwell_flux_nonconst_cube_vec(nTotalFaces, nSides, nFaceDofs, faceRep, faceFlux, leftPos, rightPos, var, material_left, material_right, poly_proj, modalCoeffs, pntVal, nodalNumFlux, numFluxBuffer)
face-vector
This subroutine assumes the Maxwell equations with D and B as input variables. Furthermore, it is able to handle arbitray material parameters by a pseudo-spectral technique.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nTotalFaces
integer, intent(in) :: nSides
integer, intent(in) :: nFaceDofs
real(kind=rk), intent(in) :: faceRep(nTotalFaces,nFaceDofs,6,2)
The modal representation on the faces, left and right trace.
real(kind=rk), intent(inout) :: faceFlux(nTotalFaces,nFaceDofs,6,2)
The fluxes for all faces, for left and right elements.
integer, intent(in) :: leftPos(nSides)
Positions for the left and right elements of all faces
integer, intent(in) :: rightPos(nsides)
Positions for the left and right elements of all faces
integer, intent(in) :: var(6)
Variable rotation indices
real(kind=rk), intent(in) :: material_left(nSides,nFaceDofs,2)
Material parameters for the left faces.
real(kind=rk), intent(in) :: material_right(nSides,nFaceDofs,2)
Material parameters for the right faces.
FPT to convert between nodes and modes.
type(ply_poly_project_type) :: poly_proj
Data for projection method
real(kind=rk), intent(inout) :: modalCoeffs(:,:,:)
Working array for the left and right modal coefficients
real(kind=rk), intent(inout) :: pntVal(:,:,:)
Working array for the left and right point values
real(kind=rk), intent(inout) :: nodalNumFlux(:,:)
Working array for the nodal flux
real(kind=rk), intent(inout) :: numFluxBuffer(:,:)
Working array for the modal numerical flux
Calls
Called by
Call graph
maxwell_flux_nonconst_cube_vec calls ply_poly_project_m2n, ply_poly_project_n2m, maxwell_flux_cube, ply_convert2oversample, ply_convertfromoversample
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
ply_poly_project_m2n_multivar calls ply_legtopnt_2d, ply_legtopnt_3d, ply_fxt_m2n_1d, ply_fxt_m2n_2d, ply_fxt_m2n_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d, ply_pnttoleg_3d, ply_fxt_n2m_1d, ply_fxt_n2m_2d, ply_fxt_n2m_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
atl_maxwell_flux calls maxwell_flux_nonconst_cube_vec
atl_modg_maxwell_numflux calls atl_maxwell_flux
compute_rhs_cubes_modg calls atl_modg_maxwell_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg