maxwell_flux_cube_vec – Ateles
maxwell_flux_cube_vec Subroutine
39 statements
Source File
private subroutine maxwell_flux_cube_vec(nTotalFaces, nSides, nFaceDofs, faceRep, faceFlux, leftPos, rightPos, var, material_left, material_right)
face-vector
This subroutine assumes the Maxwell equations with D and B as input variables. Furthermore, it is able to handle jumping material parameters.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nTotalFaces
integer, intent(in) :: nSides
integer, intent(in) :: nFaceDofs
real(kind=rk), intent(in) :: faceRep(nTotalFaces,nFaceDofs,6,2)
real(kind=rk), intent(inout) :: faceFlux(nTotalFaces,nFaceDofs,6,2)
integer, intent(in) :: leftPos(nSides)
integer, intent(in) :: rightPos(nsides)
integer, intent(in) :: var(6)
real(kind=rk), intent(in) :: material_left(nSides,1,2)
real(kind=rk), intent(in) :: material_right(nSides,1,2)
Called by
Call graph
atl_maxwell_flux calls maxwell_flux_cube_vec
atl_modg_maxwell_numflux calls atl_maxwell_flux
compute_rhs_cubes_modg calls atl_modg_maxwell_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg