maxwell_flux_cube_2d – Ateles
maxwell_flux_cube_2d Subroutine
21 statements
Source File
private subroutine maxwell_flux_cube_2d(left, right, left_mu, left_epsi, right_mu, right_epsi, flux)
any divergence cleaning on the reference cubic face in 2D.
This subroutine calculates the flux of the Maxwell equation on the reference cubic face. The underlying 2D formulation is transverse electric mode formulation - TE mode.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: left(7)
Left state vector (as conservative variables). The order of this vector has to be \f$ (D_x, D_y, B_3) \f$ where E and B denoted electric field vetor and magnetic field (also called magnetic induction) vector.
real(kind=rk), intent(in) :: right(7)
Right state vector (as conservative variables). The order of this vector has to be (D_x, D_y, B_3) where E and B denoted the electric field vetor and magnetic field (also called magnetic induction) vector.
real(kind=rk), intent(in) :: left_mu
The magnetic permeability of the left element.
real(kind=rk), intent(in) :: left_epsi
The electric permitivity of the left element.
real(kind=rk), intent(in) :: right_mu
The magnetic permeability of the right element.
real(kind=rk), intent(in) :: right_epsi
The electric permitivity of the right element.
real(kind=rk), intent(out) :: flux(7)
The flux between left and right cell. The order of this vector is the same as the input arguments.
Called by
Call graph
atl_maxwell_flux_2d calls maxwell_flux_cube_2d, maxwell_flux_nonconst_cube_vec_2d
maxwell_flux_nonconst_cube_vec_2d calls maxwell_flux_cube_2d
atl_modg_maxwell_2d_numflux calls atl_maxwell_flux_2d
compute_rhs_cubes_modg_2d calls atl_modg_maxwell_2d_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg_2d