maxwell_flux_nonconst_cube_vec_2d – Ateles
maxwell_flux_nonconst_cube_vec_2d Subroutine
54 statements
Source File
private subroutine maxwell_flux_nonconst_cube_vec_2d(nTotalFaces, nSides, nFaceDofs, faceRep, faceFlux, leftPos, rightPos, var, material_left, material_right, poly_proj, modalCoeffs, pntVal, nodalNumFlux, numFluxBuffer)
(formulation is based on TE mode formulation for 2D).
This subroutine assumes the Maxwell equations with D and B as input variables. Furthermore, it is able to handle arbitray material parameters by a pseudo-spectral technique.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nTotalFaces
integer, intent(in) :: nSides
integer, intent(in) :: nFaceDofs
real(kind=rk), intent(in) :: faceRep(nTotalFaces,nFaceDofs,7,2)
The modal representation on the faces, left and right trace.
real(kind=rk), intent(inout) :: faceFlux(nTotalFaces,nFaceDofs,7,2)
The fluxes for all faces, for left and right elements.
integer, intent(in) :: leftPos(nSides)
Positions for the left and right elements of all faces
integer, intent(in) :: rightPos(nsides)
Positions for the left and right elements of all faces
integer, intent(in) :: var(7)
Variable rotation indices
real(kind=rk), intent(in) :: material_left(nSides,nFaceDofs,3)
Material parameters for the left faces.
real(kind=rk), intent(in) :: material_right(nSides,nFaceDofs,3)
Material parameters for the right faces.
FPT to convert between nodes and modes.
type(ply_poly_project_type) :: poly_proj
Data for projection method
real(kind=rk), intent(inout) :: modalCoeffs(:,:,:)
Working array for the left and right modal coefficients
real(kind=rk), intent(inout) :: pntVal(:,:,:)
Working array for the left and right point values
real(kind=rk), intent(inout) :: nodalNumFlux(:,:)
Working array for the nodal flux
real(kind=rk), intent(inout) :: numFluxBuffer(:,:)
Working array for the modal numerical flux
Calls
Called by
Call graph
maxwell_flux_nonconst_cube_vec_2d calls ply_poly_project_m2n, ply_poly_project_n2m, maxwell_flux_cube_2d
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
ply_poly_project_m2n_multivar calls ply_legtopnt_2d, ply_legtopnt_3d, ply_fxt_m2n_1d, ply_fxt_m2n_2d, ply_fxt_m2n_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d, ply_pnttoleg_3d, ply_fxt_n2m_1d, ply_fxt_n2m_2d, ply_fxt_n2m_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_legtopnt_2d calls ply_legtopnt_2d_multvar, ply_legtopnt_2d_singvar
ply_legtopnt_3d calls ply_legtopnt_3d_multvar, ply_legtopnt_3d_singvar
ply_pnttoleg_2d calls ply_pnttoleg_2d_multvar, ply_pnttoleg_2d_singvar
ply_pnttoleg_3d calls ply_pnttoleg_3d_multvar, ply_pnttoleg_3d_singvar
ply_fxt_m2n_1d calls fxtf_flptld_m2n
ply_fxt_m2n_2d calls fxtf_flptld_m2n
ply_fxt_m2n_3d calls fxtf_flptld_m2n
ply_fxt_n2m_1d calls fxtf_flptld_n2m
ply_fxt_n2m_2d calls fxtf_flptld_n2m
ply_fxt_n2m_3d calls fxtf_flptld_n2m
ply_l2p_trafo_1d calls ply_l2_projection
ply_l2p_trafo_2d calls ply_l2_projection
ply_l2p_trafo_3d calls ply_l2_projection
atl_maxwell_flux_2d calls maxwell_flux_nonconst_cube_vec_2d
atl_modg_maxwell_2d_numflux calls atl_maxwell_flux_2d
compute_rhs_cubes_modg_2d calls atl_modg_maxwell_2d_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg_2d