mesh_timestep_ssprk2 – Ateles
mesh_timestep_ssprk2 Subroutine
50 statements
Source File
private subroutine mesh_timestep_ssprk2(minLevel, maxLevel, currentLevel, cubes, tree, timestep_list, nSteps, equation, general, commStateTimer, poly_proj_list)
Subroutine for timestepping with explicit runge kutta of order 2.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: minLevel
The minimum refinement level of the mesh.
integer, intent(in) :: maxLevel
The maximum refinement level of the mesh.
integer, intent(in) :: currentLevel
The level the timestep has to be performed for.
type(atl_cube_container_type), intent(inout) :: cubes
Container for the cubical elements.
type(treelmesh_type), intent(in) :: tree
treelm mesh
type(atl_timestep_type), intent(inout) :: timestep_list(minLevel:)
List of levelwise timestepping algorihtms
integer, intent(in) :: nSteps
The number of steps of the time stepping scheme (assumed to be 2)
type(atl_Equations_type), intent(inout) :: equation
The equation you are operating with.
type(tem_general_type), intent(inout) :: general
General treelm settings
integer, intent(inout) :: commStateTimer
Timer for measuring the communication time inside this routine.
type(ply_poly_project_type), intent(inout) :: poly_proj_list(:)
unique list for projection methods
Calls
Call graph
mesh_timestep_ssprk2 calls nelems, atl_stabilize, atl_write_precice, compute_intermediate, rk2_substep, rk2_update, tem_startTimer, tem_stopTimer