mesh_timestep_imexrk – Ateles
mesh_timestep_imexrk Subroutine
82 statements
Source File
private subroutine mesh_timestep_imexrk(minLevel, maxLevel, currentLevel, cubes, tree, timestep_list, nSteps, equation, general, commStateTimer, poly_proj_list)
Subroutine for timestepping with IMEX Runge-Kutta.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: minLevel
The minimum refinement level of the mesh.
integer, intent(in) :: maxLevel
The maximum refinement level of the mesh.
integer, intent(in) :: currentLevel
The level the timestep has to be performed for.
type(atl_cube_container_type), intent(inout) :: cubes
Container for the cubical elements.
type(treelmesh_type), intent(in) :: tree
treelm mesh
type(atl_timestep_type), intent(inout) :: timestep_list(minLevel:)
List of levelwise timestepping algorihtms
integer, intent(in) :: nSteps
The number of steps of the time stepping scheme (assumed to be 4)
type(atl_Equations_type), intent(inout) :: equation
The equation you are operating with.
type(tem_general_type), intent(inout) :: general
General treelm settings
integer, intent(inout) :: commStateTimer
Timer for measuring the communication time inside this routine.
type(ply_poly_project_type), intent(inout) :: poly_proj_list(:)
unique list for projection methods
Calls
Call graph
mesh_timestep_imexrk calls nelems, atl_stabilize, atl_write_precice, imexrk_substep, imexrk_update, implicit_update