mesh_timestep_predcor_cerk4 – Ateles
mesh_timestep_predcor_cerk4 Subroutine
100 statements
Source File
private subroutine mesh_timestep_predcor_cerk4(minLevel, maxLevel, currentLevel, cubes, tree, timestep_list, nSteps, equation, general, commStateTimer, poly_proj_list)
Subroutine for timestepping with explicit runge kutta of order 4.
Stabilize the intermediate result of this stage of the predcor_cerk4 scheme
Stabilize the intermediate result of this stage of the predcor_cerk4 scheme
Stabilize the intermediate result of this stage of the predcor_cerk4 scheme
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: minLevel
The minimum refinement level of the mesh.
integer, intent(in) :: maxLevel
The maximum refinement level of the mesh.
integer, intent(in) :: currentLevel
The level the timestep has to be performed for.
type(atl_cube_container_type), intent(inout) :: cubes
Container for the cubical elements.
type(treelmesh_type), intent(in) :: tree
treelm mesh
type(atl_timestep_type), intent(inout) :: timestep_list(minLevel:)
List of levelwise timestepping algorihtms
integer, intent(in) :: nSteps
The number of steps of the time stepping scheme (assumed to be 4)
type(atl_Equations_type), intent(inout) :: equation
The equation you are operating with.
type(tem_general_type), intent(inout) :: general
General treelm settings
integer, intent(inout) :: commStateTimer
Timer for measuring the communication time inside this routine.
type(ply_poly_project_type), intent(inout) :: poly_proj_list(:)
unique list for projection methods
Calls
Call graph
mesh_timestep_predcor_cerk4 calls nelems, global_corrector_substep, local_predictor_substep
global_corrector_substep calls atl_compute_rhs, atl_postprocess_rhs, atl_preprocess_rhs
local_predictor_substep calls nelems, atl_preprocess_local_rhs
atl_compute_rhs calls compute_rhs_cubes
atl_postprocess_rhs calls postprocess_rhs_cubes
atl_preprocess_local_rhs calls preprocess_local_rhs_cubes
atl_preprocess_rhs calls preprocess_rhs_cubes