mesh_timestep_euler – Ateles
mesh_timestep_euler Subroutine
21 statements
Source File
private recursive subroutine mesh_timestep_euler(minLevel, maxLevel, currentLevel, cubes, tree, timestep_list, nSteps, equation, general, commStateTimer, poly_proj_list)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: minLevel
The minimum refinement level of the mesh.
integer, intent(in) :: maxLevel
The maximum refinement level of the mesh.
integer, intent(in) :: currentLevel
The level the timestep has to be performed for.
type(atl_cube_container_type), intent(inout) :: cubes
Container for the cubical elements.
type(treelmesh_type), intent(in) :: tree
treelm mesh
type(atl_timestep_type), intent(inout) :: timestep_list(minLevel:)
List of levelwise timestepping algorihtms
integer, intent(in) :: nSteps
The number of steps of the time stepping scheme (assumed to be 1)
type(atl_Equations_type), intent(inout) :: equation
The equation you are operating with.
type(tem_general_type), intent(inout) :: general
General treelm settings
integer, intent(inout) :: commStateTimer
Timer for measuring the communication time inside this routine.
type(ply_poly_project_type), intent(inout) :: poly_proj_list(:)
unique list for projection methods
Calls
Call graph
mesh_timestep_euler calls mesh_timestep_euler, atl_compute_rhs, atl_postprocess_rhs, atl_preprocess_rhs, atl_stabilize
atl_compute_rhs calls compute_rhs_cubes
atl_postprocess_rhs calls postprocess_rhs_cubes
atl_preprocess_rhs calls preprocess_rhs_cubes
atl_stabilize calls dimbydimdesc, ply_poly_project_m2n, nelems, atl_cheb_spectral_visc_1d, atl_cons_positivity_preserv, atl_cons_positivity_preserv_2d, atl_covolume, atl_covolume_1d, atl_covolume_2d, atl_get_numbndelems, atl_positivity_preserv, atl_positivity_preserv_2d, atl_spectral_visc_1d, atl_spectral_visc_2d, atl_spectral_visc_3d, ply_change_poly_space, ply_convert2oversample, tem_abort, tem_startTimer, tem_stopTimer