modg_nerplanck_z_numFlux_pre – Ateles
modg_nerplanck_z_numFlux_pre Subroutine
64 statements
Source File
private subroutine modg_nerplanck_z_numFlux_pre(mesh, equation, statedata, scheme)
Numerical flux calculation for Nernst-Planck equation across the faces in Z direction.
Arguments
Type Intent Optional Attributes Name
type(atl_cube_elem_type) :: mesh
The mesh you are working with.
type(atl_Equations_type) :: equation
The equation you solve.
type(atl_statedata_type) :: statedata
THe state if the equation
type(atl_modg_scheme_type), intent(in) :: scheme
Parameters of the modal dg scheme
Calls
Called by
Call graph
modg_nerplanck_z_numflux_pre calls faces, atl_nerplanck_numflux_preprocess, leftpos, ply_facevalleftbndans, ply_facevalleftbndtest, ply_facevalrightbndtest, ply_scalproddualleg, rightpos, vartransformindices
atl_nerplanck_numflux_preprocess calls nerplanck_numflux_diffusiveflux
preprocess_modg_nerplanck_kernel calls modg_nerplanck_z_numflux_pre
atl_preprocess_modg_nerplanck_kernel calls preprocess_modg_nerplanck_kernel