modg_2d_compute_project_physFlux – Ateles
modg_2d_compute_project_physFlux Subroutine
148 statements
Source File
private subroutine modg_2d_compute_project_physFlux(mesh, equation, kerneldata, statedata, scheme, poly_proj, dl_prod, penalizationdata, material, minLevel, maxLevel, currentLevel, eval_phy, apply_pen, usePenalization)
Uses
atl_equation_module
atl_kerneldata_module
atl_materialPrp_module
atl_scheme_module
atl_cube_elem_module
atl_modg_2d_heat_kernel_module
atl_project_physflux_module
ply_poly_project_module
ply_oversample_module
atl_modg_2d_euler_kernel_module
atl_modg_2d_acoustic_kernel_module
atl_physFlux_module
atl_physFluxEuler_2d_module
atl_penalization_module
ply_leg_diff_module
atl_modg_2d_LoclinEuler_kernel_module
This subroutine computes the physical fluxes for various equation system
If the element is covered completely by the material, than just the first mode is considered for the flux computation. write(,) 'Elements with chi 0 using nonlinear flux '
Arguments
Type Intent Optional Attributes Name
type(atl_cube_elem_type), intent(in) :: mesh
Descritption of the cubical elements in the mesh
type(atl_Equations_type), intent(in) :: equation
The equation description.
type(atl_kerneldata_type), intent(inout) :: kerneldata
The data of the kernel. Holds the physical fluxes.
type(atl_statedata_type), intent(in) :: statedata
The representation on the face + representation of the flux.
type(atl_scheme_type), intent(inout) :: scheme(minLevel:maxLevel)
The parameters of the MODG scheme
type(ply_poly_project_type) :: poly_proj
Data for projection method
real(kind=rk), intent(in) :: dl_prod(2,scheme(currentLevel)%modg_2d%maxPolyDegree+1)
stored scalar products of the testfunction and anstaz function
type(atl_penalizationData_type), intent(inout) :: penalizationdata
type(atl_material_type), intent(inout) :: material
Material parameters (mu, epsilon) for all elements
integer, intent(in) :: minLevel
the levels of the geometry
integer, intent(in) :: maxLevel
the levels of the geometry
integer, intent(in) :: currentLevel
the levels of the geometry
type(atl_physflux_pointer_type) :: eval_phy(2)
type(atl_penalization_pointer_type) :: apply_pen(2)
logical, intent(in) :: usePenalization
Flag indicating whether to apply the penalization or not.
When a implicit scheme is used to integrate the penalized parts, this can be used to switch it off here.
Calls
Called by
Call graph
modg_2d_compute_project_physflux calls ply_poly_project_m2n, ply_poly_project_n2m, pnttid, atl_initialize_state_der, atl_modg_2d_loclineuler_physflux, atl_modg_2d_project_physflux_testfunc, atl_physfluxeuler_2d, ply_calcdiff_leg_2d, ply_convert2oversample, ply_convertfromoversample, tem_startTimer, tem_stopTimer, vartransformindices
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
atl_modg_2d_loclineuler_physflux calls vartransformindices
atl_modg_2d_project_physflux_testfunc calls modg_2d_project_physfluxx_p, modg_2d_project_physfluxx_q, modg_2d_project_physfluxy_p, modg_2d_project_physfluxy_q
ply_calcdiff_leg_2d calls ply_calcdiff_leg_2d_normal
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
compute_rhs_cubes_modg_2d calls modg_2d_compute_project_physflux
compute_rhs_cubes calls compute_rhs_cubes_modg_2d
atl_compute_rhs calls compute_rhs_cubes
global_corrector_substep calls atl_compute_rhs
imexrk_substep calls atl_compute_rhs
mesh_timestep_euler calls atl_compute_rhs
rk2_substep calls atl_compute_rhs
rk4_substep calls atl_compute_rhs
rktaylor_substep calls atl_compute_rhs