modg_1d_project_testFunc_Q – Ateles
modg_1d_project_testFunc_Q Subroutine
20 statements
Source File
private subroutine modg_1d_project_testFunc_Q(mesh, equation, kerneldata, facedata, penalizationdata, usePenalization, sourcedata, Currentlevel, scheme)
Subroutine to project modal representations of physical flux, numerical flux and source terms onto test functions.
Arguments
Type Intent Optional Attributes Name
type(atl_cube_elem_type), intent(in) :: mesh
Descritption of the cubical elements in the mesh
type(atl_Equations_type), intent(in) :: equation
The equation description.
type(atl_kerneldata_type), intent(inout) :: kerneldata
The data of the kernel. Holds the physical fluxes.
type(atl_facedata_type), intent(inout) :: facedata
The representation on the face + representation of the flux.
type(atl_penalizationData_type), intent(in) :: penalizationdata
Volumetric data for the penalization
logical, intent(in) :: usePenalization
Flag to indicate whether the penalization data has to be considered, or if it is taken care of somewhere else (imex)
type(atl_source_type), intent(inout) :: sourcedata
Modal representation of the sources.
integer, intent(in) :: Currentlevel
The level you compute for
type(atl_modg_1d_scheme_type), intent(in) :: scheme
The parameters of the MODG scheme
Calls
Called by
Call graph
modg_1d_project_testfunc_q calls nelems, modg_1d_project_numflux_difftestx_q, modg_1d_project_numfluxx_q, modg_1d_project_penalization, modg_1d_project_source_q
modg_1d_project_numflux_difftestx_q calls ply_facevalleftbndgradtest, ply_facevalrightbndgradtest
modg_1d_project_numfluxx_q calls ply_facevalleftbndtest, ply_facevalrightbndtest
modg_1d_project_penalization calls nelems, ply_scalproddualleg
modg_1d_project_source_q calls ply_scalproddualleg, val
atl_modg_1d_project_testfunc calls modg_1d_project_testfunc_q
compute_rhs_cubes_modg_1d calls atl_modg_1d_project_testfunc
compute_rhs_cubes calls compute_rhs_cubes_modg_1d
atl_compute_rhs calls compute_rhs_cubes