modg_1d_compute_project_physFlux – Ateles
modg_1d_compute_project_physFlux Subroutine
173 statements
Source File
private subroutine modg_1d_compute_project_physFlux(mesh, equation, material, kerneldata, statedata, scheme, poly_proj, penalizationdata, minLevel, maxLevel, currentLevel, usePenalization)
Uses
atl_scheme_module
atl_elemental_time_integration_module
atl_modg_1d_advection_kernel_module
atl_physFluxEuler_1d_module
atl_facedata_module
ply_poly_project_module
ply_oversample_module
ply_dynarray_project_module
atl_modg_1d_kernel_module
atl_modg_1d_euler_kernel_module
atl_cube_elem_module
atl_modg_1d_multilevel_module
atl_materialPrp_module
atl_kerneldata_module
atl_penalization_module
atl_equation_module
atl_modg_1d_LoclinEuler_kernel_module
atl_modg_1d_heat_kernel_module
Arguments
Type Intent Optional Attributes Name
type(atl_cube_elem_type), intent(in) :: mesh
Descritption of the cubical elements in the mesh
type(atl_Equations_type), intent(in) :: equation
The equation description.
type(atl_material_type), intent(in) :: material
Description of the material parameters.
type(atl_kerneldata_type), intent(inout) :: kerneldata
The data of the kernel. Holds the physical fluxes.
type(atl_statedata_type), intent(in) :: statedata
The representation on the face + representation of the flux.
type(atl_scheme_type), intent(inout) :: scheme(minLevel:maxLevel)
The parameters of the MODG scheme
type(ply_poly_project_type) :: poly_proj
Data for projection method
type(atl_penalizationData_type), intent(inout) :: penalizationdata
Penalization terms
integer, intent(in) :: minLevel
the levels of the geometry
integer, intent(in) :: maxLevel
the levels of the geometry
integer, intent(in) :: currentLevel
the levels of the geometry
logical, intent(in) :: usePenalization
Flag indicating whether to apply the penalization or not.
When a implicit scheme is used to integrate the penalized parts, this can be used to switch it off here.
Calls
Called by
Call graph
modg_1d_compute_project_physflux calls ply_poly_project_m2n, ply_poly_project_n2m, nelems, pnttid, atl_initialize_state_der, atl_modg_1d_advection_physflux, atl_modg_1d_euler_penalization_const, atl_modg_1d_euler_penalization_nonconst, atl_modg_1d_euler_physflux_const, atl_modg_1d_euler_physflux_nonconst, atl_modg_1d_heat_physflux, atl_modg_1d_loclineuler_physflux, atl_modg_1d_project_physflux_testfunc, atl_physfluxeuler_1d, ply_convert2oversample, ply_convertfromoversample, tem_abort, tem_startTimer, tem_stopTimer, totalpnt
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
atl_modg_1d_euler_penalization_const calls ply_poly_project_n2m, ply_convertfromoversample
atl_modg_1d_euler_penalization_nonconst calls ply_poly_project_n2m, ply_convertfromoversample
atl_modg_1d_euler_physflux_const calls atl_physfluxeuler_1d
atl_modg_1d_euler_physflux_nonconst calls atl_physfluxeuler_1d
atl_modg_1d_heat_physflux calls ply_calcdiff_leg_1d
atl_modg_1d_project_physflux_testfunc calls modg_1d_project_physfluxx_q
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
compute_rhs_cubes_modg_1d calls modg_1d_compute_project_physflux
compute_rhs_cubes calls compute_rhs_cubes_modg_1d
atl_compute_rhs calls compute_rhs_cubes
global_corrector_substep calls atl_compute_rhs
imexrk_substep calls atl_compute_rhs
mesh_timestep_euler calls atl_compute_rhs
rk2_substep calls atl_compute_rhs
rk4_substep calls atl_compute_rhs
rktaylor_substep calls atl_compute_rhs