modg_1d_volToFace_Q – Ateles
modg_1d_volToFace_Q Subroutine
35 statements
Source File
private subroutine modg_1d_volToFace_Q(volState, maxPolyDegree, faceDir, nScalars, nElems, faceState)
Projects derivative of modal representation of each cell to its faces, i.e. this subroutine creates a modal representation on the faces. Project modal representation of an element to one of its faces for Q space.
Project modal representation of an element onto one of its faces. Therefore, this function returns the modal representation of the solution on the face. This function can project onto an arbitrary face direction.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: volState(:,:,:)
The modal representation in the volume. First dimension is the number of voluemtrix numbers of degrees of freedom and second dimension is the number of scalar variables in the equation system.
integer, intent(in) :: maxPolyDegree
The maximal polynomial degree per spatial direction.
integer, intent(in) :: faceDir
The face to project the modal representation to. Use one of the first six directions of \link tem_param_module \endlink, e.g. \link tem_param_module::q__e \endlink
integer, intent(in) :: nScalars
The number of scalar variables in your equation system.
integer, intent(in) :: nElems
The number of elements
real(kind=rk), intent(inout) :: faceState(:,:,:,:)
The modal representation on the face
Calls
Called by
Call graph
modg_1d_voltoface_q calls ply_facevalleftbndans, tem_abort
atl_modg_1d_modalvoltomodalface calls modg_1d_voltoface_q