modg_1d_heat_oneDim_numFlux – Ateles
modg_1d_heat_oneDim_numFlux Subroutine
46 statements
Source File
private subroutine modg_1d_heat_oneDim_numFlux(equation, facedata, scheme, faces, faceDir, elem_len)
Numerical flux calculation for the Heat equation across the faces in a single spatial direction.
Arguments
Type Intent Optional Attributes Name
type(atl_Equations_type), intent(in) :: equation
The equation you solve.
type(atl_facedata_type), intent(inout) :: facedata
The face state if the equation
type(atl_modg_1d_scheme_type), intent(in) :: scheme
Parameters of the modal dg scheme
type(tem_faceIterator_type), intent(in) :: faces
The faces to calculate the fluxes for.
integer, intent(in) :: faceDir
The spatial direction of the faces you calc the fluxes for, use the following: 1 --> x direction.
real(kind=rk), intent(in) :: elem_len
Length of the element
Called by
Call graph
atl_modg_1d_heat_numflux calls modg_1d_heat_onedim_numflux
compute_rhs_cubes_modg_1d calls atl_modg_1d_heat_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg_1d
atl_compute_rhs calls compute_rhs_cubes