modg_2d_project_physFluxX_P – Ateles
modg_2d_project_physFluxX_P Subroutine
51 statements
Source File
private subroutine modg_2d_project_physFluxX_P(nScalars, maxPolyDegree, length, dl_prod, state, iElem, nDofs, state_der)
Projection of the physical flux in x direction onto the testfunctions.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nScalars
The number of scalar variables in your equation system.
integer, intent(in) :: maxPolyDegree
The maximal polynomial degree in each spatial direction.
real(kind=rk), intent(in) :: length
The length of the cubes.
real(kind=rk), intent(in) :: dl_prod(2,maxPolyDegree+1)
Precomputed dual Legendre products:
real(kind=rk), intent(inout) :: state(:,:,:)
The state to alter.
integer, intent(in) :: iElem
The element index
integer, intent(in) :: nDofs
Number of degrees of freedom
real(kind=rk), intent(in) :: state_der(nDofs,nScalars)
The state data for the element
Calls
Called by
Call graph
modg_2d_project_physfluxx_p calls ply_scalprodduallegdiff
atl_modg_2d_project_physflux_testfunc calls modg_2d_project_physfluxx_p
modg_2d_compute_project_physflux calls atl_modg_2d_project_physflux_testfunc
compute_rhs_cubes_modg_2d calls modg_2d_compute_project_physflux
compute_rhs_cubes calls compute_rhs_cubes_modg_2d