modg_bnd_mirrorPoint – Ateles
modg_bnd_mirrorPoint Function
15 statements
Source File
private function modg_bnd_mirrorPoint(bc, varSys, time, currentFace, currentLevel, nPoints) result(pointFace)
Function to mirror pointvalues for a given boundary conditions.
Arguments
Type Intent Optional Attributes Name
type(tem_bc_state_type), intent(in) :: bc
The boundary state.
type(tem_varSys_type), intent(in) :: varSys
Global variable system
type(tem_time_type), intent(in) :: time
The current absolute time.
integer, intent(in) :: currentFace
current face used to compute correct index in indices array
integer, intent(in) :: currentLevel
current level
integer, intent(in) :: nPoints
The number of point values to be mirrored.
Return Value real(kind=rk), (npoints)
The mirrored isNodalScheme representation.
Calls
Called by
Call graph
modg_bnd_mirrorpoint calls get_valofindex, tem_startTimer, tem_stopTimer, val
modg_modal_bnd calls modg_bnd_mirrorpoint
modg_nodal_bnd calls modg_bnd_mirrorpoint
atl_modg_bnd calls modg_modal_bnd, modg_nodal_bnd
atl_modg_set_bnd calls atl_modg_bnd
atl_set_covolume_bnd calls atl_modg_bnd
atl_interpolate_elemstate calls atl_set_covolume_bnd
preprocess_rhs_cubes calls atl_modg_set_bnd