modg_project_numFlux_Q – Ateles
modg_project_numFlux_Q Subroutine
83 statements
Source File
private subroutine modg_project_numFlux_Q(nTotalFaces, nFaceDofs, nScalars, faceFlux, maxPolyDegree, length, nElems_fluid, dl_prod, projection, dirVec)
Projection of the numerical flux onto the testfunctions for Q_space.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nTotalFaces
dimensions
integer, intent(in) :: nFaceDofs
dimensions
integer, intent(in) :: nScalars
dimensions
real(kind=rk), intent(in) :: faceFlux(:,:,:,:)
The numerical flux on the left face in modal representations. Dimension is nTotalFaces, (maxPolyDegree+1)^2 , nScalars, 2
integer, intent(in) :: maxPolyDegree
The maximal polynomial degree in each spatial direction.
real(kind=rk), intent(in) :: length
The length of the cubes.
integer, intent(in) :: nElems_fluid
The element index
real(kind=rk), intent(in) :: dl_prod(2,maxPolyDegree+1)
Precomputed dual Legendre products:
real(kind=rk), intent(inout) :: projection(:,:,:)
The numerical flux projected onto the test functions.
integer, intent(in) :: dirVec(3)
direction (x,y,z)
Calls
Called by
Call graph
modg_project_numflux_q calls ply_facevalleftbndtest, ply_facevalrightbndtest
atl_modg_project_numflux calls modg_project_numflux_q
compute_rhs_cubes_modg calls atl_modg_project_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg
atl_compute_rhs calls compute_rhs_cubes