modg_semiCoarseElem – Ateles
modg_semiCoarseElem Subroutine
57 statements
Source File
private subroutine modg_semiCoarseElem(modalRepFace, modg_basis, schemeCoarse, schemeFine, coarseDir, fineElemShift, modalCoarsed)
Subroutine to semi-coarsen an element with modal polynomial representation to its semi-parent.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: modalRepFace(:,:)
Modal representation of a function on one of refined element. Which fine element is determined by fineFaceShift Dimensions are: (modg%maxPolyDegree+1)^3 for the first dimension and nScalars for the second dimension.
type(ply_modg_basis_type) :: modg_basis
Informations about the polynomial basis of a MODG scheme.
type(atl_modg_scheme_type), intent(in) :: schemeCoarse
The parameters of your MODG scheme on the coarse level.
type(atl_modg_scheme_type), intent(in) :: schemeFine
The parameters of your MODG scheme on the fint level.
integer, intent(in) :: coarseDir
The direction of the semi-coarsening. Either 1 or 2 or 3. Have a look at the function description.
integer, intent(in) :: fineElemShift
The semi-refined element you want to obtain.
real(kind=rk), intent(inout) :: modalCoarsed(:,:)
The modal representation of modalRepFace on the coarser element, restricted to the given fine element.
Called by
Call graph
atl_modg_finetocoarseelem calls modg_semicoarseelem
atl_interpolate_elemstate calls atl_modg_finetocoarseelem, atl_interpolate_elemstate
atl_covolume_tocovolume calls atl_interpolate_elemstate
atl_covolume_tocovolume_1d calls atl_interpolate_elemstate
atl_covolume_tocovolume_2d calls atl_interpolate_elemstate
atl_covolume calls atl_covolume_tocovolume
atl_covolume_1d calls atl_covolume_tocovolume_1d
atl_covolume_2d calls atl_covolume_tocovolume_2d