modg_2d_project_numFluxX_Q – Ateles
modg_2d_project_numFluxX_Q Subroutine
43 statements
Source File
private subroutine modg_2d_project_numFluxX_Q(numFlux, nScalars, maxPolyDegree, length, nElems_fluid, dl_prod, projection)
Projection of the numerical flux in x direction onto the testfunctions for Q_space.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(inout) :: numFlux(:,:,:,:)
The numerical flux on the faces in modal representations. Dimension is (maxPolyDegree+1)^2 , nScalars
integer, intent(in) :: nScalars
The number of scalar variables in your equation system.
integer, intent(in) :: maxPolyDegree
The maximal polynomial degree in each spatial direction.
real(kind=rk), intent(in) :: length
The length of the cubes.
integer, intent(in) :: nElems_fluid
The element index
real(kind=rk), intent(in) :: dl_prod(2,maxPolyDegree+1)
Precomputed dual Legendre products:
real(kind=rk), intent(inout) :: projection(:,:,:)
The numerical flux projected onto the test functions.
Calls
Called by
Call graph
modg_2d_project_numfluxx_q calls ply_facevalleftbndtest, ply_facevalrightbndtest
atl_modg_2d_project_numflux calls modg_2d_project_numfluxx_q
compute_rhs_cubes_modg_2d calls atl_modg_2d_project_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg_2d
atl_compute_rhs calls compute_rhs_cubes