modg_2d_bnd_mirrorPoint – Ateles
modg_2d_bnd_mirrorPoint Subroutine
15 statements
Source File
private subroutine modg_2d_bnd_mirrorPoint(bc, nPoints, time, varSys, currentFace, pointFace, currentLevel)
Function to mirror pointvalues for a given boundary conditions.
Arguments
Type Intent Optional Attributes Name
type(tem_bc_state_type), intent(in) :: bc
The boundary state.
integer, intent(in) :: nPoints
The number of point values to be mirrored.
type(tem_time_type), intent(in) :: time
The current absolute time.
type(tem_varSys_type), intent(in) :: varSys
Global variable system
integer, intent(in) :: currentFace
Current Face to get the correct position in index array
real(kind=rk), intent(inout) :: pointFace(:)
The mirrored isNodalScheme representation.
integer, intent(in) :: currentLevel
current level
Calls
Called by
Call graph
modg_2d_bnd_mirrorpoint calls get_valofindex, tem_startTimer, tem_stopTimer, val
modg_2d_modal_bnd calls modg_2d_bnd_mirrorpoint
modg_2d_nodal_bnd calls modg_2d_bnd_mirrorpoint
atl_modg_2d_bnd calls modg_2d_modal_bnd, modg_2d_nodal_bnd
atl_modg_2d_set_bnd calls atl_modg_2d_bnd
atl_set_covolume_bnd calls atl_modg_2d_bnd
atl_interpolate_elemstate calls atl_set_covolume_bnd
preprocess_rhs_cubes calls atl_modg_2d_set_bnd