modg_compute_project_physFlux – Ateles
modg_compute_project_physFlux Subroutine
132 statements
Source File
private subroutine modg_compute_project_physFlux(mesh, equation, kerneldata, statedata, dirVec, poly_proj, material, scheme, dl_prod, apply_pen, penalizationdata, minLevel, currentLevel, maxLevel, eval_phy, usePenalization)
Uses
atl_scheme_module
atl_project_physflux_module
ply_poly_project_module
ply_leg_diff_module
atl_physFlux_module
ply_oversample_module
atl_modg_LoclinEuler_kernel_module
atl_modg_euler_kernel_module
atl_cube_elem_module
atl_kerneldata_module
atl_materialPrp_module
atl_penalization_module
atl_equation_module
atl_physFluxEuler_module
TODO NA - Move this routine to the atl_modg_kernel_module
Arguments
Type Intent Optional Attributes Name
type(atl_cube_elem_type), intent(in) :: mesh
Descritption of the cubical elements in the mesh
type(atl_Equations_type), intent(in) :: equation
The equation description.
type(atl_kerneldata_type), intent(inout) :: kerneldata
The data of the kernel. Holds the physical fluxes.
type(atl_statedata_type), intent(inout) :: statedata
The representation on the face + representation of the flux.
integer, intent(in) :: dirVec(3,3)
vector for direction indicators
type(ply_poly_project_type) :: poly_proj
Data for projection method
type(atl_material_type), intent(inout) :: material
Material parameters (mu, epsilon) for all elements
type(atl_scheme_type), intent(inout) :: scheme(minLevel:maxLevel)
The parameters of the MODG scheme
real(kind=rk), intent(in) :: dl_prod(:,:)
stored scalar products of the testfunction and anstaz function
type(atl_penalization_pointer_type) :: apply_pen(2)
type(atl_penalizationData_type), intent(inout) :: penalizationdata
integer, intent(in) :: minLevel
integer, intent(in) :: currentLevel
integer, intent(in) :: maxLevel
type(atl_physflux_pointer_type) :: eval_phy(2)
logical, intent(in) :: usePenalization
Flag indicating whether to apply the penalization or not.
When a implicit scheme is used to integrate the penalized parts, this can be used to switch it off here.
Calls
Called by
Call graph
modg_compute_project_physflux calls ply_poly_project_m2n, ply_poly_project_n2m, pnttid, atl_initialize_state_der, atl_modg_project_physflux_testfunc, atl_physfluxeuler, ply_calcdiff_leg, ply_convert2oversample, ply_convertfromoversample, tem_startTimer, tem_stopTimer, vartransformindices
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
atl_modg_project_physflux_testfunc calls modg_prj_pflux1_q_5, modg_prj_pflux1_q_6, modg_prj_pflux2_q_5, modg_prj_pflux2_q_6, modg_prj_pflux3_q_5, modg_prj_pflux3_q_6, modg_project_physflux_p, modg_project_physflux_q
ply_calcdiff_leg calls ply_calcdiff_leg_x_vec, ply_calcdiff_leg_y_vec, ply_calcdiff_leg_z_vec
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
compute_rhs_cubes_modg calls modg_compute_project_physflux
compute_rhs_cubes calls compute_rhs_cubes_modg
atl_compute_rhs calls compute_rhs_cubes
global_corrector_substep calls atl_compute_rhs
imexrk_substep calls atl_compute_rhs
mesh_timestep_euler calls atl_compute_rhs
rk2_substep calls atl_compute_rhs
rk4_substep calls atl_compute_rhs
rktaylor_substep calls atl_compute_rhs