modg_modal_bnd – Ateles
modg_modal_bnd Subroutine
50 statements
Source File
private subroutine modg_modal_bnd(bc, faceOp, poly_proj, equation, normalRot, time, currentFace, currentLevel, nQuadPoints, nDofs, oversamp_dofs, modalFace, faceMaterial)
Set boundary values in a modal way
Arguments
Type Intent Optional Attributes Name
type(atl_boundary_type), intent(in) :: bc
The boundary condition to generate the modal representation for.
real(kind=rk), intent(inout) :: faceOp(:,:)
The modal representation on the face of the neighboring element.
type(ply_poly_project_type), intent(inout) :: poly_proj
Data for the projection methods
type(atl_Equations_type), intent(in) :: equation
The equation system you use.
type(coordRotation_type), intent(in) :: normalRot
Rotation indices to rotate global coordinate system into face normal coordinate system.
type(tem_time_type), intent(in) :: time
The absolute time point.
integer, intent(in) :: currentFace
integer, intent(in) :: currentLevel
the level to compute on
integer, intent(in) :: nQuadPoints
Number of quadurature points and Number of Dofs for the face
integer, intent(in) :: nDofs
Number of quadurature points and Number of Dofs for the face
integer, intent(in) :: oversamp_dofs
Number of quadurature points and Number of Dofs for the face
real(kind=rk), intent(inout) :: modalFace(:,:)
The modal representation on the boundary face.
real(kind=rk), intent(in), optional :: faceMaterial(:,:)
current face to compute on, used for getting index The material of the boundary face. First dimension is the number of points on the face. Second dimension is the number of material parameters.
Calls
Called by
Call graph
modg_modal_bnd calls ply_poly_project_n2m, modg_bnd_extrapolate, modg_bnd_mirrorpoint, ply_convertfromoversample, tem_abort, val
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
modg_bnd_mirrorpoint calls val, get_valofindex, tem_startTimer, tem_stopTimer
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d, ply_pnttoleg_3d, ply_fxt_n2m_1d, ply_fxt_n2m_2d, ply_fxt_n2m_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_pnttoleg_2d calls ply_pnttoleg_2d_multvar, ply_pnttoleg_2d_singvar
ply_pnttoleg_3d calls ply_pnttoleg_3d_multvar, ply_pnttoleg_3d_singvar
ply_fxt_n2m_1d calls fxtf_flptld_n2m
ply_fxt_n2m_2d calls fxtf_flptld_n2m
ply_fxt_n2m_3d calls fxtf_flptld_n2m
ply_l2p_trafo_1d calls ply_l2_projection
ply_l2p_trafo_2d calls ply_l2_projection
ply_l2p_trafo_3d calls ply_l2_projection
atl_modg_bnd calls modg_modal_bnd
atl_modg_set_bnd calls atl_modg_bnd
atl_set_covolume_bnd calls atl_modg_bnd
atl_interpolate_elemstate calls atl_set_covolume_bnd, atl_interpolate_elemstate
preprocess_rhs_cubes calls atl_modg_set_bnd
atl_preprocess_rhs calls preprocess_rhs_cubes
atl_covolume_tocovolume calls atl_interpolate_elemstate
atl_covolume_tocovolume_1d calls atl_interpolate_elemstate
atl_covolume_tocovolume_2d calls atl_interpolate_elemstate