modg_1d_project_penalization – Ateles
modg_1d_project_penalization Subroutine
24 statements
Source File
private subroutine modg_1d_project_penalization(nScalars, mesh, maxPolyDegree, kerneldata, penalizationdata)
Projection of the penalization terms (in modal representation) to the test functions.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nScalars
The number scalar variables in the equation system.
type(atl_cube_elem_type), intent(in) :: mesh
The cubical elements.
integer, intent(in) :: maxPolyDegree
The maximal polynomial degree of the modg scheme
type(atl_kerneldata_type), intent(inout) :: kerneldata
The data of the kernel. This one is updated by the projection.
type(atl_penalizationData_type), intent(in) :: penalizationdata
Volumetric data for the penalization
Calls
Called by
Call graph
modg_1d_project_penalization calls nelems, ply_scalproddualleg
modg_1d_project_testfunc_q calls modg_1d_project_penalization
atl_modg_1d_project_testfunc calls modg_1d_project_testfunc_q
compute_rhs_cubes_modg_1d calls atl_modg_1d_project_testfunc
compute_rhs_cubes calls compute_rhs_cubes_modg_1d