modg_2d_project_source_P – Ateles
modg_2d_project_source_P Subroutine
51 statements
Source File
private subroutine modg_2d_project_source_P(nScalars, sourcedata, maxPolyDegree, mesh, kerneldata, currentLevel)
Projection of the source terms (in modal representation) to the test functions.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nScalars
The number scalar variables in the equation system.
type(atl_source_type), intent(in) :: sourcedata
The modal representation of the source
integer, intent(in) :: maxPolyDegree
The maximal polynomial degree of the modg scheme
type(atl_cube_elem_type), intent(in) :: mesh
The cubical elements.
type(atl_kerneldata_type), intent(inout) :: kerneldata
The data of the kernel. This one is updated by the projection.
integer, intent(in) :: currentLevel
The current level
Calls
Called by
Call graph
modg_2d_project_source_p calls ply_scalproddualleg, val
atl_modg_2d_project_source calls modg_2d_project_source_p
compute_rhs_cubes_modg_2d calls atl_modg_2d_project_source
compute_rhs_cubes calls compute_rhs_cubes_modg_2d
atl_compute_rhs calls compute_rhs_cubes