modg_2d_semiRefineFace – Ateles
modg_2d_semiRefineFace Subroutine
32 statements
Source File
private subroutine modg_2d_semiRefineFace(modalRepFace, modg_basis, schemeCoarse, schemeFine, refineDir, fineFaceShift, modalRefined)
that is refined in one of the spatial directions.
Project modal representation on a face to a semi-refined face (i.e. on a face that is refined in one of the spatial directions. The result is a modal representation on the semi-refined element. \n \n The function is executing one of the following projections: \n
  face on current                      semi-refined                            \n
       level                               face                                \n
------------------------ ------------------------ \n | | | | | \n | | refineDir | | | \n | | == 1 | fineFace | fineFace | \n | | -------->> | Shift | Shift | \n | | | == 1 | == 2 | \n | | | | | \n | | | | | \n ------------------------ ------------------------ \n
or:
------------------------ ------------------------ \n | | | | \n | | refineDir | fineFaceShift | \n | | == 2 | == 2 | \n | | -------->> ------------------------ \n | | | | \n | | | fineFaceShift | \n | | | == 1 | \n ------------------------ ------------------------ \n
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: modalRepFace(:,:)
Modal representation of a function on the non-refined face. Dimensions are: (modg%maxPolyDegree+1)^2 for the first dimension and nScalars for the second dimension.
type(ply_modg_basis_type) :: modg_basis
Informations about the polynomial basis of the MODG scheme.
type(atl_modg_2d_scheme_type), intent(in) :: schemeCoarse
The parameters of your MODG scheme on the coarse level.
type(atl_modg_2d_scheme_type), intent(in) :: schemeFine
The parameters of your MODG scheme on the fine level.
integer, intent(in) :: refineDir
The direction of the semi-refinement. Either 1 or 2. Have a look at the function description.
integer, intent(in) :: fineFaceShift
The semi-refined element you want to obtain.
real(kind=rk), intent(inout) :: modalRefined(:,:)
The modal representation of modalRepFace restricted to the semi-refined element.
Called by
Call graph
atl_modg_2d_coarsetofineface calls modg_2d_semirefineface
preprocess_rhs_cubes calls atl_modg_2d_coarsetofineface
atl_preprocess_rhs calls preprocess_rhs_cubes
global_corrector_substep calls atl_preprocess_rhs
imexrk_substep calls atl_preprocess_rhs
mesh_timestep_euler calls atl_preprocess_rhs
rk2_substep calls atl_preprocess_rhs
rk4_substep calls atl_preprocess_rhs
rktaylor_substep calls atl_preprocess_rhs