modg_2d_modal_bnd – Ateles
modg_2d_modal_bnd Subroutine
63 statements
Source File
private subroutine modg_2d_modal_bnd(bc, faceOp, poly_proj, equation, normalRot, time, currentFace, currentLevel, nquadpoints, ndofs, oversamp_dofs, modalFace, faceMaterial)
Set boundary values in a modal way
usually generic call to convertFromOversample
Arguments
Type Intent Optional Attributes Name
type(atl_boundary_type), intent(in) :: bc
The boundary condition to generate the modal representation for.
real(kind=rk), intent(inout) :: faceOp(:,:)
The modal representation on the face of the neighboring element.
type(ply_poly_project_type), intent(inout) :: poly_proj
The parameters for projection method.
type(atl_Equations_type), intent(in) :: equation
The equation system you use.
type(coordRotation_type), intent(in) :: normalRot
Rotation indices to rotate global coordinate system into face normal coordinate system.
type(tem_time_type), intent(in) :: time
The absolute time point.
integer, intent(in) :: currentFace
Current Face to compute
integer, intent(in) :: currentLevel
the level to compute on
integer, intent(in) :: nquadpoints
integers for allocation of temp arrays, depend on number of quadrature points and for modal values number of dofs
integer, intent(in) :: ndofs
integers for allocation of temp arrays, depend on number of quadrature points and for modal values number of dofs
integer, intent(in) :: oversamp_dofs
integers for allocation of temp arrays, depend on number of quadrature points and for modal values number of dofs
real(kind=rk), intent(inout) :: modalFace(:,:)
result of the bnd routine, modal coefficent on the boundary faces
real(kind=rk), intent(in), optional :: faceMaterial(:,:)
The material of the boundary face. First dimension is the number of points on the face. Second dimension is the number of material parameters.
Calls
Called by
Call graph
modg_2d_modal_bnd calls ply_poly_project_n2m, modg_2d_bnd_extrapolate, modg_2d_bnd_mirrorpoint, tem_abort, val
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
modg_2d_bnd_mirrorpoint calls val, get_valofindex, tem_startTimer, tem_stopTimer
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d, ply_pnttoleg_3d, ply_fxt_n2m_1d, ply_fxt_n2m_2d, ply_fxt_n2m_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_pnttoleg_2d calls ply_pnttoleg_2d_multvar, ply_pnttoleg_2d_singvar
ply_pnttoleg_3d calls ply_pnttoleg_3d_multvar, ply_pnttoleg_3d_singvar
ply_fxt_n2m_1d calls fxtf_flptld_n2m
ply_fxt_n2m_2d calls fxtf_flptld_n2m
ply_fxt_n2m_3d calls fxtf_flptld_n2m
ply_l2p_trafo_1d calls ply_l2_projection
ply_l2p_trafo_2d calls ply_l2_projection
ply_l2p_trafo_3d calls ply_l2_projection
atl_modg_2d_bnd calls modg_2d_modal_bnd
atl_modg_2d_set_bnd calls atl_modg_2d_bnd
atl_set_covolume_bnd calls atl_modg_2d_bnd
atl_interpolate_elemstate calls atl_set_covolume_bnd, atl_interpolate_elemstate
preprocess_rhs_cubes calls atl_modg_2d_set_bnd
atl_preprocess_rhs calls preprocess_rhs_cubes
atl_covolume_tocovolume calls atl_interpolate_elemstate
atl_covolume_tocovolume_1d calls atl_interpolate_elemstate
atl_covolume_tocovolume_2d calls atl_interpolate_elemstate