modg_nerplanck_physFlux_pre – Ateles
modg_nerplanck_physFlux_pre Subroutine
96 statements
Source File
private subroutine modg_nerplanck_physFlux_pre(mesh, equation, statedata, scheme)
Calculate the projection of the physical flux for the MODG scheme and Nernst-Planck equation.
Arguments
Type Intent Optional Attributes Name
type(atl_cube_elem_type) :: mesh
The mesh you are working with.
type(atl_Equations_type) :: equation
The equation you solve.
type(atl_statedata_type) :: statedata
THe state if the equation
type(atl_modg_scheme_type), intent(in) :: scheme
Parameters of the modal dg scheme
Calls
Called by
Call graph
modg_nerplanck_physflux_pre calls atl_nerplanck_physflux_preprocess, nelems, ply_scalproddualleg, ply_scalprodduallegdiff
atl_nerplanck_physflux_preprocess calls nerplanck_physflux_diffusiveflux
preprocess_modg_nerplanck_kernel calls modg_nerplanck_physflux_pre
atl_preprocess_modg_nerplanck_kernel calls preprocess_modg_nerplanck_kernel