modg_1d_bnd_mirrorModalConst – Ateles
modg_1d_bnd_mirrorModalConst Function
5 statements
Source File
private function modg_1d_bnd_mirrorModalConst(st_fun) result(modalFace)
Function to mirror a modal representation around a given boundary condition in modal space.
Arguments
Type Intent Optional Attributes Name
type(tem_spacetime_fun_type), intent(in) :: st_fun
List of constant spacetime functions
Return Value real(kind=rk), (1)
The mirrored modal representation.
Called by
Call graph
modg_1d_modal_bnd calls modg_1d_bnd_mirrormodalconst
atl_modg_1d_bnd calls modg_1d_modal_bnd
atl_modg_1d_set_bnd calls atl_modg_1d_bnd
atl_set_covolume_bnd calls atl_modg_1d_bnd
atl_interpolate_elemstate calls atl_set_covolume_bnd
preprocess_rhs_cubes calls atl_modg_1d_set_bnd