modg_2d_invMassMatrix_P – Ateles
modg_2d_invMassMatrix_P Subroutine
36 statements
Source File
private subroutine modg_2d_invMassMatrix_P(mesh, kerneldata, scheme, nElems)
Applies the inverse of the mass matrix for a 2D scheme in P_space.
Arguments
Type Intent Optional Attributes Name
type(atl_cube_elem_type) :: mesh
The mesh you are working with.
type(atl_kerneldata_type) :: kerneldata
The data of the kernel.
type(atl_modg_2d_scheme_type), intent(in) :: scheme
Parameters of the modal dg scheme
integer, intent(in) :: nElems
Called by
Call graph
atl_modg_2d_invmassmatrix calls modg_2d_invmassmatrix_p
postprocess_rhs_cubes calls atl_modg_2d_invmassmatrix
atl_postprocess_rhs calls postprocess_rhs_cubes
global_corrector_substep calls atl_postprocess_rhs
imexrk_substep calls atl_postprocess_rhs
mesh_timestep_euler calls atl_postprocess_rhs
rk2_substep calls atl_postprocess_rhs
rk4_substep calls atl_postprocess_rhs
rktaylor_substep calls atl_postprocess_rhs