modg_2d_bnd_extrapolate – Ateles
modg_2d_bnd_extrapolate Function
7 statements
Source File
private function modg_2d_bnd_extrapolate(nVals, faceOp) result(modalFace)
Function to extrapolate face values for a given boundary condition in physical or modal space.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nVals
The number of coefficients to extrapolate
real(kind=rk), intent(in) :: faceOp(:)
Modal representation on the face of the neighboring element.
Return Value real(kind=rk), allocatable, (:)
The extrapolated modal representation.
Called by
Call graph
modg_2d_modal_bnd calls modg_2d_bnd_extrapolate
modg_2d_nodal_bnd calls modg_2d_bnd_extrapolate
atl_modg_2d_bnd calls modg_2d_modal_bnd, modg_2d_nodal_bnd
atl_modg_2d_set_bnd calls atl_modg_2d_bnd
atl_set_covolume_bnd calls atl_modg_2d_bnd
atl_interpolate_elemstate calls atl_set_covolume_bnd
preprocess_rhs_cubes calls atl_modg_2d_set_bnd