modg_2d_viscRans_oneDim_numFlux – Ateles
modg_2d_viscRans_oneDim_numFlux Subroutine
71 statements
Source File
private subroutine modg_2d_viscRans_oneDim_numFlux(equation, facedata, scheme, faces, faceDir, poly_proj, elemLength)
Numerical flux calculation for viscous part of the RANS equation across the faces in a single spatial direction.
Arguments
Type Intent Optional Attributes Name
type(atl_Equations_type), intent(in) :: equation
The equation you solve.
type(atl_facedata_type), intent(inout) :: facedata
The face state if the equation
type(atl_modg_2d_scheme_type), intent(in) :: scheme
Parameters of the modal dg scheme
type(tem_faceIterator_type), intent(in) :: faces
The faces to calculate the fluxes for.
integer, intent(in) :: faceDir
The spatial direction of the faces you calc the fluxes for, use the following: 1 --> x direction. \n 2 --> y direction. \n 3 --> z direction.
type(ply_poly_project_type), intent(inout) :: poly_proj
Parameter for used projection
real(kind=rk), intent(in) :: elemLength
The length of an element
Calls
Called by
Call graph
modg_2d_viscrans_onedim_numflux calls dertransformindices, ply_poly_project_m2n, ply_poly_project_n2m, atl_get_penaltyip_2d, atl_viscrans_2d, vartransformindices
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
atl_viscrans_2d calls atl_viscphysfluxrans_2d
atl_viscphysfluxrans_2d calls atl_get_lower_bound_turb_disscipation, atl_get_pointwise_velocity_gradient_2d, atl_get_pointwise_visc_stress_tensor_2d
ply_poly_project_m2n_multivar calls ply_legtopnt_2d, ply_legtopnt_3d, ply_fxt_m2n_1d, ply_fxt_m2n_2d, ply_fxt_m2n_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d, ply_pnttoleg_3d, ply_fxt_n2m_1d, ply_fxt_n2m_2d, ply_fxt_n2m_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
atl_modg_2d_filnvrstk_numflux calls modg_2d_viscrans_onedim_numflux
compute_rhs_cubes_modg_2d calls atl_modg_2d_filnvrstk_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg_2d
atl_compute_rhs calls compute_rhs_cubes