modg_project_stabViscNumFluxY_Q – Ateles
modg_project_stabViscNumFluxY_Q Subroutine
187 statements
Source File
private subroutine modg_project_stabViscNumFluxY_Q(numFlux, faceState, equation, maxPolyDegree, length, nElems_fluid, projection, poly_proj)
Projection of the numerical flux in y direction onto the testfunctions.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(inout) :: numFlux(:,:,:,:)
The numerical flux on the faces in modal representations. Dimension is (maxPolyDegree+1)^2 , nScalars
real(kind=rk), intent(inout) :: faceState(:,:,:,:)
The state on the faces in modal representations. Dimension is (maxPolyDegree+1)^2 , nScalars
type(atl_Equations_type), intent(in) :: equation
The equation system under consideration
integer, intent(in) :: maxPolyDegree
The maximal polynomial degree in each spatial direction.
real(kind=rk), intent(in) :: length
The length of the cubes.
integer, intent(in) :: nElems_fluid
The element index
real(kind=rk), intent(inout) :: projection(:,:,:)
The numerical flux projected onto the test functions.
type(ply_poly_project_type), intent(inout) :: poly_proj
Projection for the current level
Calls
Called by
Call graph
modg_project_stabviscnumfluxy_q calls ply_poly_project_m2n, ply_poly_project_n2m, atl_mult_nu12_navierstokes, atl_mult_nu22_navierstokes, atl_mult_nu32_navierstokes, ply_facevalleftbndtest, ply_facevalleftbndtestgrad, ply_facevalrightbndtest, ply_facevalrightbndtestgrad, ply_scalproddualleg, ply_scalprodduallegdiff
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
ply_poly_project_m2n_multivar calls ply_legtopnt_2d, ply_legtopnt_3d, ply_fxt_m2n_1d, ply_fxt_m2n_2d, ply_fxt_m2n_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d, ply_pnttoleg_3d, ply_fxt_n2m_1d, ply_fxt_n2m_2d, ply_fxt_n2m_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
atl_modg_project_numflux calls modg_project_stabviscnumfluxy_q
test_project_stabviscnumflux calls modg_project_stabviscnumfluxy_q
atl_modg_kernel_utests calls test_project_stabviscnumflux
compute_rhs_cubes_modg calls atl_modg_project_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg
atl_compute_rhs calls compute_rhs_cubes