outputAppendResult – Ateles
outputAppendResult Subroutine
10 statements
Source File
private subroutine outputAppendResult(wasAdded, varName)
Outputs the result of appending a variable. If appending was not successful, the program is aborted.
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: wasAdded
The result of the append call
character(len=*), intent(in) :: varName
The name of the variable was appended (or not)
Calls
Called by
Call graph
outputappendresult calls tem_abort
atl_append_euler_2d_consvars calls outputappendresult
atl_append_euler_2d_derivedvars calls outputappendresult
atl_append_euler_2d_primvars calls outputappendresult
atl_init_euler_2d_vars calls atl_append_euler_2d_consvars, atl_append_euler_2d_derivedvars, atl_append_euler_2d_primvars
atl_eqn_euler_init calls atl_init_euler_2d_vars
atl_eqn_nvrstk_init calls atl_init_euler_2d_vars
atl_init_equation calls atl_eqn_euler_init, atl_eqn_nvrstk_init