ply_scalProdLeg – Ateles
ply_scalProdLeg Function
5 statements
Source File
public pure function ply_scalProdLeg(ansFunc) result(scalProd)
Function to calculate the L2 scalar product of a Legendre polynomial with itself on the reference element [-1,+1].
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ansFunc
The Legendre polynomial to calculate the scalar product for. The first Legendre polynomial has index 1.
Return Value real(kind=rk)
The scalar product on the refenece element [-1,+1].
Called by
Call graph
ply_init_l2p calls ply_scalprodleg
ply_init_modg_covolumecoeffs calls ply_scalprodleg
approximate_1d_jump calls ply_scalprodleg, ply_poly_project_fillbody
atl_init_spacebasis calls ply_init_modg_covolumecoeffs
ply_poly_project_fillbody calls ply_init_l2p
ply_l2p_test calls ply_init_l2p
atl_initialize calls atl_init_spacebasis, ply_fill_project_list
check_fpt calls ply_poly_project_fillbody
check_fpt_2d calls ply_poly_project_fillbody
check_fxt_2d calls ply_poly_project_fillbody
check_fxt_3d calls ply_poly_project_fillbody
ply_fill_project_list calls ply_poly_project_fillbody
test_project_stabviscnumflux calls ply_poly_project_fillbody
atl_initialize_program calls atl_initialize
atl_modg_kernel_utests calls test_project_stabviscnumflux
atl_harvesting calls atl_initialize
ply_project_2d_fpt_lobattopoints_test calls check_fpt_2d
ply_project_2d_fpt_test calls check_fpt_2d
ply_project_fpt_lobattopoints_test calls check_fpt
ply_project_fpt_test calls check_fpt
test_fxtd_n2m2n calls check_fxt_2d, check_fxt_3d