ply_calcDiff_leg_1d – Ateles
ply_calcDiff_leg_1d Subroutine
25 statements
Source File
public subroutine ply_calcDiff_leg_1d(legCoeffs, legCoeffsDiff, maxPolyDegree, elemLength)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: legCoeffs(:,:)
real(kind=rk), intent(inout) :: legCoeffsDiff(:,:)
Modal expansion of the derivative of legCoeffs in terms of Legendre modal coefficients. \n First index is the number of modal coefficients. \n Second index is the number of var components \n
integer, intent(in) :: maxPolyDegree
real(kind=rk), intent(in) :: elemLength
The physical length of the element to build the derivatives for.
Called by
Call graph
atl_modg_1d_heat_physflux calls ply_calcdiff_leg_1d
atl_modg_1d_voltoface_grad_q calls ply_calcdiff_leg_1d
atl_op_gradient_forelement calls ply_calcdiff_leg_1d
atl_op_gradientx_forelement calls ply_calcdiff_leg_1d
modg_1d_voltoface_grad_q calls ply_calcdiff_leg_1d
atl_modg_1d_modalvoltomodalface calls modg_1d_voltoface_grad_q, atl_modg_1d_voltoface_grad_q
modg_1d_compute_project_physflux calls atl_modg_1d_heat_physflux
compute_rhs_cubes_modg_1d calls modg_1d_compute_project_physflux
preprocess_rhs_cubes calls atl_modg_1d_modalvoltomodalface
atl_preprocess_rhs calls preprocess_rhs_cubes
compute_rhs_cubes calls compute_rhs_cubes_modg_1d