ply_sampling_adaptive_load – Ateles
ply_sampling_adaptive_load Subroutine
56 statements
Source File
public subroutine ply_sampling_adaptive_load(me, conf, parent)
Load the configuration for adaptive subsampling.
Arguments
Type Intent Optional Attributes Name
type(ply_sampling_adaptive_type), intent(out) :: me
Sampling definition to load.
type(flu_State), intent(in) :: conf
Configuration to read the sampling settings from.
integer, intent(in), optional :: parent
Parent table in which to look for the adaptive sampling settings.
Calls
Called by
Call graph
ply_sampling_adaptive_load calls aot_get_val, ply_filter_element_load, tem_abort, upper_to_lower
ply_filter_element_load calls aot_get_val, tem_abort, upper_to_lower, aot_table_close, aot_table_open
ply_sampling_load calls ply_sampling_adaptive_load
ply_sampled_tracking_load calls ply_sampling_load
atl_load_solver_parameters calls ply_sampled_tracking_load
atl_load_config calls atl_load_solver_parameters