ply_Poly_Transformation – Ateles
ply_Poly_Transformation Subroutine
41 statements
Source File
public subroutine ply_Poly_Transformation(subsamp, dofReduction, mesh, meshData, varDofs, varComps, ndims, refine_tree, new_refine_tree, newMeshData, newVarDofs)
Projection of polynomial data from parent elements to child elements. The projection is done by a direct transformation of the modal coeffiecients to another coordinate system with z=ax+b.
Arguments
Type Intent Optional Attributes Name
type(ply_subsample_type), intent(in) :: subsamp
Parameters for the subsampling
real(kind=rk), intent(in) :: dofReduction(:)
Factor for reduction of degrees of freedom.
type(treelmesh_type), intent(in) :: mesh
The mesh related to meshData.
type(ply_array_type), intent(in) :: meshData(:)
The data for subsampling.
integer, intent(in) :: varDofs(:)
The number of degrees of freedom for every variable.
integer, intent(in) :: varComps(:)
The number of components for every variable.
integer, intent(in) :: ndims
Number of dimensions in the polynomial representation.
logical, intent(in) :: refine_tree(:)
Logical array that marks elements for refinement of the previous sampling level.
logical, intent(in) :: new_refine_tree(:)
Logical array that marks elements for refinement.
type(ply_array_type), intent(out), allocatable :: newMeshData(:)
The subsampled data for new_refine_tree.
integer, intent(out), allocatable :: newVarDofs(:)
The number of dofs for the subsampled data.
Calls
Call graph
ply_poly_transformation calls ply_subsampledata
ply_subsampledata calls ply_projdatatochild, ply_transform_matrix
ply_transform_matrix calls ply_alpha, ply_alpha_beta, ply_alpha_frac, ply_beta