ply_fill_project_list – Ateles
ply_fill_project_list Subroutine
22 statements
Source File
public subroutine ply_fill_project_list(proj_list, dyn_projectArray, scheme_dim)
Fill ups the bodys accroding to the DA.
Arguments
Type Intent Optional Attributes Name
type(ply_poly_project_type), intent(out), allocatable :: proj_list(:)
type(dyn_projectionarray_type), intent(in) :: dyn_projectArray
integer, intent(in) :: scheme_dim
Calls
Called by
Call graph
ply_fill_project_list calls ply_poly_project_fillbody, tem_horizontalSpacer
ply_poly_project_fillbody calls ply_init_fxt, ply_init_l2p, ply_init_legfpt, ply_nodes_create, tem_abort
ply_init_fxt calls fxtf_flptld_init
ply_init_l2p calls tem_abort, ply_gausslegpoints, ply_lagrange_1d, ply_lagrange_define, ply_legendre_1d, ply_scalprodleg
ply_init_legfpt calls fftw_plan_many_r2r, fftw_plan_r2r_1d, ply_fpt_init
ply_nodes_create calls ply_nodes_surface_coords, ply_nodes_volume_coords
fxtf_flptld_init calls fxt_flptld_init, fxt_flptld_wsize, fxt_vecld_new
ply_fpt_init calls ply_l, ply_l_int, ply_m, ply_m_int
ply_lagrange_1d calls ply_lagrange_mode_at
ply_nodes_surface_coords calls ply_point_tensor
ply_nodes_volume_coords calls ply_point_tensor
atl_initialize calls ply_fill_project_list
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program