ply_split_element_1D_test – Ateles
ply_split_element_1D_test Subroutine
53 statements
Source File
private subroutine ply_split_element_1D_test(nModes, success)
Testing the 1D splitting.
We test all combinations, even though a higher number of modes in the children is probably not that relevant, it should still be possible.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nModes
Number of modes in the (1D) polynomials to use in the check.
logical, intent(out) :: success
Indication whether the tests were completed successfully.
Calls
Called by
Call graph
ply_split_element_1d_test calls ply_legendre_1d, ply_split_element_init, ply_split_element_singled
ply_split_element_init calls ply_split_legendre_matrix
ply_split_legendre_matrix calls alpha, alpha_beta, alpha_frac, beta
ply_split_element_test calls ply_split_element_1d_test
ply_split_element_test_prog calls ply_split_element_test