ply_degree_2dof – Ateles
ply_degree_2dof Function
20 statements
Source File
public elemental function ply_degree_2dof(deg, space, nDims) result(nDofs)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: deg
integer, intent(in) :: space
integer, intent(in) :: nDims
Return Value integer
Called by
Call graph
ply_dof_2degree calls ply_degree_2dof
read_legpolyvar_modes calls ply_degree_2dof
atl_generic_frommodal_getelement calls ply_dof_2degree
atl_legpolyvar_append calls read_legpolyvar_modes
atl_kineticenergy_getelement calls atl_generic_frommodal_getelement
atl_lambda2_getelement calls atl_generic_frommodal_getelement
atl_machnumber_getelement calls atl_generic_frommodal_getelement
atl_op_dividevecbyscal_forelement calls atl_generic_frommodal_getelement
atl_op_division_forelement calls atl_generic_frommodal_getelement
atl_pressure_1d_getelement calls atl_generic_frommodal_getelement
atl_pressure_2d_getelement calls atl_generic_frommodal_getelement
atl_pressure_getelement calls atl_generic_frommodal_getelement
atl_qcriterion_getelement calls atl_generic_frommodal_getelement
atl_rans_pressure_getelement calls atl_generic_frommodal_getelement
atl_speedofsound_getelement calls atl_generic_frommodal_getelement
atl_temperature_getelement calls atl_generic_frommodal_getelement