ply_sampling_free_methodData – Ateles
ply_sampling_free_methodData Subroutine
12 statements
Source File
public subroutine ply_sampling_free_methodData(fun)
Free previously allocated methodData of variable.
This routine provides a method to free allocated methodData again.
Arguments
Type Intent Optional Attributes Name
class(tem_varSys_op_type), intent(inout) :: fun
Description of the method to free the data for.
Called by
Call graph
ply_sampled_track_output calls ply_sampling_free_methoddata
atl_initialize_program calls ply_sampled_track_output
atl_solve_program calls ply_sampled_track_output
atl_harvesting calls ply_sampled_track_output
ateles calls atl_initialize_program, atl_solve_program