ply_transfer_dofs – Ateles
ply_transfer_dofs Subroutine
17 statements
Source File
public subroutine ply_transfer_dofs(indat, inspace, indegree, outdat, outspace, outdegree, ndims)
Small helping routine to wrap transfers in all allowed dimensions.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: indat(:)
Input data to transfer to output data.
integer, intent(in) :: inspace
Multi-dimensional polynomial layout of the input data.
Has to be either Q_space or P_space.
integer, intent(in) :: indegree
Maximal polynomial degree in the input data.
real(kind=rk), intent(out) :: outdat(:)
Output data to fill with input data.
integer, intent(in) :: outspace
Multi-dimensional polynomial layout of the output data.
Has to be either Q_space or P_space.
integer, intent(in) :: outdegree
Maximal polynomial degree in the output data.
integer, intent(in) :: ndims
Number of dimensions in the polynomials to transfer
Calls
Called by
Call graph
ply_transfer_dofs calls ply_transfer_dofs_1d, ply_transfer_dofs_2d, ply_transfer_dofs_3d
ply_subres_import_color calls ply_transfer_dofs
serializedata calls ply_transfer_dofs
atl_readrestart calls serializedata
atl_writerestart calls serializedata
atl_initialize calls atl_readrestart
atl_writerestartifnecessary calls atl_writerestart
atl_harvesting calls atl_writerestart, atl_initialize
atl_finalize_program calls atl_writerestartifnecessary
atl_initialize_program calls atl_initialize, atl_writerestartifnecessary
atl_solve_program calls atl_writerestartifnecessary