ply_prj_header_out – Ateles
ply_prj_header_out Subroutine
13 statements
Source File
public subroutine ply_prj_header_out(me, conf)
Load settings to describe a projection method from a Lua table.
Arguments
Type Intent Optional Attributes Name
type(ply_prj_header_type), intent(in) :: me
type(aot_out_type) :: conf
Calls
Call graph
ply_prj_header_out calls aot_out_val, ply_fpt_header_out, ply_fxt_header_out, ply_l2p_header_out
ply_fpt_header_out calls aot_out_val
ply_fxt_header_out calls aot_out_val
ply_l2p_header_out calls aot_out_val