ply_sampling_var_allocate – Ateles
ply_sampling_var_allocate Subroutine
9 statements
Source File
public subroutine ply_sampling_var_allocate(var, nElems, datalen)
Allocate memory for a sampled variable.
Arguments
Type Intent Optional Attributes Name
type(ply_sampling_var_type), intent(inout) :: var
The variable to allocate the space for.
integer, intent(in) :: nElems
Number of elements the data lives in.
integer, intent(in) :: datalen
Size of the container to use for representation of the polynomial data across all elements.
Called by
Call graph
ply_sample_adaptive calls ply_sampling_var_allocate, ply_sampling_varsys_for_track
ply_sampling_varsys_for_track calls ply_sampling_var_allocate
ply_sample_data calls ply_sample_adaptive
ply_sampled_track_output calls ply_sample_data
atl_initialize_program calls ply_sampled_track_output
atl_solve_program calls ply_sampled_track_output
atl_harvesting calls ply_sampled_track_output