ply_init_modg_covolumeCoeffs – Ateles
ply_init_modg_covolumeCoeffs Subroutine
40 statements
Source File
public subroutine ply_init_modg_covolumeCoeffs(nPoints, nFunc, integral)
Integral of combination of all anzatz functions for projection onto finer element
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nPoints
integer, intent(in) :: nFunc
type(ply_modg_covolume_type), intent(out) :: integral
Calls
Called by
Call graph
ply_init_modg_covolumecoeffs calls ply_gausslegpoints, ply_legendre_1d, ply_scalprodleg
atl_init_spacebasis calls ply_init_modg_covolumecoeffs
atl_initialize calls atl_init_spacebasis
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program