ply_sampling_varsys_for_track – Ateles
ply_sampling_varsys_for_track Subroutine
74 statements
Source File
public subroutine ply_sampling_varsys_for_track(varsys, trackInst, mesh, nDims, lvl_degree, sample_varsys, var, time)
Create a variable system for the given tracking instance.
Arguments
Type Intent Optional Attributes Name
type(tem_varSys_type), intent(in) :: varsys
Variable system describing the access to the original data to sample.
type(tem_tracking_instance_type), intent(in) :: trackInst
The tracking object that should be sampled.
type(treelmesh_type), intent(in) :: mesh
Original mesh describing the spatial organisation of the data to sample.
integer, intent(in) :: nDims
Dimensionality of the data to sample.
integer, intent(in) :: lvl_degree(:)
Maximal polynomial degree for each level.
type(tem_varSys_type), intent(out) :: sample_varsys
Variable system for the sampled data.
type(ply_sampling_var_type), pointer :: var(:)
Extracted data for all the variables requested in the given tracking instance.
type(tem_time_type), intent(in) :: time
Point in time to get the data for.
Calls
Called by
Call graph
ply_sampling_varsys_for_track calls get_element, ply_sampling_var_allocate, tem_LevelOf, tem_varSys_init, val
ply_sample_adaptive calls ply_sampling_varsys_for_track
ply_sample_data calls ply_sample_adaptive
ply_sampled_track_output calls ply_sample_data
atl_initialize_program calls ply_sampled_track_output
atl_solve_program calls ply_sampled_track_output
atl_harvesting calls ply_sampled_track_output