ply_legToPnt_lobatto_vec – Ateles
ply_legToPnt_lobatto_vec Subroutine
15 statements
Source File
private subroutine ply_legToPnt_lobatto_vec(fpt, legCoeffs, pntVal, nIndeps)
Vectorizing subroutine to transform Legendre expansion to point values at Chebyshev-Lobatto nodes.
Arguments
Type Intent Optional Attributes Name
class(ply_legFpt_type), intent(inout) :: fpt
real(kind=rk), intent(inout) :: legCoeffs(:)
real(kind=rk), intent(inout) :: pntVal(:)
integer, intent(in) :: nIndeps
Calls
Call graph
ply_legtopnt_lobatto_vec calls fftw_execute_r2r, ply_fpt_exec_striped
fftw_execute_r2r calls tem_abort
ply_fpt_exec_striped calls ply_calculate_coeff_strip