ply_check_legToPnt – Ateles
ply_check_legToPnt Subroutine
36 statements
Source File
subroutine ply_check_legToPnt(blocksize, maxPolyDegree, res)
do iPoint = 1, maxPolyDegree+1 write(,) 'Point: ', chebPnt(iPoint), & & ' FPT: ', pntVal(iPoint), & & ' Ref.: ', refVal(iPoint), & & ' error: ', pntVal(iPoint)-refVal(iPoint) end do
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: blocksize
integer, intent(in) :: maxPolyDegree
real(kind=rk), intent(out) :: res
Calls
Called by
Call graph
ply_check_legtopnt calls ply_fpt_header_define, ply_init_legfpt, ply_legendre_1d
ply_fpt_header_define calls tem_abort
ply_init_legfpt calls fftw_plan_many_r2r, fftw_plan_r2r_1d, ply_fpt_init
ply_fpt_init calls ply_l, ply_l_int, ply_m, ply_m_int
ply_l calls ply_lambda
ply_l_int calls ply_l, ply_lambda
ply_m calls ply_lambda
ply_m_int calls ply_lambda
ply_fpt_test calls ply_check_legtopnt