ply_lagrange_define – Ateles
ply_lagrange_define Function
11 statements
Source File
public function ply_lagrange_define(nPoints, nodeset, values) result(me)
Define a new polynomial in the Lagrange basis.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nPoints
Number of points to define the polynomial.
procedure(ply_nodeset_coords) :: nodeset
The set of nodes where the function assumes the given values.
real(kind=rk), intent(in) :: values(nPoints)
Function values at all nPoints of the nodeset.
Return Value type(ply_lagrange_type)
The newly created Lagrange series describing the polynomial function.
Called by
Call graph
ply_init_l2p calls ply_lagrange_define
ply_lagrange_test calls ply_lagrange_define
ply_poly_project_fillbody calls ply_init_l2p
ply_l2p_test calls ply_init_l2p
check_fpt calls ply_poly_project_fillbody
check_fpt_2d calls ply_poly_project_fillbody
check_fxt_2d calls ply_poly_project_fillbody
check_fxt_3d calls ply_poly_project_fillbody
ply_fill_project_list calls ply_poly_project_fillbody
test_project_stabviscnumflux calls ply_poly_project_fillbody
approximate_1d_jump calls ply_poly_project_fillbody
atl_initialize calls ply_fill_project_list
atl_modg_kernel_utests calls test_project_stabviscnumflux
ply_project_2d_fpt_lobattopoints_test calls check_fpt_2d
ply_project_2d_fpt_test calls check_fpt_2d
ply_project_fpt_lobattopoints_test calls check_fpt
ply_project_fpt_test calls check_fpt
test_fxtd_n2m2n calls check_fxt_2d, check_fxt_3d