ply_prj_init_define – Ateles
ply_prj_init_define Subroutine
9 statements
Source File
public pure subroutine ply_prj_init_define(me, header, maxPolyDegree, basisType)
Define a projection, without filling its body.
Arguments
Type Intent Optional Attributes Name
type(ply_prj_init_type), intent(inout) :: me
type(ply_prj_header_type), intent(in) :: header
integer, intent(in) :: maxPolyDegree
integer, intent(in) :: basisType
Called by
Call graph
check_fpt calls ply_prj_init_define
check_fpt_2d calls ply_prj_init_define
check_fxt_2d calls ply_prj_init_define
check_fxt_3d calls ply_prj_init_define
ply_fill_dynprojectarray calls ply_prj_init_define
atl_load_general_projection calls ply_fill_dynprojectarray
atl_load_subprojection calls ply_fill_dynprojectarray
ply_project_2d_fpt_lobattopoints_test calls check_fpt_2d
ply_project_2d_fpt_test calls check_fpt_2d
ply_project_fpt_lobattopoints_test calls check_fpt
ply_project_fpt_test calls check_fpt
test_fxtd_n2m2n calls check_fxt_2d, check_fxt_3d
atl_load_projection calls atl_load_general_projection, atl_load_subprojection
atl_initialize calls atl_load_projection