ply_filter_element_load – Ateles
ply_filter_element_load Subroutine
62 statements
Source File
public subroutine ply_filter_element_load(me, conf, parent)
Loading parameters for the filtering from the configuration script. This needs to be performed before any call of the actual transformation ply_split_element_1D.
The initialization will compute the transformation matrix for Legendre polynomials with at least nMaxModes. If the initialization was already called before with the same or larger nMaxModes, the matrix will not be changed. Thus, calling this routine will only increase the size of the module variable split_legendre, never decrease it.
Arguments
Type Intent Optional Attributes Name
type(ply_filter_element_type), intent(out) :: me
Data structure that holds the filter parameters.
type(flu_State) :: conf
Lua script to get the filter parameters from.
integer, intent(in), optional :: parent
Table handle to a possible parent, that contains the filter table to load.
Calls
Called by
Call graph
ply_filter_element_load calls aot_get_val, aot_table_close, aot_table_open, tem_abort, upper_to_lower
ply_sampling_adaptive_load calls ply_filter_element_load
ply_sampling_load calls ply_sampling_adaptive_load
ply_sampled_tracking_load calls ply_sampling_load
atl_load_solver_parameters calls ply_sampled_tracking_load