ply_transform_matrix – Ateles
ply_transform_matrix Subroutine
36 statements
Source File
private subroutine ply_transform_matrix(max_modes, v)
Compute the transformation matrix for a projection to the left and right half-interval of Legendre polynomials for the given maximal number of modes.
Note: The transformation matrices to each subinterval are triangular, and the diagonal entries are the same. To save memory both matrices are stored in a single 2 dimensional array of size (max_modes, max_modes).
This matrix only needs to be computed once for a sufficiently high order, as submatices out of it can by used to perform the transformation for any lower polynomial degree.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: max_modes
The maximal number of modes to compute the transformation for.
The resulting matrix v will be max_modes x max_modes large and can be used for the transformation of all polynomials with up to this many modes.
real(kind=rk), intent(out), allocatable :: v(:,:)
The transformation matrix.
Upper triangular matrix is created for shifting and lower triangular for (-1) * shifting. For the right interval we interpret the first index as row index and the second as column. For the left interval this is reverted and we interpret the first index as columns of the matrix.
Calls
Called by
Call graph
ply_transform_matrix calls ply_alpha, ply_alpha_beta, ply_alpha_frac, ply_beta
ply_subsampledata calls ply_transform_matrix
ply_poly_transformation calls ply_subsampledata