ply_nodes_create – Ateles
ply_nodes_create Subroutine
25 statements
Source File
public subroutine ply_nodes_create(me, nodes, faces, nQuadPointsPerDir, ndims)
Initialize points with the Chebyshev quadrature points, 3D
Arguments
Type Intent Optional Attributes Name
type(ply_nodes_header_type), intent(in) :: me
real(kind=rk), intent(out), allocatable :: nodes(:,:)
type(ply_faceNodes_type), intent(out), allocatable :: faces(:,:)
integer, intent(in) :: nQuadPointsPerDir
integer, intent(in) :: ndims
Calls
Called by
Call graph
ply_nodes_create calls ply_nodes_surface_coords, ply_nodes_volume_coords
ply_nodes_surface_coords calls ply_point_tensor
ply_nodes_volume_coords calls ply_point_tensor
ply_poly_project_fillbody calls ply_nodes_create
check_fpt calls ply_poly_project_fillbody
check_fpt_2d calls ply_poly_project_fillbody
check_fxt_2d calls ply_poly_project_fillbody
check_fxt_3d calls ply_poly_project_fillbody
ply_fill_project_list calls ply_poly_project_fillbody
test_project_stabviscnumflux calls ply_poly_project_fillbody
approximate_1d_jump calls ply_poly_project_fillbody
atl_initialize calls ply_fill_project_list
atl_modg_kernel_utests calls test_project_stabviscnumflux
ply_project_2d_fpt_lobattopoints_test calls check_fpt_2d
ply_project_2d_fpt_test calls check_fpt_2d
ply_project_fpt_lobattopoints_test calls check_fpt
ply_project_fpt_test calls check_fpt
test_fxtd_n2m2n calls check_fxt_2d, check_fxt_3d
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize