ply_pntToLeg_single – Ateles
ply_pntToLeg_single Subroutine
19 statements
Source File
private subroutine ply_pntToLeg_single(fpt, pntVal, legCoeffs, nIndeps)
Subroutine to transform point values at Chebyshev nodes to a Legendre expansion.
Arguments
Type Intent Optional Attributes Name
class(ply_legFpt_type), intent(inout) :: fpt
real(kind=rk), intent(inout) :: pntVal(:)
real(kind=rk), intent(inout) :: legCoeffs(:)
integer, intent(in) :: nIndeps
Calls
Call graph
ply_pnttoleg_single calls fftw_execute_r2r, ply_fpt_single
fftw_execute_r2r calls tem_abort
ply_fpt_single calls ply_calculate_coeff_strip