ply_poly_project_n2m_multiVar – Ateles
ply_poly_project_n2m_multiVar Subroutine
53 statements
Source File
private subroutine ply_poly_project_n2m_multiVar(me, dim, nVars, nodal_data, modal_data)
Convert nodal values to nDoFs modes.
Arguments
Type Intent Optional Attributes Name
type(ply_poly_project_type), intent(inout) :: me
integer, intent(in) :: dim
integer, intent(in) :: nVars
real(kind=rk), intent(inout) :: nodal_data(:,:)
real(kind=rk), intent(inout) :: modal_data(:,:)
Calls
Called by
Call graph
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d, ply_pnttoleg_3d, ply_fxt_n2m_1d, ply_fxt_n2m_2d, ply_fxt_n2m_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_pnttoleg_2d calls ply_pnttoleg_2d_multvar, ply_pnttoleg_2d_singvar
ply_pnttoleg_3d calls ply_pnttoleg_3d_multvar, ply_pnttoleg_3d_singvar
ply_fxt_n2m_1d calls fxtf_flptld_n2m
ply_fxt_n2m_2d calls fxtf_flptld_n2m
ply_fxt_n2m_3d calls fxtf_flptld_n2m
ply_l2p_trafo_1d calls ply_l2_projection
ply_l2p_trafo_2d calls ply_l2_projection
ply_l2p_trafo_3d calls ply_l2_projection
fxtf_flptld_n2m calls fxtf_flptld_exp
ply_pnttoleg_2d_multvar calls ply_pnttoleg_2d
ply_pnttoleg_3d_multvar calls ply_pnttoleg_3d
ply_poly_project_n2m calls ply_poly_project_n2m_multivar