ply_sampling_load – Ateles
ply_sampling_load Subroutine
53 statements
Source File
public subroutine ply_sampling_load(me, conf, parent)
This subroutine reads the sampling configuration from the Lua script provided in conf and fills the sampling data in 'me' accordingly.
The data is expected to be stored in a table under the name 'ply_sampling'.
Actually need to do sampling, read in the rest of configuration settings.
Arguments
Type Intent Optional Attributes Name
type(ply_sampling_type), intent(out) :: me
Sampling definition to load.
type(flu_State), intent(in) :: conf
Configuration to read the sampling settings from.
integer, intent(in), optional :: parent
Parent table in which to look for the sampling settings.
Calls
Called by
Call graph
ply_sampling_load calls aot_get_val, aot_table_close, aot_table_open, ply_sampling_adaptive_load, tem_abort, upper_to_lower
ply_sampling_adaptive_load calls aot_get_val, tem_abort, upper_to_lower, ply_filter_element_load
ply_filter_element_load calls aot_get_val, aot_table_close, aot_table_open, tem_abort, upper_to_lower
ply_sampled_tracking_load calls ply_sampling_load
atl_load_solver_parameters calls ply_sampled_tracking_load
atl_load_config calls atl_load_solver_parameters
ateles calls atl_load_config
atl_harvesting calls atl_load_config