ply_calcDiff_leg_2d_normal – Ateles
ply_calcDiff_leg_2d_normal Subroutine
49 statements
Source File
public subroutine ply_calcDiff_leg_2d_normal(legCoeffs, legCoeffsDiff, mPd, nVars, elemLength, iDir, dirVec)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: legCoeffs(:,:)
real(kind=rk), intent(inout) :: legCoeffsDiff(:,:)
Modal expansion of the derivative of legCoeffs in terms of Legendre modal coefficients. \n First index is the number of modal coefficients. \n Second index is the number of velocity components \n Third index is the number of partial derivatives, i.e. 3 in 3D.
integer, intent(in) :: mPd
integer, intent(in) :: nVars
The number of varibales to differentiate
real(kind=rk), intent(in) :: elemLength
The physical length of the element to build the derivatives for.
integer, intent(in) :: iDir
The direction to differentiate
integer, optional :: dirVec(2)
The direction vector for the rotation
Called by
Call graph
atl_modg_2d_heat_physflux calls ply_calcdiff_leg_2d_normal
ply_calcdiff_leg_2d calls ply_calcdiff_leg_2d_normal
atl_modg_2d_voltoface_grad_q calls ply_calcdiff_leg_2d
atl_op_gradient_forelement calls ply_calcdiff_leg_2d
eval_source_rans2d calls ply_calcdiff_leg_2d
modg_2d_compute_project_physflux calls ply_calcdiff_leg_2d
atl_modg_2d_modalvoltomodalface calls atl_modg_2d_voltoface_grad_q
compute_rhs_cubes_modg_2d calls modg_2d_compute_project_physflux
compute_rhs_cubes calls compute_rhs_cubes_modg_2d
preprocess_rhs_cubes calls atl_modg_2d_modalvoltomodalface