ply_init_l2p – Ateles
ply_init_l2p Subroutine
57 statements
Source File
public subroutine ply_init_l2p(l2p, header, degree)
Initialize the transformations via L2 projections.
Arguments
Type Intent Optional Attributes Name
type(ply_l2p_type), intent(out) :: l2p
type(ply_l2p_header_type), intent(in) :: header
integer, intent(in) :: degree
Calls
Called by
Call graph
ply_init_l2p calls ply_gausslegpoints, ply_lagrange_1d, ply_lagrange_define, ply_legendre_1d, ply_scalprodleg, tem_abort
ply_lagrange_1d calls ply_lagrange_mode_at
ply_poly_project_fillbody calls ply_init_l2p
ply_l2p_test calls ply_init_l2p
check_fpt calls ply_poly_project_fillbody
check_fpt_2d calls ply_poly_project_fillbody
check_fxt_2d calls ply_poly_project_fillbody
check_fxt_3d calls ply_poly_project_fillbody
ply_fill_project_list calls ply_poly_project_fillbody
test_project_stabviscnumflux calls ply_poly_project_fillbody
approximate_1d_jump calls ply_poly_project_fillbody
atl_initialize calls ply_fill_project_list
atl_modg_kernel_utests calls test_project_stabviscnumflux
ply_project_2d_fpt_lobattopoints_test calls check_fpt_2d
ply_project_2d_fpt_test calls check_fpt_2d
ply_project_fpt_lobattopoints_test calls check_fpt
ply_project_fpt_test calls check_fpt
test_fxtd_n2m2n calls check_fxt_2d, check_fxt_3d
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize