ply_alpha_frac – Ateles
ply_alpha_frac Function
14 statements
Source File
private function ply_alpha_frac(denominator, numerator) result(alpha_frac)
Quotient of two alpha values.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: denominator
Denominator
integer, intent(in) :: numerator
Numerator
Return Value real(kind=rk)
The quotient of two alpha values.
Called by
Call graph
ply_transform_matrix calls ply_alpha_frac
ply_subsampledata calls ply_transform_matrix
ply_poly_transformation calls ply_subsampledata