ply_subres_import_color – Ateles
ply_subres_import_color Subroutine
95 statements
Source File
public subroutine ply_subres_import_color(me, tree, coloring, iColor, target_degree, target_space, target_dim, subresdat)
Get the subresolution data for all elements for a given color and in the requested format.
Arguments
Type Intent Optional Attributes Name
type(ply_subresolution_type), intent(in) :: me
type(treelmesh_type), intent(in) :: tree
type(tem_color_prop_type), intent(in) :: coloring
integer, intent(in) :: iColor
integer, intent(in) :: target_degree
integer, intent(in) :: target_space
integer, intent(in) :: target_dim
real(kind=rk), intent(out), allocatable :: subresdat(:,:)
Calls
Call graph
ply_subres_import_color calls nelems, newunit, offset, ply_transfer_dofs, ply_transfer_p_dim, tem_abort
ply_transfer_dofs calls ply_transfer_dofs_1d, ply_transfer_dofs_2d, ply_transfer_dofs_3d