ply_prj_header_load – Ateles
ply_prj_header_load Subroutine
51 statements
Source File
public subroutine ply_prj_header_load(me, conf, parent)
Load settings to describe a projection method from a Lua table.
Arguments
Type Intent Optional Attributes Name
type(ply_prj_header_type), intent(out) :: me
type(flu_State) :: conf
integer, intent(in) :: parent
A parent Lua table, in which the boundary conditions are to be found.
Calls
Called by
Call graph
ply_prj_header_load calls aot_get_val, ply_fpt_header_display, ply_fpt_header_load, ply_fxt_header_display, ply_fxt_header_load, ply_l2p_header_display, ply_l2p_header_load, tem_abort, upper_to_lower
ply_fpt_header_load calls aot_get_val, tem_abort, upper_to_lower
ply_fxt_header_load calls aot_get_val, tem_abort
ply_l2p_header_load calls aot_get_val, tem_abort, upper_to_lower
ply_fill_dynprojectarray calls ply_prj_header_load
atl_load_general_projection calls ply_fill_dynprojectarray
atl_load_subprojection calls ply_fill_dynprojectarray
atl_load_projection calls atl_load_general_projection, atl_load_subprojection
atl_initialize calls atl_load_projection