ply_evalLegendreTensPoly – Ateles
ply_evalLegendreTensPoly Subroutine
64 statements
Source File
public subroutine ply_evalLegendreTensPoly(coords, nCoords, maxPolyDegree, basisType, polyVal)
Evaluate three-dimensional tensor product Legendre polynomials (not-normalized) at a given set of coordinates.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: coords(:,:)
Array of coordinates (on the reference element) to evaluate the tensor product polynomials at. First dimension is nCoord, second is 3 for x,y,z component.
integer, intent(in) :: nCoords
The number of coordinates to evaluate the polynomials at.
integer, intent(in) :: maxPolyDegree
The maximum polynomail degree of the MODG scheme.
integer, intent(in) :: basisType
real(kind=rk), intent(out), allocatable :: polyVal(:,:)
The polynomial values. First dimension is the number of tensor product polynomials and the second dimension is the number of points, i.e. nCoords.
Called by
Call graph
atl_op_gradient_forpoint calls ply_evallegendretenspoly
atl_op_gradient_fromindex calls ply_evallegendretenspoly
atl_varsys_getstateforpoint calls ply_evallegendretenspoly
atl_varsys_getstatevalofindex calls ply_evallegendretenspoly