ply_get_quadpoints_faces_2d – Ateles
ply_get_quadpoints_faces_2d Subroutine
8 statements
Source File
public subroutine ply_get_quadpoints_faces_2d(poly_proj, idir, ialign, points)
Arguments
Type Intent Optional Attributes Name
type(ply_poly_project_type), intent(in) :: poly_proj
integer, intent(in) :: idir
integer, intent(in) :: ialign
real(kind=rk), intent(out), allocatable :: points(:,:)
Called by
Call graph
atl_evalfacematerial calls ply_get_quadpoints_faces_2d
atl_init_materialparams calls atl_evalfacematerial
atl_update_materialparams calls atl_evalfacematerial
atl_initialize calls atl_init_materialparams
atl_preprocess_modg_1d_kernel calls atl_update_materialparams
atl_preprocess_modg_2d_kernel calls atl_update_materialparams
atl_preprocess_modg_kernel calls atl_update_materialparams
atl_initialize_program calls atl_initialize
preprocess_local_rhs_cubes calls atl_preprocess_modg_kernel
preprocess_rhs_cubes calls atl_preprocess_modg_1d_kernel, atl_preprocess_modg_2d_kernel, atl_preprocess_modg_kernel
atl_harvesting calls atl_initialize