ply_nodes_volume_coords – Ateles
ply_nodes_volume_coords Subroutine
13 statements
Source File
private subroutine ply_nodes_volume_coords(num_intp_per_direction, nDims, nodeset, points)
Create multidimensional points from given 1D set of nodes in the cubic reference element.
The points will be created by a tensor product of the provided 1d nodeset for the given number of dimensions.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: num_intp_per_direction
Number auf integration points in each direction.
integer, intent(in) :: nDims
Number of dimensions to create the points for.
procedure(ply_nodeset_coords) :: nodeset
Set of node coordinates to use in the element.
real(kind=rk), intent(out), allocatable :: points(:,:)
Resulting list of points. First index runs over all points, second indicates the coordinate dimension (x=1,y=2,z=3).
For ndims smaller than 3, the higher dimensions will be set to 0.
Calls
Called by
Call graph
ply_nodes_volume_coords calls ply_point_tensor
ply_nodes_create calls ply_nodes_volume_coords
ply_poly_project_fillbody calls ply_nodes_create
check_fpt calls ply_poly_project_fillbody
check_fpt_2d calls ply_poly_project_fillbody
check_fxt_2d calls ply_poly_project_fillbody
check_fxt_3d calls ply_poly_project_fillbody
ply_fill_project_list calls ply_poly_project_fillbody
test_project_stabviscnumflux calls ply_poly_project_fillbody
approximate_1d_jump calls ply_poly_project_fillbody
atl_initialize calls ply_fill_project_list
atl_modg_kernel_utests calls test_project_stabviscnumflux
ply_project_2d_fpt_lobattopoints_test calls check_fpt_2d
ply_project_2d_fpt_test calls check_fpt_2d
ply_project_fpt_lobattopoints_test calls check_fpt
ply_project_fpt_test calls check_fpt
test_fxtd_n2m2n calls check_fxt_2d, check_fxt_3d