ply_fpt_exec_striped – Ateles
ply_fpt_exec_striped Subroutine
75 statements
Source File
public subroutine ply_fpt_exec_striped(nIndeps, alph, gam, params)
Convert coefficients of a modal representation in terms of Legendre polynomials to modal coefficients in terms of Chebyshev polynomials.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nIndeps
Number of values that can be computed independently.
real(kind=rk), intent(in) :: alph(:)
Modal coefficients of the Legendre expansion. Size has to be: (1:params%n*indeps,nVars)
The direction which is to be transformed has to run fastest in the array.
real(kind=rk), intent(out) :: gam(:)
Modal coefficients of the Chebyshev expansion. Size has to be: (1:indeps*params%n,nVars)
Note, that the resulting array will have changed layout, and the transformed direction will run slowest in the array.
type(ply_trafo_params_type), intent(inout) :: params
The parameters of the fast polynomial transformation.
Calls
Called by
Call graph
ply_fpt_exec_striped calls ply_calculate_coeff_strip
atl_cheb_spectral_visc_1d calls ply_fpt_exec_striped
ply_legtopnt_lobatto_vec calls ply_fpt_exec_striped
ply_legtopnt_vec calls ply_fpt_exec_striped
ply_pnttoleg_lobatto_vec calls ply_fpt_exec_striped
ply_pnttoleg_vec calls ply_fpt_exec_striped
atl_stabilize calls atl_cheb_spectral_visc_1d
mesh_timestep_euler calls atl_stabilize, mesh_timestep_euler
mesh_timestep_imexrk calls atl_stabilize
mesh_timestep_rk4 calls atl_stabilize
mesh_timestep_rktaylor calls atl_stabilize
mesh_timestep_ssprk2 calls atl_stabilize
atl_harvesting calls atl_stabilize