ply_l2p_trafo_2D – Ateles
ply_l2p_trafo_2D Subroutine
10 statements
Source File
public subroutine ply_l2p_trafo_2D(trafo, projected, original)
Transformation between modal and nodal values in 2D via L2 projection.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: trafo(:,:)
L2 Projection matrix, this determines the direction of the trafo at hand
l2p%leg2node = modal to nodal l2p%node2leg = nodal to modal
real(kind=rk), intent(inout) :: projected(:)
Projected coefficients.
real(kind=rk), intent(inout) :: original(:)
Original coefficients to project.
Calls
Called by
Call graph
ply_l2p_trafo_2d calls ply_l2_projection
ply_poly_project_m2n_multivar calls ply_l2p_trafo_2d
ply_poly_project_n2m_multivar calls ply_l2p_trafo_2d
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar