ply_convertFromOversample – Ateles
ply_convertFromOversample Subroutine
15 statements
Source File
public subroutine ply_convertFromOversample(modalCoeffs, poly_proj, nDim, state, nScalars)
Truncating an oversampled polynomial representation back to the original representation.
Note, that the oversampled array, which is given as an input here is is always a Q-Polynomial representation, while the target truncated state might also be a P-Polynomial.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: modalCoeffs(:,:)
Oversampled modal array for one element
type(ply_poly_project_type), intent(in) :: poly_proj
Data of the projection method
integer, intent(in) :: nDim
The number of dimensions to determine the correct oversampling routine.
real(kind=rk), intent(out) :: state(:,:)
Truncated state for one element obtained from the modalCoeffs
integer, intent(in), optional :: nScalars
The number of scalar variables to convert. If nScalars is not passed to this subroutine, all variables of argument state will be considered by this routine.
Calls
Called by
atl_cons_positivity_preserv w ply_convertFromOversample
w
atl_cons_positivity_preserv_2d w
w
atl_eqn_euler_implicit_pen w
w
atl_eqn_maxwell_implicit_pen w
w
atl_equation_evaluate_source_modal w
w
atl_equation_evaluate_source_nodal w
w
atl_generic_fromModal_getElement w
w
atl_generic_fromNodal_getElement w
w
atl_load_initial_condition w
w
atl_modg_1d_euler_penalization_Const w
w
atl_modg_1d_euler_penalization_NonConst w
w
atl_modg_2d_euler_oneDim_numFlux_const w
w
atl_modg_2d_euler_oneDim_numFlux_nonconst w
w
atl_modg_2d_euler_penalization_const w
w
atl_modg_2d_euler_penalization_NonConst w
w
atl_modg_2d_navierstokes_penalization_const w
w
atl_modg_2d_navierstokes_penalization_Nonconst w
w
atl_modg_euler_oneDim_numFlux_const w
w
atl_modg_euler_oneDim_numFlux_nonconst w
w
atl_modg_euler_penalization_const w
w
atl_modg_euler_penalization_NonConst w
w
atl_modg_maxwell_2d_penalization_NonConst w
w
atl_modg_navierstokes_penalization_const w
w
atl_modg_navierstokes_penalization_nonconst w
w
atl_positivity_preserv w
w
atl_positivity_preserv_2d w
w
check_fxt_3D w
w
compute_physFlux_nonConst w
w
compute_physFlux_nonConst_2d w
w
compute_physFluxDivCor_nonConst w
w
eval_source_rans2D w
w
implicit_update w
w
maxwell_flux_nonconst_cube_vec w
w
maxwell_hc_flux_nonconst_cube_vec w
w
modg_1d_compute_project_physFlux w
w
modg_2d_compute_project_physFlux w
w
modg_2d_nodal_bnd w
w
modg_2d_rans_oneDim_numFlux_const w
w
modg_2d_rans_oneDim_numFlux_nonconst w
w
modg_compute_project_physFlux w
w
modg_modal_bnd w
w
modg_nodal_bnd w
w
Call graph
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d