ply_l – Ateles
ply_l Function
5 statements
Source File
private elemental function ply_l(iReal, jReal) result(lVal)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: iReal
real(kind=rk), intent(in) :: jReal
Return Value real(kind=rk)
Calls
Called by
Call graph
ply_l calls ply_lambda
ply_fpt_init calls ply_l, ply_l_int
ply_l_int calls ply_l
ply_init_legfpt calls ply_fpt_init
check_fwd_bwd calls ply_init_legfpt
ply_check_legtopnt calls ply_init_legfpt
ply_check_legtopnt_2d calls ply_init_legfpt
ply_check_legtopnt_3d calls ply_init_legfpt
ply_check_pnttoleg calls ply_init_legfpt
ply_poly_project_fillbody calls ply_init_legfpt