ply_sampled_track_init – Ateles
ply_sampled_track_init Subroutine
51 statements
Source File
public subroutine ply_sampled_track_init(me, mesh, solver, varSys, bc, stencil, proc, nDofs, nDims)
Initialize the sampled tracking entities.
This is necessary to properly setup the tem_tracking data. It includes building the subtree and the varmap.
Arguments
Type Intent Optional Attributes Name
type(ply_sampled_tracking_type), intent(inout) :: me
Sampled tracking variable to initialize. It has to be configured by ply_sampled_tracking_load beforehand.
type(treelmesh_type), intent(in) :: mesh
The global mesh.
type(tem_solveHead_type), intent(in) :: solver
Information about the solver (used to construct file name strings).
type(tem_varSys_type), intent(in) :: varSys
Global variable system with description of the data to get the tracking variables from.
type(tem_BC_prop_type), intent(in) :: bc
Boundary condition properties, used to identify elements close to the boundary.
type(tem_stencilHeader_type), intent(in), optional :: stencil
Description of the stencil in the numerical scheme.
This is needed to describe elements adjacent to specific boundary labels.
type(tem_comm_env_type), intent(in) :: proc
General communication environment
integer, intent(in) :: nDofs
Number of degrees of freedom to use in the output.
integer, intent(in) :: nDims
Number of dimensions in the polynomial representations.
Calls
Called by
Call graph
ply_sampled_track_init calls config, hvs_output_init, instance, tem_abort, tem_create_varMap, tem_init_tracker, tem_init_tracker_subTree, tem_reduction_spatial_init, val, varname
atl_initialize calls ply_sampled_track_init
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program