ply_gaussLegPoints – Ateles
ply_gaussLegPoints Subroutine
34 statements
Source File
public subroutine ply_gaussLegPoints(x1, x2, x, w, nIntP)
Create Gauss-Legendre integration points and weights for one-dimensional integration on the interval [x1,x2].
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: x1
lower limit of integration interval
real(kind=rk), intent(in) :: x2
upper limit of integration interval
real(kind=rk), intent(out) :: x(:)
The coordinates of the gauss points on the interval [x1,x2]. The array has the length nIntP.
real(kind=rk), intent(out) :: w(:)
The quadrature weights. The array has the length nIntP.
integer, intent(in) :: nIntP
The number of integration points.
Called by
Call graph
ply_init_l2p calls ply_gausslegpoints
ply_init_modg_covolumecoeffs calls ply_gausslegpoints
ply_init_modg_multilevelcoeffs calls ply_gausslegpoints
atl_init_spacebasis calls ply_init_modg_covolumecoeffs, ply_init_modg_multilevelcoeffs
ply_poly_project_fillbody calls ply_init_l2p
approximate_1d_jump calls ply_init_modg_multilevelcoeffs, ply_poly_project_fillbody
ply_l2p_test calls ply_init_l2p
atl_initialize calls atl_init_spacebasis, ply_fill_project_list
check_fpt calls ply_poly_project_fillbody
check_fpt_2d calls ply_poly_project_fillbody
check_fxt_2d calls ply_poly_project_fillbody
check_fxt_3d calls ply_poly_project_fillbody
ply_fill_project_list calls ply_poly_project_fillbody
test_project_stabviscnumflux calls ply_poly_project_fillbody
atl_initialize_program calls atl_initialize
atl_modg_kernel_utests calls test_project_stabviscnumflux
atl_harvesting calls atl_initialize
ply_project_2d_fpt_lobattopoints_test calls check_fpt_2d
ply_project_2d_fpt_test calls check_fpt_2d
ply_project_fpt_lobattopoints_test calls check_fpt
ply_project_fpt_test calls check_fpt
test_fxtd_n2m2n calls check_fxt_2d, check_fxt_3d