ply_calcDiff_leg_x_vec – Ateles
ply_calcDiff_leg_x_vec Subroutine
36 statements
Source File
public subroutine ply_calcDiff_leg_x_vec(legCoeffs, legCoeffsDiff, mPd, nVars, elemLength)
Compute the derivative in X direction for 3D Legendre polynomial.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: legCoeffs(:,:)
real(kind=rk), intent(inout) :: legCoeffsDiff(:,:)
Modal expansion of the derivative of legCoeffs in terms of Legendre modal coefficients. * First index is the number of modal coefficients. * Second index is the number of variable components
integer, intent(in) :: mPd
integer, intent(in) :: nVars
The number of varibales to differentiate
real(kind=rk), intent(in) :: elemLength
The physical length of the element to build the derivatives for.
Called by
Call graph
atl_op_gradientx_forelement calls ply_calcdiff_leg_x_vec
ply_calcdiff_leg calls ply_calcdiff_leg_x_vec
atl_modg_voltoface_grad_q calls ply_calcdiff_leg
atl_op_gradient_forelement calls ply_calcdiff_leg
modg_compute_project_physflux calls ply_calcdiff_leg
atl_modg_modalvoltomodalface calls atl_modg_voltoface_grad_q
compute_rhs_cubes_modg calls modg_compute_project_physflux
compute_rhs_cubes calls compute_rhs_cubes_modg
preprocess_rhs_cubes calls atl_modg_modalvoltomodalface