ply_init_fxt – Ateles
ply_init_fxt Subroutine
8 statements
Source File
public subroutine ply_init_fxt(fxt, header, degree)
Initialize the flpt data structure for fast legendre polynomial transformation via the fxtpack.
Arguments
Type Intent Optional Attributes Name
type(ply_fxt_type), intent(out) :: fxt
Handle to the resulting fast polynomial table.
type(ply_fxt_header_type), intent(in) :: header
integer, intent(in) :: degree
Polynomial degree.
Calls
Called by
Call graph
ply_init_fxt calls fxtf_flptld_init
fxtf_flptld_init calls fxt_flptld_init, fxt_flptld_wsize, fxt_vecld_new
ply_poly_project_fillbody calls ply_init_fxt
check_fpt calls ply_poly_project_fillbody
check_fpt_2d calls ply_poly_project_fillbody
check_fxt_2d calls ply_poly_project_fillbody
check_fxt_3d calls ply_poly_project_fillbody
ply_fill_project_list calls ply_poly_project_fillbody
test_project_stabviscnumflux calls ply_poly_project_fillbody
approximate_1d_jump calls ply_poly_project_fillbody
atl_initialize calls ply_fill_project_list
atl_modg_kernel_utests calls test_project_stabviscnumflux
ply_project_2d_fpt_lobattopoints_test calls check_fpt_2d
ply_project_2d_fpt_test calls check_fpt_2d
ply_project_fpt_lobattopoints_test calls check_fpt
ply_project_fpt_test calls check_fpt
test_fxtd_n2m2n calls check_fxt_2d, check_fxt_3d
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize