ply_scalProdDualLeg – Ateles
ply_scalProdDualLeg Function
12 statements
Source File
public pure function ply_scalProdDualLeg(ansFunc, testFunc) result(scalProd)
Function to calculate the scalar product between a Legendre polynomial (ansatz function) and a dual Legendre polynomial (test function) on the reference element [-1;+1].
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ansFunc
The ansatz function index, there first ansatz function has index 1.
integer, intent(in) :: testFunc
The test function index, there first test function has index 1.
Return Value real(kind=rk)
The scalar product of the two functions.
Called by
Call graph
atl_modg_project_source_p calls ply_scalproddualleg
atl_modg_project_source_q calls ply_scalproddualleg
compute_scalprod_dualleg calls ply_scalproddualleg
modg_1d_project_penalization calls ply_scalproddualleg
modg_1d_project_source_q calls ply_scalproddualleg
modg_2d_project_penalization_q calls ply_scalproddualleg
modg_2d_project_source_p calls ply_scalproddualleg
modg_2d_project_source_q calls ply_scalproddualleg
modg_2d_project_stabviscnumfluxx_q calls ply_scalproddualleg
modg_2d_project_stabviscnumfluxy_q calls ply_scalproddualleg
modg_nerplanck_physflux_pre calls ply_scalproddualleg
modg_nerplanck_x_numflux_pre calls ply_scalproddualleg
modg_nerplanck_y_numflux_pre calls ply_scalproddualleg
modg_nerplanck_z_numflux_pre calls ply_scalproddualleg
modg_project_penalization_q calls ply_scalproddualleg
modg_project_stabviscnumfluxx_q calls ply_scalproddualleg
modg_project_stabviscnumfluxy_q calls ply_scalproddualleg
modg_project_stabviscnumfluxz_q calls ply_scalproddualleg
atl_init_scheme calls compute_scalprod_dualleg
atl_modg_2d_project_numflux calls modg_2d_project_penalization_q, modg_2d_project_stabviscnumfluxx_q, modg_2d_project_stabviscnumfluxy_q
atl_modg_2d_project_source calls modg_2d_project_source_p, modg_2d_project_source_q
atl_modg_project_numflux calls modg_project_penalization_q, modg_project_stabviscnumfluxx_q, modg_project_stabviscnumfluxy_q, modg_project_stabviscnumfluxz_q
atl_modg_project_source calls atl_modg_project_source_p, atl_modg_project_source_q
modg_1d_project_testfunc_q calls modg_1d_project_penalization, modg_1d_project_source_q
preprocess_modg_nerplanck_kernel calls modg_nerplanck_physflux_pre, modg_nerplanck_x_numflux_pre, modg_nerplanck_y_numflux_pre, modg_nerplanck_z_numflux_pre
test_project_stabviscnumflux calls modg_project_stabviscnumfluxx_q, modg_project_stabviscnumfluxy_q, modg_project_stabviscnumfluxz_q