ply_faceValLeftBndAns – Ateles
ply_faceValLeftBndAns Function
5 statements
Source File
public pure function ply_faceValLeftBndAns(ansFunc) result(val)
Returns the value of the non-normalized Legendre polynomial at the left boundary of the reference element, i.e. at -1.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ansFunc
The ansatz function index, first ansatz function has index 1.
Return Value real(kind=rk)
The function value.
Called by
Call graph
atl_modg_1d_voltoface_grad_q calls ply_facevalleftbndans
atl_modg_1d_voltoface_q calls ply_facevalleftbndans
atl_modg_2d_voltoface_grad_q calls ply_facevalleftbndans
atl_modg_2d_voltoface_p calls ply_facevalleftbndans
atl_modg_2d_voltoface_q calls ply_facevalleftbndans
atl_modg_voltoface_grad_q calls ply_facevalleftbndans
atl_modg_voltoface_p calls ply_facevalleftbndans
atl_modg_voltoface_q calls ply_facevalleftbndans
atl_voltoface calls ply_facevalleftbndans
atl_voltoface_1d calls ply_facevalleftbndans
atl_voltoface_2d calls ply_facevalleftbndans
modg_1d_voltoface_grad_q calls ply_facevalleftbndans
modg_1d_voltoface_q calls ply_facevalleftbndans
modg_nerplanck_x_numflux_pre calls ply_facevalleftbndans
modg_nerplanck_y_numflux_pre calls ply_facevalleftbndans
modg_nerplanck_z_numflux_pre calls ply_facevalleftbndans
atl_modg_1d_modalvoltomodalface calls atl_modg_1d_voltoface_grad_q, atl_modg_1d_voltoface_q, modg_1d_voltoface_grad_q, modg_1d_voltoface_q
atl_modg_2d_modalvoltomodalface calls atl_modg_2d_voltoface_grad_q, atl_modg_2d_voltoface_p, atl_modg_2d_voltoface_q
atl_modg_modalvoltomodalface calls atl_modg_voltoface_grad_q, atl_modg_voltoface_p
atl_set_covolume_bnd calls atl_voltoface, atl_voltoface_1d, atl_voltoface_2d
preprocess_modg_nerplanck_kernel calls modg_nerplanck_x_numflux_pre, modg_nerplanck_y_numflux_pre, modg_nerplanck_z_numflux_pre
atl_preprocess_modg_nerplanck_kernel calls preprocess_modg_nerplanck_kernel
atl_interpolate_elemstate calls atl_set_covolume_bnd, atl_interpolate_elemstate
preprocess_rhs_cubes calls atl_modg_1d_modalvoltomodalface, atl_modg_2d_modalvoltomodalface, atl_modg_modalvoltomodalface
atl_preprocess_rhs calls preprocess_rhs_cubes
atl_covolume_tocovolume calls atl_interpolate_elemstate
atl_covolume_tocovolume_1d calls atl_interpolate_elemstate
atl_covolume_tocovolume_2d calls atl_interpolate_elemstate