ply_scalProdDualLegDiff – Ateles
ply_scalProdDualLegDiff Function
10 statements
Source File
public pure function ply_scalProdDualLegDiff(ansFunc, testFunc) result(scalProd)
Function to calculate the scalar product between a Legendre polynomial (ansatz function) and a differentiated dual Legendre polynomial (test function) on the reference element [-1;+1].
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ansFunc
The ansatz function index, there first ansatz function has index 1.
integer, intent(in) :: testFunc
The test function index, there first test function has index 1.
Return Value real(kind=rk)
The scalar product of the two functions.
Called by
Call graph
compute_scalprod_dualleg calls ply_scalprodduallegdiff
modg_1d_project_physfluxx_q calls ply_scalprodduallegdiff
modg_2d_project_physfluxx_p calls ply_scalprodduallegdiff
modg_2d_project_physfluxx_q calls ply_scalprodduallegdiff
modg_2d_project_physfluxy_p calls ply_scalprodduallegdiff
modg_2d_project_physfluxy_q calls ply_scalprodduallegdiff
modg_2d_project_stabviscnumfluxx_q calls ply_scalprodduallegdiff
modg_2d_project_stabviscnumfluxy_q calls ply_scalprodduallegdiff
modg_nerplanck_physflux_pre calls ply_scalprodduallegdiff
modg_project_physflux_p calls ply_scalprodduallegdiff
modg_project_physflux_q calls ply_scalprodduallegdiff
modg_project_stabviscnumfluxx_q calls ply_scalprodduallegdiff
modg_project_stabviscnumfluxy_q calls ply_scalprodduallegdiff
modg_project_stabviscnumfluxz_q calls ply_scalprodduallegdiff
atl_init_scheme calls compute_scalprod_dualleg
atl_modg_1d_project_physflux_testfunc calls modg_1d_project_physfluxx_q
atl_modg_2d_project_numflux calls modg_2d_project_stabviscnumfluxx_q, modg_2d_project_stabviscnumfluxy_q
atl_modg_2d_project_physflux_testfunc calls modg_2d_project_physfluxx_p, modg_2d_project_physfluxx_q, modg_2d_project_physfluxy_p, modg_2d_project_physfluxy_q
atl_modg_project_numflux calls modg_project_stabviscnumfluxx_q, modg_project_stabviscnumfluxy_q, modg_project_stabviscnumfluxz_q
atl_modg_project_physflux_testfunc calls modg_project_physflux_p, modg_project_physflux_q
preprocess_modg_nerplanck_kernel calls modg_nerplanck_physflux_pre
test_project_stabviscnumflux calls modg_project_stabviscnumfluxx_q, modg_project_stabviscnumfluxy_q, modg_project_stabviscnumfluxz_q
atl_preprocess_modg_nerplanck_kernel calls preprocess_modg_nerplanck_kernel
atl_init_elem_container calls atl_init_scheme
atl_modg_kernel_utests calls test_project_stabviscnumflux
compute_rhs_cubes_modg calls atl_modg_project_numflux
compute_rhs_cubes_modg_2d calls atl_modg_2d_project_numflux
modg_1d_compute_project_physflux calls atl_modg_1d_project_physflux_testfunc
modg_2d_compute_project_physflux calls atl_modg_2d_project_physflux_testfunc
modg_compute_project_physflux calls atl_modg_project_physflux_testfunc