ply_init_modg_multilevelCoeffs – Ateles
ply_init_modg_multilevelCoeffs Subroutine
30 statements
Source File
public subroutine ply_init_modg_multilevelCoeffs(nPoints, nFunc, integral)
Integral of combination of all anzatz functions for projection onto finer element
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nPoints
integer, intent(in) :: nFunc
type(ply_modg_refine_type), intent(out) :: integral
Calls
Called by
Call graph
ply_init_modg_multilevelcoeffs calls ply_gausslegpoints, ply_legendre_1d
atl_init_spacebasis calls ply_init_modg_multilevelcoeffs
approximate_1d_jump calls ply_init_modg_multilevelcoeffs
atl_initialize calls atl_init_spacebasis
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program