ply_fxt_header_load – Ateles
ply_fxt_header_load Subroutine
15 statements
Source File
public subroutine ply_fxt_header_load(me, conf, thandle)
Load settings to describe a projection method from a Lua table.
\todo Check, wether Lobatto Points could be used with FXTPACK. call aot_get_val(L = conf, & & thandle = thandle, & & key = 'lobattoPoints', & & val = me%nodes_header%lobattoPoints, & & ErrCode = iError, & & default = .false.)
Arguments
Type Intent Optional Attributes Name
type(ply_fxt_header_type), intent(out) :: me
type(flu_State) :: conf
integer, intent(in) :: thandle
Calls
Called by
Call graph
ply_fxt_header_load calls aot_get_val, tem_abort
ply_prj_header_load calls ply_fxt_header_load
ply_fill_dynprojectarray calls ply_prj_header_load
atl_load_general_projection calls ply_fill_dynprojectarray
atl_load_subprojection calls ply_fill_dynprojectarray
atl_load_projection calls atl_load_general_projection, atl_load_subprojection