ply_calculate_coeff_strip – Ateles
ply_calculate_coeff_strip Subroutine
478 statements
Source File
private subroutine ply_calculate_coeff_strip(n, s, gam, matrix, alph, nDiagonals, block_offset, remainder, strip_lb, strip_ub, subblockingWidth)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
integer, intent(in) :: s
real(kind=rk), intent(inout) :: gam(:)
Modal coefficients of the Chebyshev expansion. Size has to be: (1:indeps*params%n,nVars)
Note, that the resulting array will have changed layout, and the transformed direction will run slowest in the array.
real(kind=rk), intent(in) :: matrix(:,:)
The arraz that holds the coefficients to calculate.
real(kind=rk), intent(in) :: alph(:)
Modal coefficients of the Legendre expansion. Size has to be: (1:params%n*indeps,nVars)
The direction which is to be transformed has to run fastest in the array.
integer, intent(in) :: nDiagonals
The number of diagonals to calculcate
integer, intent(in) :: block_offset
The offset of the block relative to the origin of the whole matrix.
integer, intent(in) :: remainder
The diagonals that are not covered by any block.
integer, intent(in) :: strip_lb
The lower bound of the strip to calculate.
integer, intent(in) :: strip_ub
The upper bound of the strip to calculate.
integer, intent(in) :: subblockingWidth
The subblocking width defines the size of the blocking of the diagonal strides, i.e. in y direction. This subblocking is used to get a better cache locality.
Called by
Call graph
ply_fpt_exec calls ply_calculate_coeff_strip
ply_fpt_exec_striped calls ply_calculate_coeff_strip
ply_fpt_single calls ply_calculate_coeff_strip
atl_cheb_spectral_visc_1d calls ply_fpt_exec_striped
ply_legtopnt_lobatto_single calls ply_fpt_single
ply_legtopnt_lobatto_vec calls ply_fpt_exec_striped
ply_legtopnt_single calls ply_fpt_single
ply_legtopnt_vec calls ply_fpt_exec_striped
ply_pnttoleg_lobatto_single calls ply_fpt_single
ply_pnttoleg_lobatto_vec calls ply_fpt_exec_striped
ply_pnttoleg_single calls ply_fpt_single
ply_pnttoleg_vec calls ply_fpt_exec_striped
atl_stabilize calls atl_cheb_spectral_visc_1d
mesh_timestep_euler calls atl_stabilize
mesh_timestep_imexrk calls atl_stabilize
mesh_timestep_rk4 calls atl_stabilize
mesh_timestep_rktaylor calls atl_stabilize
mesh_timestep_ssprk2 calls atl_stabilize
atl_harvesting calls atl_stabilize