ply_faceValLeftBndTestGrad – Ateles
ply_faceValLeftBndTestGrad Function
9 statements
Source File
public pure function ply_faceValLeftBndTestGrad(testFunc) result(val)
Returns the value of the derivaitve of the dual Legendre polynomial at the left boundary of the reference element, i.e. at -1.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: testFunc
The ansatz function index, first test function has index 1.
Return Value real(kind=rk)
The function value.
Called by
Call graph
modg_2d_project_stabviscnumfluxx_q calls ply_facevalleftbndtestgrad
modg_2d_project_stabviscnumfluxy_q calls ply_facevalleftbndtestgrad
modg_project_stabviscnumfluxx_q calls ply_facevalleftbndtestgrad
modg_project_stabviscnumfluxy_q calls ply_facevalleftbndtestgrad
modg_project_stabviscnumfluxz_q calls ply_facevalleftbndtestgrad
atl_modg_2d_project_numflux calls modg_2d_project_stabviscnumfluxx_q, modg_2d_project_stabviscnumfluxy_q
atl_modg_project_numflux calls modg_project_stabviscnumfluxx_q, modg_project_stabviscnumfluxy_q, modg_project_stabviscnumfluxz_q
test_project_stabviscnumflux calls modg_project_stabviscnumfluxx_q, modg_project_stabviscnumfluxy_q, modg_project_stabviscnumfluxz_q
atl_modg_kernel_utests calls test_project_stabviscnumflux
compute_rhs_cubes_modg calls atl_modg_project_numflux
compute_rhs_cubes_modg_2d calls atl_modg_2d_project_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg, compute_rhs_cubes_modg_2d