ply_sample_data – Ateles
ply_sample_data Subroutine
263 statements
Source File
public subroutine ply_sample_data(me, orig_mesh, orig_bcs, varsys, var_degree, lvl_degree, var_space, ndims, trackInst, trackConfig, time, new_mesh, resvars)
Sampling polynomial data from a given array and mesh to a new mesh with a new data array, where just a single degree of freedom per element is used.
Arguments
Type Intent Optional Attributes Name
type(ply_sampling_type), intent(in) :: me
A ply_sampling_type to describe the sampling method.
type(treelmesh_type), intent(in) :: orig_mesh
The original mesh to be refined.
type(tem_BC_prop_type), intent(in) :: orig_bcs
Boundary conditions for the original mesh.
type(tem_varSys_type), intent(in) :: varsys
integer, intent(in) :: var_degree(:)
Maximal polynomial degree for each variable.
Needs to be matching the variable definition in the variable system.
Todo
Needs to be changed to be an information per element per variable! Possibly by defining a variable in the varsys, providing the degree.
integer, intent(in) :: lvl_degree(:)
Maximal polynomial degree for each level.
integer, intent(in) :: var_space(:)
Polynomial space for each variable.
Needs to be matching the variable definition in the variable system.
integer, intent(in) :: ndims
Number of dimensions in the polynomial representation.
type(tem_tracking_instance_type), intent(in) :: trackInst
type(tem_tracking_config_type), intent(in) :: trackConfig
type(tem_time_type), intent(in) :: time
type(treelmesh_type), intent(out) :: new_mesh
The new mesh with the refined elements.
type(tem_varSys_type), intent(out) :: resvars
Resulting system of variables describing the data in the arrays of subsampled elements.
Calls
Called by
Call graph
ply_sample_data calls free_treelmesh, get_element, ply_legendre_1d, ply_sample_adaptive, tem_CoordOfId, tem_abort, tem_create_subTree_of, tem_create_tree_from_sub, tem_destroy_subTree, tem_refine_global_subtree, tem_varSys_append_stateVar, tem_varSys_init, val
ply_sample_adaptive calls tem_create_subTree_of, tem_create_tree_from_sub, tem_destroy_subTree, tem_refine_global_subtree, tem_varSys_append_stateVar, val, mpi_allreduce, ply_sampling_var_allocate, ply_sampling_var_compute_elemdev, ply_sampling_var_move, ply_sampling_varsys_for_track, ply_split_element_init, property, tem_LevelOf, tem_bc_prop_pos, tem_bc_prop_sublist, tem_subTree_from
ply_sampling_varsys_for_track calls get_element, tem_varSys_init, val, ply_sampling_var_allocate, tem_LevelOf
ply_split_element_init calls ply_split_legendre_matrix
ply_split_legendre_matrix calls alpha, alpha_beta, alpha_frac, beta
ply_sampled_track_output calls ply_sample_data
atl_initialize_program calls ply_sampled_track_output
atl_solve_program calls ply_sampled_track_output
atl_harvesting calls ply_sampled_track_output
ateles calls atl_initialize_program, atl_solve_program