ply_fpt_header_display – Ateles
ply_fpt_header_display Subroutine
21 statements
Source File
public subroutine ply_fpt_header_display(me)
Print the FPT settings to the log output.
Arguments
Type Intent Optional Attributes Name
type(ply_fpt_header_type), intent(in) :: me
Called by
Call graph
ply_prj_header_load calls ply_fpt_header_display
ply_fill_dynprojectarray calls ply_prj_header_load
atl_load_general_projection calls ply_fill_dynprojectarray
atl_load_subprojection calls ply_fill_dynprojectarray
atl_load_projection calls atl_load_general_projection, atl_load_subprojection