ply_QPolyProjection – Ateles
ply_QPolyProjection Subroutine
53 statements
Source File
public subroutine ply_QPolyProjection(subsamp, dofReduction, tree, meshData, varDofs, ndims, varcomps, refine_tree, new_refine_tree, newMeshData, newVarDofs)
Subsampling by L2-Projection of the Q-Tensorproduct Legendre polynomials.
Arguments
Type Intent Optional Attributes Name
type(ply_subsample_type), intent(in) :: subsamp
Parameters for the subsampling.
real(kind=rk), intent(in) :: dofReduction(:)
Factor for reducion of degrees of freedom.
type(treelmesh_type), intent(in) :: tree
The tree the data is written for.
type(ply_array_type), intent(in) :: meshData(:)
The data to sub-sample.
integer, intent(in) :: varDofs(:)
The number of degrees of freedom for each scalar variable.
integer, intent(in) :: ndims
Number of dimensions in the polynomial representation.
integer, intent(in) :: varcomps(:)
Number of components
logical, intent(in) :: refine_tree(:)
Logical array that marks elements for refinement from the last sampling
logical, intent(in) :: new_refine_tree(:)
Logical array that marks elements for refinment.
type(ply_array_type), intent(out), allocatable :: newMeshData(:)
The subsampled data.
integer, intent(out), allocatable :: newVarDofs(:)
The number of dofs for the subsampled dofs.
Calls
Call graph
ply_qpolyprojection calls ply_initqlegprojcoeff, ply_subsampledata, tem_abort
ply_initqlegprojcoeff calls tem_abort, ply_doftoqpoly, ply_qlegonedimcoeff
ply_subsampledata calls ply_projdatatochild
ply_qlegonedimcoeff calls ply_gauleg, ply_legval, ply_qlegsqnorm