ply_legendre_1D – Ateles
ply_legendre_1D Function
15 statements
Source File
public pure function ply_legendre_1D(points, degree) result(one_dim_eval)
Evaluate all 1D Legendre polynomials at a given set of points up to the given degree.
init the first two Legendre polynomials. ... the first Legendre polynomial is 1
... the second Legendre polynomial is x Recursive polynomial evaluation: \f$ n L_{n}(x)= (2n - 1) x L_{n-1}(x) - (n-1)L_{n-2}(x) \f$
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: points(:)
1D points to evaluate.
integer, intent(in) :: degree
Degree up to which to evaluate the polynomials
Return Value real(kind=rk), (degree+1,size(points))
Resulting vector of all mode values at all points
Called by
Call graph
ply_check_legtopnt calls ply_legendre_1d
ply_check_pnttoleg calls ply_legendre_1d
ply_init_l2p calls ply_legendre_1d
ply_init_modg_covolumecoeffs calls ply_legendre_1d
ply_init_modg_multilevelcoeffs calls ply_legendre_1d
ply_sample_data calls ply_legendre_1d
ply_split_element_1d_test calls ply_legendre_1d
ply_split_element_2d_test calls ply_legendre_1d
ply_split_element_3d_test calls ply_legendre_1d
approximate_1d_jump calls ply_legendre_1d, ply_init_modg_multilevelcoeffs
integrateleg_test calls ply_legendre_1d
ply_split_legendre_test_prog calls ply_legendre_1d
atl_init_spacebasis calls ply_init_modg_covolumecoeffs, ply_init_modg_multilevelcoeffs
ply_poly_project_fillbody calls ply_init_l2p
ply_sampled_track_output calls ply_sample_data
ply_split_element_test calls ply_split_element_1d_test, ply_split_element_2d_test, ply_split_element_3d_test
ply_fpt_lobattonodes_test calls ply_check_legtopnt
ply_fpt_test calls ply_check_legtopnt
ply_ifpt_lobattonodes_test calls ply_check_pnttoleg
ply_ifpt_test calls ply_check_pnttoleg
ply_l2p_test calls ply_init_l2p