ply_subresolution_load – Ateles
ply_subresolution_load Subroutine
35 statements
Source File
public subroutine ply_subresolution_load(me, tree, proc, coloring)
Subroutine to load subresolution information for a given tree.
Arguments
Type Intent Optional Attributes Name
type(ply_subresolution_type), intent(out) :: me
type(treelmesh_type), intent(in) :: tree
type(tem_comm_env_type), intent(in) :: proc
type(tem_color_prop_type), intent(in) :: coloring
Calls
Call graph
ply_subresolution_load calls aot_get_val, close_config, tem_abort, tem_open_distconf, tem_subres_prop_load, upper_to_lower