ply_change_poly_space – Ateles
ply_change_poly_space Subroutine
73 statements
Source File
public subroutine ply_change_poly_space(inspace, instate, outstate, maxPolyDeg, nElems, nVars, nDims)
Subroutine to change the polynomial space (Q or P) of an atl_statedata_type from Q-space to P-space and vice versa.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: inspace
Polynomial space of the input state (P_sapce or Q_space)
real(kind=rk), intent(in) :: instate(:,:,:)
States of the variables of the input in polynomial space as prescribed in inspace.
real(kind=rk), intent(inout) :: outstate(:,:,:)
States of the variables of the output.
integer, intent(in) :: maxPolyDeg
integer, intent(in) :: nElems
integer, intent(in) :: nVars
integer, intent(in) :: nDims
Called by
Call graph
atl_modg_2d_heat_physflux calls ply_change_poly_space
atl_modg_2d_modalvoltomodalface calls ply_change_poly_space
atl_modg_2d_project_numflux calls ply_change_poly_space
atl_modg_heat_physflux calls ply_change_poly_space
atl_modg_modalvoltomodalface calls ply_change_poly_space
atl_modg_project_numflux calls ply_change_poly_space
atl_stabilize calls ply_change_poly_space
compute_rhs_cubes_modg calls atl_modg_project_numflux
compute_rhs_cubes_modg_2d calls atl_modg_2d_project_numflux
mesh_timestep_euler calls atl_stabilize, mesh_timestep_euler, atl_preprocess_rhs
mesh_timestep_imexrk calls atl_stabilize
mesh_timestep_rk4 calls atl_stabilize
mesh_timestep_rktaylor calls atl_stabilize
mesh_timestep_ssprk2 calls atl_stabilize
preprocess_rhs_cubes calls atl_modg_2d_modalvoltomodalface, atl_modg_modalvoltomodalface
atl_harvesting calls atl_stabilize
atl_preprocess_rhs calls preprocess_rhs_cubes
compute_rhs_cubes calls compute_rhs_cubes_modg, compute_rhs_cubes_modg_2d
atl_compute_rhs calls compute_rhs_cubes
global_corrector_substep calls atl_preprocess_rhs
imexrk_substep calls atl_preprocess_rhs
rk2_substep calls atl_preprocess_rhs
rk4_substep calls atl_preprocess_rhs
rktaylor_substep calls atl_preprocess_rhs