ply_faceValRightBndTest – Ateles
ply_faceValRightBndTest Function
9 statements
Source File
public pure function ply_faceValRightBndTest(testFunc) result(val)
Returns the value of the dual Legendre polynomial at the right boundary of the reference element, i.e. at +1.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: testFunc
The ansatz function index, first test function has index 1.
Return Value real(kind=rk)
The function value.
Called by
Call graph
modg_1d_project_numfluxx_q calls ply_facevalrightbndtest
modg_2d_project_numfluxx_q calls ply_facevalrightbndtest
modg_2d_project_numfluxy_q calls ply_facevalrightbndtest
modg_2d_project_stabviscnumfluxx_q calls ply_facevalrightbndtest
modg_2d_project_stabviscnumfluxy_q calls ply_facevalrightbndtest
modg_nerplanck_x_numflux_pre calls ply_facevalrightbndtest
modg_nerplanck_y_numflux_pre calls ply_facevalrightbndtest
modg_nerplanck_z_numflux_pre calls ply_facevalrightbndtest
modg_project_numflux_p calls ply_facevalrightbndtest
modg_project_numflux_q calls ply_facevalrightbndtest
modg_project_stabviscnumfluxx_q calls ply_facevalrightbndtest
modg_project_stabviscnumfluxy_q calls ply_facevalrightbndtest
modg_project_stabviscnumfluxz_q calls ply_facevalrightbndtest
atl_modg_2d_project_numflux calls modg_2d_project_numfluxx_q, modg_2d_project_numfluxy_q, modg_2d_project_stabviscnumfluxx_q, modg_2d_project_stabviscnumfluxy_q
atl_modg_project_numflux calls modg_project_numflux_p, modg_project_numflux_q, modg_project_stabviscnumfluxx_q, modg_project_stabviscnumfluxy_q, modg_project_stabviscnumfluxz_q
modg_1d_project_testfunc_q calls modg_1d_project_numfluxx_q
preprocess_modg_nerplanck_kernel calls modg_nerplanck_x_numflux_pre, modg_nerplanck_y_numflux_pre, modg_nerplanck_z_numflux_pre
test_project_stabviscnumflux calls modg_project_stabviscnumfluxx_q, modg_project_stabviscnumfluxy_q, modg_project_stabviscnumfluxz_q
atl_preprocess_modg_nerplanck_kernel calls preprocess_modg_nerplanck_kernel
atl_modg_1d_project_testfunc calls modg_1d_project_testfunc_q
atl_modg_kernel_utests calls test_project_stabviscnumflux
compute_rhs_cubes_modg calls atl_modg_project_numflux
compute_rhs_cubes_modg_2d calls atl_modg_2d_project_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg, compute_rhs_cubes_modg_2d
compute_rhs_cubes_modg_1d calls atl_modg_1d_project_testfunc