ply_legToPnt_2D_multVar – Ateles
ply_legToPnt_2D_multVar Subroutine
10 statements
Source File
private subroutine ply_legToPnt_2D_multVar(fpt, legCoeffs, pntVal, nVars)
Subroutine to transform Legendre expansion to point values at Chebyshev nodes.
Arguments
Type Intent Optional Attributes Name
type(ply_legFpt_type), intent(inout) :: fpt
The FPT parameters.
real(kind=rk), intent(inout) :: legCoeffs(:,:)
The Legendre coefficients to convert to point values (Chebyshev nodes). \attention Although this array serves as input only, it is modified inside of this routine by the underlying FPT algorithm. So, when this routine returns from its call the original values of pntVal will be modified.
real(kind=rk), intent(inout) :: pntVal(:,:)
The resulting point values (Chebyshev nodes).
integer, intent(in) :: nVars
The number of scalar variables to transform.
Calls
Called by
Call graph
ply_legtopnt_2d_multvar calls ply_legtopnt_2d
ply_legtopnt_2d calls ply_legtopnt_2d_multvar, ply_legtopnt_2d_singvar
ply_check_legtopnt_2d calls ply_legtopnt_2d
ply_poly_project_m2n_multivar calls ply_legtopnt_2d
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_fpt_ifpt_2d_multivar_lobattonodes_test calls ply_check_legtopnt_2d
ply_fpt_ifpt_2d_multivar_test calls ply_check_legtopnt_2d
ply_fpt_ifpt_2d_singvar_lobattonodes_test calls ply_check_legtopnt_2d
ply_fpt_ifpt_2d_singvar_test calls ply_check_legtopnt_2d