ply_convert2oversample – Ateles
ply_convert2oversample Subroutine
16 statements
Source File
public subroutine ply_convert2oversample(state, poly_proj, nDim, modalCoeffs, nScalars, ensure_positivity)
Copy a single element state into a larger array and pad it with zeroes.
The additional modes might be necessary for proper dealing with nonlinear operations. Please note, that the oversampled representation is always a Q-Space polynomial.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: state(:,:)
State in a single element, to be oversampled.
type(ply_poly_project_type), intent(in) :: poly_proj
Description of the projection method.
integer, intent(in) :: nDim
The number of dimensions to determine the correct oversampling routine.
real(kind=rk), intent(inout) :: modalCoeffs(:,:)
Oversampled array for modal coefficients from state.
These are always Q-Polynomial representations, as projections only work with those.
integer, intent(in), optional :: nScalars
The number of scalar variables to convert. If nScalars is not passed to this subroutine, all variables of argument state will be considered by this routine.
logical, intent(in), optional :: ensure_positivity(:)
Only use modes up to the point, where we are sure that the resulting polynomial will be positive everywhere. This is an array of logicals for each variable, if not given, the default is false (no positivity ensured).
Calls
Called by
atl_cons_positivity_preserv w ply_convert2oversample
w
atl_cons_positivity_preserv_2d w
w
atl_eqn_euler_implicit_pen w
w
atl_eqn_maxwell_implicit_pen w
w
atl_equation_evaluate_source_nodal w
w
atl_generic_fromModal_getElement w
w
atl_initTimeStepInfo w
w
atl_modg_2d_euler_oneDim_numFlux_const w
w
atl_modg_2d_euler_oneDim_numFlux_nonconst w
w
atl_modg_euler_oneDim_numFlux_const w
w
atl_modg_euler_oneDim_numFlux_nonconst w
w
atl_modg_viscNavierStokes_oneDim_numFlux w
w
atl_physCheck_acoustic w
w
atl_physCheck_acoustic_2d w
w
atl_physCheck_euler w
w
atl_physCheck_euler1d w
w
atl_physCheck_euler2d w
w
atl_physCheck_lineareuler w
w
atl_physCheck_lineareuler_2d w
w
atl_physCheck_Rans w
w
atl_physCheck_Rans_2d w
w
atl_positivity_preserv w
w
atl_positivity_preserv_2d w
w
atl_stabilize w
w
check_fxt_3D w
w
compute_physFlux_nonConst w
w
compute_physFlux_nonConst_2d w
w
compute_physFluxDivCor_nonConst w
w
eval_source_rans2D w
w
implicit_update w
w
maxwell_flux_nonconst_cube_vec w
w
maxwell_hc_flux_nonconst_cube_vec w
w
modg_1d_compute_project_physFlux w
w
modg_2d_compute_project_physFlux w
w
modg_2d_nodal_bnd w
w
modg_2d_rans_oneDim_numFlux_const w
w
modg_2d_rans_oneDim_numFlux_nonconst w
w
modg_compute_project_physFlux w
w
modg_nodal_bnd w
w
Call graph
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d