ply_check_pntToLeg – Ateles
ply_check_pntToLeg Subroutine
36 statements
Source File
subroutine ply_check_pntToLeg(power, res)
do iPoly = 1, maxPolyDegree+1 write(,) 'Poly degree: ', iPoly, & & ' iFPT: ', legVal(iPoly), & & ' Ref.: ', legCoeffs(iPoly), & & ' error: ', legVal(iPoly)-legCoeffs(iPoly) end do
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: power
real(kind=rk), intent(out) :: res
Calls
Called by
Call graph
ply_check_pnttoleg calls ply_fpt_header_define, ply_init_legfpt, ply_legendre_1d
ply_fpt_header_define calls tem_abort
ply_init_legfpt calls fftw_plan_many_r2r, fftw_plan_r2r_1d, ply_fpt_init
ply_fpt_init calls ply_l, ply_l_int, ply_m, ply_m_int
ply_l calls ply_lambda
ply_l_int calls ply_l, ply_lambda
ply_m calls ply_lambda
ply_m_int calls ply_lambda
ply_ifpt_lobattonodes_test calls ply_check_pnttoleg