ply_fpt_header_load – Ateles
ply_fpt_header_load Subroutine
39 statements
Source File
public subroutine ply_fpt_header_load(me, conf, thandle)
Read the FPT configuration options from the provided Lua script in conf.
Arguments
Type Intent Optional Attributes Name
type(ply_fpt_header_type), intent(out) :: me
type(flu_State), intent(inout) :: conf
integer, intent(in) :: thandle
Calls
Called by
Call graph
ply_fpt_header_load calls aot_get_val, tem_abort, upper_to_lower
ply_prj_header_load calls ply_fpt_header_load
ply_fill_dynprojectarray calls ply_prj_header_load
atl_load_general_projection calls ply_fill_dynprojectarray
atl_load_subprojection calls ply_fill_dynprojectarray
atl_load_projection calls atl_load_general_projection, atl_load_subprojection