ply_transfer_dofs_1D – Ateles
ply_transfer_dofs_1D Subroutine
10 statements
Source File
public subroutine ply_transfer_dofs_1D(indat, indegree, outdat, outdegree)
Transfer of degrees of freedom from one polynomial to another in 1D.
If the indat is larger than outdat, the higher modes are truncated. If outdat is larger, higher modes are padded with zeros.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: indat(:)
Input data to transfer to output data.
integer, intent(in) :: indegree
Degree of the input polynomial. There are indegree+1 modes expected in indat.
real(kind=rk), intent(out) :: outdat(:)
Output data to fill with input data.
integer, intent(in) :: outdegree
Degree of the output polynomial. There are outdegree+1 modes expected in outdat.
Called by
Call graph
ply_test_transfer_1d calls ply_transfer_dofs_1d
ply_transfer_dofs calls ply_transfer_dofs_1d
ply_subres_import_color calls ply_transfer_dofs
serializedata calls ply_transfer_dofs
ply_transfer_test calls ply_test_transfer_1d
atl_readrestart calls serializedata
atl_writerestart calls serializedata
atl_initialize calls atl_readrestart
atl_writerestartifnecessary calls atl_writerestart
atl_harvesting calls atl_writerestart