ply_check_legToPnt_2D – Ateles
ply_check_legToPnt_2D Subroutine
30 statements
Source File
subroutine ply_check_legToPnt_2D(power, res)
do iDof = 1, (maxPolyDegree+1)2 write(,) 'Leg coeff ', iDof, ' has error: ', legVal(iDof) - legCoeffs(iDof) end do
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: power
real(kind=rk), intent(out) :: res
Calls
Called by
Call graph
ply_check_legtopnt_2d calls ply_legtopnt_2d, ply_pnttoleg_2d, ply_fpt_header_define, ply_init_legfpt
ply_legtopnt_2d calls ply_legtopnt_2d_multvar, ply_legtopnt_2d_singvar
ply_pnttoleg_2d calls ply_pnttoleg_2d_multvar, ply_pnttoleg_2d_singvar
ply_fpt_header_define calls tem_abort
ply_init_legfpt calls fftw_plan_many_r2r, fftw_plan_r2r_1d, ply_fpt_init
ply_fpt_init calls ply_l, ply_l_int, ply_m, ply_m_int
ply_legtopnt_2d_multvar calls ply_legtopnt_2d
ply_pnttoleg_2d_multvar calls ply_pnttoleg_2d
ply_l calls ply_lambda
ply_l_int calls ply_l, ply_lambda
ply_m calls ply_lambda
ply_m_int calls ply_lambda
ply_fpt_ifpt_2d_singvar_test calls ply_check_legtopnt_2d