ply_sampling_var_move – Ateles
ply_sampling_var_move Subroutine
17 statements
Source File
public subroutine ply_sampling_var_move(source, destination)
Move the variable data from source to destination.
If there is data in destination, it will be discarded. The data in source becomes accessible via destination and source itself gets nullified.
Arguments
Type Intent Optional Attributes Name
type(ply_sampling_var_type), pointer :: source(:)
Variable data to move (and make accessible via destination).
Source itself will be null after moving.
type(ply_sampling_var_type), pointer :: destination(:)
Pointer to refer to the data in source. If destination already contains data, this data will be discarded.
Called by
Call graph
ply_sample_adaptive calls ply_sampling_var_move
ply_sample_data calls ply_sample_adaptive
ply_sampled_track_output calls ply_sample_data
atl_initialize_program calls ply_sampled_track_output
atl_solve_program calls ply_sampled_track_output
atl_harvesting calls ply_sampled_track_output