ply_split_element_test – Ateles
ply_split_element_test Subroutine
19 statements
Source File
public subroutine ply_split_element_test(success)
Testing routine for the functions of this module.
Arguments
Type Intent Optional Attributes Name
logical, intent(out) :: success
Indication whether the tests were completed successfully.
Calls
Called by
Call graph
ply_split_element_test calls ply_split_element_1d_test, ply_split_element_2d_test, ply_split_element_3d_test, ply_split_element_init
ply_split_element_1d_test calls ply_split_element_init, ply_legendre_1d, ply_split_element_singled
ply_split_element_2d_test calls ply_split_element_init, ply_legendre_1d, ply_split_element_2d
ply_split_element_3d_test calls ply_split_element_init, ply_legendre_1d, ply_split_element_3d
ply_split_element_init calls ply_split_legendre_matrix
ply_split_element_2d calls ply_split_element_singled
ply_split_element_3d calls ply_split_element_singled
ply_split_legendre_matrix calls alpha, alpha_beta, alpha_frac, beta
ply_split_element_test_prog calls ply_split_element_test