ply_get_quadpoints_faces_1d – Ateles
ply_get_quadpoints_faces_1d Subroutine
8 statements
Source File
public subroutine ply_get_quadpoints_faces_1d(poly_proj, idir, ialign, points)
Arguments
Type Intent Optional Attributes Name
type(ply_poly_project_type), intent(in) :: poly_proj
integer, intent(in) :: idir
integer, intent(in) :: ialign
real(kind=rk), intent(out), allocatable :: points(:,:)
Called by
Call graph
atl_evalfacematerial calls ply_get_quadpoints_faces_1d
modg_1d_bnd_mirrorpoint calls ply_get_quadpoints_faces_1d
atl_init_materialparams calls atl_evalfacematerial
atl_update_materialparams calls atl_evalfacematerial
modg_1d_modal_bnd calls modg_1d_bnd_mirrorpoint
modg_1d_nodal_bnd calls modg_1d_bnd_mirrorpoint
atl_initialize calls atl_init_materialparams
atl_modg_1d_bnd calls modg_1d_modal_bnd, modg_1d_nodal_bnd
atl_preprocess_modg_1d_kernel calls atl_update_materialparams
atl_preprocess_modg_2d_kernel calls atl_update_materialparams
atl_preprocess_modg_kernel calls atl_update_materialparams
atl_initialize_program calls atl_initialize
atl_modg_1d_set_bnd calls atl_modg_1d_bnd
atl_set_covolume_bnd calls atl_modg_1d_bnd
preprocess_local_rhs_cubes calls atl_preprocess_modg_kernel
preprocess_rhs_cubes calls atl_preprocess_modg_1d_kernel, atl_preprocess_modg_2d_kernel, atl_preprocess_modg_kernel
atl_harvesting calls atl_initialize