ply_fill_dynProjectArray – Ateles
ply_fill_dynProjectArray Subroutine
18 statements
Source File
public subroutine ply_fill_dynProjectArray(proj_pos, dyn_projectionArray, basisType, maxPolyDegree, conf, parent)
Load settings to describe a projection method from a Lua table.
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: proj_pos
type(dyn_projectionarray_type), intent(inout) :: dyn_projectionArray
integer, intent(in) :: basisType
integer, intent(in) :: maxPolyDegree
type(flu_State), intent(in) :: conf
integer, intent(in) :: parent
Calls
Called by
Call graph
ply_fill_dynprojectarray calls append, ply_prj_header_load, ply_prj_init_define
append calls append_da_projection, append_da_vecprojection
ply_prj_header_load calls aot_get_val, ply_fpt_header_display, ply_fpt_header_load, ply_fxt_header_display, ply_fxt_header_load, ply_l2p_header_display, ply_l2p_header_load, tem_abort, upper_to_lower
append_da_projection calls expand, sortedposofval
append_da_vecprojection calls expand
ply_fpt_header_load calls aot_get_val, tem_abort, upper_to_lower
ply_fxt_header_load calls aot_get_val, tem_abort
ply_l2p_header_load calls aot_get_val, tem_abort, upper_to_lower
expand calls expand_da_projection
sortedposofval calls sortposofval_projection
atl_load_general_projection calls ply_fill_dynprojectarray
atl_load_subprojection calls ply_fill_dynprojectarray
atl_load_projection calls atl_load_general_projection, atl_load_subprojection
atl_initialize calls atl_load_projection
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize