ply_point_tensor – Ateles
ply_point_tensor Subroutine
35 statements
Source File
private subroutine ply_point_tensor(nPoints1D, nDims, nodeset, points)
Compute a multi-dimensional tensor for the given set of nodes.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nPoints1D
Number auf integration points in each direction.
integer, intent(in) :: nDims
Number of dimensions to create the points for.
procedure(ply_nodeset_coords) :: nodeset
Set of node coordinates to use in the element.
real(kind=rk), intent(out) :: points(nPoints1D**nDims,nDims)
Resulting list of points. First index runs over all points, second indicates the coordinate dimension (x=1,y=2,z=3).
Called by
Call graph
ply_nodes_surface_coords calls ply_point_tensor
ply_nodes_volume_coords calls ply_point_tensor
ply_nodes_create calls ply_nodes_surface_coords, ply_nodes_volume_coords
ply_poly_project_fillbody calls ply_nodes_create
check_fpt calls ply_poly_project_fillbody
check_fpt_2d calls ply_poly_project_fillbody
check_fxt_2d calls ply_poly_project_fillbody
check_fxt_3d calls ply_poly_project_fillbody
ply_fill_project_list calls ply_poly_project_fillbody
test_project_stabviscnumflux calls ply_poly_project_fillbody
approximate_1d_jump calls ply_poly_project_fillbody