ply_fxt_m2n_2D – Ateles
ply_fxt_m2n_2D Subroutine
19 statements
Source File
public subroutine ply_fxt_m2n_2D(fxt, modal_data, nodal_data, oversamp_degree)
Convert modal data to nodal data in 2D using flpt.
Arguments
Type Intent Optional Attributes Name
type(ply_fxt_type) :: fxt
Description of the Fast Legendre Polynomial Transform
real(kind=rk), intent(inout), target :: modal_data(:)
Modal data
real(kind=rk), intent(inout), target :: nodal_data(:)
Nodal data
integer, intent(in) :: oversamp_degree
Calls
Called by
Call graph
ply_fxt_m2n_2d calls fxtf_flptld_m2n
fxtf_flptld_m2n calls fxtf_flptld_evl
ply_poly_project_m2n_multivar calls ply_fxt_m2n_2d
ply_poly_project_m2n calls ply_poly_project_m2n_multivar