ply_fpt_single – Ateles
ply_fpt_single Subroutine
58 statements
Source File
public subroutine ply_fpt_single(alph, gam, params)
Convert strip of coefficients of a modal representation in terms of Legendre polynomials to modal coefficients in terms of Chebyshev polynomials.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(inout) :: alph(params%n)
Modal coefficients of the Legendre expansion. Size has to be: params%n
The direction which is to be transformed has to run fastest in the array.
real(kind=rk), intent(out) :: gam(params%n)
Modal coefficients of the Chebyshev expansion. Size has to be: params%n
type(ply_trafo_params_type), intent(inout) :: params
The parameters of the fast polynomial transformation.
Calls
Called by
Call graph
ply_fpt_single calls ply_calculate_coeff_strip
ply_legtopnt_lobatto_single calls ply_fpt_single
ply_legtopnt_single calls ply_fpt_single
ply_pnttoleg_lobatto_single calls ply_fpt_single
ply_pnttoleg_single calls ply_fpt_single