ply_split_element_init – Ateles
ply_split_element_init Subroutine
10 statements
Source File
public subroutine ply_split_element_init(nMaxModes)
Initialization of the module. This needs to be performed before any call of the actual transformation ply_split_element_1D.
The initialization will compute the transformation matrix for Legendre polynomials with at least nMaxModes. If the initialization was already called before with the same or larger nMaxModes, the matrix will not be changed. Thus, calling this routine will only increase the size of the module variable split_legendre, never decrease it.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nMaxModes
Maximal number of expected modes to perform the splitting for.
Calls
Called by
Call graph
ply_split_element_init calls ply_split_legendre_matrix
ply_split_legendre_matrix calls alpha, alpha_beta, alpha_frac, beta
ply_sample_adaptive calls ply_split_element_init
ply_split_element_1d_test calls ply_split_element_init
ply_split_element_2d_test calls ply_split_element_init
ply_split_element_3d_test calls ply_split_element_init
ply_split_element_test calls ply_split_element_init, ply_split_element_1d_test, ply_split_element_2d_test, ply_split_element_3d_test
ply_sample_data calls ply_sample_adaptive
ply_split_element_test_prog calls ply_split_element_test
ply_sampled_track_output calls ply_sample_data
atl_initialize_program calls ply_sampled_track_output
atl_solve_program calls ply_sampled_track_output
atl_harvesting calls ply_sampled_track_output