ply_fpt_init – Ateles
ply_fpt_init Subroutine
179 statements
Source File
public subroutine ply_fpt_init(n, params, trafo, blocksize, approx_terms, striplen, subblockingWidth)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
type(ply_trafo_params_type), intent(inout) :: params
integer, intent(in) :: trafo
integer, intent(in), optional :: blocksize
Smallest block that is approximated by approx_terms coefficients.
Please note, that this has to be larger than 2*approx_terms to result in a reduced number of operations. Default is 64.
integer, intent(in), optional :: approx_terms
Number of approximation terms used to compute off-diagonal products.
Defaults to 18, which is the suggested accuracy for double precision.
integer, intent(in) :: striplen
Length to use in vectorization, this is the number of independent matrix multiplications that are to be done simultaneously.
integer, intent(in), optional :: subblockingWidth
The width of the subblocks used during the unrolled base exchange to ensure a better cache usage.
Calls
Called by
Call graph
ply_fpt_init calls ply_l, ply_l_int, ply_m, ply_m_int
ply_l calls ply_lambda
ply_l_int calls ply_l, ply_lambda
ply_m calls ply_lambda
ply_m_int calls ply_lambda
ply_init_legfpt calls ply_fpt_init
check_fwd_bwd calls ply_init_legfpt
ply_check_legtopnt calls ply_init_legfpt
ply_check_legtopnt_2d calls ply_init_legfpt
ply_check_legtopnt_3d calls ply_init_legfpt
ply_check_pnttoleg calls ply_init_legfpt
ply_poly_project_fillbody calls ply_init_legfpt