ply_init_legFpt – Ateles
ply_init_legFpt Subroutine
58 statements
Source File
public subroutine ply_init_legFpt(maxPolyDegree, nIndeps, fpt, header, fft_flags)
Subroutine to initialize the fast polynomial transformation for Legendre expansion.
fpt%planPntToCheb = fftw_plan_r2r_1d(n = n, & & in = tmpIn, & & out = tmpOut, & & kind = FFTW_REDFT10, & & flags = planning_flags) fpt%planPntToCheb = fftw_plan_r2r_1d(n = n, & & in = tmpIn, & & out = tmpOut, & & kind = FFTW_REDFT10, & & flags = planning_flags) fpt%planChebToPnt = fftw_plan_r2r_1d(n = n, & & in = tmpIn, & & out = tmpOut, & & kind = FFTW_REDFT00, & & flags = planning_flags)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: maxPolyDegree
Maximal polynomial degree for the transformation.
integer, intent(in) :: nIndeps
Number of independent values that can be computed simultaneously.
type(ply_legFpt_type), intent(inout) :: fpt
The Fast Polynomial Transformation setting to initialize.
type(ply_fpt_header_type), intent(in) :: header
Configuration settings for the projection.
integer, intent(in), optional :: fft_flags
Planning flags for the FFT.
Configuration to how much time to spend on finding an optimal FFT implementation in the FFTW. See: http://www.fftw.org/doc/Planner-Flags.html#Planner-Flags
Defaults to FFTW_MEASURE.
Calls
Called by
Call graph
ply_init_legfpt calls fftw_plan_many_r2r, fftw_plan_r2r_1d, ply_fpt_init
ply_fpt_init calls ply_l, ply_l_int, ply_m, ply_m_int
ply_l calls ply_lambda
ply_l_int calls ply_l, ply_lambda
ply_m calls ply_lambda
ply_m_int calls ply_lambda
check_fwd_bwd calls ply_init_legfpt
ply_check_legtopnt calls ply_init_legfpt
ply_check_legtopnt_2d calls ply_init_legfpt
ply_check_legtopnt_3d calls ply_init_legfpt
ply_check_pnttoleg calls ply_init_legfpt
ply_poly_project_fillbody calls ply_init_legfpt