ply_split_legendre_test – Ateles
ply_split_legendre_test Subroutine
105 statements
Source File
public subroutine ply_split_legendre_test(success)
A small testing routine to check the functions of this module.
Arguments
Type Intent Optional Attributes Name
logical, intent(out) :: success
Indication whether the tests were completed successfully.
Calls
Called by
Call graph
ply_split_legendre_test calls alpha, alpha_beta, alpha_frac, beta, ply_split_legendre_matrix
ply_split_legendre_matrix calls alpha, alpha_beta, alpha_frac, beta
ply_split_legendre_test_prog calls ply_split_legendre_test