ply_poly_project_fillbody – Ateles
ply_poly_project_fillbody Subroutine
117 statements
Source File
public subroutine ply_poly_project_fillbody(me, proj_init, scheme_dim)
Fill the body of the projection with all required data, ply_poly_project_define has to be used beforehand to set necessary header information.
Initialization/Create of the volume quadrature nodes and the quadrature points on the face
Arguments
Type Intent Optional Attributes Name
type(ply_poly_project_type), intent(inout) :: me
type(ply_prj_init_type), intent(in) :: proj_init
integer, intent(in) :: scheme_dim
Calls
Called by
Call graph
ply_poly_project_fillbody calls ply_init_fxt, ply_init_l2p, ply_init_legfpt, ply_nodes_create, tem_abort
ply_init_fxt calls fxtf_flptld_init
ply_init_l2p calls tem_abort, ply_gausslegpoints, ply_lagrange_1d, ply_lagrange_define, ply_legendre_1d, ply_scalprodleg
ply_init_legfpt calls fftw_plan_many_r2r, fftw_plan_r2r_1d, ply_fpt_init
ply_nodes_create calls ply_nodes_surface_coords, ply_nodes_volume_coords
fxtf_flptld_init calls fxt_flptld_init, fxt_flptld_wsize, fxt_vecld_new
ply_fpt_init calls ply_l, ply_l_int, ply_m, ply_m_int
ply_lagrange_1d calls ply_lagrange_mode_at
ply_nodes_surface_coords calls ply_point_tensor
ply_nodes_volume_coords calls ply_point_tensor
ply_l calls ply_lambda
ply_l_int calls ply_l, ply_lambda
ply_m calls ply_lambda
ply_m_int calls ply_lambda
check_fpt calls ply_poly_project_fillbody
check_fpt_2d calls ply_poly_project_fillbody
check_fxt_2d calls ply_poly_project_fillbody
check_fxt_3d calls ply_poly_project_fillbody
ply_fill_project_list calls ply_poly_project_fillbody
test_project_stabviscnumflux calls ply_poly_project_fillbody
approximate_1d_jump calls ply_poly_project_fillbody
atl_initialize calls ply_fill_project_list
atl_modg_kernel_utests calls test_project_stabviscnumflux
ply_project_2d_fpt_lobattopoints_test calls check_fpt_2d
ply_project_2d_fpt_test calls check_fpt_2d
ply_project_fpt_lobattopoints_test calls check_fpt
ply_project_fpt_test calls check_fpt
test_fxtd_n2m2n calls check_fxt_2d, check_fxt_3d
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program