ply_lagrange_mode_at – Ateles
ply_lagrange_mode_at Function
16 statements
Source File
public function ply_lagrange_mode_at(me, mode, x) result(f)
Evaluate the given Lagrangian mode (which is 1 at coord(mode) and 0 in all other points) at a given point x.
Arguments
Type Intent Optional Attributes Name
type(ply_lagrange_type), intent(in) :: me
The polynomial in Lagrange basis.
integer, intent(in) :: mode
Mode to evaluate at x.
Here mode identifies the polynomial that is 1 in me%coord(mode) and 0 in all other nodes.
real(kind=rk), intent(in) :: x
Coordinate at which the mode is to be evaluated.
Return Value real(kind=rk)
Value of the polynomial at coordinate x.
Called by
Call graph
ply_lagrange_1d calls ply_lagrange_mode_at
ply_lagrange_eval calls ply_lagrange_mode_at
ply_lagrange_test calls ply_lagrange_mode_at, ply_lagrange_eval
ply_init_l2p calls ply_lagrange_1d
ply_poly_project_fillbody calls ply_init_l2p
ply_l2p_test calls ply_init_l2p
check_fpt calls ply_poly_project_fillbody
check_fpt_2d calls ply_poly_project_fillbody
check_fxt_2d calls ply_poly_project_fillbody
check_fxt_3d calls ply_poly_project_fillbody
ply_fill_project_list calls ply_poly_project_fillbody
test_project_stabviscnumflux calls ply_poly_project_fillbody
approximate_1d_jump calls ply_poly_project_fillbody