ply_sampled_tracking_load – Ateles
ply_sampled_tracking_load Subroutine
6 statements
Source File
public subroutine ply_sampled_tracking_load(me, conf)
Load the configuration of sampled tracking objects.
Arguments
Type Intent Optional Attributes Name
type(ply_sampled_tracking_type), intent(out) :: me
Sampled tracking data to load from the config
type(flu_State) :: conf
Lua config to load the tracking from
Calls
Called by
Call graph
ply_sampled_tracking_load calls ply_sampling_load, tem_load_tracking
ply_sampling_load calls aot_get_val, aot_table_close, aot_table_open, ply_sampling_adaptive_load, tem_abort, upper_to_lower
ply_sampling_adaptive_load calls aot_get_val, tem_abort, upper_to_lower, ply_filter_element_load
ply_filter_element_load calls aot_get_val, aot_table_close, aot_table_open, tem_abort, upper_to_lower
atl_load_solver_parameters calls ply_sampled_tracking_load
atl_load_config calls atl_load_solver_parameters
ateles calls atl_load_config
atl_harvesting calls atl_load_config