posofval_projection – Ateles
posofval_projection Function
20 statements
Source File
private function posofval_projection(me, val, nextifnotfound, lower, upper) result(pos)
the actual position of a given value in the dynamic array
most likely this is what you need in codes, using this data structure, it first does the binary search on the sorted values with sortposofval_projection and then returns the looked up position in the original unsorted array, which corresponds to the position returned by the append routine.
Arguments
Type Intent Optional Attributes Name
type(dyn_projectionarray_type), intent(in) :: me
type(ply_prj_init_type), intent(in) :: val
logical, intent(in), optional :: nextifnotfound
flag to indicate, if the position of the next entry in the sorted list should be returned instead, if val is not found.
integer, intent(in), optional :: lower
integer, intent(in), optional :: upper
Return Value integer
Calls
Called by
Call graph
posofval_projection calls sortedposofval
sortedposofval calls sortposofval_projection
positionofval calls posofval_projection