postprocess_rhs_cubes – Ateles
postprocess_rhs_cubes Subroutine
29 statements
Source File
private subroutine postprocess_rhs_cubes(mesh, kerneldata, statedata, scheme, timestep, equation)
Uses
ply_poly_project_module
atl_cube_elem_module
atl_scheme_module
atl_equation_module
atl_modg_2d_kernel_module
atl_modg_kernel_module
atl_elemental_time_integration_module
atl_kerneldata_module
atl_modg_1d_kernel_module
Arguments
Type Intent Optional Attributes Name
type(atl_cube_elem_type), intent(inout) :: mesh
List of mesh parts. For each level we have one.
type(atl_kerneldata_type), intent(inout) :: kerneldata
List of kerneldatas. For each level we have one
type(atl_statedata_type), intent(inout) :: statedata
List of states you want to calc the rhs for. For each level we have one.
type(atl_scheme_type), intent(inout) :: scheme
List of schemes, for each level.
type(atl_timestep_type), intent(inout) :: timestep
List of levelwise timestepping algorihtms
type(atl_Equations_type), intent(in) :: equation
The equation you are operating with.
Calls
Called by
Call graph
postprocess_rhs_cubes calls atl_modg_1d_invmassmatrix, atl_modg_2d_invmassmatrix, atl_modg_invmassmatrix, tem_abort, tem_startTimer, tem_stopTimer
atl_modg_1d_invmassmatrix calls nelems, modg_1d_invmassmatrix_q
atl_modg_2d_invmassmatrix calls nelems, modg_2d_invmassmatrix_p, modg_2d_invmassmatrix_q
atl_modg_invmassmatrix calls nelems, modg_invmassmatrix_p, modg_invmassmatrix_q
atl_postprocess_rhs calls postprocess_rhs_cubes
global_corrector_substep calls atl_postprocess_rhs
imexrk_substep calls atl_postprocess_rhs, imexrk_substep
mesh_timestep_euler calls atl_postprocess_rhs, mesh_timestep_euler
rk2_substep calls atl_postprocess_rhs, rk2_substep
rk4_substep calls atl_postprocess_rhs, rk4_substep
rktaylor_substep calls atl_postprocess_rhs, rktaylor_substep
mesh_timestep_imexrk calls imexrk_substep
mesh_timestep_predcor_cerk4 calls global_corrector_substep
mesh_timestep_rk4 calls rk4_substep
mesh_timestep_rktaylor calls rktaylor_substep
mesh_timestep_ssprk2 calls rk2_substep