preprocess_local_rhs_cubes – Ateles
preprocess_local_rhs_cubes Subroutine
23 statements
Source File
private subroutine preprocess_local_rhs_cubes(mesh, statedata, scheme, general, boundary, poly_proj_list, equation, material)
Arguments
Type Intent Optional Attributes Name
type(atl_cube_elem_type), intent(inout) :: mesh
List of mesh parts. For each level we have one.
type(atl_statedata_type), intent(inout) :: statedata
List of states you want to calc the rhs for. For each level we have one.
type(atl_scheme_type), intent(inout) :: scheme
List of schemes, for each level.
type(tem_general_type), intent(inout) :: general
General treelm structures.
type(atl_level_boundary_type), intent(in) :: boundary
type(ply_poly_project_type), intent(inout) :: poly_proj_list(:)
Data for projection, for each level.
type(atl_Equations_type), intent(inout) :: equation
The equation you are operating with.
type(atl_material_type), intent(inout) :: material
The material description
Calls
Called by
Call graph
preprocess_local_rhs_cubes calls atl_preprocess_modg_kernel, tem_abort, tem_startTimer, tem_stopTimer
atl_preprocess_modg_kernel calls atl_update_materialparams
atl_update_materialparams calls atl_create_materialboundarylist, atl_evalelemmaterial, atl_evalfacematerial
atl_create_materialboundarylist calls tem_abort, tem_startTimer, tem_stopTimer, append, init, pnttid, val
atl_evalelemmaterial calls tem_abort, tem_startTimer, tem_stopTimer, neigh, nelems, nghelems, pnttid, atl_reftophyscoord, tem_spacetime_for
atl_evalfacematerial calls tem_abort, tem_startTimer, tem_stopTimer, facepos, leftpos, nelems, pnttid, atl_reftophyscoord, ply_get_quadpoints_faces, ply_get_quadpoints_faces_1d, ply_get_quadpoints_faces_2d, rightpos, tem_spacetime_for
atl_preprocess_local_rhs calls preprocess_local_rhs_cubes
local_predictor_substep calls atl_preprocess_local_rhs
mesh_timestep_predcor_cerk4 calls local_predictor_substep