preprocess_rhs_cubes – Ateles
preprocess_rhs_cubes Subroutine
163 statements
Source File
private subroutine preprocess_rhs_cubes(minLevel, maxLevel, currentLevel, mesh_list, tree, statedata_list, facedata_list, boundary_list, bc, scheme_list, poly_proj_list, equation, material_list, general)
Uses
atl_modg_2d_multilevel_module
atl_elemental_time_integration_module
atl_cube_elem_module
atl_modg_multilevel_module
atl_kerneldata_module
ply_dynarray_project_module
atl_modg_bnd_module
atl_bc_header_module
atl_modg_kernel_module
tem_comm_env_module
atl_equation_module
atl_modg_1d_kernel_module
atl_scheme_module
atl_volToFace_module
atl_modg_1d_bnd_module
atl_facedata_module
ply_poly_project_module
atl_source_types_module
atl_boundary_module
atl_materialPrp_module
atl_modg_2d_bnd_module
treelmesh_module
atl_modg_1d_multilevel_module
atl_modg_2d_kernel_module
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: minLevel
The minimum level of the mesh.
integer, intent(in) :: maxLevel
The maximum level of the mesh.
integer, intent(in) :: currentLevel
the level to compute on
type(atl_cube_elem_type), intent(inout) :: mesh_list(minLevel:maxLevel)
List of mesh parts. For each level we have one.
type(treelmesh_type), intent(in) :: tree
treelm mesh
type(atl_statedata_type), intent(inout) :: statedata_list(minLevel:maxLevel)
List of states you want to calc the rhs for. For each level we have one.
type(atl_facedata_type), intent(inout) :: facedata_list(minLevel:maxLevel)
List of face states you want to calc the rhs for. For each level we have one.
type(atl_level_boundary_type), intent(inout) :: boundary_list(minLevel:maxLevel)
List of boundaries, for each level.
type(atl_boundary_type), intent(in) :: bc(:)
The global boundary description.
type(atl_scheme_type), intent(inout) :: scheme_list(minLevel:maxLevel)
List of schemes, for each level.
type(ply_poly_project_type), intent(inout) :: poly_proj_list(:)
unique list for projection methods
type(atl_Equations_type), intent(inout) :: equation
The equation you are operating with.
type(atl_material_type), intent(inout) :: material_list(minlevel:maxlevel)
Information about the material parameters of the equation.
type(tem_general_type), intent(inout) :: general
General treelm settings.
Calls
Called by
Call graph
preprocess_rhs_cubes calls exchange_real, nelems, atl_eqn_update_background, atl_modg_1d_coarsetofineface, atl_modg_1d_ensure_pos_face, atl_modg_1d_modalvoltomodalface, atl_modg_1d_set_bnd, atl_modg_2d_coarsetofineface, atl_modg_2d_ensure_pos_facemean, atl_modg_2d_modalvoltomodalface, atl_modg_2d_set_bnd, atl_modg_coarsetofineface, atl_modg_ensure_pos_facemean, atl_modg_modalvoltomodalface, atl_modg_set_bnd, atl_preprocess_modg_1d_kernel, atl_preprocess_modg_2d_kernel, atl_preprocess_modg_kernel, recvbuffer_state, sendbuffer_state, tem_abort, tem_startTimer, tem_stopTimer
atl_preprocess_rhs calls preprocess_rhs_cubes
global_corrector_substep calls atl_preprocess_rhs
imexrk_substep calls atl_preprocess_rhs, imexrk_substep
mesh_timestep_euler calls atl_preprocess_rhs, mesh_timestep_euler
rk2_substep calls atl_preprocess_rhs, rk2_substep
rk4_substep calls atl_preprocess_rhs, rk4_substep
rktaylor_substep calls atl_preprocess_rhs, rktaylor_substep
mesh_timestep_imexrk calls imexrk_substep
mesh_timestep_predcor_cerk4 calls global_corrector_substep
mesh_timestep_rk4 calls rk4_substep
mesh_timestep_rktaylor calls rktaylor_substep
mesh_timestep_ssprk2 calls rk2_substep