serializeData – Ateles
serializeData Subroutine
101 statements
Source File
private subroutine serializeData(mesh, restart, tree, equation, chunk, iChunk, chunkdegree, chunkspace, statespace, nDims, reverse)
This subroutine serializes the given data to perform a restart.
Todo
The modal background should not be applied here, but rather later on.
Arguments
Type Intent Optional Attributes Name
type(atl_cube_container_type), intent(inout) :: mesh
Informations and states of the cubic mesh.
type(tem_restart_type), intent(inout) :: restart
type(treelmesh_type), intent(in) :: tree
type(atl_Equations_type), intent(in) :: equation
The equation system you use.
real(kind=rk), intent(inout) :: chunk(:)
integer, intent(in) :: iChunk
integer, intent(in) :: chunkdegree
Polynomial degree of the data in the IO chunk
integer, intent(in) :: chunkspace
Polynomial space of the serialized data
integer, intent(in) :: statespace
Polynomial space of the state data
integer, intent(in) :: nDims
Dimensionality of the polynomials
logical, intent(in) :: reverse
deserialize the data instead of serializing it?
Calls
Called by
Call graph
serializedata calls ply_transfer_dofs, tem_LevelOf, tem_abort
ply_transfer_dofs calls ply_transfer_dofs_1d, ply_transfer_dofs_2d, ply_transfer_dofs_3d
atl_readrestart calls serializedata
atl_writerestart calls serializedata
atl_initialize calls atl_readrestart
atl_writerestartifnecessary calls atl_writerestart
atl_harvesting calls atl_writerestart, atl_initialize
atl_finalize_program calls atl_writerestartifnecessary
atl_initialize_program calls atl_initialize, atl_writerestartifnecessary
atl_solve_program calls atl_writerestartifnecessary
ateles calls atl_finalize_program, atl_initialize_program, atl_solve_program