sorttruncate_da_projection – Ateles
sorttruncate_da_projection Subroutine
13 statements
Source File
private subroutine sorttruncate_da_projection(me)
fixing the dynamic array
truncate the array after the last valid entry and hence cut off the empty trailing empty entries store the array in the sorted order according to the sorted() array
Arguments
Type Intent Optional Attributes Name
type(dyn_projectionarray_type) :: me
Calls
Called by
Call graph
sorttruncate_da_projection calls append, destroy, init
append calls append_da_projection, append_da_vecprojection
destroy calls destroy_da_projection
init calls init_da_projection
append_da_projection calls expand, sortedposofval
append_da_vecprojection calls expand
expand calls expand_da_projection
sortedposofval calls sortposofval_projection
sorttruncate calls sorttruncate_da_projection