sortposofval_projection – Ateles
sortposofval_projection Function
44 statements
Source File
private function sortposofval_projection(me, val, nextifnotfound, lower, upper) result(pos)
return the sorted position of a value in the given dynamic array
if the value was not found, - return 0 if nextifnotfound = .false. - return position at the end if nextifnotfound = .true.
binary search on sorted list
Arguments
Type Intent Optional Attributes Name
type(dyn_projectionarray_type), intent(in) :: me
type(ply_prj_init_type), intent(in) :: val
logical, intent(in), optional :: nextifnotfound
flag to indicate, if the next entry in the list should be returned, if the searched one is not found.
integer, intent(in), optional :: lower
integer, intent(in), optional :: upper
Return Value integer
Called by
Call graph
sortedposofval calls sortposofval_projection
append_da_projection calls sortedposofval
posofval_projection calls sortedposofval
append calls append_da_projection
positionofval calls posofval_projection
atl_load_projection calls append
ply_fill_dynprojectarray calls append
sorttruncate_da_projection calls append