test_project_stabViscNumFlux – Ateles
test_project_stabViscNumFlux Subroutine
80 statements
Source File
private subroutine test_project_stabViscNumFlux(polydegree, oversamplefactor, dir, equation, length, rotated_mom)
Uses
ply_dynarray_project_module
ply_poly_project_module
ply_dof_module
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: polydegree
real(kind=rk), intent(in) :: oversamplefactor
integer, intent(in) :: dir
type(atl_Equations_type), intent(in) :: equation
real(kind=rk), intent(in) :: length
real(kind=rk), intent(out) :: rotated_mom(:)
Calls
Called by
Call graph
test_project_stabviscnumflux calls modg_project_stabviscnumfluxx_q, modg_project_stabviscnumfluxy_q, modg_project_stabviscnumfluxz_q, ply_poly_project_fillbody
modg_project_stabviscnumfluxx_q calls ply_poly_project_m2n, ply_poly_project_n2m, atl_mult_nu11_navierstokes, atl_mult_nu21_navierstokes, atl_mult_nu31_navierstokes, ply_facevalleftbndtest, ply_facevalleftbndtestgrad, ply_facevalrightbndtest, ply_facevalrightbndtestgrad, ply_scalproddualleg, ply_scalprodduallegdiff
modg_project_stabviscnumfluxy_q calls ply_poly_project_m2n, ply_poly_project_n2m, atl_mult_nu12_navierstokes, atl_mult_nu22_navierstokes, atl_mult_nu32_navierstokes, ply_facevalleftbndtest, ply_facevalleftbndtestgrad, ply_facevalrightbndtest, ply_facevalrightbndtestgrad, ply_scalproddualleg, ply_scalprodduallegdiff
modg_project_stabviscnumfluxz_q calls ply_poly_project_m2n, ply_poly_project_n2m, atl_mult_nu13_navierstokes, atl_mult_nu23_navierstokes, atl_mult_nu33_navierstokes, ply_facevalleftbndtest, ply_facevalleftbndtestgrad, ply_facevalrightbndtest, ply_facevalrightbndtestgrad, ply_scalproddualleg, ply_scalprodduallegdiff
ply_poly_project_fillbody calls ply_init_fxt, ply_init_l2p, ply_init_legfpt, ply_nodes_create, tem_abort
atl_modg_kernel_utests calls test_project_stabviscnumflux