append – Ateles
append Interface
4 statements
Source File
public interface append
append a value to the dynamic array and return its position.
Calls
Called by
Module Procedures
private subroutine append_da_projection(me, val, length, pos, wasadded)
appending a value to the dynamic array
Read more…
Arguments
Type Intent Optional Attributes Name
type(dyn_projectionarray_type) :: me
type(ply_prj_init_type), intent(in) :: val
integer, intent(in), optional :: length
optional length to expand the array
integer, intent(out), optional :: pos
position in the array, if the value is found
logical, intent(out), optional :: wasadded
flag to indicate, if val was newly added
private subroutine append_da_vecprojection(me, val, length, pos, wasadded)
appending a sorted list of values to the dynamic array
Read more…
Arguments
Type Intent Optional Attributes Name
type(dyn_projectionarray_type) :: me
type(ply_prj_init_type), intent(in) :: val(:)
integer, intent(in), optional :: length
optional length to expand the array
integer, intent(out), optional :: pos(:)
position in the array, the values are found at.
logical, intent(out), optional :: wasadded(:)
flag to indicate, if val was newly added
Call graph
append calls append_da_projection, append_da_vecprojection
append_da_projection calls expand, sortedposofval
append_da_vecprojection calls expand
expand calls expand_da_projection
sortedposofval calls sortposofval_projection
atl_load_projection calls append, atl_load_general_projection, atl_load_subprojection
ply_fill_dynprojectarray calls append
sorttruncate_da_projection calls append
sorttruncate calls sorttruncate_da_projection
atl_initialize calls atl_load_projection
atl_load_general_projection calls ply_fill_dynprojectarray
atl_load_subprojection calls ply_fill_dynprojectarray
atl_initialize_program calls atl_initialize
atl_harvesting calls atl_initialize
ateles calls atl_initialize_program