atl_acoustic_numflux – Ateles
atl_acoustic_numflux Interface
3 statements
Source File
public interface atl_acoustic_numflux
Interface for fluxes of acoustic equations.
Calls
Called by
Module Procedures
private subroutine atl_acoustic_numflux_cube_vec(nTotalFaces, nSides, nFaceDofs, faceRep, faceFlux, leftPos, rightPos, var, acoustic, idir)
c a l c u l a t e
f l u x
o f
p u r e
a c o u s t i c
e q u a t i o n
d i r e c t l y
o n
t h e
f a c e - v e c t o r
Read more…
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nTotalFaces
integer, intent(in) :: nSides
integer, intent(in) :: nFaceDofs
real(kind=rk), intent(in) :: faceRep(nTotalFaces,nFaceDofs,4,2)
real(kind=rk), intent(inout) :: faceFlux(nTotalFaces,nFaceDofs,4,2)
integer, intent(in) :: leftPos(nSides)
integer, intent(in) :: rightPos(nsides)
integer, intent(in) :: var(4)
type(atl_acoustic_type), intent(in) :: acoustic
Datatype for acoustic equation include all background data
integer, intent(in) :: idir
Direction of the flow, used for background velocity
Call graph
atl_acoustic_numflux calls atl_acoustic_numflux_cube_vec
atl_acoustic_numflux_cube_vec calls atl_acoustic_numflux_onedir
atl_modg_acoustic_numflux calls atl_acoustic_numflux
compute_rhs_cubes_modg calls atl_modg_acoustic_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg
atl_compute_rhs calls compute_rhs_cubes