atl_nerplanck_physflux_preprocess – Ateles
atl_nerplanck_physflux_preprocess Interface
3 statements
Source File
public interface atl_nerplanck_physflux_preprocess
Calls
Called by
Module Procedures
private subroutine nerplanck_physflux_diffusiveFlux(state, diffusivity, flux)
Subroutine to calculate the flux for Nernst-Planck equations.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: state(4)
State vector (as conservative variables). The order of this vector has to be where and denoted concentration (scalar) and diffusive fluxes (vector).
real(kind=rk), intent(in) :: diffusivity
The diffusivity in the cell.
real(kind=rk), intent(out) :: flux
The flux inside the cell. The order of this vector is the same as the input arguments.
Call graph
atl_nerplanck_physflux_preprocess calls nerplanck_physflux_diffusiveflux
modg_nerplanck_physflux_pre calls atl_nerplanck_physflux_preprocess
preprocess_modg_nerplanck_kernel calls modg_nerplanck_physflux_pre
atl_preprocess_modg_nerplanck_kernel calls preprocess_modg_nerplanck_kernel