atl_preprocess_modg_nerplanck_kernel – Ateles
atl_preprocess_modg_nerplanck_kernel Interface
3 statements
Source File
public interface atl_preprocess_modg_nerplanck_kernel
interface for preprocessing the data for the kernel
Calls
Module Procedures
private subroutine preprocess_modg_nerplanck_kernel(equation, kerneldata, statedata, mesh, scheme)
Arguments
Type Intent Optional Attributes Name
type(atl_Equations_type) :: equation
The equation you solve.
type(atl_kerneldata_type) :: kerneldata
The data of the kernel.
type(atl_statedata_type) :: statedata
THe state if the equation
type(atl_cube_elem_type) :: mesh
The mesh you are working with.
type(atl_modg_scheme_type) :: scheme
Parameters of the modal dg scheme
Call graph
atl_preprocess_modg_nerplanck_kernel calls preprocess_modg_nerplanck_kernel
preprocess_modg_nerplanck_kernel calls modg_invmassmatrix_pre, modg_nerplanck_physflux_pre, modg_nerplanck_x_numflux_pre, modg_nerplanck_y_numflux_pre, modg_nerplanck_z_numflux_pre
modg_invmassmatrix_pre calls nelems
modg_nerplanck_physflux_pre calls atl_nerplanck_physflux_preprocess, nelems, ply_scalproddualleg, ply_scalprodduallegdiff
modg_nerplanck_x_numflux_pre calls faces, atl_nerplanck_numflux_preprocess, leftpos, ply_facevalleftbndans, ply_facevalleftbndtest, ply_facevalrightbndtest, ply_scalproddualleg, rightpos
modg_nerplanck_y_numflux_pre calls faces, atl_nerplanck_numflux_preprocess, leftpos, ply_facevalleftbndans, ply_facevalleftbndtest, ply_facevalrightbndtest, ply_scalproddualleg, rightpos, vartransformindices
modg_nerplanck_z_numflux_pre calls faces, atl_nerplanck_numflux_preprocess, leftpos, ply_facevalleftbndans, ply_facevalleftbndtest, ply_facevalrightbndtest, ply_scalproddualleg, rightpos, vartransformindices
atl_nerplanck_numflux_preprocess calls nerplanck_numflux_diffusiveflux
atl_nerplanck_physflux_preprocess calls nerplanck_physflux_diffusiveflux