atl_maxwell_flux – Ateles
atl_maxwell_flux Interface
5 statements
Source File
public interface atl_maxwell_flux
Interface for fluxes of pure Maxwell equations.
Calls
Called by
Module Procedures
private subroutine maxwell_flux_cube(left, right, left_mu, left_epsi, right_mu, right_epsi, flux)
Subroutine to calculate the flux for pure Maxwell equations without any divergence cleaning on the reference cubic face.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: left(6)
Left state vector (as conservative variables). The order of this vector has to be \f$ (D_x, D_y, D_z, B_1, B_2, B_3) \f$ where E and B denoted electric field vetor and magnetic field (also called magnetic induction) vector.
real(kind=rk), intent(in) :: right(6)
Right state vector (as conservative variables). The order of this vector has to be (D_x, D_y, D_z, B_1, B_2, B_3) where E and B denoted the electric field vetor and magnetic field (also called magnetic induction) vector.
real(kind=rk), intent(in) :: left_mu
The magnetic permeability of the left element.
real(kind=rk), intent(in) :: left_epsi
The electric permitivity of the left element.
real(kind=rk), intent(in) :: right_mu
The magnetic permeability of the right element.
real(kind=rk), intent(in) :: right_epsi
The electric permitivity of the right element.
real(kind=rk), intent(out) :: flux(6)
The flux between left and right cell. The order of this vector is the same as the input arguments.
private subroutine maxwell_flux_cube_vec(nTotalFaces, nSides, nFaceDofs, faceRep, faceFlux, leftPos, rightPos, var, material_left, material_right)
c a l c u l a t e
f l u x
o f
p u r e
m a x w e l l
e q u a t i o n
d i r e c t l y
o n
t h e
Read more…
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nTotalFaces
integer, intent(in) :: nSides
integer, intent(in) :: nFaceDofs
real(kind=rk), intent(in) :: faceRep(nTotalFaces,nFaceDofs,6,2)
real(kind=rk), intent(inout) :: faceFlux(nTotalFaces,nFaceDofs,6,2)
integer, intent(in) :: leftPos(nSides)
integer, intent(in) :: rightPos(nsides)
integer, intent(in) :: var(6)
real(kind=rk), intent(in) :: material_left(nSides,1,2)
real(kind=rk), intent(in) :: material_right(nSides,1,2)
private subroutine maxwell_flux_nonconst_cube_vec(nTotalFaces, nSides, nFaceDofs, faceRep, faceFlux, leftPos, rightPos, var, material_left, material_right, poly_proj, modalCoeffs, pntVal, nodalNumFlux, numFluxBuffer)
c a l c u l a t e
f l u x
o f
p u r e
m a x w e l l
e q u a t i o n
d i r e c t l y
o n
t h e
Read more…
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nTotalFaces
integer, intent(in) :: nSides
integer, intent(in) :: nFaceDofs
real(kind=rk), intent(in) :: faceRep(nTotalFaces,nFaceDofs,6,2)
The modal representation on the faces, left and right trace.
real(kind=rk), intent(inout) :: faceFlux(nTotalFaces,nFaceDofs,6,2)
The fluxes for all faces, for left and right elements.
integer, intent(in) :: leftPos(nSides)
Positions for the left and right elements of all faces
integer, intent(in) :: rightPos(nsides)
Positions for the left and right elements of all faces
integer, intent(in) :: var(6)
Variable rotation indices
real(kind=rk), intent(in) :: material_left(nSides,nFaceDofs,2)
Material parameters for the left faces.
real(kind=rk), intent(in) :: material_right(nSides,nFaceDofs,2)
Material parameters for the right faces.
Read more…
type(ply_poly_project_type) :: poly_proj
Data for projection method
real(kind=rk), intent(inout) :: modalCoeffs(:,:,:)
Working array for the left and right modal coefficients
real(kind=rk), intent(inout) :: pntVal(:,:,:)
Working array for the left and right point values
real(kind=rk), intent(inout) :: nodalNumFlux(:,:)
Working array for the nodal flux
real(kind=rk), intent(inout) :: numFluxBuffer(:,:)
Working array for the modal numerical flux
Call graph
atl_maxwell_flux calls maxwell_flux_cube, maxwell_flux_cube_vec, maxwell_flux_nonconst_cube_vec
maxwell_flux_nonconst_cube_vec calls maxwell_flux_cube, ply_poly_project_m2n, ply_poly_project_n2m, ply_convert2oversample, ply_convertfromoversample
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
ply_poly_project_m2n_multivar calls ply_legtopnt_2d, ply_legtopnt_3d, ply_fxt_m2n_1d, ply_fxt_m2n_2d, ply_fxt_m2n_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d, ply_pnttoleg_3d, ply_fxt_n2m_1d, ply_fxt_n2m_2d, ply_fxt_n2m_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
atl_modg_maxwell_numflux calls atl_maxwell_flux
compute_rhs_cubes_modg calls atl_modg_maxwell_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg
atl_compute_rhs calls compute_rhs_cubes