atl_maxwell_hc_flux – Ateles
atl_maxwell_hc_flux Interface
5 statements
Source File
public interface atl_maxwell_hc_flux
Interface for fluxes of Maxwell equations with hyperbolic divergence cleaning.
Calls
Called by
Module Procedures
private subroutine maxwell_hc_flux_cube(left, right, mat_left, mat_right, flux)
Subroutine to calculate the flux for pure Maxwell equations with
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: left(8)
Left state vector (as conservative variables). The order of this vector has to be \f$ (D_x, D_y, D_z, B_1, B_2, B_3, phi, psi) \f$ where E and B denoted electric field vetor and magnetic field (also called magnetic induction) vector.
real(kind=rk), intent(in) :: right(8)
Right state vector (as conservative variables). The order of this vector has to be (D_x, D_y, D_z, B_1, B_2, B_3, phi, psi) where E and B denoted the electric field vetor and magnetic field (also called magnetic induction) vector.
real(kind=rk), intent(in) :: mat_left(4)
Material for the left face
real(kind=rk), intent(in) :: mat_right(4)
Material for the right face !> The magnetic permeability of the left element. real(kind=rk), intent(in) :: left_mu !> The electric permitivity of the left element. real(kind=rk), intent(in) :: left_epsi !> Parameter for the magnetic correction on the left element. real(kind=rk), intent(in) :: left_gam !> Parameter for the electric correction on the left element. real(kind=rk), intent(in) :: left_chi !> The magnetic permeability of the right element. real(kind=rk), intent(in) :: right_mu !> The electric permitivity of the right element. real(kind=rk), intent(in) :: right_epsi !> Parameter for the magnetic correction on the right element. real(kind=rk), intent(in) :: right_gam !> Parameter for the electric correction on the right element. real(kind=rk), intent(in) :: right_chi
real(kind=rk), intent(out) :: flux(8)
The flux between left and right cell. The order of this vector is the same as the input arguments.
Read more…
private subroutine maxwell_hc_flux_cube_vec(nTotalFaces, nSides, nFaceDofs, faceRep, faceFlux, leftPos, rightPos, var, material_left, material_right)
calculate flux of maxwell equation with hyperbolic divergence
Read more…
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nTotalFaces
integer, intent(in) :: nSides
integer, intent(in) :: nFaceDofs
real(kind=rk), intent(in) :: faceRep(nTotalFaces,nFaceDofs,8,2)
real(kind=rk), intent(inout) :: faceFlux(nTotalFaces,nFaceDofs,8,2)
integer, intent(in) :: leftPos(nSides)
integer, intent(in) :: rightPos(nsides)
integer, intent(in) :: var(8)
real(kind=rk), intent(in) :: material_left(nSides,1,4)
real(kind=rk), intent(in) :: material_right(nSides,1,4)
private subroutine maxwell_hc_flux_nonconst_cube_vec(nTotalFaces, nSides, nFaceDofs, faceRep, faceFlux, leftPos, rightPos, var, material_left, material_right, poly_proj, left_modalCoeffs, right_modalCoeffs, left_pntVal, right_pntVal, nodalNumFlux, numFluxBuffer)
calculate flux of maxwell equation with hyperbolic divergence
Read more…
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nTotalFaces
integer, intent(in) :: nSides
integer, intent(in) :: nFaceDofs
real(kind=rk), intent(in) :: faceRep(nTotalFaces,nFaceDofs,8,2)
The modal representation on the faces, left and right trace.
real(kind=rk), intent(inout) :: faceFlux(nTotalFaces,nFaceDofs,8,2)
The fluxes for all faces, for left and right elements.
integer, intent(in) :: leftPos(nSides)
Positions for the left and right elements of all faces
integer, intent(in) :: rightPos(nsides)
Positions for the left and right elements of all faces
integer, intent(in) :: var(8)
Variable rotation indices
real(kind=rk), intent(in) :: material_left(nSides,nFaceDofs,4)
Material parameters for the left faces.
real(kind=rk), intent(in) :: material_right(nSides,nFaceDofs,4)
Material parameters for the right faces.
type(ply_poly_project_type) :: poly_proj
Data for projection method !> Working array for the left and right modal coefficients real(kind=rk), intent(inout) :: left_modalCoeffs((fpt%nQuadPoints)2,8) real(kind=rk), intent(inout) :: right_modalCoeffs((fpt%nQuadPoints)2,8) !> Working array for the left and right point values real(kind=rk), intent(inout) :: left_pntVal((fpt%nQuadPoints)2,8) real(kind=rk), intent(inout) :: right_pntVal((fpt%nQuadPoints)2,8) !> Working array for the nodal flux real(kind=rk), intent(inout) :: nodalNumFlux((fpt%nQuadPoints)2,8) !> Working array for the modal numerical flux real(kind=rk), intent(inout) :: numFluxBuffer((fpt%nQuadPoints)2,8)
real(kind=rk), intent(inout), allocatable :: left_modalCoeffs(:,:)
Working array for the left and right modal coefficients
real(kind=rk), intent(inout), allocatable :: right_modalCoeffs(:,:)
real(kind=rk), intent(inout), allocatable :: left_pntVal(:,:)
Working array for the left and right point values
real(kind=rk), intent(inout), allocatable :: right_pntVal(:,:)
real(kind=rk), intent(inout), allocatable :: nodalNumFlux(:,:)
Working array for the nodal flux
real(kind=rk), intent(inout), allocatable :: numFluxBuffer(:,:)
Working array for the modal numerical flux
Call graph
atl_maxwell_hc_flux calls maxwell_hc_flux_cube, maxwell_hc_flux_cube_vec, maxwell_hc_flux_nonconst_cube_vec
maxwell_hc_flux_cube calls atl_physfluxmaxwelldivcor
maxwell_hc_flux_cube_vec calls atl_physfluxmaxwelldivcor
maxwell_hc_flux_nonconst_cube_vec calls maxwell_hc_flux_cube, ply_poly_project_m2n, ply_poly_project_n2m, ply_convert2oversample, ply_convertfromoversample
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
ply_convert2oversample calls ply_convert2oversample_1d, ply_convert2oversample_2d, ply_convert2oversample_3d
ply_convertfromoversample calls ply_convertfromoversample_1d, ply_convertfromoversample_2d, ply_convertfromoversample_3d
ply_poly_project_m2n_multivar calls ply_legtopnt_2d, ply_legtopnt_3d, ply_fxt_m2n_1d, ply_fxt_m2n_2d, ply_fxt_m2n_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d, ply_pnttoleg_3d, ply_fxt_n2m_1d, ply_fxt_n2m_2d, ply_fxt_n2m_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
atl_modg_maxwelldivcor_numflux calls atl_maxwell_hc_flux
compute_rhs_cubes_modg calls atl_modg_maxwelldivcor_numflux
compute_rhs_cubes calls compute_rhs_cubes_modg
atl_compute_rhs calls compute_rhs_cubes