atl_postprocess_rhs – Ateles
atl_postprocess_rhs Interface
3 statements
Source File
public interface atl_postprocess_rhs
Calls
Called by
Module Procedures
private subroutine postprocess_rhs_cubes(mesh, kerneldata, statedata, scheme, timestep, equation)
A p p l i e s
t h e
p o s t p r o c e s s i n g
s t e p
o f
t h e
c o m p u t e
s t e p .
Read more…
Arguments
Type Intent Optional Attributes Name
type(atl_cube_elem_type), intent(inout) :: mesh
List of mesh parts. For each level we have one.
type(atl_kerneldata_type), intent(inout) :: kerneldata
List of kerneldatas. For each level we have one
type(atl_statedata_type), intent(inout) :: statedata
List of states you want to calc the rhs for. For each level we have one.
type(atl_scheme_type), intent(inout) :: scheme
List of schemes, for each level.
type(atl_timestep_type), intent(inout) :: timestep
List of levelwise timestepping algorihtms
type(atl_Equations_type), intent(in) :: equation
The equation you are operating with.
Call graph
atl_postprocess_rhs calls postprocess_rhs_cubes
postprocess_rhs_cubes calls atl_modg_1d_invmassmatrix, atl_modg_2d_invmassmatrix, atl_modg_invmassmatrix, tem_abort, tem_startTimer, tem_stopTimer
atl_modg_1d_invmassmatrix calls nelems, modg_1d_invmassmatrix_q
atl_modg_2d_invmassmatrix calls nelems, modg_2d_invmassmatrix_p, modg_2d_invmassmatrix_q
atl_modg_invmassmatrix calls nelems, modg_invmassmatrix_p, modg_invmassmatrix_q
global_corrector_substep calls atl_postprocess_rhs
imexrk_substep calls atl_postprocess_rhs, imexrk_substep
mesh_timestep_euler calls atl_postprocess_rhs, mesh_timestep_euler
rk2_substep calls atl_postprocess_rhs, rk2_substep
rk4_substep calls atl_postprocess_rhs, rk4_substep
rktaylor_substep calls atl_postprocess_rhs, rktaylor_substep
mesh_timestep_imexrk calls imexrk_substep
mesh_timestep_predcor_cerk4 calls global_corrector_substep
mesh_timestep_rk4 calls rk4_substep
mesh_timestep_rktaylor calls rktaylor_substep
mesh_timestep_ssprk2 calls rk2_substep