atl_nerplanck_numflux_preprocess – Ateles
atl_nerplanck_numflux_preprocess Interface
3 statements
Source File
public interface atl_nerplanck_numflux_preprocess
Calls
Called by
Module Procedures
private subroutine nerplanck_numflux_diffusiveFlux(left, right, diffusivity, flux)
S u b r o u t i n e
t o
c a l c u l a t e
t h e
f l u x
f o r
N e r n s t - P l a n c k
e q u a t i o n s .
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: left(4)
Left state vector (as conservative variables). The order of this vector has to be where and denoted concentration (scalar) and diffusive fluxes (vector).
real(kind=rk), intent(in) :: right(4)
Right state vector (as conservative variables). The order of this vector has to be where and denoted concentration (scalar) and diffusive fluxes (vector).
real(kind=rk), intent(in) :: diffusivity
The diffusivity in the left and right cell. Since this is assumed to be equal in both cells, this flux function cannot be used to calculate the flux for cells with different material properties
real(kind=rk), intent(out) :: flux(3)
The flux between left and right cell. The order of this vector is the same as the input arguments.
Call graph
atl_nerplanck_numflux_preprocess calls nerplanck_numflux_diffusiveflux
modg_nerplanck_x_numflux_pre calls atl_nerplanck_numflux_preprocess
modg_nerplanck_y_numflux_pre calls atl_nerplanck_numflux_preprocess
modg_nerplanck_z_numflux_pre calls atl_nerplanck_numflux_preprocess
preprocess_modg_nerplanck_kernel calls modg_nerplanck_x_numflux_pre, modg_nerplanck_y_numflux_pre, modg_nerplanck_z_numflux_pre
atl_preprocess_modg_nerplanck_kernel calls preprocess_modg_nerplanck_kernel