atl_preprocess_local_rhs – Ateles
atl_preprocess_local_rhs Interface
3 statements
Source File
public interface atl_preprocess_local_rhs
Calls
Called by
Module Procedures
private subroutine preprocess_local_rhs_cubes(mesh, statedata, scheme, general, boundary, poly_proj_list, equation, material)
should only evaluate sources
Read more…
Arguments
Type Intent Optional Attributes Name
type(atl_cube_elem_type), intent(inout) :: mesh
List of mesh parts. For each level we have one.
type(atl_statedata_type), intent(inout) :: statedata
List of states you want to calc the rhs for. For each level we have one.
type(atl_scheme_type), intent(inout) :: scheme
List of schemes, for each level.
type(tem_general_type), intent(inout) :: general
General treelm structures.
type(atl_level_boundary_type), intent(in) :: boundary
type(ply_poly_project_type), intent(inout) :: poly_proj_list(:)
Data for projection, for each level.
type(atl_Equations_type), intent(inout) :: equation
The equation you are operating with.
type(atl_material_type), intent(inout) :: material
The material description
Call graph
atl_preprocess_local_rhs calls preprocess_local_rhs_cubes
preprocess_local_rhs_cubes calls atl_preprocess_modg_kernel, tem_abort, tem_startTimer, tem_stopTimer
atl_preprocess_modg_kernel calls atl_update_materialparams
atl_update_materialparams calls atl_create_materialboundarylist, atl_evalelemmaterial, atl_evalfacematerial
local_predictor_substep calls atl_preprocess_local_rhs
mesh_timestep_predcor_cerk4 calls local_predictor_substep