expand – Ateles
expand Interface
3 statements
Source File
private interface expand
increase the size of the container for the array.
Calls
Called by
Module Procedures
private subroutine expand_da_projection(me, increment, length)
expanding the dynamic array
Read more…
Arguments
Type Intent Optional Attributes Name
type(dyn_projectionarray_type) :: me
integer, optional :: increment
integer, intent(in), optional :: length
optional length to expand the array
Call graph
expand calls expand_da_projection
append_da_projection calls expand
append_da_vecprojection calls expand
append calls append_da_projection, append_da_vecprojection
atl_load_projection calls append
ply_fill_dynprojectarray calls append
sorttruncate_da_projection calls append
sorttruncate calls sorttruncate_da_projection
atl_initialize calls atl_load_projection
atl_load_general_projection calls ply_fill_dynprojectarray
atl_load_subprojection calls ply_fill_dynprojectarray