ply_pntToLeg_2D – Ateles
ply_pntToLeg_2D Interface
4 statements
Source File
public interface ply_pntToLeg_2D
Calls
Called by
Module Procedures
private subroutine ply_pntToLeg_2D_singVar(fpt, pntVal, legCoeffs)
Subroutine to transform Legendre expansion to point values at Chebyshev nodes.
Arguments
Type Intent Optional Attributes Name
type(ply_legFpt_type), intent(inout) :: fpt
Parameters of the Fast Polynomial transformation.
real(kind=rk), intent(inout) :: pntVal(:)
The point values to transform to 2D modal Legendre expansion. \attention Although this array serves as input only, it is modified inside of this routine by the underlying DCT algorithm. So, when this routine returns from its call the original values of pntVal will be modified.
real(kind=rk), intent(inout) :: legCoeffs(:)
The Legendre coefficients.
private subroutine ply_pntToLeg_2D_multVar(fpt, pntVal, legCoeffs, nVars)
Subroutine to transform Legendre expansion to point values at Chebyshev nodes.
Arguments
Type Intent Optional Attributes Name
type(ply_legFpt_type), intent(inout) :: fpt
Parameters of the Fast Polynomial transformation.
real(kind=rk), intent(inout) :: pntVal(:,:)
The point values to transform to 2D modal Legendre expansion. \attention Although this array serves as input only, it is modified inside of this routine by the underlying DCT algorithm. So, when this routine returns from its call the original values of pntVal will be modified.
real(kind=rk), intent(inout) :: legCoeffs(:,:)
The Legendre coefficients.
integer, intent(in) :: nVars
The number of scalar variables to transform.
Call graph
ply_pnttoleg_2d calls ply_pnttoleg_2d_multvar, ply_pnttoleg_2d_singvar
ply_pnttoleg_2d_multvar calls ply_pnttoleg_2d
ply_check_legtopnt_2d calls ply_pnttoleg_2d
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
ply_fpt_ifpt_2d_multivar_lobattonodes_test calls ply_check_legtopnt_2d
ply_fpt_ifpt_2d_multivar_test calls ply_check_legtopnt_2d
ply_fpt_ifpt_2d_singvar_lobattonodes_test calls ply_check_legtopnt_2d
ply_fpt_ifpt_2d_singvar_test calls ply_check_legtopnt_2d