ply_poly_project_m2n – Ateles
ply_poly_project_m2n Interface
3 statements
Source File
public interface ply_poly_project_m2n
Calls
Called by
atl_cons_positivity_preserv w ply_poly_project_m2n
w
atl_cons_positivity_preserv_2d w
w
atl_eqn_euler_implicit_pen w
w
atl_eqn_maxwell_implicit_pen w
w
atl_equation_evaluate_source_nodal w
w
atl_generic_fromModal_getElement w
w
atl_initTimeStepInfo w
w
atl_modg_2d_euler_oneDim_numFlux_const w
w
atl_modg_2d_euler_oneDim_numFlux_nonconst w
w
atl_modg_euler_oneDim_numFlux_const w
w
atl_modg_euler_oneDim_numFlux_nonconst w
w
atl_modg_viscNavierStokes_oneDim_numFlux w
w
atl_physCheck_acoustic w
w
atl_physCheck_acoustic_2d w
w
atl_physCheck_euler w
w
atl_physCheck_euler1d w
w
atl_physCheck_euler2d w
w
atl_physCheck_lineareuler w
w
atl_physCheck_lineareuler_2d w
w
atl_physCheck_Rans w
w
atl_physCheck_Rans_2d w
w
atl_positivity_preserv w
w
atl_positivity_preserv_2d w
w
atl_stabilize w
w
check_fpt w
w
check_fpt w
w
check_fpt_2d w
w
check_fpt_2d w
w
check_fxt_2d w
w
check_fxt_3D w
w
compute_physFlux_nonConst w
w
compute_physFlux_nonConst_2d w
w
compute_physFluxDivCor_nonConst w
w
eval_source_rans2D w
w
implicit_update w
w
maxwell_flux_nonconst_cube_vec w
w
maxwell_flux_nonconst_cube_vec_2d w
w
maxwell_hc_flux_nonconst_cube_vec w
w
modg_1d_compute_project_physFlux w
w
modg_2d_compute_project_physFlux w
w
modg_2d_nodal_bnd w
w
modg_2d_project_stabViscNumFluxX_Q w
w
modg_2d_project_stabViscNumFluxY_Q w
w
modg_2d_rans_oneDim_numFlux_const w
w
modg_2d_rans_oneDim_numFlux_nonconst w
w
modg_2d_viscNavierStokes_oneDim_numFlux w
w
modg_2d_viscRans_oneDim_numFlux w
w
modg_compute_project_physFlux w
w
modg_nodal_bnd w
w
modg_project_stabViscNumFluxX_Q w
w
modg_project_stabViscNumFluxY_Q w
w
modg_project_stabViscNumFluxZ_Q w
w
Module Procedures
private subroutine ply_poly_project_m2n_multiVar(me, dim, nVars, modal_data, nodal_data)
Convert nDoF modes to nodal values.
Arguments
Type Intent Optional Attributes Name
type(ply_poly_project_type), intent(inout) :: me
integer, intent(in) :: dim
integer, intent(in) :: nVars
The number of variables to project. If a variable consists of more than one component, the number of components has to be passed. If there are more than one variable, the sum of all components has to be passed (e.g. 6 when there are two three-dimensional vectors).
real(kind=rk), intent(inout) :: modal_data(:,:)
real(kind=rk), intent(inout) :: nodal_data(:,:)
Call graph
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_m2n_multivar calls ply_legtopnt_2d, ply_legtopnt_3d, ply_fxt_m2n_1d, ply_fxt_m2n_2d, ply_fxt_m2n_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_legtopnt_2d calls ply_legtopnt_2d_multvar, ply_legtopnt_2d_singvar
ply_legtopnt_3d calls ply_legtopnt_3d_multvar, ply_legtopnt_3d_singvar
ply_fxt_m2n_1d calls fxtf_flptld_m2n
ply_fxt_m2n_2d calls fxtf_flptld_m2n
ply_fxt_m2n_3d calls fxtf_flptld_m2n
ply_l2p_trafo_1d calls ply_l2_projection
ply_l2p_trafo_2d calls ply_l2_projection
ply_l2p_trafo_3d calls ply_l2_projection
fxtf_flptld_m2n calls fxtf_flptld_evl
ply_legtopnt_2d_multvar calls ply_legtopnt_2d
ply_legtopnt_3d_multvar calls ply_legtopnt_3d