ply_poly_project_n2m – Ateles
ply_poly_project_n2m Interface
3 statements
Source File
public interface ply_poly_project_n2m
Calls
Called by
approximate_1D_jump w ply_poly_project_n2m
w
atl_cons_positivity_preserv w
w
atl_cons_positivity_preserv_2d w
w
atl_eqn_euler_implicit_pen w
w
atl_eqn_maxwell_implicit_pen w
w
atl_equation_evaluate_source_modal w
w
atl_equation_evaluate_source_nodal w
w
atl_generic_fromModal_getElement w
w
atl_generic_fromNodal_getElement w
w
atl_load_initial_condition w
w
atl_modg_1d_euler_penalization_Const w
w
atl_modg_1d_euler_penalization_NonConst w
w
atl_modg_2d_euler_oneDim_numFlux_const w
w
atl_modg_2d_euler_oneDim_numFlux_nonconst w
w
atl_modg_2d_euler_penalization_const w
w
atl_modg_2d_euler_penalization_NonConst w
w
atl_modg_2d_navierstokes_penalization_const w
w
atl_modg_2d_navierstokes_penalization_Nonconst w
w
atl_modg_euler_oneDim_numFlux_const w
w
atl_modg_euler_oneDim_numFlux_nonconst w
w
atl_modg_euler_penalization_const w
w
atl_modg_euler_penalization_NonConst w
w
atl_modg_maxwell_2d_penalization_NonConst w
w
atl_modg_navierstokes_penalization_const w
w
atl_modg_navierstokes_penalization_nonconst w
w
atl_modg_viscNavierStokes_oneDim_numFlux w
w
atl_positivity_preserv w
w
atl_positivity_preserv_2d w
w
check_fpt w
w
check_fpt w
w
check_fpt_2d w
w
check_fpt_2d w
w
check_fxt_2d w
w
check_fxt_3D w
w
compute_physFlux_nonConst w
w
compute_physFlux_nonConst_2d w
w
compute_physFluxDivCor_nonConst w
w
eval_source_rans2D w
w
implicit_update w
w
maxwell_flux_nonconst_cube_vec w
w
maxwell_flux_nonconst_cube_vec_2d w
w
maxwell_hc_flux_nonconst_cube_vec w
w
modg_1d_compute_project_physFlux w
w
modg_2d_compute_project_physFlux w
w
modg_2d_modal_bnd w
w
modg_2d_nodal_bnd w
w
modg_2d_project_stabViscNumFluxX_Q w
w
modg_2d_project_stabViscNumFluxY_Q w
w
modg_2d_rans_oneDim_numFlux_const w
w
modg_2d_rans_oneDim_numFlux_nonconst w
w
modg_2d_viscNavierStokes_oneDim_numFlux w
w
modg_2d_viscRans_oneDim_numFlux w
w
modg_compute_project_physFlux w
w
modg_modal_bnd w
w
modg_nodal_bnd w
w
modg_project_stabViscNumFluxX_Q w
w
modg_project_stabViscNumFluxY_Q w
w
modg_project_stabViscNumFluxZ_Q w
w
Module Procedures
private subroutine ply_poly_project_n2m_multiVar(me, dim, nVars, nodal_data, modal_data)
Convert nodal values to nDoFs modes.
Arguments
Type Intent Optional Attributes Name
type(ply_poly_project_type), intent(inout) :: me
integer, intent(in) :: dim
integer, intent(in) :: nVars
real(kind=rk), intent(inout) :: nodal_data(:,:)
real(kind=rk), intent(inout) :: modal_data(:,:)
Call graph
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
ply_poly_project_n2m_multivar calls ply_pnttoleg_2d, ply_pnttoleg_3d, ply_fxt_n2m_1d, ply_fxt_n2m_2d, ply_fxt_n2m_3d, ply_l2p_trafo_1d, ply_l2p_trafo_2d, ply_l2p_trafo_3d
ply_pnttoleg_2d calls ply_pnttoleg_2d_multvar, ply_pnttoleg_2d_singvar
ply_pnttoleg_3d calls ply_pnttoleg_3d_multvar, ply_pnttoleg_3d_singvar
ply_fxt_n2m_1d calls fxtf_flptld_n2m
ply_fxt_n2m_2d calls fxtf_flptld_n2m
ply_fxt_n2m_3d calls fxtf_flptld_n2m
ply_l2p_trafo_1d calls ply_l2_projection
ply_l2p_trafo_2d calls ply_l2_projection
ply_l2p_trafo_3d calls ply_l2_projection
fxtf_flptld_n2m calls fxtf_flptld_exp
ply_pnttoleg_2d_multvar calls ply_pnttoleg_2d
ply_pnttoleg_3d_multvar calls ply_pnttoleg_3d