sorttruncate – Ateles
sorttruncate Interface
3 statements
Source File
public interface sorttruncate
fix the dynamic array, meaning: store the array in the sorted order and cut off the trailing empty entries
Calls
Module Procedures
private subroutine sorttruncate_da_projection(me)
fixing the dynamic array
Read more…
Arguments
Type Intent Optional Attributes Name
type(dyn_projectionarray_type) :: me
Call graph
sorttruncate calls sorttruncate_da_projection
sorttruncate_da_projection calls append, destroy, init
append calls append_da_projection, append_da_vecprojection
destroy calls destroy_da_projection
init calls init_da_projection
append_da_projection calls expand, sortedposofval
append_da_vecprojection calls expand