sortedposofval – Ateles
sortedposofval Interface
3 statements
Source File
private interface sortedposofval
return the position of a given value in the list 'sorted'. this is mainly for internal usage. the sorted list is only a pointer list to the actual values thus, in order to get the index of a given value, you need to look up the entry in the sorted list. this is done by the positionofval routine
Calls
Called by
Module Procedures
private function sortposofval_projection(me, val, nextifnotfound, lower, upper) result(pos)
return the sorted position of a value in the given dynamic array
Read more…
Arguments
Type Intent Optional Attributes Name
type(dyn_projectionarray_type), intent(in) :: me
type(ply_prj_init_type), intent(in) :: val
logical, intent(in), optional :: nextifnotfound
flag to indicate, if the next entry in the list should be returned, if the searched one is not found.
integer, intent(in), optional :: lower
integer, intent(in), optional :: upper
Return Value integer
Call graph
sortedposofval calls sortposofval_projection
append_da_projection calls sortedposofval
posofval_projection calls sortedposofval
append calls append_da_projection
positionofval calls posofval_projection
atl_load_projection calls append
ply_fill_dynprojectarray calls append
sorttruncate_da_projection calls append
sorttruncate calls sorttruncate_da_projection
atl_initialize calls atl_load_projection
atl_load_general_projection calls ply_fill_dynprojectarray
atl_load_subprojection calls ply_fill_dynprojectarray