ateles – Ateles
ateles Program
42 statements
Source File
Uses
atl_aux_module
treelmesh_module
atl_program_module
atl_timer_module
tem_general_module
ply_poly_project_module
atl_varSys_module
tem_precice_module
atl_solver_param_module
mpi
atl_container_module
atl_equation_module
env_module
ATELES
This is the main program of the Adaptive Tree-based Efficient and Lithe Equation Solver. It provides the Modal Discontinuous Galerkin solver in the APES framework. (c) 2011 German Research School for Simulation Sciences GmbH (c) 2013-2016 University of Siegen
Calls
Variables
Type Attributes Name Initial
type(atl_solver_param_type) :: params
type(atl_Equations_type) :: equation
type(treelmesh_type) :: tree
type(atl_varSys_solverData_type) :: varSys_data
integer, allocatable :: nCellsNoBnd(:)
type(atl_element_container_type) :: element_container
type(ply_poly_project_type), allocatable :: poly_proj_list(:)
real(kind=rk) :: precice_dt
integer :: iError
Call graph
ateles calls mpi_barrier, atl_addtimers, atl_banner, atl_finalize_program, atl_initialize_program, atl_load_config, atl_solve_program, tem_finalize, tem_start