atl_harvesting – Ateles
atl_harvesting Program
114 statements
Source File
Uses
treelmesh_module
ply_poly_project_module
tem_tracking_module
atl_container_module
atl_solver_param_module
atl_aux_module
atl_scheme_module
atl_cube_elem_module
atl_stabilize_module
atl_restart_module
atl_equation_module
atl_program_module
tem_tools_module
tem_logging_module
aotus_module
mpi
ply_sampled_tracking_module
aot_table_module
atl_timer_module
atl_kerneldata_module
tem_timer_module
tem_general_module
atl_initialize_module
atl_varSys_module
tem_restart_module
ATELES Postprocessing
This is the harvesting tool for Ateles, enabling the post-processing simulation data from the solver. (c) 2015 University of Siegen
Calls
Variables
Type Attributes Name Initial
type(treelmesh_type) :: tree
type(atl_solver_param_type) :: params
type(atl_element_container_type) :: element_container
type(atl_Equations_type) :: equation
type(atl_varSys_solverData_type) :: varSys_data
integer, allocatable :: nCellsNoBnd(:)
integer :: iConf
integer :: iLevel
integer :: iError
integer :: firstlevel
integer :: lastLevel
integer :: scheme_table
integer :: spatial_table
logical :: use_post_filter
type(flu_State) :: conf
type(ply_poly_project_type), allocatable :: poly_proj_list(:)
Call graph
atl_harvesting calls aot_get_val, aot_table_close, aot_table_open, aot_table_set_val, close_config, conf, atl_addtimers, atl_banner, atl_get_numberofelemsperlevel, atl_initialize, atl_kerneldata_update_estimates, atl_load_config, atl_stabilize, atl_writerestart, ply_sampled_track_output, tem_finalize, tem_horizontalSpacer, tem_restart_finalize, tem_start, tem_startTimer, tem_stopTimer, tem_tracking_finalize, tem_tracking_print_last_VTK_files