fxtp_test – Ateles
fxtp_test Program
38 statements
Source File
Uses
fxt_fwrap
iso_c_binding
env_module
Calls
Variables
Type Attributes Name Initial
type(fxtf_flptld_type), target :: flpt
real(kind=rk) :: nodal_orig(10)
real(kind=c_double) :: modal(10)
real(kind=c_double) :: nodal(10)
integer(kind=c_int) :: modalLen
integer(kind=c_int) :: nodalLen
integer :: nPoints
integer :: maxDegree
real(kind=rk) :: prec
Call graph
fxtp_test calls fxtf_flptld_evl, fxtf_flptld_exp, fxtf_flptld_init
fxtf_flptld_init calls fxt_flptld_init, fxt_flptld_wsize, fxt_vecld_new