integrateLeg_test – Ateles
integrateLeg_test Program
66 statements
Source File
Uses
env_module
ply_modg_basis_module
Testing the integration of Legendre Polynomials.
Calls
Variables
Type Attributes Name Initial
real(kind=rk), allocatable :: integrand(:)
real(kind=rk), allocatable :: integral(:)
real(kind=rk), allocatable :: evalatends(:,:)
real(kind=rk), allocatable :: asserted_half(:)
real(kind=rk) :: halfint
real(kind=rk) :: signfact
integer, parameter :: maxdegree = 10
integer :: iMode
integer :: nEven
logical :: check_ok
Functions
elemental function bico(n, k) result(b)
Compute the binomial n over k
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
integer, intent(in) :: k
Return Value real(kind=rk)
Call graph
integrateleg_test calls bico, ply_integrateleg, ply_legendre_1d