ply_fpt_ifpt_2D_multiVar_lobattoNodes_test – Ateles
ply_fpt_ifpt_2D_multiVar_lobattoNodes_test Program
60 statements
Source File
Uses
tem_general_module
ply_legFpt_module
tem_logging_module
ply_fpt_header_module
env_module
ply_legFpt_2D_module
Unit test to check functionallity of fast polynomial transformations. \author{Jens Zudrop}
Calls
Variables
Type Attributes Name Initial
integer :: iPower
real(kind=rk) :: res
real(kind=rk) :: newRes
type(tem_general_type) :: general
Subroutines
subroutine ply_check_legToPnt_2D(power, res)
do iDof = 1, (maxPolyDegree+1)2 write(,) 'Leg coeff ', iDof, ' has error: ', legVal(iDof) - legCoeffs(iDof) end do
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: power
real(kind=rk), intent(out) :: res
Call graph
ply_fpt_ifpt_2d_multivar_lobattonodes_test calls fin_env, ply_check_legtopnt_2d, tem_start
ply_check_legtopnt_2d calls ply_legtopnt_2d, ply_pnttoleg_2d, ply_fpt_header_define, ply_init_legfpt
ply_legtopnt_2d calls ply_legtopnt_2d_multvar, ply_legtopnt_2d_singvar
ply_pnttoleg_2d calls ply_pnttoleg_2d_multvar, ply_pnttoleg_2d_singvar
ply_fpt_header_define calls tem_abort
ply_init_legfpt calls fftw_plan_many_r2r, fftw_plan_r2r_1d, ply_fpt_init
ply_fpt_init calls ply_l, ply_l_int, ply_m, ply_m_int
ply_legtopnt_2d_multvar calls ply_legtopnt_2d
ply_pnttoleg_2d_multvar calls ply_pnttoleg_2d