ply_fpt_test – Ateles
ply_fpt_test Program
68 statements
Source File
Uses
ply_fpt_header_module
tem_general_module
tem_logging_module
env_module
tem_param_module
ply_modg_basis_module
ply_legFpt_module
Unit test to check functionallity of fast polynomial transformations. \author{Jens Zudrop}
Calls
Variables
Type Attributes Name Initial
integer :: iDegree
integer :: iBSize
real(kind=rk) :: res
real(kind=rk) :: newRes
type(tem_general_type) :: general
integer, parameter :: nDegrees = 14
integer, parameter :: degree(nDegrees) = [1, 2, 3, 4, 5, 9, 31, 63, 71, 72, 107, 127, 179, 255]
integer, parameter :: nBSizes = 3
integer, parameter :: blocksize(nBSizes) = [36, 37, 64]
Subroutines
subroutine ply_check_legToPnt(blocksize, maxPolyDegree, res)
do iPoint = 1, maxPolyDegree+1 write(,) 'Point: ', chebPnt(iPoint), & & ' FPT: ', pntVal(iPoint), & & ' Ref.: ', refVal(iPoint), & & ' error: ', pntVal(iPoint)-refVal(iPoint) end do
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: blocksize
integer, intent(in) :: maxPolyDegree
real(kind=rk), intent(out) :: res
Call graph
ply_fpt_test calls fin_env, ply_check_legtopnt, tem_start
ply_check_legtopnt calls ply_fpt_header_define, ply_init_legfpt, ply_legendre_1d
ply_fpt_header_define calls tem_abort
ply_init_legfpt calls fftw_plan_many_r2r, fftw_plan_r2r_1d, ply_fpt_init
ply_fpt_init calls ply_l, ply_l_int, ply_m, ply_m_int