ply_split_element_test_prog – Ateles
ply_split_element_test_prog Program
11 statements
Source File
Uses
ply_split_element_module
Calls
Variables
Type Attributes Name Initial
logical :: success
Call graph
ply_split_element_test_prog calls ply_split_element_test
ply_split_element_test calls ply_split_element_1d_test, ply_split_element_2d_test, ply_split_element_3d_test, ply_split_element_init
ply_split_element_1d_test calls ply_split_element_init, ply_legendre_1d, ply_split_element_singled
ply_split_element_2d_test calls ply_split_element_init, ply_legendre_1d, ply_split_element_2d
ply_split_element_3d_test calls ply_split_element_init, ply_legendre_1d, ply_split_element_3d
ply_split_element_init calls ply_split_legendre_matrix
ply_split_element_2d calls ply_split_element_singled
ply_split_element_3d calls ply_split_element_singled
ply_split_legendre_matrix calls alpha, alpha_beta, alpha_frac, beta