ply_lagrange_test – Ateles
ply_lagrange_test Program
58 statements
Source File
Uses
ply_nodeset_module
ply_lagrange_module
env_module
Calls
Variables
Type Attributes Name Initial
integer :: iSample
real(kind=rk), allocatable :: linear(:)
real(kind=rk), allocatable :: quad(:)
real(kind=rk) :: sample_x
real(kind=rk) :: f
real(kind=rk) :: diff
real(kind=rk) :: maxdiff
real(kind=rk) :: lobval(3)
type(ply_lagrange_type) :: poly
type(ply_lagrange_type) :: lobpoly
Call graph
ply_lagrange_test calls ply_lagrange_define, ply_lagrange_eval, ply_lagrange_mode_at, ply_nodeset_chebyshev, ply_nodeset_legendre
ply_lagrange_eval calls ply_lagrange_mode_at