ply_l2p_test – Ateles
ply_l2p_test Program
61 statements
Source File
Uses
ply_l2p_module
ply_nodeset_module
ply_l2p_header_module
env_module
Unit test to check the L2P implementation.
Calls
Variables
Type Attributes Name Initial
type(ply_l2p_header_type) :: header
type(ply_l2p_type) :: trafo
real(kind=rk), allocatable :: modaldat(:)
real(kind=rk), allocatable :: recovered(:)
real(kind=rk), allocatable :: nodevals(:)
real(kind=rk), allocatable :: coords(:)
real(kind=rk) :: maxdiff
real(kind=rk) :: diff
integer :: degree
Call graph
ply_l2p_test calls ply_init_l2p, ply_l2p_header_define, ply_l2p_trafo_1d, ply_nodeset_chebyloba
ply_init_l2p calls ply_gausslegpoints, ply_lagrange_1d, ply_lagrange_define, ply_legendre_1d, ply_scalprodleg, tem_abort
ply_l2p_header_define calls tem_abort, upper_to_lower
ply_l2p_trafo_1d calls ply_l2_projection
ply_lagrange_1d calls ply_lagrange_mode_at