ply_fpt_header_test – Ateles
ply_fpt_header_test Program
222 statements
Source File
Uses
env_module
ply_fpt_header_module
Calls
Functions
function isEqual()
Arguments
None
Return Value logical
function isUnequal()
Arguments
None
Return Value logical
function isSmaller()
Arguments
None
Return Value logical
function isSmallerOrEqual()
Arguments
None
Return Value logical
function isGreater()
Arguments
None
Return Value logical
function isGreaterOrEqual()
Arguments
None
Return Value logical
Subroutines
subroutine init_fptHeader(header)
Arguments
Type Intent Optional Attributes Name
type(ply_fpt_header_type), intent(inout) :: header
Call graph
ply_fpt_header_test calls isequal, isgreaterorequal, isgreater, issmallerorequal, issmaller, isunequal
isequal calls init_fptheader
isgreaterorequal calls init_fptheader
isgreater calls init_fptheader
issmallerorequal calls init_fptheader
issmaller calls init_fptheader
isunequal calls init_fptheader