ply_split_legendre_test_prog – Ateles
ply_split_legendre_test_prog Program
59 statements
Source File
Uses
env_module
ply_split_legendre_module
ply_modg_basis_module
Calls
Variables
Type Attributes Name Initial
integer, parameter :: nModes = 30
integer, parameter :: nPoints = nModes
integer, parameter :: nOps = nModes**2
real(kind=rk), parameter :: tolerance = nOps*epsilon(1.0_rk)
logical :: success
logical :: matching_right
logical :: matching_left
integer :: iMode
integer :: iPoint
real(kind=rk) :: parentval
real(kind=rk) :: childval
real(kind=rk) :: parentmode(nModes)
real(kind=rk) :: childmode(nModes)
real(kind=rk) :: legparent(nModes,nPoints)
real(kind=rk) :: legchild(nModes,nPoints)
real(kind=rk) :: xi(nPoints)
real(kind=rk) :: x(nPoints)
real(kind=rk) :: split_matrix(nModes,nModes)
Call graph
ply_split_legendre_test_prog calls ply_legendre_1d, ply_split_legendre_matrix, ply_split_legendre_test
ply_split_legendre_matrix calls alpha, alpha_beta, alpha_frac, beta
ply_split_legendre_test calls ply_split_legendre_matrix, alpha, alpha_beta, alpha_frac, beta