ply_project_fpt_test – Ateles
ply_project_fpt_test Program
81 statements
Source File
Uses
tem_general_module
ply_poly_project_module
ply_dynarray_project_module
ply_dof_module
ply_fpt_header_module
tem_logging_module
env_module
ply_prj_header_module
\todo Check reading of the projection configuration. The input has to be configured on the fly! \todo Put various projections into a projection descriptor. \todo Check those projections by doing m2n and n2m, where input and output should be the same within certain bounds. \todo If everything worked fine, write PASSED on the very last line of output, to indicate a successful run of the unit test:
Calls
Variables
Type Attributes Name Initial
real(kind=rk) :: res
real(kind=rk) :: newRes
integer :: power
type(tem_general_type) :: general
Subroutines
subroutine check_fpt(power, res)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: power
real(kind=rk), intent(out) :: res
Call graph
ply_project_fpt_test calls fin_env, check_fpt, tem_start
check_fpt calls ply_poly_project_m2n, ply_poly_project_n2m, ply_fpt_header_define, ply_poly_project_fillbody, ply_prj_init_define
ply_poly_project_m2n calls ply_poly_project_m2n_multivar
ply_poly_project_n2m calls ply_poly_project_n2m_multivar
ply_fpt_header_define calls tem_abort
ply_poly_project_fillbody calls ply_init_fxt, ply_init_l2p, ply_init_legfpt, ply_nodes_create, tem_abort