ply_ifpt_lobattoNodes_test – Ateles
ply_ifpt_lobattoNodes_test Program
63 statements
Source File
Uses
tem_param_module
tem_aux_module
tem_general_module
tem_logging_module
ply_legFpt_module
env_module
ply_fpt_header_module
ply_modg_basis_module
Unit test to check functionallity of fast polynomial transformations to nodal values at Lobatto-Chebyshev-Nodes. \author{Jens Zudrop}
Calls
Variables
Type Attributes Name Initial
integer :: iPower
real(kind=rk) :: res
real(kind=rk) :: newRes
type(tem_general_type) :: general
Subroutines
subroutine ply_check_pntToLeg(power, res)
do iPoly = 1, maxPolyDegree+1 write(,) 'Poly degree: ', iPoly, & & ' iFPT: ', legVal(iPoly), & & ' Ref.: ', legCoeffs(iPoly), & & ' error: ', legVal(iPoly)-legCoeffs(iPoly) end do
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: power
real(kind=rk), intent(out) :: res
Call graph
ply_ifpt_lobattonodes_test calls fin_env, ply_check_pnttoleg, tem_start
ply_check_pnttoleg calls ply_fpt_header_define, ply_init_legfpt, ply_legendre_1d
ply_fpt_header_define calls tem_abort
ply_init_legfpt calls fftw_plan_many_r2r, fftw_plan_r2r_1d, ply_fpt_init
ply_fpt_init calls ply_l, ply_l_int, ply_m, ply_m_int