test_fxtd_n2m2n – Ateles
test_fxtd_n2m2n Program
186 statements
Source File
Uses
ply_dynarray_project_module
tem_general_module
ply_poly_project_module
ply_prj_header_module
ply_oversample_module
tem_logging_module
env_module
ply_fxt_module
fxt_fwrap
ply_dof_module
If everything worked fine, write PASSED on the very last line of output, to indicate a successful run of the unit test:
Calls
Variables
Type Attributes Name Initial
real(kind=rk) :: res1
real(kind=rk) :: res2
real(kind=rk) :: newRes2
real(kind=rk) :: res3
real(kind=rk) :: newRes3
integer :: power
type(tem_general_type) :: general
Subroutines
subroutine check_fxt_1d(res)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(out) :: res
subroutine check_fxt_2d(power, res)
todo NA: Check if nodes kind and factor are correctly used for
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: power
real(kind=rk), intent(out) :: res
subroutine check_fxt_3D(power, res)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: power
real(kind=rk), intent(out) :: res
Call graph
test_fxtd_n2m2n calls fin_env, check_fxt_1d, check_fxt_2d, check_fxt_3d, tem_start
check_fxt_1d calls fxtf_flptld_init, fxtf_flptld_m2n, fxtf_flptld_n2m
check_fxt_2d calls ply_poly_project_m2n, ply_poly_project_n2m, ply_poly_project_fillbody, ply_prj_init_define
check_fxt_3d calls ply_poly_project_m2n, ply_poly_project_n2m, ply_convert2oversample, ply_convertfromoversample, ply_poly_project_fillbody, ply_prj_init_define