name: Compilation and Tests

on:
  pull_request:
    branches: [ "main" ]
  merge_group:
    types: [checks_requested]

jobs:
  compile-test:
    permissions:
      checks: write
      pull-requests: write
    uses: apes-suite/reus/.github/workflows/compile.yml@v1.3.1
    with:
      name: Ateles
      systest: ${{ github.event.action == 'checks_requested' }}
